### ISSUE TITLE
Localize decimal separator

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#1]
Bei Währungs-, Gewichts und anderen Zahlenangaben wird derzeit nur der Dezimalpunkt verwendet.
Ideal wäre, wenn Punkt oder Komma abhängig von der Herkunft des Besuchers verwendet werden könnte.

Alternative (nicht so günstig): Der Shop-Betreiber legt per Konfiguration fest, was verwendet wird.

**Comment by cmb69** [comment]
Hm, soweit ich es überblicke, gibt es da zwei etwas unterschiedliche Fälle: einmal die `<input type=number>` welches schon lokalisiert ist (und zwar gemäß dem Browser), und die anderen Anzeigen, die derzeit ein Dezimalkomma verwenden, wenn als Sprache `de` gewählt ist, und einen Dezimalpunkt in allen anderen Fällen. Irre ich mich?

Falls nicht, dann würde ich die `<input type=number>` einfach so lassen, wie sie sind. Für alle anderen Fälle könnte man statt [`number_format`](http://php.net/manual/en/function.number-format.php) [`NumberFormatter`](http://php.net/manual/en/class.numberformatter.php) verwenden, welcher beliebige Locales unterstützt. Allerdings müsste man dann die Intl Extension voraussetzen. Wenn das ein Problem darstellt, dann bliebe nur number_format() und vielleicht auch money_format() und die nötigen Infos (Dezimaltrennzeichen, Wärungszeichen, Anzahl der Nachkommastellen, und eventuell Tausendertrennzeichen) müssten einzeln konfiguriert werden.

**Comment by frase-git** [comment]
> ... und die anderen Anzeigen, die derzeit ein Dezimalkomma verwenden, wenn als Sprache de gewählt ist, und einen Dezimalpunkt in allen anderen Fällen. Irre ich mich?

Ja. So war das mal ursprünglich. Mit den number-Feldern musste ich das aber ändern, weil sonst im Backend gar keine Zahlen mehr zu sehen wären.  In der Demo kannst du sehen, dass **_immer_** der Punkt verwendet wird.

**Comment by cmb69** [comment]
Bingo – ich war noch in der alten Testumgebung. Schau ich mir an.

**Comment by cmb69** [comment]
Ich habe nun mal im Feature-Branch `localized-numbers` das ursprüngliche Verhalten der Lokalisierung wieder hergestellt (außer für `<input type=number>`), siehe 0f9c34c.

**Comment by frase-git** [comment]
Hm, ja.
Jetzt wird wieder zwischen "de" und "Rest der Welt" unterschieden.

**Comment by cmb69** [comment]
> Jetzt wird wieder zwischen "de" und "Rest der Welt" unterschieden.

Ja, so war das erst mal gedacht. Ich habe nun einen weiteren Commit (0e72554)  in den `localized-numbers` Branch gemacht, der zumindest andeutet, wie es mit `NumberFormatter` ausschauen könnte. Für jetzt müsste das gewünschte Locale in [dieser Zeile](https://github.com/cmsimple-xh/xhshop/commit/0e72554b337fd2ee6ccefbba624fc5d1c6339d80#diff-9937f2e70553ee6f5c0822a120f1df39R216) angepasst werden. Einfach mal `en_US`, `de_CH` (@manu37 wird's freuen) oder ein beliebiges anderes Locale ausprobieren. Wenn `NumberFormatter` verwendet wird, dann wäre es vermutlich auch sinnvoll `formatCurrency()` zu nutzen, was gleich das passende Währungssymbol an der passenden Stelle mit anzeigt (`$` steht üblicherweise vor der Zahl).

Und es müsste halt noch geklärt werden, wo das Locale eingegeben/gespeichert wird. `shopsettings.php` bietet sich an, aber vielleicht sollte das der Einfachheit halber sowieso `config.php` werden (die sprachspezifischen Einstellungen müssten dann aber in die Sprachdatei).

**Comment by frase-git** [comment]
Tja, ich - als manchmal Hobby-Programmierer - verstehe wirklich nicht alles, was du hier schreibst.
Ich bitte um Nachsicht.
Einiges ist mir aber klar:
- `shopsettings.php` sollte gut und gerne CMSXHmäßig `config.php` werden.
- Währungssymbol **vor** der Zahl finde ich grauselig - das ist bei Geldhändlern und anderen Finanzjongleuren üblich, aber nicht im Einzelhandel.

Verstehe ich das richtig?
Wenn `NumberFormatter` verwendet wird, wird Locale festgelegt und alle Besucher sehen dieses Format? Unabhängig davon, wie es im Land des Besuchers üblich ist?

**Comment by cmb69** [comment]
> shopsettings.php sollte gut und gerne CMSXHmäßig config.php werden.

Von mir aus gerne, aber die sprachspezifischen Einstellungen müssen dann eben in die Sprachdateien weichen, wo es keine Hilfstexte und keine Checkboxen/Selects etc. gibt.

> Währungssymbol vor der Zahl finde ich grauselig - das ist bei Geldhändlern und anderen Finanzjongleuren üblich, aber nicht im Einzelhandel.

Wo das Währungsymbol geschrieben wird, hängt vom Locale ab. Bei `de_DE` wird `$` nach der Zahl geschrieben, bei `en_US` aber davor. Eben so, wie es in den jeweiligen Ländern üblich ist.

> Wenn NumberFormatter verwendet wird, wird Locale festgelegt und alle Besucher sehen dieses Format? Unabhängig davon, wie es im Land des Besuchers üblich ist?

Der NumberFormatter läuft unter PHP, weiß also zunächst mal nichts vom Browser. Daher ist es zunächst mal eine serverseitige Einstellung. Man könnte allerdings auch den vom Browser gesendeten `accept-language` Header auswerten, und versuchen daraus das gewünschte Locale abzuleiten. Das ist allerdings etwas tricky, und ich bin mir auch nicht sicher, ob man das wirklich will. Wenn ich in einem englischsprachigen Shop bestelle, dann bin ich wohl auch in der Lage (und erwarte es vielleicht sogar), dass dort eben ein Dezimalpunkt verwendet wird (genauso wie ich dort auch englische Datumsangaben erwarte).

Was auf jeden Fall aber immer serverseitig eingestellt werden muss, ist das Währungsymbol oder -kürzel.

**Comment by cmb69** [comment]
Ich hab noch mal nachgedacht. ext/intl schein problematisch, da nicht unbedingt verfügbar, wie in anderen Tickets bereits erwähnt. `number_format()` reicht aber eigentlich aus, und Dezimal- und Tausendertrennzeichen können ja einfach in der Sprachdatei definiert sein; diejenigen die kein Tausendertrennzeichen wollen, können die entsprechende Variable einfach leer lassen. Unterstützung für etwas anderes als 2 Nachkommastellen ist vermutlich bei Geldbeträgen nicht wirklich nötig, und könnte bei Bedarf noch nachgebessert werden.

Somit schlage ich vor PR #44 zu mergen.
