### ISSUE TITLE
Unnecessary file creation

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#10]
Es gibt immer nur ein `bill.rtf` das nach Abschluss des Bestellvorgangs erstellt, und dann per Mail an den Shopbetreiber verschickt wird. Wenn zwei Bestellungen quasi zeitgleich vorgenommen werden kann es passieren, dass für beide Bestellungen das selbe `bill.rtf` verschickt wird. Sehr unwahrscheinlich, aber möglich – mit problematischen Folgen.

Entweder müsste `bill.rtf` gesperrt werden sobald mit dessen Erstellung begonnen wird, und es dürfte erst wieder freigegeben werden, wenn das Ergebnis gelesen wurde. Alternativ könnte man auch den Rechnungen eindeutige IDs zuweisen (etwa `bill-12345.rtf`), in welchem Fall sich alte Rechnungen auf dem Webspace ansammeln würden (kann aber auch ein Vorteil sein). In beiden Fällen müsste auf jeden Fall der `bills/` Ordner vor direktem HTTP-Zugriff geschützt werden (ansonsten können Neugierige die aktuelle oder gar alle Bestellungen einsehen – Datenschutz).

Mir sieht es aber so aus, als müsse die Rechnung überhaupt nicht gespeichert werden, sondern könnte direkt an die Mail angehängt werden – das wäre wohl die eleganteste Lösung.

**Comment by frase-git** [comment]
Stichwort Transaktionssicherheit.

Wir sollten hier nochmal gründlich nachdenken, ob eine solche Rechnung wirklich sinnvoll ist.
Im Forum haben Hartmut und Albert bestätigt, dass sie nur die Daten "irgendwie" übernehmen.
Auch bei oben genanntem Shop wird mit Copy&Paste übernommen und eine eigen Rechnung verschickt.
Eine CSV, die problemlos (ohne Import-Optionen) in Excel geöffnet werden kann, scheint mir sinnvoller - bis jemand 'ne bessere Idee hat ;-)

**Comment by cmb69** [comment]
> Wir sollten hier nochmal gründlich nachdenken, ob eine solche Rechnung wirklich sinnvoll ist.

Ich kann mir schon vorstellen, dass diese Rechnung tatsächlich genutzt wird. Wenn das Template entsprechend vorbereitet wird, dann muss im Zweifel nur noch die Rechnungsnummer ergänzt werden, und fertig.

> Eine CSV, die problemlos (ohne Import-Optionen) in Excel geöffnet werden kann, scheint mir sinnvoller […]

Zu Excel kann ich wenig sagen; habe ich seit vielen Jahren nicht mehr. Bei LibreOffice poppt aber wohl immer ein Import-Dialog auf. Das Problem, dass man mehrere CSV-Dateien bräuchte, existiert aber wohl nicht, da man ja nicht unbedingt alle Zeilen mit den selben Spalten befüllen muss.

Eine Universallösung gibt es hier aber sicherlich nicht: so mancher verwendet für WaWi (FiBu) vermutlich eine eher manuelle Lösung (Tabellekalkulation und/oder Textverarbeitung), aber vermutlich hat auch so mancher ein fertiges Programm dafür im Einsatz (Lexware etc.)

Wenn überhaupt wäre es denkbar, verschiedene Formate zur Auswahl anzubieten. Dann kann sich jeder das geeignetste Aussuchen.

**Comment by frase-git** [comment]
Klingt alles nach sehr viel Programmier-Arbeit.
Und wenn schon eine Rechnung, warum dann nicht gleich gut nach DIN gestaltet und als PDF?
In der Shop-Konfiguration noch ein Firmen-Logo hochgeladen - und das dann auch noch auf die Rechnung.
Gambio&Co lassen grüßen. Und die Datenübernahme bleibt trotzdem.

**Comment by cmb69** [comment]
> Und wenn schon eine Rechnung, warum dann nicht gleich gut nach DIN gestaltet und als PDF?

PDF ist möglich, erfordert aber vermutlich eine umfangreiche Bibliothek, und es ist nicht unbedingt einfach dafür Templates anzubieten. Letztlich liefe dann alles auf HTML-Templates und HTML→PDF Konvertierung raus, und da braucht es wirklich eine sehr umfangreiche Bibliothek.

Aber ein Problem bliebe: die Rechnungsnummer, die ja quasi fortlaufend sein muss. Und wer will sich schon eine Software leisten, um PDFs zu bearbeiten.

Ich arbeite mal eine CSV-Variante aus.

**Comment by XHalbert** [comment]
> Ich arbeite mal eine CSV-Variante aus.


 bitte bitte kein CSV
1. das rtf kann mehrere Tabellen enthalten
2. der Shopbetreiber kann es ändern, indem er template.rtf editiert - nichts im Code wird geändert

**Comment by XHalbert** [comment]
> Wenn zwei Bestellungen quasi zeitgleich vorgenommen werden kann es passieren, dass für beide Bestellungen das selbe bill.rtf verschickt wird.

man könnte wohl jeweils sofort nach Emailversand die bill.rtf löschen

**Comment by XHalbert** [comment]
> XHalbert korrigiert: bitte bitte kein CSV

> 1.    das rtf kann mehrere Tabellen enthalten

> 2.    der Shopbetreiber kann es ändern, indem er template.rtf editiert - nichts im Code wird geändert


zu 2. mir ist grad aufgegangen, dass er CSV ja genauso editieren kann.
zu 1. Ich finde mehrere CSV kommt nicht in Frage.
Man könnte vllt. das drag&drop von ALLEN Daten aus **einer einzigen CSV** machen, aber wie?
Damit könnte ich mich wohl anfreunden, wenn da nicht das Problem mit den bestellten Artikeln wäre, die müssten ja auch in die CSV (%rows%). Daran habe ich früher sehr viel experimentiert. Ich wollte %rows% hinter die Kundendaten anfügen. Hat nicht geklappt, daher meine Lösung mit den zwei oder sogar drei Tabellen: Kundendaten - abweichende Lieferadresse - Artikel)

Mir leuchtet im Moment (noch) nicht ein, warum CSV besser wäre. Ich ärgere mich jedesmal bei der Buchführung über CSVs, wenn ich von Sparkasse, paypal u. Kartenzahlungsdienst die Auszüge runterlade, um sie in das Buchf.Programm reinzukriegen...

PS: Will wirklich keiner die bill.rtf? Kleine Shops, Hobbyleute, Vereine? 
Man kann die rtf doch ansprechend als brauchbare Rechnung gestalten, in die der Shopbetreiber nur noch die Rechnungsnummer eintragen muss. Z.B. Seite1: Tabellen, Seite 2: Rechnungsvorlage

**Comment by cmb69** [comment]
> Man könnte vllt. das drag&drop von ALLEN Daten aus einer einzigen CSV machen, aber wie?

Die CSV-Datei könnte ganz grob wie folgt aufgebaut sein:
````
Christoph,Becker,Rheinstr. 147,55424,Münster-Sarmsheim

1,Schraubendreher,9.99€
7,Schrauben,0.09€
````
Also eben eigentlich keine "richtige" CSV-Datei. Die kann dann in eine Tabellenkalkulation importiert werden, und von dort können die einzelnen Tabellen ins Programm übernommen werden.

Nachteil: das Layout der CSV-Datei kann man nicht ohne weiteres anpassen (so wie derzeit) beim RTF. Aber natürlich könnte man auch dafür ein kleines Templatesystem basteln.

Ich selbst habe aber auch gewisse Zweifel, ob CSV hier wirklich sinnvoll ist. Aber die nur mäßige Anpassbarkeit von RTF ist halt auch nicht so toll. Ein OpenDokument-Format *könnte* hier hilfreich sein.

**Comment by XHalbert** [comment]
wenn ich das:

Christoph,Becker,Rheinstr. 147,55424,Münster-Sarmsheim
1,Schraubendreher,9.99€
7,Schrauben,0.09€

in die Kundenkartei reinziehe gibts Chaos

> Ein OpenDokument-Format könnte hier hilfreich sein.

gerne, wenn es mit Exel kompatibel ist

**Comment by frase-git** [comment]
> wenn ich das:
> ...
> in die Kundenkartei reinziehe gibts Chaos

Hm, für welche Kundenkartei soll es denn funktionieren? Für deine? Für Hartmuts?
Das wird nicht einfach, hier etwas allgemeingültiges zu finden.

**Comment by cmb69** [comment]
> Das wird nicht einfach, hier etwas allgemeingültiges zu finden.

Ja, definitiv. Für Addressen gibt es [vCard](https://de.wikipedia.org/wiki/VCard), aber ich fürchte nichts vergleichbares für Bestellposten. Und selbst wenn, dann kann eine handgemachte Auftragsverwaltung damit vermutlich gar nichts anfangen.

> gerne, wenn es [OpenDocument Format] mit Exel kompatibel ist

Zumindest mit halbwegs aktuellen Versionen (zumindest wenn man sich auf rudimentäre Funktionalität beschränkt, was hier kein Problem sein sollte). Vermutlich dann auf jeden Fall mit Excel 2010 und neuer.

Allerdings habe ich unter PHP noch nie mit OpenDocument Dokumenten gearbeitet, und kann daher keine Bibliothek empfehlen, und allein [hier](http://opendocumentformat.org/developers/) werden schon eine ganze Reihe Alternativen gelistet, die ggf. evaluiert werden müssten.

> Mir sieht es aber so aus, als müsse die Rechnung überhaupt nicht gespeichert werden, sondern könnte direkt an die Mail angehängt werden – das wäre wohl die eleganteste Lösung.

Tatsächlich ist es so, dass die gespeicherte `bill.rtf` gar nicht verwendet wird, und der Code zum Speichern überflüssig ist. Ich werde diesen also entfernen, und das diesem Ticket zuweisen; über alternative Formate für `bill.rtf` können wir dann in Ticket #18 weiter diskutieren.

**Comment by frase-git** [comment]
Vielleicht hilft das:
CSV mit `;` (Semikolon) als Feldtrenner und [CR][LF] als Datensatz-Trenner kommt in Excel (2010, PC) sauber an.
CSV mit `,` (Komma) als Feldtrenner macht oft Probleme.

Bsp.:
```
artikel 1;2kg;1.00
artikel 2;0.5kg;2.00
```
Nachtrag:
Die CSV muss bei mir ANSI codiert sein für Excel.
Utf-8 kommt falsch an.
