### ISSUE TITLE
language config: shop page

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#100]
Bin gerade dabei im Wiki Sprache - Config zu schreiben.
`?Shop` haben wir als Standard-Adresse drin.

Ich hatte überlegt,: Was ist, wenn der Shop die Startseite ist?
(das war falsch, weil **auch dann** dort `?Shop` stehen muss oder ?Home ...)

Egal, ich habe den Eintrag mal leer gemacht und den Shop aufgerufen. Wird angezeigt. Debug meldet:

> XH-NOTICE: XHS_CMSimple_Bridge::getHeadingOfUrl($url) - does not exist.
> ... \plugins\xhshop\classes\CmsBridge.php:37

Das ist logisch: der Warenkorb, die Detailseiten ... werden nicht angezeigt.

Ich überlege jetzt, was da als minimal-Anforderung drinstehen muss. Wie erkläre ich das?
Muss geprüft werden, ob leer?

**Comment by cmb69** [comment]
> Das ist logisch: der Warenkorb, die Detailseiten ... werden nicht angezeigt.

Nein, ist nicht wirklich logisch, sondern die Systemprüfung ist [hier schlampig](https://github.com/cmsimple-xh/xhshop/blob/37b9603e23c69feb29b9b449c23ea86a56592a13/classes/SystemCheckService.php#L129) weil das führende `?` optional vorhanden sein kann. Wenn man hier sauberer prüft, dann würde die Systemprüfung leere Einträge bemängeln.

Alternativ könnte man möglicherweise auch an anderen Stellen den leeren Eintrag berücksichtigen, so dass man den Shop auf der Startseite laufen lassen kann. Aber da werd ich immer etwas hippelig wegen cmsimple-xh/cmsimple-xh#35, und den Shop gleich auf der Startseite zu haben, ist vermutlich auch eher ungewollt, oder?

**Comment by XHalbert** [comment]
> den Shop gleich auf der Startseite zu haben,

ich brauchs nicht, hab ich aber schon öfter gesehen!

**Comment by cmb69** [comment]
> hab ich aber schon öfter gesehen!

Bei reinen Shops, oder bei Shop, die auf einer Website integriert sind? Und es ist ja schon jetzt möglich den Shop auf der Startseite zu betreiben, nur muss diese dann eben explizit eingestellt werden.

**Comment by frase-git** [comment]
1. Post - die letzten zwei Fragen !

**Comment by frase-git** [comment]
Information:
Shop als Startseite funktioniert NICHT - bzw. nicht praktikabel.
Siehe: https://github.com/cmsimple-xh/xhshop/wiki/Bekannte-Probleme#startseite-ohne-warenkorb-button

Gerade getestet.
Sobald die Seite ohne ?Shop aufgerufen wird, ist kein Warenkorb zugänglich.
Zumindest auf der Shop-Seite - auf den anderen schon.
In meiner Demo führt ein Klick auf den Header zur Startseite ohne ?...
Das gibt es auch in anderen Templates.

Nachtrag:
Erstaufruf der Seite ohne ?...
Shop Übersicht -> gleich einen Artikel in den Korb legen
= Kein Warenkorb

**Comment by cmb69** [comment]
> Shop als Startseite funktioniert NICHT - bzw. nicht praktikabel.

Okay, dann zumindest für Version 1: Shop auf Startseite wird nicht vollständig unterstützt.

* Doku ist okay, denn Warenkorbproblem ist ja bereits dokumentiert
* Systemprüfung wird überarbeitet, so dass ein `?` erforderlich ist. Mach ich bei Gelegenheit.

**Comment by frase-git** [comment]
Doku aktualisiert:
https://github.com/cmsimple-xh/xhshop/wiki/Start/#shop-seiten-anlegen

**Comment by cmb69** [comment]
> Systemprüfung wird überarbeitet, so dass ein ? erforderlich ist. Mach ich bei Gelegenheit.

Upps, das war ja schon so. Da in der Doku nun explizit auf die durchzuführende Systemprüfung hingewiesen wird, schließe ich dieses Ticket.
