### ISSUE TITLE
Move bill.rtf to templates/email_confirmation/

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#102]
Irgendwie erscheint es mir sinnlos, für `template.rtf` einen eigenen Ordner zu haben, und die Datei würde doch gut in `templates/email_confirmation/` passen.

Okay?

PS: es geht natürlich nicht um `bill.rtf` sondern um `template.rtf`

**Comment by frase-git** [comment]
Ebenso `paypal-logo.png` ?

**Comment by cmb69** [comment]
> Ebenso paypal-logo.png ?

Eher nicht, da das mit Templates ja nun gar nichts zu tun hat (okay, das Custom-Attachment von #16 ist auch kein Template, aber gehört wenigstens zur E-Mail). Wenn der `image/` Ordner stört, dann könnte man das Logo vielleicht eher nach `css/` verschieben.

**Comment by frase-git** [comment]
Kann bleiben wo es ist.
