### ISSUE TITLE
Admin modus: shop screen

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#103]
`Adminmodus -> Shop aufrufen -> Artikelübersicht gleich zum Bearbeiten.`
Perfekt.

`Adminmodus -> Plugins -> xhshop -> das Gleiche`
Nicht perfekt.
Hier wäre es besser, die Systemprüfung zu haben (About?)
Außerdem steht hier immer noch ganz oben `stylesheet` (Link) bzw. `setting`
Diese beiden Links weg.

**Comment by cmb69** [comment]
Ja, das muss alles noch überarbeitet werden. Hab's nicht vergessen – im Gegenteil werde ich bei jedem Test wieder daran erinnert. :(

> Außerdem steht hier immer noch ganz oben stylesheet (Link) bzw. setting
Diese beiden Links weg.

Auch das "XH-Shop, Version 1alpha-preview" mit dem Cart-Logo? Steht ja auch unter About.

**Comment by cmb69** [comment]
> Diese beiden Links weg.

Erledigt mit 2ddadb2

**Comment by frase-git** [comment]
Ja, auch weg.

**Comment by frase-git** [comment]
erledigt - mit #108 ?
