### ISSUE TITLE
No protection against CSRF attacks

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#104]
Es muss unbedingt ein Schutz vor [Cross-Site-Request-Forgery](https://de.wikipedia.org/wiki/Cross-Site-Request-Forgery) implementiert werden, und zwar nicht nur für das Backend, sondern auch fürs Frontend (ab da, wo die Session gestartet wird).

**Comment by frase-git** [comment]
@cmb69 
heute morgen neuesten Master synchronisiert.
Fatal error: ... Leider nicht notiert. Es ging gar nichts mehr.
Github Desktop angeschaut. Da wird "Revert" für die einzelnen Änderungen angeboten.
Das habe ich schrittweise von der Letzten bis zur drittletzten gemacht, erst dann lief es wieder.
Dann habe ich anschließend im Desktop nochmals auf "Sync" geklickt, weil ich wieder auf den aktuellen Stand kommen wollte um das Problem zu melden.
Das war wohl ein Fehler, denn statt meinen Desktop wieder zu aktualisieren, hat er meine Reverts im Master ausgeführt. Das war nicht meine Absicht.

Ich werde jetzt mal schauen, ob ich meine Reverts wieder revertieren kann.

**Comment by frase-git** [comment]
Uff, offensichtlich konnte ich meinen Fehler tatsächlich rückgängig machen.
Also:
Die Fehlermeldung lautet (weißer Bildschirm):

> Fatal error: Class 'Xhshop\XH_CSRFProtection' not found in ... \plugins\xhshop\classes\Controller.php on line 61

**Comment by cmb69** [comment]
> Uff, offensichtlich konnte ich meinen Fehler tatsächlich rückgängig machen.

Ja, sieht gut aus. :)

> Die Fehlermeldung lautet (weißer Bildschirm):

Da hätte ich wohl mal im ausgeloggten Zustand testen sollen. Behoben mit 4a53247 (hoffentlich auch für XH 1.6)

**Comment by frase-git** [comment]
Geht in 1.7 wieder.
1.6 kann ich gerade nicht testen.
