### ISSUE TITLE
Warenwert in Sprachdatei

### ISSUE THREAD

**Issue by XHalbert** [cmsimple-xh/xhshop#105]
"Warenwert plus Versandkosten" wie in bill.rtf find ich besser.

Stattdessen steht bei der Bestellung im Warenkorb, 3. Schritt und Email "Zwischensumme".

Vorschlag Änderung:
`Subtotal   |   Warenwert`

Wenn z.B. später mal Rabatt o.ä. eingeführt wird, kann man sich sprachlich besser auf "Warenwert" beziehen als auf "Zwischensumme".

**Comment by frase-git** [comment]
👍 

@cmb69 
https://github.com/cmsimple-xh/xhshop/blob/master/languages/de.php#L126
