### ISSUE TITLE
Version and version.nfo

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#106]
Wie sollen wir die Versionsangabe im Code und für `version.nfo` handhaben? 

1. Entweder können wir das manuell durchführen oder es automatisch beim "Build" (Erstellen der auslieferbaren Zips) machen lassen. Letzteres hat den Vorteil, dass beide Versionsangaben (also [im Code](https://github.com/cmsimple-xh/xhshop/blob/5a4a428521442147b82d1061e6933148788c7350/classes/Controller.php#L11) und in [version.nfo](https://github.com/cmsimple-xh/xhshop/blob/5a4a428521442147b82d1061e6933148788c7350/version.nfo#L1)) auf jeden Fall übereinstimmen, aber den Nachteil dass während der Entwicklung ein paar Dinge nicht funktionieren (Update-Check, Anzeige der Version im Backend). 

2. Des weiteren ist zu bedenken, welche URL in der ausgelieferten `version.nfo` die serverseitige `version.nfo` bezeichnet. Auf jeden Fall können wir etwas in der Art von https://raw.githubusercontent.com/cmsimple-xh/xhshop/master/version.nfo verwenden, aber die "Version" (hier `master`) müsste individueller gehandhabt werden, weil wir ja nicht einem Nutzer von 1.0 plötzlich einen frühen `master` für 2.0 nahelegen wollen.

**Comment by frase-git** [comment]
zu 1.
Da wäre ich für "automatisch".
Wenn wirklich nur die beiden Dinge nicht funktionieren (Update-Check, Anzeige der Version im Backend), wäre das zu verschmerzen.
zu 2.
Du meinst: Nutzer hat 1.0 und bekommt 2.alpha1 angeboten?
Kann denn nicht nur mit stable Releases verglichen werden?
Wie läuft das bei XH?
(Fürchte, ich habe ich das nicht richtig verstanden?)

**Comment by cmb69** [comment]
> Du meinst: Nutzer hat 1.0 und bekommt 2.alpha1 angeboten?

Genau, das meine ich.

> Kann denn nicht nur mit stable Releases verglichen werden?

Aber wohin zeigt dann `version.nfo` bei den 1er Beta-Releases? Und wie werden Tester von 2.0beta1 informiert, dass es 2.0rc1 gibt?

> Wie läuft das bei XH?

Da wird `version.nfo` von Hand auf cmsimple-xh.org hoch geladen, sobald ein neues stable Release veröffentlich wird. Und wenn ich's recht bedenke, dann können wir das auch beim XH-Shop so halten, wenn wir ein [Gist](https://gist.github.com/cmsimple-xh) dafür anlegen. Danke! :) Bzw. eben gleich eines pro Hauptversion (also `version1.nfo`, `version2.nfo` usw.), und wenn Version 1 Lebensende hat, kann einfach der Inhalt von `version1.nfo` durch den Inhalt von `version2.nfo` ersetzt werden.

**Comment by frase-git** [comment]
Scheint so, dass händisch besser wäre, nach deiner Beschreibung.

(Gist???)

**Comment by cmb69** [comment]
> Scheint so, dass händisch besser wäre, nach deiner Beschreibung.

Die Versionsangaben im Quellcode können wir gerne automatisch einfügen lassen. Nur eben die serverseitige version.nfo müsste dann manuell aktualisiert werden. Damit kann man aber leben.

> (Gist???)

Keine Ahnung was der Name bedeutet, aber eigentlich sind die gedacht um kleinere Codeschnipsel auszutauschen. Könnten wir aber gut als serverseitige version.nfo verwenden.

Ich habe die version.nfo mal für ein [Gist](https://gist.github.com/cmb69/d6f681e90d62ad17b37a1b71631dc85f) vorbereitet. Wenn du master aktualisierst, dann sollte nun der Update-Check funktionieren.

**Comment by frase-git** [comment]
> XH-Shop 1.0dev1 ist aktuell.

;-)))

**Comment by cmb69** [comment]
Und jetzt kommt

> For XH-Shop is the new version 1.0dev1 available!

weil die tatsächliche Version erst beim Build vergeben wird.

**Comment by frase-git** [comment]
Gut.
Aber Obacht.
Falls du dir ständiges Nachfragen ersparen willst, wegen
`@VERSION@,@VERSION@`
dann sollte der Link zu [releases](https://github.com/cmsimple-xh/xhshop/releases) führen.

**Comment by cmb69** [comment]
> Falls du dir ständiges Nachfragen ersparen willst, wegen
@VERSION@,@VERSION@

Wer soll denn da nachfragen? Ich vermute im wesentlichen sind es nur du, Albert und ich, die überhaupt mit einem Git-Clone arbeiten. Wenn `1.0beta1` veröffentlicht wird, dann steht dort ja kein `@VERSION@` mehr drin. Und die Entwicklerdoku kann ja diesbezüglich noch ergänzt werden (ist sowieso noch ein bisschen was zu dokumentieren).

> dann sollte der Link zu releases führen.

Ja, guter Punkt (es geht um ja den Downloadlink). Aber wenn wir Klone ignorieren können (siehe vorheriger Absatz), dann könnte man auch gleich zum jeweiligen Release verlinken, denn wie ich gerade mit Freude festgestellt habe, wird der von UpdateCheck angezeigt Downloadlink nicht aus der lokalen version.nfo, sondern der serverseitigen genommen. Dann landet man ganz konkret beim Release, vergleichbar mit https://github.com/cmsimple-xh/cmsimple-xh/releases/tag/1.7.0.

**Comment by frase-git** [comment]
alles gut

Übrigens:
Wer ist [rclilly](https://github.com/cmsimple-xh/xhshop/network/members)?

**Comment by cmb69** [comment]
> Wer ist rclilly?

Vielleicht ein zukünftiger Contributor. :) Obgleich ich Zweifel habe, dass der Shop in den USA genutzt werden kann; siehe z.B. https://www.mehrwertsteuerrechner.de/umsatzsteuer-usa.

**Comment by frase-git** [comment]
> siehe z.B. https://www.mehrwertsteuerrechner.de/umsatzsteuer-usa.

Sehr schön.
Mittelalter.
