### ISSUE TITLE
Browser-Adresszeile bei Kategorie-Auswahl über Newsbox

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#11]
http://fhs.bplaced.net/xhshop-demo/?Shop

Wenn ich im Shop Kategorie "Essen" wähle, bleibt in der Adresszeile stehen:
http://fhs.bplaced.net/xhshop-demo/?Shop

Wenn ich aus dem Neben-Menü in der Newsbox wähle, erscheint in der Adresszeile:
http://fhs.bplaced.net/xhshop-demo/?Shop&xhsCategory=Essen

Wähle ich nun eine andere Kategorie aus dem DropDown-Menü, bleibt in der Adresszeile **immer** das "Essen" stehen.

Ist das ein Problem?

**Comment by cmb69** [comment]
> Ist das ein Problem?

IMO ja. Die Auswahl einer Kategorie sollte immer per GET-Request erfolgen (kann dann vom Browser und Proxies gecache't werden, und User können das bookmarken, teilen etc.), und idealerweise auch immer zur gleichen URL (vermeiden von DC). Das war vor XH 1.6 nicht ohne Tricksereien möglich, stellt mittlerweile aber kein Problem mehr dar.

**Comment by frase-git** [comment]
Ist doch mit GET jetzt erledigt?
Sieht bei mir zumindest so aus.

**Comment by cmb69** [comment]
> Ist doch mit GET jetzt erledigt?

Ja, zumindest wenn es (dich) nicht stört, dass bei der Auswahl per Select immer noch `&xhsTask=productList` an die URL angehängt wird. Das ist aber zumindest im richtigen Plugin-Backend (?xhshop) erforderlich.

**Comment by frase-git** [comment]
Stört nicht.
Zumindest nicht mich und schon gar nicht jetzt.
Danke.
Ich close mal, damit das ein bisschen weniger wird.
