### ISSUE TITLE
editing categories

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#111]
Die Verschiebe-Pfeile sind noch nicht internationalisiert.

Die OK-Buttons mit Title versehen?
Ist OK als Text nötig? Oder reicht das Icon?

Verschieberei wie bei Shop-Übersicht?

**Comment by cmb69** [comment]
> Die Verschiebe-Pfeile sind noch nicht internationalisiert.

Erledigt: 67866c0

> Die OK-Buttons mit Title versehen?
Ist OK als Text nötig? Oder reicht das Icon?

Ich selbst verwende Title-Attribute nur, wenn der Platz knapp ist; aus Gründen der Zugänglichkeit sind explizite Texte besser. Daher würde ich sagen, so lassen, aber internationalisieren. Da es bereits `labels_save_settings` gibt, hab ich das einfach mal übernommen: a5424c4

> Verschieberei wie bei Shop-Übersicht?

Wirklich gelungen finde ich das auch in der Shop-Übersicht nicht, und bei den Kategorien ist es wohl nicht so problematisch, so dass ich es erst mal lassen würde.

**Comment by frase-git** [comment]
Verschieberei nicht so wichtig.

Vielleicht hätte man die Verschiebebuttons in Kategorie und Artikelübersicht vereinheitlichen sollen.
Einfach nur: "nach oben verschieben" und "nach unten verschieben" für beide Seiten?
Dann könnte man sich den langen Text auf der Übersichtsseite auch sparen?

Title: verstanden. gut

**Comment by cmb69** [comment]
> Vielleicht hätte man die Verschiebebuttons in Kategorie und Artikelübersicht vereinheitlichen sollen.
Einfach nur: "nach oben verschieben" und "nach unten verschieben" für beide Seiten?
Dann könnte man sich den langen Text auf der Übersichtsseite auch sparen?

Gute Idee! Umgesetzt mit 3de266a.

**Comment by frase-git** [comment]
Super.
Ich close mal. Zur Reduzierung.
