### ISSUE TITLE
Don't use floats for money calculations

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#114]
Warum wird [hier](https://stackoverflow.com/questions/3730019/why-not-use-double-or-float-to-represent-currency) erklärt. Siehe auch dieses [konkretes Problembeispiel](https://github.com/cmsimple-xh/xhshop/issues/72#issuecomment-314441833).

**Comment by cmb69** [comment]
So, ein erster Zwischenstand befindet sich im [decimals Branch](https://github.com/cmsimple-xh/xhshop/tree/decimals). Bezüglich der Bestellung (Warenwert, Rechnungsbetrag, Steuern etc.) sollte nun alles passen, und ich habe auch automatisierte Tests geschrieben, so dass sich in der Folge nicht unbemerkt Regressionen einschleichen sollten. Schaut euch den Stand bitte mal an, und prüft, ob im Schritt 3 alles korrekt ist. Besonders Kalkulationen mit gemischten Steuersätzen sind etwas knifflig.

**Comment by frase-git** [comment]
Kleiner Aufstoßer, aber **kein** Fehler:
In Step 1 werden Versandkosten angekündigt, obwohl in Step 3 dann keine berechnet werden.

> Warenwert | 50,70 €
> Alle Preisangaben inkl. Mehrwertsteuer zzgl. Versandkosten. Die genauen Versandkosten werden im dritten Schritt aufgelistet.

Das lässt sich wohl gar nicht anders lösen - oder?

---

Solange keine Gebühren oder Versandkosten mit Misch-MwSt. dabei sind, wird richtig gerechnet.
Das konnte ich schon prüfen.
Wie ist das mit den Gebühren/Nachlass?
Werden die auch anteilig berechnet? Ja, ne.

**Comment by cmb69** [comment]
> In Step 1 werden Versandkosten angekündigt, obwohl in Step 3 dann keine berechnet werden.

In Step 1 müsste aber auch der Hinweis erscheinen, dass ab 50,00€ (oder was immer konfiguriert wurde), keine Versandkosten anfallen. Ist das nicht genug?

> Wie ist das mit den Gebühren/Nachlass?
Werden die auch anteilig berechnet? Ja, ne.

Das wurde vom Wellrad Shop schon so gehandhabt, und im Prinzip habe ich das auch übernommen (die Berechnung ist jetzt halt etwas anders, sollte aber das gleiche Ergebnis haben). Vgl. "Mehrwertsteuer auf Verpackung und Versand" auf http://www.onlineshop-basics.de/leitfaden-zur-mehrwertsteuer-21.html und http://www.it-recht-kanzlei.de/umsatzsteuer-versandkosten-mehrwertsteuer.html.

**Comment by frase-git** [comment]
> Warenwert | 50,70 €
> Alle Preisangaben inkl. Mehrwertsteuer zzgl. Versandkosten. Die genauen Versandkosten werden im dritten Schritt aufgelistet.
>>In Step 1 müsste aber auch der Hinweis erscheinen, dass ab 50,00€ (oder was immer konfiguriert wurde), keine Versandkosten anfallen. Ist das nicht genug?

Warenwert ist 50,70
Da kommt die 50 €-Meldung nicht - aber das zitierte.
Ein User denk: Mann, nun habe ich extra einen Warenwert über 50 € genommen und die wollen immer noch Versandkosten.
Dass am Ende gar keine berechnet werden, weiß er da noch nicht.

**Comment by cmb69** [comment]
> Warenwert ist 50,70
Da kommt die 50 €-Meldung nicht - aber das zitierte.

Ja, natürlich. Das sollte nicht so bleiben. Soll der Einfachheit halber der Hinweis, dass ab 50,00€ keine Versandkosten anfallen, immer angezeigt werden?

**Comment by frase-git** [comment]
Warte mal, was @XHalbert  dazu sagt.

**Comment by frase-git** [comment]
Mir ist noch etwas aufgefallen:
In Step 1 war bisher der Warenwert (Summe) in `<strong>` eingebettet.
Das ist jetzt nicht mehr so. Sieht etwas "dünn" aus.
Die einzelnen Artikelsummen sind in `<b>`.
Falls du änderst, dann könntest du bitte aus diesen `<b>` noch `<strong>` machen?
(Das spielt u.U. eine Rolle bei bestimmten Templates.)

**Comment by frase-git** [comment]
`8,024275504594361`
Diese per Rechner errechnete MwSt. wird (falsch) gerundet zu:
`8,03`

Das Beispiel lautet (ohne Gebühren, ohne Versandkosten)
```
[19%] | 49,95 € = 7,975210084033613
[7%] | 0,75 € = 0,0490654205607477
```
Rundet man allerdings **vor** der Addition, dann stimmen die `8,03`.

Und je länger ich es anschaue, denke ich: Es ist in Ordnung. ;-)

**Comment by cmb69** [comment]
> Falls du änderst, dann könntest du bitte aus diesen `<b>` noch `<strong>` machen?

Erledigt mit 5aa18be.

> Diese per Rechner errechnete MwSt. wird (falsch) gerundet zu:

Ich errechne hier 7,98 (voll) + 0,05 (reduziert) = 8,03. Klar, wenn man nicht vorher auf Cent rundet, dann kommt man zu dem von dir errechneten Ergebnis. Aber das Finanzamt möchte doch, dass volle und reduzierte MwSt. separat ausgewiesen werden, und 7,98 + 0,05 = 8,02 geht gar nicht.

**Comment by frase-git** [comment]
Sorry, das habe ich schon festgestellt. Siehe oben.
War nur im ersten Moment verwirrt.
Schadet aber auch nichts, mal kurz drüber nachzudenken.

**Comment by frase-git** [comment]
> Erledigt mit 5aa18be.

Danke.
Das ist jetzt im Master?
Im decimal-Branch nicht - oder?

**Comment by cmb69** [comment]
> Sorry, das habe ich schon festgestellt. Siehe oben.

Ah, da hatte mein Browser nicht aktualisiert. Ich habe mir gestern darüber den Kopf zermartert, und kam irgendwann zu dem Schluss, dass es so wohl wirklich die korrekteste Berechnung ist, und vermutlich die einzige, die mit präzisen Dezimalzahlen überhaupt vernünftig realisierbar ist.

> Das ist jetzt im Master?
Im decimal-Branch nicht - oder?

Ja, genau. Ich könnte den decimal-Branch rebasen, aber dann müsste ich force-pushen, was ich eigentlich lieber vermeide. Und diese kleine Änderung sollte beim späteren Mergen automatisch eingespielt werden.

**Comment by frase-git** [comment]
Nochmal zum Spruch mit den 50 €.
Ginge es nicht, wenn im Step 1 schon klar ist, dass keine Versandkosten anfallen, dass nur da steht:
Alle Preisangaben inkl. Mehrwertsteuer.
Und das auch nur wenn mit taxis gedealt wird?

Und auch hier muss ich mich korrigieren.
Zu diesem Zeitpunkt ist ja das Lieferland noch nicht bekannt :(

**Comment by cmb69** [comment]
> Zu diesem Zeitpunkt ist ja das Lieferland noch nicht bekannt :(

Kein Problem, solange wir die länderspezifische Obergrenze nicht einführen. Dann wäre folgendes möglich:

> Ginge es nicht, wenn im Step 1 schon klar ist, dass keine Versandkosten anfallen, dass nur da steht:
Alle Preisangaben inkl. Mehrwertsteuer.
Und das auch nur wenn mit taxis gedealt wird?

Erforderte aber zwei weitere Sprachvariablen (wenn ich's recht überblicke), und die Logik ist etwas komplexer.
