### ISSUE TITLE
Inconsistent localization of the RHS checkout buttons

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#115]
Die rechten Schalter beim Checkout sind sehr inkonsistent lokalisiert.

DE: weiter → weiter → jetzt kaufen!
EN: order now → next → send order

Besonders verwirrend finde ich "order now" im englischen. Da wird doch gar nichts bestellt. IMHO könnten die Buttons für Schritt 1 & 2 immer "weiter"/"next" heißen. Und statt "send order" fände ich "buy now!" auch griffiger.

**Comment by frase-git** [comment]
👍 
Ich vermute, dass der Shop schon durch viele deutsche Hände gegangen ist. das Englische blieb irgendwie auf der Strecke.

**Comment by cmb69** [comment]
> Ich vermute, dass der Shop schon durch viele deutsche Hände gegangen ist. das Englische blieb irgendwie auf der Strecke.

Ja, das wird's wohl sein. Ich habe daher auch gleich "previous" zu "back" geändert, was das dt. "zurück" besser wiedergibt.
