### ISSUE TITLE
"Sofortüberweisung" darf nicht einziges Gratis-Bezahlverfahren sein

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#116]
Siehe https://www.heise.de/newsticker/meldung/BGH-Sofortueberweisung-darf-nicht-einziges-Gratis-Bezahlverfahren-sein-3777580.html?wt_mc=rss.ho.beitrag.atom

Ich weiß nicht, inwiefern das auch für Paypal gilt, aber vielleicht sollten wir das in Doku aufnehmen? Auch der vorletzte Abschnitt über den neuen Gesetzentwurf sollten wir ggf. berücksichtigen.

(Off Topic: bei den Payment-Modules sollten wir wohl auch aufstocken)

**Comment by frase-git** [comment]
> Bei "Sofortüberweisung" müsse der Verbraucher dagegen einem Dritten sensible Kontozugangsdaten mitteilen und in den Abruf weiter Kontoinformationen einwilligen, befanden die Richter. Dadurch erhalte der Dienstleister umfassenden Einblick in Finanzdaten, "die auch zur Erstellung von Persönlichkeitsprofilen genutzt werden könnten". Zudem müsse der Kunde der Sofort AG personalisierte Sicherheitsmerkmale wie PIN und TAN mitteilen. Dies berge "erhebliche Risiken für die Datensicherheit" und eröffne große Missbrauchsmöglichkeiten. Den Kunden müssten also weitere kostenlose Zahlungsmöglichkeiten angeboten werden.

Das trifft für PayPal nicht zu. Wer den Knopf drückt hat's schon. Und es ist ein _übliches_ Verfahren.
Aber im Ernst:
Wir sind doch keine Rechtsberatung. Wir können doch nicht bei jedem neuen Richterspruch den Shop updaten.

Was meint ihr?
Soll ich im Wiki unter Tipps als ersten Punkt sowas ähnliches schreiben wie:
Bevor du einen Shop eröffnest, informiere dich über die aktuelle Rechtslage in deinem Land ...

**Comment by XHalbert** [comment]
> Wir können doch nicht bei jedem neuen Richterspruch den Shop updaten.

find ich auch, aber...

> Bevor du einen Shop eröffnest, informiere dich über die aktuelle Rechtslage in deinem Land ...

das ist wohl zu allgemein und daher eher überflüssig.

Sinnvoll finde ich trotzdem, ein kurzer Hinweis im Wiki, "dass (je nach Land) möglicherweise mind. 1 kostenlose Bezahlart anbegoten werden muss".
Feste Vorgaben im Shop finde ich nicht nötig.
PS: Paypal ist zwar kostenlos, aber auch hier muss der Kunde Daten eingeben... ("die auch zur Erstellung von Persönlichkeitsprofilen genutzt werden könnten")

**Comment by XHalbert** [comment]
Auf jeden Fall finde ich es sinnvoll, in der config 
"Cash-in-advance" auf 0,00  voreinzustellen

**Comment by frase-git** [comment]
ist momentan auf `-3,00`
das ist besser als 0,00

**Comment by XHalbert** [comment]
stimmt, minus übersehen

**Comment by cmb69** [comment]
> Soll ich im Wiki unter Tipps als ersten Punkt sowas ähnliches schreiben wie:
Bevor du einen Shop eröffnest, informiere dich über die aktuelle Rechtslage in deinem Land ...

Ja, das erscheint mir sinnvoll – vielleicht sogar in der Hilfedatei. Und ich fände es gut, wenn das zwar knapp und allgemein gehalten wird, aber doch sehr deutlich und eindringlich vermittelt wird. Ich denke, damit sichern wir uns zusätzlich ab, und auch für Anwender kann es nützlich sein zu begreifen, dass zumindest hierzulande Online-Shopping doch recht streng reguliert ist.

**Comment by frase-git** [comment]
[Erster Entwurf](https://github.com/cmsimple-xh/xhshop/wiki/Tipps#online-shopping-ist-gef%C3%A4hrlich).
Ihr dürft bei besseren Ideen gerne ändern.

**Comment by cmb69** [comment]
> Erster Entwurf.

Gefällt mir!

Stichwort Datenschutz: sollen wir noch genau erklären, was mit den eingegeben Daten passiert? Eben dass während des Bestellvorgangs erhobene Daten nur *temporär* in einer Session gespeichert werden, und diese beim Kauf gelöscht werden, und dann nur noch die Daten in den E-Mails existieren. Plus, dass die E-Mail-Adresse im Log protokolliert wird. Und dass die Session ein Cookie verwendet, dass beim Schließen des Browsers erlischt.

Mir geht es nicht darum, Nutzern eine Datenschutzerklärung in die Hand zu liefern, sondern lediglich die technischen Hintergründe offenzulegen, damit Anwender eine solche korrekt erstellen können.

**Comment by frase-git** [comment]
technischer Hintergrund / Cookies / logging:
Vielleicht eine neue Seite im Wiki "Technische Hintergründe"
Dort alles erklären.
Da passen dann auch Tipps für zusätzliche Bezahlmethoden für Entwickler hin?

**Comment by cmb69** [comment]
> Vielleicht eine neue Seite im Wiki "Technische Hintergründe"

Ich denke, eher nicht. Infos für Entwickler und Infos für Endanwender sollten besser getrennt werden; der Endanwender versteht sonst schnell nur noch Bahnhof, oder der Entwickler ist gelangweilt, und liest nicht mehr weiter.

**Comment by frase-git** [comment]
erledigt mit Punkt 2 und 3 unter [Tipps im Wiki](https://github.com/cmsimple-xh/xhshop/wiki/Tipps)
