### ISSUE TITLE
system check: shippingcosts page

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#117]
Ist "Versandkosten berechnen?" ausgeschaltet, wird trotzdem überprüft.

Ist keine Seite unter "Sprache" eingetragen, lautet die Meldung (in Gelb):

> Prüfe, dass die Seite '' existiert … Warnung

Tja, da weiß die Prüfung auch nicht, wie sie die Seite nennen soll ;-)

**Comment by cmb69** [comment]
> Ist "Versandkosten berechnen?" ausgeschaltet, wird trotzdem überprüft.

Upps – dabei hattest du extra darauf hingewiesen. Gefixt mit 90441a6.

> Tja, da weiß die Prüfung auch nicht, wie sie die Seite nennen soll ;-)

Stimmt. Die Zusatzinformation würde wohl drei weitere Sprachvariablen erfordern ("Shop-Seite", "AGB-Seite", "Versandkostenseite"). Sollen diese ergänzt werden?

**Comment by frase-git** [comment]
Hm. Da verlasse ich mich auf deine Einschätzung.
Ginge es denn anders?
Oder anders herum: Wären die 3 nicht auch an anderer Stelle nützlich?

**Comment by frase-git** [comment]
Habe gerade noch etwas bemerkt:
Ist Versandkostenberechnung ausgeschaltet, wir trotzdem gemeldet:

> Prüfe, dass die Versandkosten plausibel sind … OK

**Comment by cmb69** [comment]
> Ginge es denn anders?

Man könnte auch den Schlüssel (also `Shop page`, `GTC page` usw.) angeben. Für die Systemprüfung vielleicht die beste Variante.

>Ist Versandkostenberechnung ausgeschaltet, wir trotzdem gemeldet:

Ah, danke! Korrigiert: 610f539
