### ISSUE TITLE
Shipping costs and VAT in 1st step of checkout

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#119]
Im Schritt 1 des Checkout werden derzeit die Versandkosten konkret angegeben. Das passt aber nicht, wenn wir [länderspezifische Versandkosten](https://github.com/cmsimple-xh/xhshop/issues/4) implementieren wollen, da das Zielland erst im zweiten Schritt erfasst wird.

Dazu kommt, dass im 1. Schritt keinerlei Hinweis zur MwSt erfolgt.

Ich schlage daher vor, im 1. Schritt nur einen allgemeinen Hinweis bzgl. MwSt und Versandkosten anzuzeigen, etwa wie von [Frank vorgeschlagen](https://github.com/cmsimple-xh/xhshop/issues/4#issuecomment-315763996):

>> Alle Preisangaben inkl. Mehrwertsteuer zzgl. Versandkosten. Die genauen Versandkosten werden im dritten Schritt aufgelistet.
>
> Oder so ähnlich. "zzgl. Versandkosten" ist dann ein Link zur Versandkosten-Seite, wo alles erklärt ist.

Gibt es da rechtliche Bedenken?

**Comment by frase-git** [comment]
Machte ich jetzt "Daumen hoch" - denktest du vielleicht, ich bedenkte.
Nein. habe keine Bedenken (nur leichten Konjunktivismus).

Die Anzeige muss aber abhängig davon sein, ob MwSt. berechnet wird und/ oder Versandkosten.

**Comment by XHalbert** [comment]
gut

**Comment by cmb69** [comment]
Leider wieder ein Problem: der Mindestbestellwert. Dieser setzt sich zusammen aus Warenwert + Versandkosten, aber wenn die Versandkosten im 1. Schritt noch nicht bekannt sind, dann kann nicht zuverlässig ermittelt werden, ob die Bestellung zulässig ist.

Die Prüfung, ob der Mindestbestellwert eingehalten wird, könnte also erst im 3. Schritt erfolgen. Das ist natürlich weniger benutzerfreundlich.

**Comment by frase-git** [comment]
Mindestbestellwert = Warenwert + Versandkosten stößt mir schon lange auf.
Jetzt gibt es einen Grund, das ernsthaft zu hinterfragen.
Wollen wir es so machen:
`Mindestbestellwert = Warenwert`?

Was ist aufwendiger?

**Comment by cmb69** [comment]
> Mindestbestellwert = Warenwert + Versandkosten stößt mir schon lange auf.

Und eigentlich hast du recht. Den Mindestbestellwert gibt es ja, damit sich der Arbeitsaufwand für die Abwicklung des Verkaufs auch lohnt; die Versandkosten werden aber mehr oder weniger an den Lieferdienst weitergegeben, so dass man davon nichts hat.

**Comment by cmb69** [comment]
> Was ist aufwendiger?

Die Umstellung auf Mindestbestellwert = Warenwert ist vermutlich nicht aufwendiger als den derzeitigen Bug zu beheben, der den Mindestbestellwert = Warenwert + Versandkosten + Gebühr setzt, falls man nach Eingabe der Kundendaten noch mal zum 1. Schritt zurück geht.

**Comment by frase-git** [comment]
> Die Umstellung auf Mindestbestellwert = Warenwert ist vermutlich nicht aufwendiger als den derzeitigen Bug zu beheben,

Dann schlage ich vor es zu machen.
Alberts Stimme ist schon da.

**Comment by cmb69** [comment]
Ist erledigt. Bitte die Doku entsprechend anpassen.

**Comment by frase-git** [comment]
Änderungen sind noch nötig in de.php und en.php:

`$plugin_tx['xhshop']['hints_minimum_order']="( Mindestbestellwert = Warenwert + Versandkosten )";`
wird:
`$plugin_tx['xhshop']['hints_minimum_order']="( Mindestbestellwert = Warenwert)";`

`$plugin_tx['xhshop']['cf_shop_minimum_order']="Mindestbestellwert (Warenwert + Versandkosten) – Eingabe mit Dezimalpunkt";`
wird
`$plugin_tx['xhshop']['cf_shop_minimum_order']="Mindestbestellwert  – Eingabe mit Dezimalpunkt";`

**Comment by frase-git** [comment]
Doku erledigt.

**Comment by cmb69** [comment]
Bei diesem Ticket geht es eigentlich darum, dass die Versandkosten im 1. Schritt noch nicht angezeigt werden. Daher re-open.

**Comment by frase-git** [comment]
Sorry, da habe ich wohl die Übersicht verloren ... kein Wunder ;-)

**Comment by frase-git** [comment]
**Scheint** alles zu funktionieren.
Super!
