### ISSUE TITLE
Clarify license and fix exisiting issues

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#12]
We have to clarify the license under which XHShop will be distributed. In any way we have to heed the license chosen by the original author (i.e. Martin Damken), which is [as follows](http://www.wellrad.de/?Downloads/Lizenz):

>  Das wellrad-Plugin wird unter der Creative Commons Attribution 3.0 Lizenz (CC-A 2.0) veröffentlicht. Das heißt Sie dürfen das Programm kostenlos nutzen, auch kommerziell, verbreiten und ändern – unter der Bedingung, dass Sie im Impressum mit einem Link auf die Projekthomepage (www.wellrad.de) auf seine Herkunft hinweisen.

Therefore we must change respective parts of the source code, e.g. in about,html:

> The plugin is free as long as you add a link to one of the websites above to your template or give it a credit in your impressum page. If this is not o.k. with your project or your customer, please contact me for a commercial license!

The link has to point to www.wellrad.de. We may require another link to the XHShop homepage, but I'd rather make that mandatory.

**Comment by frase-git** [comment]
Tja, deshalb überall mein rotes "Fix Me!" ;-)

Vorschlag:
Nur in der Backend-Hilfe Hinweis auf Martin als ursprünglicher Urheber inkl. Link auf wellrad.de
Lizenz: Eine übliche, wie für die meisten CMSXH-Plugins genutzte.
Autoren: XH-Community
Kein Link notwendig - wohin auch? Gibt es eine "XHShop homepage"?

**Comment by cmb69** [comment]
> Lizenz: Eine übliche, wie für die meisten CMSXH-Plugins genutzte.

Da müsste Martin explizit zustimmen – wir können nicht einfach die vorhandene Lizenz ändern. Ich habe ihn u.a. diesbezüglich aber schon angeschrieben. Jetzt ist Wochenende; im Zweifel also mal ein paar Tage warten. :)

PS: > Kein Link notwendig - wohin auch? Gibt es eine "XHShop homepage"?

Na ja, im Zweifel hier zu Github, falls sich nichts besseres findet.

**Comment by cmb69** [comment]
> Ich habe ihn u.a. diesbezüglich aber schon angeschrieben.

Und er hat geantwortet, dass wir gerne auf eine für uns passendere Lizenz wechseln können, und auch der Backlink zu wellrad.de nicht nötig bzw. eher unerwünscht ist.

Ich würde also GPLv3 als Lizenz vorschlagen, aber Martin doch gerne einen Backlink zu http://zeichenkombinat.de/ spendieren.

**Comment by XHalbert** [comment]
> GPLv3 als Lizenz vorschlagen

ja

> Martin doch gerne einen Backlink zu http://zeichenkombinat.de/ spendieren

der dann vom Nutzer entfernt werden darf?

**Comment by cmb69** [comment]
> der dann vom Nutzer entfernt werden darf?

Ich dachte eher an Links im Backend und der Hilfedatei. Auch beim Wellrad-Shop gab es meines Wissens bisher keinen Backlink im Frontend.

**Comment by XHalbert** [comment]
> beim Wellrad-Shop gab es meines Wissens bisher keinen Backlink im Frontend.

aber im footer musste einer sein, sonst löhnen.

> Links im Backend und der Hilfedatei

ok warum nicht!

**Comment by cmb69** [comment]
> aber im footer musste einer sein, sonst löhnen.

Na ja, genau genommen besagt die [alte Lizenz](http://www.wellrad.de/?Downloads/Lizenz), dass ein Link _im Impressum_ enthalten sein muss. Das ist aber eben eine Möglichkeit, die bestimmte Creative Commons Lizenzen erlauben; unter GPLv3 kann eine solche Anforderung soweit ich weiß (IANAL) nicht durchgesetzt werden – ergo kann man auch gleich darauf verzichten. Die Anwender dürfte es freuen, und dem Anbieter des Plugins nicht wirklich schaden; selbst 1.000.000 Backlinks mit `rel=nofollow` dürften das Suchmaschinenranking nicht beeinflussen (bin allerdings auch kein SEO Experte).
