### ISSUE TITLE
edit product: label shipping unit

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#120]
Ich schlage vor, eine neue Sprachvariable `label shipping unit` einzuführen.

deutsch: `label shipping unit = Versandeinheit`
englisch: `label shipping unit = shipping unit`

Grund:
Bei Artikel bearbeiten steht (in Demo) nur `kg`.
Mir ist während der [Arbeit am Wiki](https://github.com/cmsimple-xh/xhshop/wiki/Artikel-bearbeiten#artikel-bearbeiten) aufgefallen, dass es für den Benutzer u.U. nicht klar ist, was an dieser Stelle gemeint ist.
Es sollte dort stehen:
`Versandeinheit kg:`
oder
`Versandeinheit in kg:`

Gibt es für das deutsche Wort "Versandeinheit" vielleicht einen treffenderen Begriff?
Englisch ist, glaube ich, ganz gut.

**Comment by cmb69** [comment]
> Ich schlage vor, eine neue Sprachvariable label shipping unit einzuführen.

Entweder das, oder wir schmeißen `config_shipping_unit` doch raus, und sprechen nur noch von "Versandeinheit" (na ja, wir bräuchten wohl einen anderen Begriff; dieser ist schon [anderweitig vergeben](https://de.wikipedia.org/wiki/Versandeinheit); vielleicht Versandkosteneinheit?). Im Front-End taucht `config_shipping_unit` jedenfalls nicht mehr auf – es wurde bis vor kurzem im 1. Schritt des Warenkorbs angegeben, aber da wurden ja die Versandkosten komplett gestrichen.

**Comment by frase-git** [comment]
> ... oder wir schmeißen config_shipping_unit doch raus ...

Da denke ich, dass wir das im Backend auf jeden Fall noch brauchen (Versankostenberechnung).
Und eben auch einen passenden Namen an genannter Stelle.
"Einheit pro Versandstück" klingt fürchterlich, trifft es wohl aber ?

**Comment by cmb69** [comment]
> Da denke ich, dass wir das im Backend auf jeden Fall noch brauchen (Versankostenberechnung).

Na ja, die tatsächliche Einheit interessiert den Shop nicht, und ich habe gewisse Zweifel, dass der Shopbetreiber eine bestimmte Einheit wählen kann, die für seine Zwecke perfekt geeignet ist. Oft werden wohl Mischkalkulationen erforderlich sein (Albert hat ja schon einiges darüber ausgeführt), und selbst ein kleiner Verlag wird schwerlich mit "Buch" oder "Band" arbeiten können (vgl. Reclam-Heftchen vs. bebilderte Bibelausgabe). Und auch der Winzer wird mit "Flasche" nicht weit kommen, weil es kleinere und größere Flaschen gibt, die auch wieder unterschiedliche Versandkosten bedeuten dürften.

Ich weiß nicht, ob wir irgendjemanden einen wirklichen Gefallen tun, wenn wir die "Versandkosteneinheit" konfigurierbar machen. Und wenn kein besserer Begriff mehr einfällt, dann können wir das auch einfach "Versandgewicht" nennen (so die programminterne Bezeichnung). Das dürfte für viele gut passen, und andere können ja entsprechend umdenken. Das ließe sich vielleicht besser und leichter dokumentieren und erklären als die jetzige Variante.

> "Einheit pro Versandstück" klingt fürchterlich, trifft es wohl aber ?

Versandstück ist wohl schon anderweitig belegt, siehe http://www.enzyklo.de/Begriff/versandst%C3%BCck.

**Comment by frase-git** [comment]
> Na ja, die tatsächliche Einheit interessiert den Shop nicht ...

Déjà-vu oder was?
Auf die Gefahr hin, dass ich jetzt verprügelt werde.

Versandeinheit xxx:
https://github.com/cmsimple-xh/xhshop/wiki/Artikel-bearbeiten#artikel-bearbeiten

Shipping unit:
https://github.com/cmsimple-xh/xhshop/wiki/Sprache#abschnitt-config

Entweder, es ist völlig falsch, was dort steht, oder es liegt ein Denkfehler vor.

Klärung:
Legt euch eine 2. Sprache Englisch an (Für Christoph Deutsch)
Wählt als Versandeineheit in Deutsch kg - in Englisch Pfund (lb).
Dann versucht mal einem Artikel eine Versandeinheit zuzuordnen - in beiden Sprachen.
Und dann zieht mal Bestellungen in beiden Sprachen durch.
Ihr werdet feststellen, dass die Versandkosten immer falsch sein werden.

Den Shop interessiert die Versandeinheit schon: bei der Versandkostenberechnung.

**Comment by cmb69** [comment]
> Den Shop interessiert die Versandeinheit schon: bei der Versandkostenberechnung.

Nein, den Shop interessiert das nicht wirklich. Wenn man natürlich inkompatible "Versandkosteneinheiten" in verschiedenen Sprachen verwendet, dann gibt's Durcheinander. Für den Shop ist nur die Menge (also die Zahl) relevant; nicht wirklich deren Einheit. Daher mein Vorschlag diese Einheit komplett wegzuabstrahieren, und einfach nur noch von "Versandkosteneinheit", "Gewicht" (ohne Einheit) oder was auch immer zu sprechen. Von mir aus könnte das auch "foo" heißen; wenn ich im wesentlichen nach Gewicht (also eigentlich Masse) verschicke, dann denke ich mir im Kopf halt: "1 foo ist gleich 1 kg". Wenn ich im wesentlichen nach Volumen verschicke, dann denke ich mir: "1 foo ist gleich 1 Liter".

**Comment by frase-git** [comment]
Dann zurück zu Post 1.
Was soll bei Artikel bearbeiten dort stehen?
Mit Sicherheit nicht "foo".
Und wie erklärt man das?

**Comment by cmb69** [comment]
> Was soll bei Artikel bearbeiten dort stehen?

Ich würde dort `label_shipping_unit` schreiben. Wie der Begriff genau heißen soll, muss so oder anders geklärt werden.

> Und wie erklärt man das?

Im Prinzip ganz analog zur jetzigen Funktion. Nur eben statt "wenn du `kg` eingetragen hast" eben "wenn du in `kg` rechnest", etc. Vielleicht ist das aber wirklich für viele schwerer zu verstehen?

**Comment by XHalbert** [comment]
> Wählt als Versandeineheit in Deutsch kg - in Englisch Pfund (lb).

nochmal dazu:
Wenn Jemand sowas macht, braucht er sich natürlich nicht wundern... auf sone Idee muss man erst mal kommen. Aber so gesehen hast du natürlich Recht, Frank.
Und insofern ist wohl eine abstrakte Bezeichnung wie "Versandkosteneinheit" das beste.

**Comment by frase-git** [comment]
Um nicht unnötig Zeit mit Nebnsachen zu verlieren, möchte ich meinen Vorschlag aus Post 1 wiederholen.
"Versandeinheit" ist zwar nicht ganz korrekt, erklärt sich aber aus dem Zusammenhang.
Ich denke vorläufig könnten wir damit leben.

(Außerdem steht dieser Begriff jetzt schon überall)

**Comment by cmb69** [comment]
> Um nicht unnötig Zeit mit Nebnsachen zu verlieren, möchte ich meinen Vorschlag aus Post 1 wiederholen.

Okay, setzt ich dann so um.

> Außerdem steht dieser Begriff jetzt schon überall

Da sollten wir vielleicht ein kleines Glossar ins Wiki stellen, wo v.a. solch vielleicht etwas ungewöhnlichen Namen aufgelistet werden. Das wäre vermutlich auch für die Entwicklung sinnvoll – derzeit geht es z.B.  bei den Begriffen "shipping", "forwarding" und "delivery" drunter und drüber.

**Comment by frase-git** [comment]
Vielleicht ist es euch aufgefallen:
Den ursprünglich geplanten Index habe ich wieder entfernt.
Keine Zeit, und viel händischer Aufwand.

Glossar wäre (ebenso wie Index) sehr nützlich - da gelten aber die gleichen Gründe.

Nachtrag:
Vielleicht findet sich ein bisher unbeteiligter?
Kennt ihr noch wellrad-Nutzer, die man mal direkt ansprechen könnte?
Das könnte ja auch nach-und-nach passieren.

**Comment by cmb69** [comment]
> Glossar wäre (ebenso wie Index) sehr nützlich - da gelten aber die gleichen Gründe.

Okay. Kann ja auch nach 1.0 noch angegangen werden; für 1.0 würde ich auf Umbenennungen im Code sowieso lieber verzichten.

> Vielleicht findet sich ein bisher unbeteiligter?

Ich hoffe, dass sich der ein oder andere nach der Veröffentlichung von 1.0beta1 involviert.
