### ISSUE TITLE
Case-insensitive search may fail

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#123]
Die Suchfunktion ist eigentlich so gedacht, dass Groß-/Kleinschreibung egal ist. Das funktioniert aber nur, wenn auch ein passendes Locale eingestellt ist, wovon wir in der Regel nicht ausgehen können.

Reproducer: Suche im dt. Demo-Shop nach `brötchen` wird fündig; suche nach `BRÖTCHEN` nicht.

**Comment by frase-git** [comment]
Hm, und die Meldung ist auch nicht glücklich gewählt:

> Wir bitten um Entschuldigung!
> 
> Leider sind in der Kategorie zurzeit keine Artikel verfügbar.

Muss man sich entschuldigen?
Muss die Kategorie angegeben werden?

**Comment by cmb69** [comment]
> Hm, und die Meldung ist auch nicht glücklich gewählt:

Wie hast du die denn hinbekommen? Bei mir heißt es:

> Es wurden leider keine Artikel mit dem Suchbegriff blödchen gefunden.

**Comment by frase-git** [comment]
Du Schlingel!
Nach Sync habe ich die gleiche Meldung ;-)

**Comment by cmb69** [comment]
> Nach Sync habe ich die gleiche Meldung ;-)

Ah, das lag an 78b024a.

Die von dir genannte Meldung erscheint aber, wenn eine Kategorie ausgewählt wird, die keine Produkte hat:

> Wir bitten um Entschuldigung!
>
> Leider sind in der Kategorie Trinken zurzeit keine Artikel verfügbar.

Die Entschuldigung erscheint mir angebracht, denn wenn eine Kategorie keine Produkte enthält, dann sollte auch die Kategorie nicht aufgelistet werden. Vielleicht sollten wir die Meldung noch verbessern:

> Wir bitten um Entschuldigung für diesen Bug.

**Comment by frase-git** [comment]
Fritzchens Oma weiß nicht was ein Bug ist.

**Comment by cmb69** [comment]
> Fritzchens Oma weiß nicht was ein Bug ist.

Okay, dann entweder "Programmfehler" oder den Bug fixen.

**Comment by frase-git** [comment]
Wenn's denn geht?
Kategorien, die keine Artikel haben nicht anzeigen?

**Comment by frase-git** [comment]
Habe mal alle Artikel gelöscht.
Shop leer.
Meldung bei Aufruf der Shop-Seite:

> Wir bitten um Entschuldigung!
> 
> Leider sind in der Kategorie Alle Artikel zurzeit keine Artikel verfügbar. 

Obwohl keine Artikel im Shop sind, werden alle Kategorien angeboten :(

**Comment by cmb69** [comment]
> Kategorien, die keine Artikel haben nicht anzeigen?

Zumindest im Frontend sollten die nicht angezeigt werden. Etwas unklar ist mir, ob Kategorien angezeigt werden sollen, die nur Artikel enthalten, die nicht lieferbar sind (der Schlüssel der Fehlermeldung ist nämlich `sold_out`).

> Obwohl keine Artikel im Shop sind, werden alle Kategorien angeboten :(

Bin nicht sicher, ob wir diesen Fall explizit behandeln sollen.

**Comment by frase-git** [comment]
`sold_out` würde ich bei der Frage, ob Artikel in einer Kategorie vorhanden sind, mit `Bestand=0` gleichsetzen.

keine Artikel im Shop:
Ist ein sicher sehr seltener Sonderfall.
Lapidare Meldung: "Keine Artikel vorhanden."

Habe gerade mal die catalog.php entfernt (!)
Abgesehen von Debug, meldet die Systemprüfung:

> Prüfe, dass './content/xhshop/catalog.php' schreibbar ist … Warnung

Später dann wieder alles OK, weil eine leere angelegt wird.

**Comment by cmb69** [comment]
> sold_out würde ich bei der Frage, ob Artikel in einer Kategorie vorhanden sind, mit Bestand=0 gleichsetzen.

Okay. Das habe ich in 2bc6c9a so umgesetzt (nur im Frontend!)

> keine Artikel im Shop:
Lapidare Meldung: "Keine Artikel vorhanden."

Ich gehe mal davon aus, dass ein freigeschalteter Shop ohne Artikel eine Fehlkonfiguration ist. Was aber tatsächlich passieren kann, vor allem wenn wir einmal eine Bestandsführung einführen, ist, dass alle Artikel ausverkauft sind. Das würde ich aber dann auch so melden:

> Pardon! Leider sind wir zur Zeit ausverkauft!

oder ähnlich.

**Comment by frase-git** [comment]
> Okay. Das habe ich in 2bc6c9a so umgesetzt (nur im Frontend!)

Schon gesehen. Gut!

> Das würde ich aber dann auch so melden:
>>     Pardon! Leider sind wir zur Zeit ausverkauft!

Genau so.
(Ich denke immer noch, dass es **zurzeit** heißt. Weißt du da mehr?
Schriebe man **derzeit** oder **momentan**, wäre es ja auch zusammen und klein.)

[Duden](http://www.duden.de/rechtschreibpruefung-online/)

**Comment by cmb69** [comment]
> Ich denke immer noch, dass es zurzeit heißt. Weißt du da mehr?

Hast recht! Mir scheint die dt. Rechtschreibung entwickelt sich schneller als das Internet. ;)

**Comment by cmb69** [comment]
Hm, nun ist mir aufgefallen, dass ein User eventuell eine Kategorie gebookmarkt hat; dann wäre die allgemeine Meldung "Leider sind wir zurzeit ausverkauft" nicht günstig, wenn nur die Artikel dieser Kategorie ausverkauft sind. Umgekehrt macht die Angabe einer Kategorie keinen Sinn, wenn `categories_use_categories` deaktiviert ist. Wird also mal wieder aufwendiger.

Und dann ist mir aufgefallen, dass man händisch (Adresszeile) beliebige Kategorien angeben kann, die dann als leer gemeldet werden. Heulen oder Lachen, das ist die Frage!

**Comment by frase-git** [comment]
Notieren. Vormerken.
Auf 2 verschieben.
Wir können doch nicht mit einer perfekten 1 rauskommen ;-)

**Comment by cmb69** [comment]
> Notieren. Vormerken.
Auf 2 verschieben.

Ja. Aber die XSS Lücke ~~muss gefixt werden~~ habe ich geschlossen.
