### ISSUE TITLE
catalog.php : separator

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#125]
Ist es nötig, den Separator bei jedem Produkt mitzuführen?

**Comment by cmb69** [comment]
Nein, einmal pro Katalog reicht völlig aus. Ich weiß allerdings nicht, ob ältere Wellrad-Versionen u.U. unterschiedliche Separatoren bei einzelnen Produkten speichern konnten (bei Wellrad 1.2.1 ist das wohl nicht so).

Insgesamt stellt sich natürlich die Frage, ob es überhaupt wichtig ist den Separator in `catalog.php` zu speichern. Ich denke, dass die meisten User inzwischen `/` verwenden, und diejenigen die einen anderen Separator gewählt haben, werden diesen wohl auch nur sehr selten umstellen – nur dann müssten halt die Produkt-Seiten neu gewählt werden.

**Comment by frase-git** [comment]
Dann schlage ich vor, den Separator **einmal** in der catalog.php zu speichern.
Ändert sich der, dann kann das der Betreiber schnell dort ändern und die Seiten stimmen wieder.

**Comment by cmb69** [comment]
> Dann schlage ich vor, den Separator einmal in der catalog.php zu speichern.

Okay.

> Ändert sich der, dann kann das der Betreiber schnell dort ändern und die Seiten stimmen wieder.

Das sollte er nicht tun. Der Separator wird ja gerade deshalb explizit gespeichert, damit bei Änderungen an der CMSimple_XH Konfiguration auch *automatisch* die Produktseitenlinks angepasst werden können.

Du kannst es ausprobieren: einfach einen Artikel mit einer Produktseite verlinken, deren Level > 1 ist. Dann `uri_separator` ändern, und die Verlinkung passt immer noch. Du musst allerdings erst syncen, weil da noch ein Fehler war (gefixt mit c8b11f5).

**Comment by frase-git** [comment]
Ah klar. Verstanden.
Muss ich nicht ausprobieren.
(trotzdem "gesynct".)
