### ISSUE TITLE
folder: tmp_orders

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#129]
Eben festgestellt:
Fehlt der Ordner "tmp_orders" gibt es bei Auswahl PayPal in Step 3 einen Crash.
Die Seite wird nur teilweise geladen. Ohne Styles. Ohne Errormeldung.
Nur ganz unten steht klein:
"could not open"

Da müsste noch eine "Vorsorge" her.
Bei PayPal ändert sich ja noch was - oder?
Vielleicht ist das damit erledigt.

**Comment by cmb69** [comment]
> Da müsste noch eine "Vorsorge" her.
Bei PayPal ändert sich ja noch was - oder?
Vielleicht ist das damit erledigt.

Ich will noch versuchen eine zusätzliche Paypal-EC Integration zu stricken, die dann vielleicht sogar die jetzige ablösen kann. Daher diesen Punkt mal im Hinterkopf behalten.

**Comment by frase-git** [comment]
Gut. Hatte mir schon sowas gedacht.

BTW:
Es gibt nur noch ganz wenige Issues ohne Milestone 2.0 ;-)
