### ISSUE TITLE
Move help to standalone HTML files

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#13]
Ich schlage vor die Hilfe, die derzeit im Backend direkt in der Seite ausgegeben wird, in CMSimple_XH typische standalone HTML-Dateien auszulagern. Das ist für eventuelle Übersetzer gewohnter, und auch individuelles Styling kann leicht angewendet werden, ohne das Pluginstylesheet damit zu füllen.

"Was ist neu?" gehört IMO gar nicht in die Hilfedatei, sondern besser in ein CHANGELOG, das eigentlich hier durch Github-Issues fortgeführt werden könnte.

"About" könnte im jetzigen Stil erhalten bleiben.

**Comment by frase-git** [comment]
Fühl dich frei ... !

Es gibt ja noch das Problem, mit den Backend-Tabs. Die habe ich **für sehr kleine Viewports** nicht passend gekriegt. "Hilfe" kann unter bestimmten Bedingungen schon mal verschwinden.
Da wäre es schon gut, wenn es da keine Unterpunkte gäbe.

Wenn gewünscht, könnte ich mich daran machen. Kleine Hilfestellung, was alles rein soll, wäre gut.
(nur eine Help-Datei - oder? - bzw. 2: help.htm und help_de.htm)

**Comment by XHalbert** [comment]
> Fühl dich frei ... !

Martin wollte schon vor vielen Jahren die "Hilfe" überarbeiten.
Denke für Einsteiger sehr wichtig - bzw. abschreckend, wenns nicht klappt, z.B. wegen den Dateiberechtigungen.

**Comment by cmb69** [comment]
> Wenn gewünscht, könnte ich mich daran machen.

Gerne!

> Kleine Hilfestellung, was alles rein soll, wäre gut.
(nur eine Help-Datei - oder? - bzw. 2: help.htm und help_de.htm)

Wenn die Datei nicht zu groß wird, dann nur eine pro Sprache. Und bezüglich Inhalt *kannst* du dich gerne an einem meiner Plugins orientieren – ist immer das gleiche (und gewiss ausbaufähig).

**Comment by frase-git** [comment]
Mach ich - mit Bitte um Geduld, da sich ja noch einiges ändert.

Dabei fällt mir auf:
Wenn die Sprachpflege noch hinzukommt, was machen wir mit den Nav-Tabs in der Plugin-Konfiguration?
Das müsste sich ja dann ändern - oder?
Auch, wenn es mir nicht gefällt: Wir sollten hier vielleicht auf das XH-übliche Plugin-Menü zurückfallen?

**Comment by XHalbert** [comment]
hab grad gefunden:
https://cmsimpleforum.com/viewtopic.php?f=16&t=4100&start=10
den "temp_orders"-Ordner auf chmode 777 gesetzt habe, in der readme steht 666, muss man erstmal drauf kommen...

**Comment by frase-git** [comment]
> den "temp_orders"-Ordner auf chmode 777

Bitte mal im Auge behalten, damit ich das in der Hilfe nicht vergesse - bin schon älter ;-)

**Comment by cmb69** [comment]
> Auch, wenn es mir nicht gefällt: Wir sollten hier vielleicht auf das XH-übliche Plugin-Menü zurückfallen?

Geht mir ganz genauso (das Standard-Menü gefällt mir nicht, aber es ist vermutlich dennoch sinnvoll dieses zu verwenden). Auf jeden Fall kann man schon jetzt direkt per Admin-Menü in die Spracheinstellungen wechseln.

> den "temp_orders"-Ordner auf chmode 777 gesetzt habe, in der readme steht 666,

0666 ist für einen Ordner i.d.R. fraglich, weil er dann nicht auflistbar ist (opendir() etc.) Wenn der FTP-User und der PHP-User der selbe ist, dann reicht hier 0755; 0777 braucht man nur, wenn der FTP-User nicht gleich dem PHP-User ist, und die Berechtigungen per FTP gesetzt werden, aber Schreibrechte für den PHP-User benötigt werden (oder umgekehrt). Ich dokumentiere daher schon seit längerem vereinfacht "vergeben Sie Schreibrechte für …" (vielleicht bessere Formulierung kürzlich bei Manu gesehen: "gewähren" statt "vergeben").

**Comment by cmb69** [comment]
Mittlerweile denke ich es wäre vielleicht sinnvoll, die ausgelieferte Hilfedatei aus Teilen des Wiki automatisch zu erstellen. Ich sehe schon jetzt eine Reihe von speziellen Tipps, die vermutlich nicht alle in die Hilfedatei kommen sollten. Dann könnte man aber auch gleich das Wiki zur primären Dokumentationsquelle machen. Und von mir aus auch Deutsch als Wiki-Sprache wählen – ich mache mir wenig Illusionen, dass der XHShop auch außerhalb des deutschen Sprachraums wirklich relevant ist oder sein wird.

**Comment by frase-git** [comment]
siehe hier https://github.com/cmsimple-xh/xhshop/issues/49
