### ISSUE TITLE
Don't break value and unit

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#133]
![screen_blank](https://user-images.githubusercontent.com/24246330/28581009-66fc0a22-7161-11e7-940c-777537b28a6a.png)

Was meint ihr?
Ignorieren wir das oder fügen wir immer zwischen Zahl und Einheit (Währung) ein `&nbsp;` ein? Besser `&#8201;` oder `&thinsp;`

Und nebenbei: zwischen 7% gehört zumindest ein thin-Leerzeichen. Das ignoriere ich geflissentlich auch öfters mal.
Wetterkarte ARD Durchlauf:
manchmal so: `Hamburg 7 ° C`
manchmal so: `Hamburg 7° C`
manchmal so: `Hamburg 7 °C` - so wäre es wohl richtig, wenn es ein "dünnes" wäre.

Und da ich nun schon dabei bin:
`1 x 9,99` hier haben wir ein normales x (Iks) dazwischen.
Theoretisch gehört da ein Multiplikationszeichen hin &#10005; (`&#10005;`) oder fett &#10006; (`&#10006;`)
Aber bitte jetzt nicht verrückt machen lassen. Das ist Kosmetik.

**Comment by cmb69** [comment]
Hm, ein [THIN SPACE](http://www.fileformat.info/info/unicode/char/2009/index.htm) ist elegant, löst aber das Umbruch-Problem nicht. Wie wäre es statt dessen mit einem [NARROW NO-BREAK SPACE](http://www.fileformat.info/info/unicode/char/202f/index.htm)? Der Font-Support für diese beiden Spaces ist vergleichbar gut.

**Comment by frase-git** [comment]
> Wie wäre es statt dessen mit einem NARROW NO-BREAK SPACE?

Sehr einverstanden!
du meinst `&#8239;` = 10,00&#8239;€ | 7&#8239;%

Es gibt viele Seiten zum Thema. [Diese](https://www.mediaevent.de/tutorial/sonderzeichen.html) fand ich eben und gut.
