### ISSUE TITLE
"vat." in rtf & csv

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#136]
In RTF und CSV erscheint vor dem Steuersatz "vat.".

Könnte doch ganz weg - oder?
`$plugin_tx['xhshop']['labels_get_vat']='vat.';`
ist dann wohl überflüssig?

**Comment by cmb69** [comment]
> Könnte doch ganz weg - oder?

Ja, denke ich auch. Es könnte in `billtemplate.rtf` vielleicht noch manuell eingetragen werden.
