### ISSUE TITLE
salutation, tel & mail in billtemplate.csv

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#138]
Wir sollten wohl Telefon, E-Mail **und** Anrede noch in die billtemplate.csv einfügen.
Und, falls es dazu kommt, auch die Zustimmung zur Mail-Weitergabe.

**Comment by XHalbert** [comment]
sollten da nicht sowieso ALLE Daten rein?

**Comment by frase-git** [comment]
Ja schon.
Im Wiki ist aber genau beschrieben, wie man es sich selbst anpassen kann und wo die Platzhalter zu finden sind.
Ich dachte nur, wir sollten bei der Vorgabe wenigstens die wichtigsten reintun.
Und das sind dann auch schon fast alle.

**Comment by cmb69** [comment]
> Wir sollten wohl Telefon, E-Mail und Anrede noch in die billtemplate.csv einfügen.

Magst du das ausarbeiten?

**Comment by frase-git** [comment]
[billtemplate.zip](https://github.com/cmsimple-xh/xhshop/files/1179832/billtemplate.zip)

Es gibt ein Problem:
Bei den Anmerkungen wird in Excel immer nur die erste Zeile angezeigt.
Was ich eben entdeckte: Klickt man doppelt auf diese Zeile, werden dann auch die anderen angezeigt.
Microsoft-Verwirrung!?

Öffne ich die angehängte csv mit Notepad++ ist alles da.
Übrigens: Die Leerzeichen vor der Währung könnten Probs machen.
In Notepad++ werden die durch ein leeres Quadrat angezeigt - klar, dieser Zeichensatz hat das nicht.

**Comment by frase-git** [comment]
[2-billtemplate.zip](https://github.com/cmsimple-xh/xhshop/files/1179869/2-billtemplate.zip)

Klar. Mail-Weitergabe Zustimmung zugefügt.

**Comment by cmb69** [comment]
> Bei den Anmerkungen wird in Excel immer nur die erste Zeile angezeigt.
Was ich eben entdeckte: Klickt man doppelt auf diese Zeile, werden dann auch die anderen angezeigt.
Microsoft-Verwirrung!?

Ich denke, das ist "nomal" bei einer Tabellenkalkulation. Da müsste halt die Zeilenhöhe entsprechend angepasst werden; diese Info kann ein CSV aber nicht mitliefern. Vielleicht liegt es auch an den Zeilenumbrüchen (LF vs. CRLF)?

> Übrigens: Die Leerzeichen vor der Währung könnten Probs machen.
In Notepad++ werden die durch ein leeres Quadrat angezeigt - klar, dieser Zeichensatz hat das nicht.

Hm, entweder ignorieren, oder das Trennzeichen konfigurierbar machen (u,U, etwas knifflig), oder dokumentieren, dass es [im Quellcode](https://github.com/cmsimple-xh/xhshop/blob/bba11f4a78bc997890ff8542ba1ea21752ac30e7/classes/View.php#L167) angepasst werden kann.

> 2-billtemplate.zip

Super, danke! (377040e)

**Comment by frase-git** [comment]
ignorieren

**Comment by frase-git** [comment]
[3-billtemplate.zip](https://github.com/cmsimple-xh/xhshop/files/1180253/3-billtemplate.zip)

Man macht eine Sache, die beim ersten Mal schief ging, niemals nur 2 mal.
Immer 3 mal (mindestens).

Es haben die Feen gefehlt!

**Comment by cmb69** [comment]
> 3-billtemplate.zip

Eingespielt (fd6eff0)
