### ISSUE TITLE
categories.tpl update

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#139]
[categories.tpl.zip](https://github.com/cmsimple-xh/xhshop/files/1179072/categories.tpl.zip)

Kleine optische Korrektur im unteren Bereich.

**Comment by cmb69** [comment]
Optisch viel besser, danke! Mittelfristig sollten wir die `<p>&nbsp;</p>`, die auch an anderen Stellen vorkommen, aber durch CSS ersetzen, denke ich.

**Comment by frase-git** [comment]
Gerne.
Dann müssten wir aber noch wesentlich mehr Klassen einführen.
Das CSS würde größer.
