### ISSUE TITLE
Warenkorb: MWSt. und Hinweis

### ISSUE THREAD

**Issue by XHalbert** [cmsimple-xh/xhshop#14]
Bei mir steht im Warenkorb unter den Artikeln:
-----------------------------------------------------------------
Zwischensumme (oder besser Warenwert) 	27,90 €
Versandkosten (25 kg) 	5,90 €
Rechnungssumme 	33,80 €
Enthaltene MWSt.: 19% 	5,40 €
------------------------------------------------------------------
**Hinweis: Versandkosten frei bei einem Bestellwert über 49,99 €.**

Hinweis: Bei Warenwert über 100 € : 10% Rabatt
Gutschrift bei der nächsten Bestellung >> Rabatt-Info
-----------------------------------------------------------------

1. MWSt. anzeigen (bei größeren Beträgen wahrscheinlich Pflicht)

2. Hinweis: "ab 50,- €" wäre mir lieber gewesen, aber das rechnet der Shop nicht richtig

3. Hinweis: vllt. geht es nicht nur mir so, dass ein weiterer Hinweis, mögl. im backend editierbar, sinvoll und wünschenswert wäre

**Comment by cmb69** [comment]
> Hinweis: "ab 50,- €" wäre mir lieber gewesen, aber das rechnet der Shop nicht richtig

Das kann vermutlich leicht umgestellt werden, und versandkostenfrei *ab* erscheint mir auch üblicher als *über*. Eine Konfigoption fände ich aber overkill.

**Comment by XHalbert** [comment]
probiers aus
wenn ich bei mir "ab 50,-" einstellte rechnete er ">50,-"
(gab mal eine böse Nachfrage deswegen...)

**Comment by frase-git** [comment]
> MWSt. anzeigen (bei größeren Beträgen wahrscheinlich Pflicht)

zurzeit sieht es so aus:

![cart-summ2](https://user-images.githubusercontent.com/24246330/27764599-6595665a-5e9d-11e7-89ac-b6687ef09630.png)

Genügt das nicht?

> Hinweis: vllt. geht es nicht nur mir so, dass ein weiterer Hinweis, mögl. im backend editierbar, sinvoll und wünschenswert wäre

Das scheint mir auch sinnvoll. Mindestens optional ein weiterer Hinweis.
Da wahrscheinlich sowieso eine Sprachdatei (XH-like) kommen wird, könnte das dort gepflegt werden - also auch Backend. Vielleicht genau so wie in der Sprachdatei des CMS: Drei Felder Text1, Text2, Text3.
Wenn etwas drin steht wird es angezeigt. Wenn nicht - dann nicht.

**Comment by XHalbert** [comment]
> Genügt das nicht?

doch, ist prima - pardon, hatte ich wegen Hinweis "Unter 20,- €" nicht gesehen
(nebenbei: ich finde MWSt. statt USt. besser, kann natürlich jeder in der Sprachdatei machen wie er will...)

**Comment by frase-git** [comment]
Ja, kann er.
Obwohl es da sicher auch wieder Vorschriften gibt: wann was?
Und was ich gestern gelernt habe; USt darf nicht mit Abkürzungspunkt geschrieben werden.

**Comment by XHalbert** [comment]
der Verbraucher wird wahrscheinlich nicht wissen, was USt bedeutet (ob mit oder ohne Punkt)...
MWSt. / MwSt. / MwSt / oder wie???

**Comment by cmb69** [comment]
> probiers aus

Schon klar, dass es ohne Änderungen am Code nicht geht. Hab's nicht ausprobiert, aber sieht mir so aus als müsste einfach [hier](https://github.com/cmsimple-xh/xhshop/blob/b074574006464a1ae08d57d09f9ed5ab12853836/classes/app/xhs_frontend_controller.php#L82) das `>` durch `>=` ersetzt werden.

**Comment by frase-git** [comment]
> der Verbraucher wird wahrscheinlich nicht wissen, was USt bedeutet (ob mit oder ohne Punkt)...
> MWSt. / MwSt. / MwSt / oder wie???

Ist mir völlig egal. Meinetwegen schreiben wir MwSt. rein. Verantwortung (und Freiheit) liegt beim Betreiber!

P.S.:
Die Mehrwertsteuer ist die besondere Form der Umsatzsteuer ...
http://definition-online.de/abkuerzung-mehrwertsteuer/

**Comment by XHalbert** [comment]
> MwSt. 

ist mein Favorit

**Comment by frase-git** [comment]
```
$plugin_tx['xhshop']['labels_dont_deal_with_taxes']='Als Kleinunternehmer berechne ich nach Par. 19 Abs. 1 UStG. keine Umsatzsteuer.';

$plugin_tx['xhshop']['hints_price_info_no_vat']="Endpreis.<br />USt wird nach &sect;&nbsp;19 UStG.<br>(Kleinunternehmerregelung)<br>nicht erhoben.";
```
Dann müssen wir u.A. hier aufpassen:
... berechne ich nach **UStG** keine **Mehrwertsteuer**
... **MwSt.** wird nach ... **UStG** ... nicht erhoben.

**Comment by XHalbert** [comment]
meines Wissens darf man beides sagen: MwSt. und USt

**Comment by TN03** [comment]
> ![27764599-6595665a-5e9d-11e7-89ac-b6687ef09630](https://user-images.githubusercontent.com/15164878/27768938-b4786a38-5f1f-11e7-9aa0-9e77234e9a1d.png)
Genügt das nicht?

Die Darstellung war auf den ersten Blick für mich unverständlich denn es sieht so aus, als würde sich die Ust. nur auf den Artikel beziehen. Für Versand und Gebühr (Verpackung?) fällt aber auch Ust. an. Die Berechnung scheint aber zu stimmen und auch die Nebenkosten werden versteuert - wenn ich richtig gerechnet habe. Vielleicht zeichnet ihr die Info besser als "Im Rechnungsbetrag enthaltene Ust. 7% / 19%" aus. Den jeweiligen Ust.-Satz beim Artikel würde ich aber auf jeden Fall lassen.
Übrigens: bei gemischtem Versand von unterschiedlich besteuerten Artikeln muss der Steuersatz für Versand (meines Wissens) entsprechend des anteiligen Wertes der Artikel berechnet werden. Ob Martin das schon berücksichtigt hatte müsste man mal austesten.
Bei "Verpackung" gilt das, mit Ausnahmen i.d.R. auch.

**Comment by cmb69** [comment]
> meines Wissens darf man beides sagen: MwSt. und USt

Soweit ich weiß, heißt es aus Sicht des Käufers MwSt. und aus Sicht des Verkäufers USt.

> Übrigens: bei gemischtem Versand von unterschiedlich besteuerten Artikeln muss der Steuersatz für Versand (meines Wissens) entsprechend des anteiligen Wertes der Artikel berechnet werden. Ob Martin das schon berücksichtigt hatte müsste man mal austesten.
Bei "Verpackung" gilt das, mit Ausnahmen i.d.R. auch.

Ja, das wird prinzipiell [alles richtig berücksichtigt](https://github.com/cmsimple-xh/xhshop/blob/e207e07098607f736b0afd8eb58b921ed6526d88/classes/app/xhs_order.php#L84-L104). Die Rechnungen mit `floats` sind aber fraglich.

**Comment by frase-git** [comment]
Holger:
> Vielleicht zeichnet ihr die Info besser als "Im Rechnungsbetrag enthaltene Ust. 7% / 19%" aus.

Gut.
@cmb69 
`$plugin_tx['xhshop']['labels_included_vat']='In der Summe enthaltene MwSt.:';`
"Summe" statt "Rechnungssumme" oder "Rechnungsbetrag" musste ich aus Platzgründen bei kleinen Viewports verwenden. Das ist eine Tabelle und die `td` "drücken".

**Comment by cmb69** [comment]
> "Summe" statt "Rechnungssumme" oder "Rechnungsbetrag" musste ich aus Platzgründen bei kleinen Viewports verwenden. Das ist eine Tabelle und die td "drücken".

Hm, steht das nicht in einem `<p>` unter der Tabelle?

**Comment by frase-git** [comment]
> Hm, steht das nicht in einem `<p>` unter der Tabelle?

Ich mein "Summe" **in der** Tabelle ;-)

**Comment by cmb69** [comment]
> Ich mein "Summe" in der Tabelle ;-)

Ah, verstehe. Aber dort stehen doch gleich obendrüber in entsprechenden Spalten "Zwischensumme" und "Versandkosten (x kg)"; da würde "Rechnungssumme" doch auch noch Platz haben. Außerdem haben diese drei Zeilen jeweils am Anfang eine Zelle mit nur einem `&nbsp;` – das könnte man doch auch noch nutzen (`colspan`).

**Comment by frase-git** [comment]
> Außerdem haben diese drei Zeilen jeweils am Anfang eine Zelle mit nur einem `&nbsp;` – das könnte man doch auch noch nutzen (colspan).

Das ist bei Schritt 1 so. Bei Schritt 3 wird es enger (Schriftgröße, fett ...)
Und "Summe" finde ich besser als "Rechnungssume" - aber: Das kann jeder Betreiber völlig easy in der Sprachkonfig ändern. Je nach Geschmack und Template.
(Die Tabellen muss ich mir sowieso nochmal anschauen ...)

**Comment by cmb69** [comment]
> Das ist bei Schritt 1 so. Bei Schritt 3 wird es enger (Schriftgröße, fett ...)

Ah, stimmt! Und ja, von mir aus kann das auch so bleiben.

**Comment by cmb69** [comment]
> Hinweis: "ab 50,- €" wäre mir lieber gewesen, aber das rechnet der Shop nicht richtig

Das habe ich mir noch mal genauer angeschaut, und das ist ganz offensichtlich Bug #55, der nun gefixt ist.

Ist hier ansonsten noch was zu tun, oder kann das Ticket geschlossen werden?

**Comment by XHalbert** [comment]
da wäre noch (siehe oben)
vllt. geht es nicht nur mir so, dass ein weiterer Hinweis, mögl. im backend editierbar, sinvoll und wünschenswert wäre
bei mir: "über 100 ,- € ... Rabatt...  Rabattlink (keine Verrechnung, nur Gutschrift)

Da fällt mir ein, dass im Forum mal ein Feld für Gutscheincode gewünscht wurde.

**Comment by cmb69** [comment]
Abgesehen von der [oben vorgeschlagenen Änderung](https://github.com/cmsimple-xh/xhshop/issues/14#issuecomment-312485085) (844ded1), habe ich nun auch in den Sprachdateien konsequent zu MwSt./VAT umbenannt (9c7e140).

> vllt. geht es nicht nur mir so, dass ein weiterer Hinweis, mögl. im backend editierbar, sinvoll und wünschenswert wäre

Ich denke, da kannst du das für dich relevante [`hints_prices_X`](https://github.com/cmsimple-xh/xhshop/blob/9c7e1406b52ff202cf4c3669ed67450b2b225830/languages/de.php#L130-L133) anpassen. Also schließe ich dieses Ticket.
