### ISSUE TITLE
Product pages: start page or shop page

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#140]
Wird bei einem Artikel unter `Bestell-Button anlegen auf:` die Startseite gewählt, wird dieser ebenfalls nicht angezeigt, falls die Startseite ohne `?...` aufgerufen wird. Also gleiches Problem, wie beim Warenkorb-Button.

Wir wissen, dass wir das nicht ändern können.
[dokumentiert](https://github.com/cmsimple-xh/xhshop/wiki/Bekannte-Probleme/#startseite-ohne-warenkorb-button)

Das ist eigentlich nur eine Info an euch. Kann also bald geschlossen werden.

**Comment by frase-git** [comment]
`Bestell-Button anlegen auf:`
Hier kann man  auch die **SHOP-Seite** wählen.
Mir scheint das geradezu ein Fehler zu sein.
Wollen wir das ausschließen - oder dem Benutzer überlassen?

**Comment by cmb69** [comment]
> Bestell-Button anlegen auf:
Hier kann man auch die SHOP-Seite wählen.

Das ist natürlich Unfug. Aber das kann wohl technisch nicht schnell gelöst werden. Die Shopseite erst gar nicht anzuzeigen, geht nicht, falls Unterseiten vorhanden sind, die verlinkt werden sollen (was vermutlich ein typischer Fall ist). Und bisher gibt es keine Validierung dieses Formulars (es wird einfach alles geschluckt, was der Shopbetreiber angibt), so dass diese erst nachgereicht werden müsste. Fehler und Warnungen werden erst im Katalog angezeigt, was ich sowieso etwas fraglich finde.

Ich denke, wir sollten es für Version 1.0 den Shopbetreibern überlassen, hier sinnvolle Seiten auszuwählen.

**Comment by frase-git** [comment]
Okay. Das hatte ich mir auch so gedacht.
Ein bisschen klaren Verstand sollten wir dem Betreiber schon zumuten.
Ich schließe das mal.
