### ISSUE TITLE
Add semantic markup for products

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#141]
Eine spezielle Auszeichnung von Artikel (auf den Detailseiten) erscheint wichtig, um Bots relevante Information zu liefern. Google kann damit so genannte "Rich Snippets" generieren und bei Suchen anzeigen, siehe https://developers.google.com/search/docs/data-types/products.

Ich fürchte, dass wir das noch für Version 1.0 liefern sollten. Einfach mal nach "google rich snippets product importance" googeln.

**Comment by frase-git** [comment]
Verschieben.
Martin hatte irgendwo erwähnt, dass automatisch eine Description für den Artikel auf den Detailseiten erstellt wird.
Aber erstens finde ich die Textstelle nicht mehr, und zweitens war das wohl nie umgesetzt.

Textstelle gefunden:
`/plugins/wellrad/help/whatsNew.html`

1.2 -> 1.2.1 (24. Sept 2012):

**Comment by cmb69** [comment]
> Aber erstens finde ich die Textstelle nicht mehr, und zweitens war das wohl nie umgesetzt.

Doch, das wurde umgesetzt, aber funktioniert nicht mehr, seit die Meta-Description aus der Sprachdatei genommen wird, siehe #142.

Darum geht es hier aber eigentlich nicht, sondern um die Rich-Snippets, die z.B. bei einer Suche nach "Dinkelkissen kaufen" prominent angezeigt werden: kleines Bildchen, Preis und gleich der Link zur Website – ich vermute, das kann helfen, mehr zu verkaufen.

**Comment by frase-git** [comment]
> ... ich vermute, das kann helfen, mehr zu verkaufen

Na klar. Auf jeden Fall.
Mir wäre für 1 aber das PayPal-Problem wichtiger.

**Comment by frase-git** [comment]
Nur eine Frage:
In `productDetails.tpl` werden meta-Angaben zum Produkt gemacht.
Finde ich mittlerweile sehr gut!
Was ich nicht finden konnte: `NAME`
Die Description und die Preisangaben sind da (FF Seiteninformationen anzeigen).
Verstehe ich da was falsch?

**Comment by cmb69** [comment]
> Was ich nicht finden konnte: NAME
Die Description und die Preisangaben sind da (FF Seiteninformationen anzeigen).

Das scheint ein Problem des Firefox zu sein. Im Quelltext findet sich nämlich etwa:
````
<h1 class="xhsProdTitle" property="name">XH Splitter HOL / GER</h1>
````
Und wenn ich den gesamten `<article>` aus dem Quelltext ausschneide, und unter https://search.google.com/structured-data/testing-tool prüfen lasse, dann wird der Name angezeigt, und auch sonst nichts beanstandet.

**Comment by frase-git** [comment]
Stimmt. Das scheint ein FF-Problem zu sein.
Habe gerade eine Seite aus der online-Demo checken lassen. Der Name ist da ;-)
Sorry, für die Störung.
