### ISSUE TITLE
Release 1.0beta1

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#146]
Soweit ich es überblicke, kann 1.0beta1 endlich freigegeben werden. :)

Wenn niemand Einwände hat, dann würde ich das am späten Nachmittag/frühen Abend machen. Ich würde mich freuen, wenn ein anderer die deutsche Release-Ankündigung im Forum schreiben würde, kann das aber bei Bedarf übernehmen.

**Comment by frase-git** [comment]
Hi Christoph,
habe leider momentan überhaupt keine Zeit.
Habe aber alles verfolgt.
Die letzten Mergereien habe ich mal schnell durchprobiert: sieht gut aus.
Paypal habe ich nicht getestet. Falls das aber alles funktioniert: Hut ab!

**Comment by cmb69** [comment]
> Paypal habe ich nicht getestet. Falls das aber alles funktioniert: Hut ab!

2 erfolgreiche Tests zu 0 heißt natürlich noch lange nicht, dass alles okay ist, aber es geht ja um eine Beta-Version, und die vielen Log-Einträge sollten helfen, eventuelle Probleme in den Griff zu bekommen.

> habe leider momentan überhaupt keine Zeit.

Kein Problem. :)

**Comment by frase-git** [comment]
> Ich würde mich freuen, wenn ein anderer die deutsche Release-Ankündigung im Forum schreiben würde ...

Einfach deine Standard-Ankündigung mit Wiki-Hinweis.
Keine Details.
