### ISSUE TITLE
Additional fields in contact data

### ISSUE THREAD

**Issue by XHalbert** [cmsimple-xh/xhshop#15]
1. Ich benötige diese Felder (und könnte mir vorstellen, dass es anderen auch so geht...)
![neu-4](https://user-images.githubusercontent.com/29812782/27764522-f1ce56ec-5e9b-11e7-96e4-f4d7d90fd1d7.JPG)
das könnte ich machen

2. ein paar im backend benennbare "besondere Wünsche" wär auch nicht schlecht
![neu-6](https://user-images.githubusercontent.com/29812782/27764551-73dcaed6-5e9c-11e7-902f-763a989b2351.JPG)
(die hab ich nicht ins backend reingekriegt...)

**Comment by frase-git** [comment]
Ja, einiges davon ist schon wichtig.
Mir stößt z.B. jedesmal auf, wenn man keine Anrede hat. Es ist heutzutage nicht leicht aus dem Vornamen ein Geschlecht abzuleiten. Telefoniert man dann, oder schreibt oder wasauchimmer, man weiß nie wie man anreden soll. Deshalb mache ich bei Kontaktformularen oft mit advform ein Dropdown mit Frau und Herr (und sonst nix) und das obligatorisch. Wer seinen Dr. mit angeben will, kann das vor dem Vornamen tun.

E-Mail Zustimmung für DHL dürfte auch wichtig sein.

**Comment by XHalbert** [comment]
> Dropdown mit Frau und Herr

und Firma
:)

**Comment by cmb69** [comment]
Ich denke ein paar Felder sollten ergänzt werden (abweichende Lieferadresse erscheint mir z.B. sinnvoll), aber wir sollten alles möglichst allgemein halten (E-Mail-Zustimmung z.B. nicht für DHL, sondern für den Spediteur), und nicht zu viel dazupacken – sonst bleibt es nicht mehr einfach. Die "besonderen Wünsche" könnten doch auch über die allgemeinen Anmerkungen (textarea) abgehandelt werden.

Konkrekt zum Firmennamen: das finde ich etwas problematisch, denn wenn ein Unternehmen bestellt, handelt sich u.U. um B2B, und dann müsste doch die USt anders gehandhabt werden.

**Comment by XHalbert** [comment]
> B2B, und dann müsste doch die USt anders gehandhabt werden

nein wieso? Ein Unternehmer zahlt auch MWSt. Es gilt nur nicht das Widerspruchsrecht.

> E-Mail-Zustimmung z.B. nicht für DHL, sondern für den Spediteur

klar (in den meisten Fällen wohl eher: Paketdienst)
wäre doch in Sprachdatei?

> Die "besonderen Wünsche" 

so wie ich das gemacht hatte war es eigentlich nicht viel Aufwand. Die Felder habe ich ja erst seit höchstens 1 Jahr, d.h. ich bin ganz schön lange ohne ausgekommen. Es hat sich aber gezeigt, dass die Kunden nur ganz selten etwas in die "Anmerkungen" schreiben. Ein paar Häkchen machen ist viel einfacher.
Ich fänds schön, wenn der Shop die Möglichkeit bietet, mind. einen "besondere Wünsche" (lieber drei) zu definieren in der Sprachdatei ( und ausblendet, wenn dort nichts drin steht)

**Comment by frase-git** [comment]
Mal konkret:
### Wohin sollen wir liefern?
Kundennummer: (optional)
Anrede: -> Select -> leer (selected) | Frau | Mann (required) **HIER NICHT FIRMA!**
Vorname: (required)
Nachname: (required)
Firma: (optional)
Adresszusatz / Postnummer: (optional) (was ist das?)
Straße Nr.: (required)
&nbsp;&nbsp;&nbsp;(Postfiliale / Packstation)
Postleitzahl: (required)
Ort: (required)
Land: (Select)
&nbsp;&nbsp;&nbsp;Hinweis zu Versand Land -> (optional / config)

Telefon: (optional)
E-Mail: (required !)
Checkbox (optional)
&nbsp;&nbsp;&nbsp;Ich bin einverstanden, meine E-Mail-Adresse an den Paketdienst weitergzugeben.

Checkbox Sonderwunsch 1:  (optional / config)
Checkbox Sonderwunsch 2:  (optional / config)

Zusatzhinweis 1:  (optional / config)
Zusatzhinweis 2:  (optional / config)

Zahlweise ...
AGB ...
Anmerkung**en** ...

Ein extra-Formular für abweichende Lieferadresse würde ich lieber nicht machen.
Das gibt dann Wirrwarr mit der Überschrift ganz oben (egal, was da steht). Außerdem kann man im Hilfetext für Anmerkungen darauf hinweisen, diese unter Anmerkungen anzugeben.
Was wäre, wenn der Besteller aus Deutschland bestellt (1. Adresse) und aber nach Jamaika abweichend geliefert haben möchte? Da braucht es dann im 2. Formular wieder eine Länderauswahl. Versandkosten?
Das würde mächtig kompliziert.

Firmenname als optionales Feld finde ich okay - man liefert aber an eine natürliche Person (Frau/Herr Vorname Name = befugter Einkäufer einer Firma). Hinweis irgendwo (AGB oder z.B. als Zusatzhinweis 1/2): Händlerkonditionen bitte erfragen (E-Mail).

**Comment by XHalbert** [comment]
das ist doch schon mal was

> Adresszusatz / Postnummer: (optional) 

ist z.B. "c/o Müller" oder "2. Hinterhof rechts", "Postnummer" ist eine persönliche Kunden-ID bei DHL-kunden notwendig bei Lieferung an Packstation oder Postfiliale. Das wird oft genutzt. Kann in der Sprachdatei einfach nur "Adresszusatz" sein. Wenn der Shopbetreiber DHL hat, kann er ja "Postnummer" hinzufügen 

Telefon: (required)  oder config - sollte (für Rückfragen)
E-Mail: (required)   muss (für Emailbestätigung)

(Checkbox nur klickbar, wenn E-Mail eingetragen)  entfällt

> abweichende Lieferadresse:

für mich ein absolutes Muss. Jamand bestellt etwas, will das Paket aber auf der Arbeit entgegen nehmen, oder bestellt etwas, und will, dass das Paket direkt zu der Schwiegermutter geliefert wird...

> Lieferadresse in Anmerkungen: 

was hier eingetragen wird, kann nicht automatisch in Datenbank übernommen werden, ist wirklich etwas zu primitiv. Außerdem schreiben die Leute dann oft komische Sachen, wenn keine Felder vorhanden sind, z.B. keine PLZ. Hab ich bevor ich die Felder eingefügt habe, oft genug erlebt, glaub mir.

> 1. Adresse DE, 2. Adresse Ausland (oder umgekehrt...)

 stimmt ist doof - aber wäre eine zweite Länderauswahl wirklich so viel schwieriger zu realisieren? 
Für Versandkostenberechnung: Wenn 2. Land leer, dann erstes Land, sonst 2. Land 

> "cmb" - B2B, und dann müsste doch die USt anders gehandhabt werden

ergänzend nochmal dazu: 
Ein Unternehmer, egal ob natürliche Person oder juristische Person, z.B. GmbH, zahlt auch MWSt., diese muss in der Rechnung ausgewiesen sein, außer wenn der Shopbetreiber Kleinunternehmer ist, dann muss stehen, dass keine MWSt. enthalten ist.  (ist im Shop alles erfüllt)
es gibt Sonderregelungen für Auslandslieferung innerhalb EU, wenn Lieferant und Kunde eine USt.-ID haben, dann wird keine USt. berechnet ..., aber das führt wohl zu weit.
Ich denke es ist ok, wenn der Kunde z.B. heißen darf:
 "Firma XH-Firma, Frau G. Müller, Str. PLZ etc."
Problematisch sind reine B2B-Shops, siehe [hier](https://www.ferner-alsdorf.de/it-recht/fernabsatz__b2b-shop-vorgaben__rechtsanwalt-alsdorf__7681/)
Ist aber für mich auch ok, wenn keine Firma eingetragen werden kann

**Comment by frase-git** [comment]
Albert schrieb:
> Adresszusatz ...

Ah, verstehe. Danke.

> E-Mail: (required) muss (für Emailbestätigung)

Da haste aber sowas von Recht. Sofort oben geändert. Sorry - es war spät ...

> stimmt ist doof - aber wäre eine zweite Länderauswahl wirklich so viel schwieriger zu realisieren?
Für Versandkostenberechnung: Wenn 2. Land leer, dann erstes Land, sonst 2. Land

So gesehen, wäre das vielleicht zu realisieren. Mal sehen, was unser XH-Screwdriver dazu sagt. ;-)

**Comment by cmb69** [comment]
> Ein Unternehmer, egal ob natürliche Person oder juristische Person, z.B. GmbH, zahlt auch MWSt., diese muss in der Rechnung ausgewiesen sein,

Aber soweit ich weiß, wird bei B2B immer Netto ausgepreist, und die USt aufgeschlagen; bei B2C wird aber Brutto ausgepreist, und die enthaltene USt angegeben.

> So gesehen, wäre das vielleicht zu realisieren. Mal sehen, was unser XH-Screwdriver dazu sagt. ;-)

Machbar ist das auf jeden Fall, aber wie es halt mit Formularen ohne Framework so ist, muss alles manuell gehandhabt werden, sprich ist halt doch etwas aufwendig.

Insgesamt sollten wir vielleicht mal überlegen, wann etwa Version 1 veröffentlich werden soll. Entsprechend könnten wir dann überlegen, was zeitlich noch machbar ist, und was nicht.

**Comment by XHalbert** [comment]
> soweit ich weiß, wird bei B2B immer Netto ausgepreist

ist wohl üblich. Aber ob das für Shops Vorschrift ist? Fest steht, dass bei B2C der Bruttopreis genannt werden m u s s.
Vllt. lassen wir "Firma" wirklich (vorerst) weg.

**Comment by XHalbert** [comment]
> wann etwa Version 1 veröffentlich werden soll

bald ?
Vers.1 muss nicht perfekt sein. 

Mir wäre für vers. 1 wichtig:
#15 Kontaktdaten siehe oben
#4 Länderversand

mir schon wichtig,  kann aber auch später (falls ihr nicht dagegen seid)
#21 Emailanhänge (Versandbestät., Bewertung)
#20 Paypal-Problem (falls es noch existiert)

Einige weitere Vorschläge sollten nur jetzt schon rein, wenn ein späteres Realisieren zuviel Extra-Aufwand wäre.

PS: Die Bezeichnung "kleiner Shop" gehört der Vergangenheit an.

**Comment by frase-git** [comment]
Wenn ich mir überlege, dass wir von den ersten Ideen zu XH-Split bis zu XH 1.7 mehr als ein Jahr gebraucht haben (ich meine die ersten neueren Ideen - das gab es ja auch schon früher), dann wird mir ganz schwindelig.
Ursprünglich wollte ich wellrad nur ä bissl aufmotzen und unter 1.7 gangbar machen.
Gut, dass wir nun schon grundlegende Änderungen vorgenommen haben (oder noch wollen). Damit sind wir für die Zukunft gerüstet - auch für weitere Erweiterungen.
Ich schlage vor, wir versuchen das bisher Besprochene umzusetzen, vielleicht auch das Ein oder Andere rauszuschmeißen und bald mit alpha1 herauszukommen. Das ist ja auch für alle Beteiligten eine Zeitfrage.
Ein Termin - sagen wir mal 28.07. - setzte automatisch Grenzen für weitere Wünsche.

**Comment by cmb69** [comment]
> ist wohl üblich. Aber ob das für Shops Vorschrift ist? Fest steht, dass bei B2C der Bruttopreis genannt werden m u s s.
Vllt. lassen wir "Firma" wirklich (vorerst) weg.

Ja, denke ich auch. Letztlich ist die Netto-Auspreisung ja auch für die Ausfuhrumsatzsteuer-Sache (#51) nötig, und vielleicht kann beides zusammen erledigt werden.

**Comment by XHalbert** [comment]
Möchte nochmal auf das eigentliche Thema zurückkommen.

ich weiß ja nicht, was ihr von "meinen" Feldern verwenden wollt
hab mal alles hier aufgelistet: [mehr-Felder.zip](https://github.com/cmsimple-xh/xhshop/files/1150914/mehr-Felder.zip)

1. "Firma" soll wohl weg? mir egal
2. neu rein m/w als Auswahl, oder m/w/Firma
3. abweichende Lieferadresse muss, finde ich
4. besondere Wünsche?
5. ein paar in Sprache benennbare "besondere Wünsche" wär auch nicht schlecht (wenn Sprache leer, keine Anzeige, geht das?
Oder wenigstens einen, z.B. "eilige Bestellung" (nebenbei ließe der sich dann bei Bedarf leichter vervielfältigen...)

**Comment by frase-git** [comment]
@cmb69 
Achtung! Bitte nur anschauen!
[preview-customersData.zip](https://github.com/cmsimple-xh/xhshop/files/1151019/preview-customersData.zip)
Wäre - wenn geklärt ist, was alles rein soll - eine solche Vorlage für dich hilfreich oder überflüssig?

**Comment by cmb69** [comment]
> Wäre - wenn geklärt ist, was alles rein soll - eine solche Vorlage für dich hilfreich oder überflüssig?

Ich denke schon. :)

Aber bezüglich dieses Thema hätte ich zwei Wünsche:

* möglichst wenig neue Felder für Version 1 (ist ja nicht nur, dass diese im .tpl ergänzt werden müssen, sondern letztlich müssen sie bis zum Billwriter durchgeschleift werden)
* noch etwas Zurückstellen, weil ich wenigstens noch die Navigation auf GET-Requests umstellen will – sonst flipp ich beim Testen noch aus :)

**Comment by XHalbert** [comment]
dann lass doch einfach (vorerst) die "neuen Felder" ganz

**Comment by frase-git** [comment]
> hilfreich oder überflüssig?
>> Ich denke schon. :)

Na , wat denn nu?
(Schon verstanden)

Dann müssen wir hier und jetzt klären, was für Version 1 unabdingbar ist, der Rest folgt später.

### Vorschlag in dieser Reihenfolge:
**Kundennummer**: (optional)
**Anrede**: -> Select -> leer (selected) | Frau | Mann (**required!**)
**Vorname**: (required)
**Nachname**: (required)
**Firma**: (optional)
**Straße Nr.**: (required)
&nbsp;&nbsp;&nbsp;&nbsp;(Postfiliale / Packstation)
**Adresszusatz / Postnummer**: (optional)
**Postleitzahl**: (required)
**Ort**: (required)
**Land**: (Select)
&nbsp;&nbsp;&nbsp;&nbsp;Hinweis zu Versand Land -> (optional / config)

**Telefon**: (optional)
**E-Mail**: (required)
Checkbox (optional)
&nbsp;&nbsp;&nbsp;&nbsp;Ich bin einverstanden, meine E-Mail-Adresse an den Paketdienst weitergzugeben.

~~Checkbox Sonderwunsch 1: (optional / config)~~ später
~~Checkbox Sonderwunsch 2: (optional / config)~~ später

~~Zusatzhinweis 1: (optional / config)~~ später
~~Zusatzhinweis 2: (optional / config)~~ später

**Zahlweise** ...
**AGB** ...
**Anmerkungen** ...
Vor dem Area Anmerkungen Text:
Tragen Sie hier Anmerkungen zu Ihrer Bestellung ein, z.B. eine abweichende Lieferadresse ...

Weiterhin muss die Überschrift ganz oben geändert werden. Zurzeit steht drin:
"Wohin sollen wir liefern?"
Das sollte geändert werden in z.B. "Ihre Kontaktdaten"

Nicht ganz so wichtig: soll in die Inputs ein placeholder?

### Also jetzt entscheiden!
Wenn Christoph bereit ist (GET-Requests), dann angehen.

**Comment by XHalbert** [comment]
aber wenn jetzt doch neue Felder, dann auch gleich "abweichende Lieferadresse"
aber wie gesagt ...dann lass doch einfach (vorerst) die "neuen Felder" ganz
Länderversand wäre tausendmal wichtiger!!!
Warum?
Weil ich das nicht hinkriege, mehr Felder aber schon...
;)
bin jetzt off bis spät

**Comment by XHalbert** [comment]
> möglichst wenig neue Felder für Version 1 (ist ja nicht nur, dass diese im .tpl ergänzt werden müssen, sondern letztlich müssen sie bis zum Billwriter durchgeschleift werden

wie ich das sehe macht ein einziges neues Feld fast genauso viel Arbeit wie mehrere neue Felder!
Also Felder vielleicht wirklich erstmal zurückstellen. Warum nicht? - s.o.
Allerdings wenn du deine CSV mit Daten füllen willst, wirst du diese Daten wohl "durchschleifen" müssen.

**Comment by frase-git** [comment]
Man könnte vielleicht noch auf Kundennummer, Firma und Adresszusatz verzichten. Die Anrede finde ich allerdings wichtig, da ich das Problem aus der Praxis kenne.

Solche neuen Felder machen natürlich Mehraufwand (durchschleifen). Wesentlich mehr Aufwand machten allerdings, Daten für eine zweite Adressenerfassung (abweichende Lieferadresse, evtl anderes Land usw.). Fände ich zwar auch wichtig, es fehlt da aber wirklich die Zeit. Das zöge noch viel mehr Probleme nach sich, als man es sich anfangs vorstellt.

Außerdem haben wir noch eine sehr große "offene Wunde". Die Länderauswahl hängt noch total in der Luft. Hängt unmittelbar mit Versandkosten usw. zusammen. Da haben wir noch einiges vor uns.

**Comment by cmb69** [comment]
> Die Anrede finde ich allerdings wichtig, da ich das Problem aus der Praxis kenne.

Die können wir gerne hinzunehmen, aber ich weiß nicht, ob ein Select nicht zu speziell ist; zumindest sollte das dann konfigurierbar gemacht werden.

> Die Länderauswahl hängt noch total in der Luft. Hängt unmittelbar mit Versandkosten usw. zusammen.

Meinst du https://github.com/cmsimple-xh/xhshop/issues/4#issuecomment-313135670? Da mach ich mich mal dran.

**Comment by XHalbert** [comment]
@frase-git da stimme ich dir natürlich zu.
Meinetwegen kann unser Chirurg entscheiden, ob er erst die "offene Wunde" versorgen will oder "mehr Felder".

**Comment by frase-git** [comment]
> Meinst du #4 (comment)? Da mach ich mich mal dran.

Genau.

**Comment by frase-git** [comment]
> Die können wir gerne hinzunehmen, aber ich weiß nicht, ob ein Select nicht zu speziell ist; zumindest sollte das dann konfigurierbar gemacht werden.

Jetzt steh ich aufm Schlauch.
Was meinst du mit konfigurierbar?

Das Select soll default leer sein und wenn leer, dann gehts nicht weiter.
Es soll dazu dienen, herauszufinden, ob man es mit Frau oder Mann zu tun hat (das dürfte die meisten Fälle abdecken).
Mehr nicht, aber auch nicht weniger.

**Comment by XHalbert** [comment]
> herauszufinden, ob man es mit Frau oder Mann zu tun

und wenn jemand das nicht verraten will?
Mal ehrlich: braucht der Shopbetreiber das für die Bearbeitung? Ich jedenfalls kann darauf verzichten und würde das "erforderlich" entfernen. Man könnte auch noch Blugruppe, Geburtstag, sex. Vorlieben etc. abfragen...

**Comment by frase-git** [comment]
> Mal ehrlich: braucht der Shopbetreiber das für die Bearbeitung?

Konkreter Fall:
**Elisa** Müller hat bestellt.
Es musste eine Rückfrage per Mail erfolgen, weil etwas anderes unklar war.
Text:
Sehr geehrte Frau Müller ...

Rückantwort:
Ich bitte Sie, mich nicht mit Frau anzureden ...

Mit ausländischen Namen wird das noch schlimmer.

[Lesetipp](http://www.beliebte-vornamen.de/3841-uni.htm)

**Comment by cmb69** [comment]
Der Hintergrund für die Anrede ist klar, und auch sinnvoll, aber ich habe da auch gewisse Bedenken. Zumindest ausschließlich Mann/Frau anzubieten, dürfte nicht genügen, siehe z.B. http://blogs.faz.net/biopolitik/2011/09/30/ein-geschlecht-mit-x-australien-macht-s-moeglich-200/. Und was ist mit Fräulein? Hierzulande wohl nicht mehr üblich, aber anderswo? Daher mein Vorschlag, das konfigurierbar zu machen; vielleicht eine Sprachvariable `salutation` als Semikolon-getrennte Liste, die der Shopbetreiber nach Belieben anpassen kann. Die könnte dann `Herr;Frau` oder `;Herr;Frau` oder auch `das geht sie nichts an;Herr;Frau` lauten.

**Comment by frase-git** [comment]
Vielleicht nicht so kompliziert.
Einfach: Anrede erfordern? ja/nein.
Wenn ja, dann wie beschrieben und gerne **plus** "X".
Aber mit leerem Feld, damit eine bewusste Auswahl getroffen wird.
Es wird wieder schwer, dem User zu erklären, was `;Herr;Frau` mit dem Semikolon vorne bedeutet.
Fräulein fällt weg. Exzellenz, Dr. usw. kann vor den Namen oder Vornamen gesetzt werden.

BTW:
mehr als 50% beachten Vorname und Nachname nicht und tragen ein, was sie gewohnt sind. Die Bürokratie-affinen schreiben prinzipiell in der Reihenfolge Name Vorname, egal was das Feld verlangt ;-)

**Comment by XHalbert** [comment]
ja was es alles gibt...
Übrigens mit meiner liberalen Einstellung, die u.a. viel Verständnis für Datenschutzbedenken der Kunden aufbringt, hatte ich früher die Tel.-Nr. optional gemacht. Meis ließen die Kunden das dann frei. Ist aber doof, wenn es mal auf die Schnelle eine Rückfrage gibt. Seit einiger Zeit ist Tel. wieder "erforderlich", und beschwert hat sich noch keiner, allerdings kommt es vor, dass eine falsche Nr. angegeben wird. Ich habe auch schon Bestellungen von Vorname "Ano" Name "Nym" erhalten, das wurde problemlos von DHL zugestellt. 
Das nur am Rande. Es ist wohl allgemein üblich, "Anrede" abzufragen... von mir aus!

**Comment by cmb69** [comment]
> Es wird wieder schwer, dem User zu erklären, was ;Herr;Frau mit dem Semikolon vorne bedeutet.

Okay. Von mir aus auch so wie von dir vorgeschlagen.

> Exzellenz, Dr. usw. kann vor den Namen oder Vornamen gesetzt werden.

Nächstes Problemchen: 
````
Hallo Christoph Becker,
vielen Dank für Ihre Bestellung!
````
Da stünde dann u.U. `Hallo Max Dr. Mustermann`. Ums einfach zu halten, würde ich Titel ganz ignorieren (wer diesen angeben will, okay, aber eben nicht explizit darauf hinweisen). Und das grundsätzliche Problem mit Vor- und Nachname ignoriere ich geflissentlich (in einigen asiatischen Ländern ist es üblich den Familiennamen zuerst anzugeben, usw.)

Der Shop deckt schon ein großes Spektrum derjenigen Bereiche beim Programmieren ab, die ich eigentlich lieber meide. Es fehlen eigentlich nur noch Datumsberechnungen.

**Comment by frase-git** [comment]
> Ums einfach zu halten, würde ich Titel ganz ignorieren

korrekt. Das meinte ich mit Dr. Excellenz, Freiherr usw.
Das kann man dort hinschreiben, wo es passt. Also:
```
Vorname: Dr. Emmett L. (Doc)
Nachname: Brown
```
ergibt:
Hallo Dr. Emmett L. (Doc) Brown
oder
```
Vorname: Heinrich Friedrich Karl
Nachname: vom und zum Stein
```

**Comment by frase-git** [comment]
> Es fehlen eigentlich nur noch Datumsberechnungen.

Bin sicher da kommen spätestens im Forum Anfragen.
Kannst dich ja _abwesend_ stellen ;-)))

**Comment by cmb69** [comment]
Damit #4 umgesetzt werden kann, habe ich nun mal im [Branch delivery-address](https://github.com/cmsimple-xh/xhshop/tree/delivery-address) die abweichende Lieferadresse implementiert. Alles nur absolutes Minimum; wird z.B. auch nur ein Feld der abweichenden Lieferadresse nicht ausgefüllt, dann wird die Lieferadresse quasi ignoriert. Schaut's euch bitte mal an.

**Comment by frase-git** [comment]
### Branch delivery-address

Na ja, unten "Lieferadresse" sehr verwirrend.
Sieht aus, als wenn man Normalbesteller zwingen will, die Daten doppelt einzutippen.
Wenn schon, dann nur ein Formular als Standard.
Darunter ein Button: Abweichende Lieferadresse -> bei Klick klappt das zweite Formular aus.
Falls das ausgeklappt ist, müssen beide Formulare geprüft werden.

Hast du dir überlegt, was das alles nach sich zieht, falls wir das so machen?

**Comment by cmb69** [comment]
> Sieht aus, als wenn man Normalbesteller zwingen will, die Daten doppelt einzutippen.

War nur ein schneller Entwurf, und da habe ich mir eine Erklärung ("die folgenden Felder nur ausfüllen, wenn eine abweichende Lieferadresse gewünscht ist") erst mal gespart.

> Darunter ein Button: Abweichende Lieferadresse -> bei Klick klappt das zweite Formular aus.

Und wer kein JavaScript hat, kann keine eingeben? Was ich mir eher vorstellen könnte ist eine Checkbox "abweichende Lieferadresse"; ist diese angehakt, sind die weiteren Felder verpflichtend. Und falls JS verfügbar ist, könnte man die anderen Felder eben toggeln.

> Hast du dir überlegt, was das alles nach sich zieht, falls wir das so machen?

Was zieht es denn nach sich? Ich sehe höchstens ein Problem mit einer abweichenden Lieferadresse in einem anderen Land (und nicht mal da bin ich sicher); das könnte man aber vermeiden, indem gar keine zweite Auswahlbox angeboten wird.

**Comment by cmb69** [comment]
Zu https://github.com/cmsimple-xh/xhshop/issues/15#issuecomment-315611573:

> Kundennummer: (optional)

Finde ich fraglich, denn wenn ich online meine Kundennummer angeben soll, dann erwarte ich eigentlich auch, dass der Rest der Daten automatisch eingetragen wird. Und eine Kundenverwaltung im Shop ist erst mal außen vor. Ich könnte aber damit leben.

> Firma: (optional)

Warum? Es ist doch völlig egal für welche Firma ein *Privat*-Kunde (natürliche Person) arbeitet. Das Feld würde IMO nur sinnvoll sein, wenn wir eine abweichende Lieferadresse einführen, und selbst da frage ich mich, ob wir nicht Vorname/Nachname einfach zu einem Feld zusammenfassen sollten.

> Anrede: -> Select -> leer (selected) | Frau | Mann (required!)
> Adresszusatz / Postnummer: (optional)
> Checkbox (optional)
    Ich bin einverstanden, meine E-Mail-Adresse an den Paketdienst weitergzugeben.

Okay (bei Anrede die an anderer Stelle besprochenen Änderungen).

---

> Telefon: (required) oder config - sollte (für Rückfragen)

Ich habe Zweifel, dass eine erforderliche Telefonnummer irgendwas bringt. Wer sie nicht angeben will, schreibt dann einfach Blödsinn in das Feld, z.B. "geht dich nix an", und eine Telefonnummernvalidierung will zumindest ich mir nicht antun.

**Comment by XHalbert** [comment]
An Kundennummer und Firma hängt mein Herz nicht, beides ist entbehrlich.
Tel.Nr. muss, egal ob required oder optional.

> Vorname/Nachname einfach zu einem Feld zusammenfassen 

Ich kann für Hermes und DHL sagen, dass das kein Problem wäre. Aber es kommt vor, dass beide zusammen sehr lang sind. Bei Hermes gibt es einen Importfehler und bei DHL wird gekürzt, wenn eine bestimmte Länge überschritten wird. Deshalb ist es sinnvoll, Vorname und Name separat zu erfassen (zwei Felder = mehr Zeichen erlaubt)

Möglich ist, Str. und Nr. zusammen zu fassen. Sollte aber nicht gemacht werden, damit Nr. ein eigenes required hat.

Übrigens Tel.Nr.
DHL verlangt bindend eine Tel.Nr. bei Auslandssendungen.

**Comment by cmb69** [comment]
> Aber es kommt vor, dass beide zusammen sehr lang sind. Bei Hermes gibt es einen Importfehler und bei DHL wird gekürzt, wenn eine bestimmte Länge überschritten wird. Deshalb ist es sinnvoll, Vorname und Name separat zu erfassen (zwei Felder = mehr Zeichen erlaubt)

Na ja, da könnte man manuell nachbessern (z,B. den Vornamen abkürzen). Aber gut, wenn wir explizit eine Anrede erfragen, dann ist die Trennung von Vor- und Nachnamen sowieso sinnvoll.

**Comment by cmb69** [comment]
So, Anrede ist implementiert. Ein Problemchen ist, dass es nun z.B. in der E-Mail und der Dankeschön-Seite heißen kann: "Sehr geehrte(r) X Karl Klammer". Und klar: jetzt wo die Anrede bekannt ist, könnte "geehrte" und "geehrter" unterschieden werden. Würde ich aber beides lieber so lassen – uns rennt die Zeit weg.

**Comment by frase-git** [comment]
Isch wer noch forriggd.
(Sorry, ein kleiner Ausbruch.)

Das war doch gar nicht geplant, dass nun überall die Anrede auftaucht.
Macht es doch nur kompliziert.
Die Anrede ist für eine **spätere** Kontaktaufnahme durch den Betreiber gedacht.

Und - auch das wurde schon angesprochen - "sehr geehrte(r)" ist eine Anrede aus der ersten Hälfte des letzten Jahrhunderts. Völlig out. Muss geändert werden.
Text:
Guten Tag, Vorname Name, ...
oder
Hallo, Vorname Name, ...

Keinerlei geschlechtsspezifische Anrede in den automatisch erzeugten Mails.

**Comment by cmb69** [comment]
> Das war doch gar nicht geplant, dass nun überall die Anrede auftaucht.

Gut, dann entferne ich das in den "Rechnungs"- und E-Mail-Templates wieder. Wer möchte, kann es sich dort ja leicht einbauen.

> Und - auch das wurde schon angesprochen - "sehr geehrte(r)" ist eine Anrede aus der ersten Hälfte des letzten Jahrhunderts.

Okay. Und sorry, dass mir das bei den gerade mal 2 oder 3 Kommentaren der letzten Wochen entgangen ist. ;)

> Hallo, Vorname Name, ...

Das ist mir dann doch zu persönlich. "Guten Tag, Vorname Name," fände ich angemessener.

**Comment by frase-git** [comment]
Ich hatte den kleinen Ausbruch, weil du dir so viel Arbeit gemacht hast.
Wir brauchen deine unersetzbare Power anderweitig.
"Guten Tag" ist gut.
Dankeschön-Seite nicht vergessen.

**Comment by cmb69** [comment]
> Ich hatte den kleinen Ausbruch, weil du dir so viel Arbeit gemacht hast.

Das war doch nur ein bisschen Search & Replace. Die Selectbox war wesentlich aufwendiger. :)

> "Guten Tag" ist gut.

Okay. Die Dankeschön-Seite habe ich schon an die E-Mail-Begrüßung angeglichen; die wird dann automatisch.

**Comment by cmb69** [comment]
Ich habe nun den Adresszusatz implementiert, und auch die Überschrift des Formulars geändert.

> Checkbox (optional)
>    Ich bin einverstanden, meine E-Mail-Adresse an den Paketdienst weitergzugeben.

Ist das wirklich nötig? Es werden ja auch andere Infos an den Paketdienst weitergegeben, ohne explizit um Erlaubnis zu fragen. Im Zweifel könnte das auch in die AGBs aufgenommen werden?

**Comment by XHalbert** [comment]
> Ist das wirklich nötig? 

die anderen Informationen, sprich Name und Adresse, müssen ja, sonst ist kein Versand möglich.
Die Emailadresse ist optional, immer mehr Kunden wünschen die "Sendungsoptionen" per Email. Aber Emailadresse ist pesonenbezogene Daten, und darf (eigentlich) nur mit ausdrücklicher Genehmigung weitergegeben werden. Trotzdem gibt es noch etliche Shops, die die Genehmigung nicht abfragen und trotzdem weitergeben. Ich rechne damit, dass es in absehbarer Zeit entsprechende Gerichtsurteile geben wird.
Ich würde nur mit Genehmigung weitergeben. AGB reicht nicht.
Viele Kunden erwarten das!
Fazit: nicht nötig aber wichtig

**Comment by cmb69** [comment]
Ich habe mal gegoogelt, und fand https://www.hk24.de/produktmarken/beratung-service/recht_und_steuern/wirtschaftsrecht/medien_it_recht/datenschutz/1156878:

> Beispiel: Kundenname und –anschrift, eine Telefonnummer für Rückfragen dürfen bei einem Lieferungsvertrag immer erfragt werden. Die Abfrage des Lebensalters und zusätzlich zur Telefonnummer einer E-Mail-Adresse wären hingegen problematisch. Deren Erhebung würde eine förmliche datenschutzrechtliche Belehrung des Betroffenen voraussetzen, siehe unten.

Sprich, bereits das Erheben der E-Mail-Adresse scheint nicht unproblematisch. 🙄

**Comment by XHalbert** [comment]
Da steht aber auch

> Grundsätzlich gilt, dass Erhebung, Verarbeitung und Nutzung von personenbezogenen Daten immer dann zulässig sind, wenn ... der Betroffene eingewilligt hat, § 4 Abs. 1 BDSG.
Ferner gilt das sogenannte „Transparenz-Gebot”. Das bedeutet: Jeder Betroffene muss erkennen können, welche seiner personenbezogenen Daten wann, von wem, zu welchem Zweck und in welchem Umfang erhoben oder in sonst einer Weise verwendet wurden.

Das Erheben einer Emailadresse ist also erlaubt, wenn der Kunde einwilligt UND wenn er erkennen kann, wofür ("für Sendungsoptionen an Paketdienst übermitteln").

Ich werde diese Abfrage auf jeden Fall weiter nutzen, aber ich finde, dass das XH-Shop das ruhig standardmäßig haben sollte.

**Comment by frase-git** [comment]
Rechtlich gesehen, hat hier sicher Albert recht. Erfassen, fragen und bei Einwilligung weitergeben ist OK.
Solange der Haken default **nicht an** ist! Man muss also explizit zustimmen.

Noch ein kleiner "optischer" Hinweis:
In meinen Vorschlägen in diesem Thread habe ich immer eine Reihenfolge für die Datenerfassung genannt.
Anrede, Name(n), Adressblock **und danach** Telefon und E-Mail.
Es ist jetzt so, wie es immer war: der Adressblock ist durch Telefon und E-Mail "zerissen".
Falls ihr ebenso empfindet, sollten wir die Reihenfolge ändern.

**Comment by cmb69** [comment]
Okay, beides gemacht. Bitte prüfen! Kann es dann für 1.0 dabei bleiben, oder müssen noch weitere Felder ergänzt werden?

**Comment by frase-git** [comment]
Ende für 1.0
Für mich sieht's gut aus.
