### ISSUE TITLE
no shipping countries

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#153]
Sprache: `Shipping countries`
Wenn keine Länder eingetragen sind, gibt es in Step 2 eine Selectbox ohne Inhalt.
Bestellung kann nicht ausgeführt werden - **ohne Hinweis** für den Kunden.

System-Check meldet zwar, dass die Versandkosten nicht plausibel sind ... ob das hilft?
Auch Debug meckert:
> NOTICE: Undefined offset: 1
> ... \plugins\xhshop\classes\Controller.php:79

Übrigens: Trägt man etwas falsches ein, z.B. nur `DE` statt `DE=Deutschland`
dann meldet der Sys-Check gar nichts - alles OK.

**Comment by cmb69** [comment]
> Bestellung kann nicht ausgeführt werden - ohne Hinweis für den Kunden.

Na ja, dem Kunden hülfe es nicht wirklich, wenn gemeldet wird, dass der Shop nicht richtig konfiguriert ist.

> Übrigens: Trägt man etwas falsches ein, z.B. nur DE statt DE=Deutschland
dann meldet der Sys-Check gar nichts - alles OK.

Da sollte im Zweifel nachgebessert werden; sprich auch die `Shipping countries` werden explizit auf Plausibilität geprüft.

**Comment by frase-git** [comment]
>Bestellung kann nicht ausgeführt werden - ohne Hinweis für den Kunden.
>>Na ja, dem Kunden hülfe es nicht wirklich, wenn gemeldet wird, dass der Shop nicht richtig konfiguriert ist.

Da hast du zwar recht - trotzdem muss da mindestens ein Hinweis hin:
"Ein Fehler ist aufgetreten. Bitte kontaktieren Sie uns per E-Mail."

**Comment by cmb69** [comment]
> Da hast du zwar recht - trotzdem muss da mindestens ein Hinweis hin:
"Ein Fehler ist aufgetreten. Bitte kontaktieren Sie uns per E-Mail."

Das sehe ich nicht so. Der Fall ist eindeutig eine Fehlkonfiguration, und ein solch fehlkonfigurierter Shop sollte gar nicht verfügbar sein. Statt dessen sollten wir lieber dafür sorgen, dass eine Fehlkonfiguration gar nicht "möglich" ist – im extremsten Fall könnte man den Shop in diesem Fall gar nicht veröffentlichen (egal was bei `published` eingestellt ist). Die Prüfung kostet aber Zeit, und vielleicht geht es auch anders.
