### ISSUE TITLE
Mark required customer data as such

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#158]
Manche Shopbetreiber möchten erforderliche Kundendaten als solche ausweisen. Um das leicht zu ermöglichen, aber flexibel zu bleiben, vergeben wir für alle erforderlichen Felder die CSS-Klasse `.xhsRequired`. Diese kann dann vom Webdesigner gestylt werden.

**Comment by cmb69** [comment]
Closed in dab557f.

**Comment by frase-git** [comment]
[dokumentiert](https://github.com/cmsimple-xh/xhshop/wiki/Tipps#erforderliche-felder-markieren)

**Comment by cmb69** [comment]
Aber siehe https://cmsimpleforum.com/viewtopic.php?f=16&t=12956&p=61563#p61563 (2. Absatz). Sorry, war mir vorher nicht bewusst.
