### ISSUE TITLE
Do not default to a payment method

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#159]
Dem Kunden soll keine Zahlungsmethode aufgedrängt werden, sondern er soll selbst wählen.

**Comment by XHalbert** [comment]
Ich finde das soll der Shopbetreiber entscheiden dürfen. Vllt. hat er eine bevorzugte Zahlmethode?

Also wäre es sinnvoll, im Wiki zu erklären, wie man eine Zahlart vorauswählen kann.

**Comment by frase-git** [comment]
Ich glaube nicht, dass das gut wäre.
Sonst könnten wir auch gleich einen Haken bei "Mail für Paketdienst" machen, die Telefonnummer required und alles andere.
Der Kunde sollte nichts vorgeschrieben bekommen.

**Comment by XHalbert** [comment]
>  einen Haken bei "Mail für Paketdienst" machen

das ist doch was ganz anderes - hier will ich nun wirklich keinen Haken.
Aber wieso eigentlich soll der Kunde nichts "vorgeschrieben" bekommen?
Wie gesagt, das sollte der Shopbetreiber entscheiden dürfen!
Tel. required (meinetwegen mir dem Hinweis "für Rückfragen") hab ich ja schon früher bevorzugt, und wie ich meine auch vernünftig begründet, aber da wurde ich überstimmt.

**Comment by cmb69** [comment]
> Ich finde das soll der Shopbetreiber entscheiden dürfen. Vllt. hat er eine bevorzugte Zahlmethode?

Darüber habe ich auch nachgedacht. Aber bei der bisherigen Variante, hätte der Shopbetreiber die Reihenfolge der Zahlungsmethoden manuell in `config.php` ändern müssen. Da erschien mir Franks Vorschlag schon sinnvoller. Und der Shopbetreiber kann eine bevorzugte Zahlungsmethode noch immer "unterstützen", indem er einen Nachlass für diese Methode gewährt. Ich gehe schon davon aus, dass viele Käufer 1-2 € Nachlass nicht einfach ignorieren.

> Tel. required (meinetwegen mir dem Hinweis "für Rückfragen") hab ich ja schon früher bevorzugt, und wie ich meine auch vernünftig begründet, aber da wurde ich überstimmt.

Ich würde das im Wiki zwar eher nicht dokumentieren, aber man kann [requiredCustomerData ](https://github.com/cmsimple-xh/xhshop/blob/92825bca633811f1d30b4e3bb0c3c1fb6169c448/classes/FrontEndController.php#L16-L18) einfach anpassen (in diesem Fall einfach noch `'phone'` hinzufügen).

**Comment by XHalbert** [comment]
> hätte der Shopbetreiber die Reihenfolge der Zahlungsmethoden manuell in config.php ändern müssen

ja stimmt, daran hatte ich nicht gedacht. Frank dein Vorschlag ist besser.
Bei mir war bisher halt eher zufällig die erste Zahlart auch meine bevorzugte.

> man kann requiredCustomerData einfach anpassen 

danke für den Hinweis, ja das werde ich für meinen Teil sowieso wieder so machen - ich spreche also nicht in erster Linie für mich, sondern wollte andere Shopbetreiber an meiner Erfahrung profitieren lassen, da sich "Tel.Nr. optional" nicht bewährt hat.

**Comment by cmb69** [comment]
> ich spreche also nicht in erster Linie für mich, sondern wollte andere Shopbetreiber an meiner Erfahrung profitieren lassen, da sich "Tel.Nr. optional" nicht bewährt hat.

Vielleicht sollte das dann doch unter [Tipps](https://github.com/cmsimple-xh/xhshop/wiki/Tipps) dokumentiert werden; es muss halt nur klar gestellt werden, dass man wirklich relevante Felder dort nicht entfernen darf.

**Comment by frase-git** [comment]
Eine Checkbox oder einen Radiobutton vorzubelegen, ist wohl auch ein datenschutzrechtliches Problem.
Auf jeden Fall dürfte sowas Verbraucherschützer auf den Plan rufen.
Das ist viel zu leicht zu übersehen.
(wie Kleingedrucktes in hellgrau auf grauem Papier)
opt-in / opt-out

**Comment by cmb69** [comment]
> Auf jeden Fall dürfte sowas Verbraucherschützer auf den Plan rufen.

Die Verbraucherschützer schützen die Verbraucher noch so lange, bis diese nichts mehr zum Verbrauchen kaufen können. Ich kann als Verbraucher da schon lange nur noch den Kopf schütteln.

**Comment by frase-git** [comment]
Leider leben wir in einer ziemlich eigenartigen Welt, der wir uns nicht vollständig verschließen können.
(Ich bin zwar weit raus aufs Land gezogen - das hilft aber auch nicht wirklich.)
Hier ein kurzer Artikel zu "[vorangehakte Checkboxen](http://t3n.de/news/dsgvo-einwilligungen-843918/3/#Ads_BA_CAD3)".

**Comment by cmb69** [comment]
> Hier ein kurzer Artikel zu "vorangehakte Checkboxen".

Interessant. Und klar, das "ich habe die AGB gelesen" darf auf keinen Fall angehakt ausgeliefert werden. Aber was, wenn es nur eine Zahlungsmethode gibt? – Letztlich aber egal, da ich denke, dass das in der Praxis eher die Ausnahme sein dürfte, und wohl jeder damit leben kann, dass der Kunde die gewünschte Zahlweise selbst auswählen muss. :)
