### ISSUE TITLE
Custom attachment for confirmation mail

### ISSUE THREAD

**Issue by XHalbert** [cmsimple-xh/xhshop#16]
Für Gewerbliche Verkäufer gilt:
1. eine AGB als CMSimple-Seite muss vorhanden sein und darf nicht versteckt sein
(z.Zt. wird glaube ich nur das Vorhandensein abgefragt)
2. Eine Widerrufsbelehrung muss meines Wissens mit der Bestellbestätigung verschickt werden.

Ich habe meine einfach in die Sprachdatei gepackt
$lang['mail']['greetings'] = "... BETTEN-BÄR<br /><br /><br />
<b>Widerrufsrecht für Verbraucher</b><br /><br />
(Verbraucher ist jede ...

Sollte man nicht besser ein Textfeld im Backend haben?

**Comment by frase-git** [comment]
zu 1.
Ja. Stimmt.
zu 2.
Das halte ich für ein Gerücht.
Die Bestell-Bestätigung braucht das nicht.
Die AGB müssen die Belehrung enthalten und sie muss hervorgehoben/deutlich sichtbar sein.
(Mehr sage ich nicht ohne meinen Anwalt.) ;-)

Jetzt aber:
Alles können wir den Leuten nicht abnehmen.
Wer einen Shop betreiben will, steht heutzutage sowieso mit einem Bein in der Küche. (bitte mit einem passenden Programm übersetzen).

**Comment by XHalbert** [comment]
> Das halte ich für ein Gerücht.

die Anwälte von http://www.internetrecht-rostock.de/wo-im-internetshop-ueber-widerrufsbelehrung-informieren.htm geben dir wohl recht.

Somit müsste das ja wohl reichen als Minimum (in der Sprachdatei)
![neu-7](https://user-images.githubusercontent.com/29812782/27764970-8022c112-5ea6-11e7-9d32-ba5375ce9ba6.jpg)

Aber das finde ich zu wenig:
Ich habe die AGB und den in ihnen enthaltenen Hinweis auf mein Widerrufsrecht gelesen und bin einverstanden.

**Comment by TN03** [comment]
> zu 2.
Das halte ich für ein Gerücht.
Die Bestell-Bestätigung braucht das nicht.

Die Widerrufsbedingungen müssen 
1. vor Vertragsschluss einsehbar sein und 
2. dem Kunden in Schriftform übermittelt werden. 
Siehe https://www.gesetze-im-internet.de/bgbeg/art_246a__4.html

Zu 2 bietet sich eine Anlage zur Bestellbestätigung oder Rechnung an. 
Falls die schriftliche Übermittlung (Mail, Fax, Brief) nicht erfolgt, beginnt die Widerrufsfrist nicht und verlängert sich auf max. 12 Monate + 14 Tage: https://www.gesetze-im-internet.de/bgb/__356.html

Nein, ich bin kein Experte, wusste das aber aus dem privaten Umfeld.

> Alles können wir den Leuten nicht abnehmen.
Wer einen Shop betreiben will, steht heutzutage sowieso mit einem Bein in der Küche.

Die Frage ist in wieweit der Anbieter des Shops, wenn solche rechtsrelevanten Funktionen angeboten werden, im Zweifel haftbar gemacht werden kann. Meiner Meinung nach steht also u.U. auch der Anbieter der Shopsoftware "in der Küche".

**Comment by XHalbert** [comment]
ja genau, so kenne ich das auch

also warum packen wir die Widerrufsbelehrung nicht in die Email?

Meine als Vorschlag:

`$lang['mail']['greetings'] = "<b>Bei Zahlungsart Überweisung im Voraus</b><br />Wenn Sie Überweisung im Voraus gewählt haben, überweisen Sie bitte den Rechnungsbetrag möglichst bald an: <br /><br />...firma<br />IBAN: ...<br />BIC: ...<br /><br />Nach Eingang der Zahlung wird die Ware verschickt und Sie erhalten von uns eine Versandbestätigung.<br /><br /><b>Bei Zahlungsart Rechnung</b><br />Bitte überweisen Sie nach Erhalt der Ware, die Rechnung liegt im Paket.<br /><br />Mit herzlichen Grüßen<br /><br />...name...\n\n<br />DER CHEF<br /><br /><br />
<b>Widerrufsrecht für Verbraucher</b><br /><br />
(Verbraucher ist jede natürliche Person, die ein Rechtsgeschäft zu Zwecken abschließt, die überwiegend weder Ihrer gewerblichen noch ihrer selbstständigen beruflichen Tätigkeit zugerechnet werden können.)<br />
Vertrag im Sinne der Widerrufsbelehrung: Kaufvertrag durch verbindliche kostenpflichtige Bestellung im Shop)<br /><br />
<b>Widerrufsbelehrung</b><br /><br />
<b>Widerrufsrecht</b><br />
Sie haben das Recht, binnen vierzehn Tagen ohne Angabe von Gründen diesen Vertrag zu widerrufen. Die Widerrufsfrist beträgt vierzehn Tage ab dem Tag an dem Sie oder ein von Ihnen benannter Dritter, der nicht der Beförderer ist, die Waren in Besitz genommen haben bzw. hat.
<br />
Um Ihr Widerrufsrecht auszuüben, müssen Sie uns
<br /><br />
name<br />
... 43a<br />
plz ort<br />
E-Mail-Adresse:   info@...
<br /><br />
mittels einer eindeutigen Erklärung (z.B. ein mit der Post versandter Brief oder E-Mail) über Ihren Entschluss, diesen Vertrag zu widerrufen, informieren. Sie können dafür das beigefügte Muster-Widerrufsformular verwenden, das jedoch nicht vorgeschrieben ist.<br />
Zur Wahrung der Widerrufsfrist reicht es aus, dass Sie die Mitteilung über die Ausübung des
Widerrufsrechts vor Ablauf der Widerrufsfrist absenden.<br /><br />
<b>Folgen des Widerrufs</b><br />
Wenn Sie diesen Vertrag widerrufen, haben wir Ihnen alle Zahlungen, die wir von Ihnen erhalten haben, einschließlich der Lieferkosten (mit Ausnahme der zusätzlichen Kosten, die sich daraus ergeben, dass Sie eine andere Art der Lieferung als die von uns angebotene, günstige Standardlieferung gewählt haben), unverzüglich und spätestens binnen vierzehn Tagen ab dem Tag zurückzuzahlen, an dem die Mitteilung über Ihren Widerruf dieses Vertrags bei uns eingegangen ist. Für diese Rückzahlung verwenden wir dasselbe Zahlungsmittel, das Sie bei der ursprünglichen Transaktion eingesetzt haben, es sei denn, mit Ihnen wurde ausdrücklich etwas anderes vereinbart; in keinem Fall werden Ihnen wegen dieser Rückzahlung Entgelte berechnet.<br />
Wir können die Rückzahlung verweigern, bis wir die Waren wieder zurückerhalten haben oder bis Sie den Nachweis erbracht haben, dass Sie die Waren zurückgesandt haben, je nachdem, welches der frühere Zeitpunkt ist.<br />
Sie haben die Waren unverzüglich und in jedem Fall spätestens binnen vierzehn Tagen ab dem Tag, an dem Sie uns über den Widerruf dieses Vertrages unterrichten, an uns zurückzusenden oder zu übergeben. Die Frist ist gewahrt, wenn Sie die Waren vor Ablauf der Frist von vierzehn Tagen absenden.<br />
Sie tragen die unmittelbaren Kosten der Rücksendung der Waren.<br />
Sie müssen für einen etwaigen Wertverlust der Waren nur aufkommen, wenn dieser Wertverlust auf einen zur Prüfung der Beschaffenheit, Eigenschaften und Funktionsweise der Waren nicht notwendigen Umgang mit ihnen zurückzuführen ist.<br /><br />
<b>Ende der Widerrufsbelehrung</b><br /><br />
<hr /><br /><b>Muster-Widerrufsformular</b><br /><br />
Wenn Sie den Vertrag widerrufen wollen, können Sie dieses Formular oder ein formloses Schreiben verwenden und senden an:<br /><br />
name<br />
...str.<br />
plz ort<br />
E-Mail-Adresse:   info@...<br /><br />
Hiermit widerrufe(n) ich/wir (*) den von mir/uns (*) abgeschlossenen Vertrag über den Kauf der folgenden Waren (*)<br /><br />
________________________________________________________<br /><br />
Bestellt am (*) ____________ / erhalten am (*) _________________<br /><br />
________________________________________________________ <br />
Name des/der Verbraucher(s)<br /><br />
________________________________________________________<br />
Anschrift des/der Verbraucher(s) <br /><br />
________________________________________________________ <br />
Unterschrift des/der Verbraucher(s) (nur bei Mitteilung auf Papier) <br /><br />
_________________________
Datum <br /><br />
*) Unzutreffendes streichen<hr /><br />
";`

**Comment by cmb69** [comment]
> also warum packen wir die Widerrufsbelehrung nicht in die Email?

Soll mir im Prinzip recht sein. Ich würde es aber so machen, dass der Shop einfach eine bestimmte Datei als Anhang verwendet (kann PDF sein), und wenn das Dokument nicht da ist, eben nichts angehängt wird. Und wenn wir überhaupt ein entsprechendes Dokument ausliefern, sollte das besser als Muster gekennzeichnet sein.

> Die Frage ist in wieweit der Anbieter des Shops, wenn solche rechtsrelevanten Funktionen angeboten werden, im Zweifel haftbar gemacht werden kann. Meiner Meinung nach steht also u.U. auch der Anbieter der Shopsoftware "in der Küche".

Daher würde ich mich gerne lizenzrechtlich [möglichst gut absichern](https://github.com/cmsimple-xh/xhshop/issues/12#issuecomment-312444363). Creative-Commons erscheint mir da nicht wirklich passend – auch nicht mit zusätzlichem Disclaimer.

**Comment by frase-git** [comment]
Also, ich fürchte, dass das ein wenig ausartet.

1. Wir sollten uns rechtlich absichern, indem wir jede Verantwortung bei Verwendung ablehnen.

2. Deutlicher Hinweis (wo?), dass der Benutzer sich selbst informieren und entsprechende Maßnahmen ergreifen muss. (Die Gesetzeslage kann sich ja ändern!) Welche gesetzeskonformen Texte die Betreiber irgendwo reinschreiben ist ihre Sache. Wir können nur ein Grund(!)Gerüst vorgeben.

3. Falls das wirklich nötig wäre, würde ich eine Option (Textfeld für Adresse) schaffen: `Datei (AGB) an Bestätigungsmail anhängen?`
Diese Datei sollte irgendwo auf dem Server (userfiles?) in irgendeinem (verschickbaren) Format liegen und könnte die AGB mit Widerrufsbelehrung und/ oder weitere Infos enthalten. Dafür ist dann jeder Betreiber selbst verantwortlich. Ein Muster würde ich nicht liefern.

(das entspricht im Wesentlichen Christophs letztem Post)

**Comment by XHalbert** [comment]
> indem wir jede Verantwortung bei Verwendung ablehnen

reinschreiben sollten wir das - ist aber die Frage, ob das rechtssicher ist. Denke, es würde immer den Shopbetreiber treffen und sehr unwahrscheinlich CMSimple

> eine Option (Textfeld für Adresse) schaffen: Datei (AGB) an Bestätigungsmail anhängen?

wär optimal - einfacher könnte man vllt. einfach immer eine Anhangdatei "bitte-beachten.pdf" mitverschicken - wenn der Shopbetreiber keine am vorgesehenen Ort hat (in Hilfedatei erwähnen), würde auch keine verschickt (oder gäbe es eine Fehlermeldung?).

**Comment by cmb69** [comment]
Nägel mit Köpfen: wir führen eine neue Spracheinstellung `config_email_attachment` ein (Voreinstellung leer), wo der Dateiname einer der Bestätigungsmail anzuhängenden Datei angegeben werden kann. Diese Datei ist in `templates/confirmation_email/` zu hinterlegen. Ist die Option leer oder es gibt die Datei nicht, dann wird eben nichts angehängt.

Das ganze habe ich absichtlich sehr allgemein gehalten, damit dieses Feature für alle möglichen Zwecke genutzt werden kann; wer rechtlich nicht an Widerufsbelehrung oder so gebunden ist, könnte auch eine kleine Broschüre anhängen lassen.

Okay?

**Comment by frase-git** [comment]
👍 
Noch nicht getestet.

**Comment by cmb69** [comment]
> Noch nicht getestet.

Ist ja auch noch nicht implementiert. Mache ich dann mal zum Testen.

**Comment by cmb69** [comment]
> Noch nicht getestet.

Bitte testen und bei Nichtgefallen das Ticket wieder öffnen.

**Comment by frase-git** [comment]
Plugin mit master aktualisiert.
In meiner Newsbox (links) erscheint:

> Fatal error: Call to protected method Xhshop\FrontEndController::shopToc() from context '' in ... \templates\fhs-simple\template.htm on line 73

Alle Seiten bleiben weiß (nur der content).

Das betrifft den Aufruf im Template: `<?php echo $xhsController->shopToc(); ?>`
Habe ich da was falsch gemacht - oder ist etwas anders?

**Comment by cmb69** [comment]
> Habe ich da was falsch gemacht - oder ist etwas anders?

Nein, das liegt an einem Fehler in 62c7c56. Sollte mit b5db8bc behoben sein.

Frage: ist die Syntax `<?php echo $xhsController->shopToc(); ?>` nicht etwas verwirrend für nicht PHP Kundige? Wäre `<?php echo display_shop_toc(); ?>` nicht einfacher? (und ja, eigentlich bin ich dafür solche Funktionen immer mit dem Pluginnamen beginnen zu lassen, also etwa `xhshop_toc_display`, aber der Hauptaufruf lautet `display_shop` und ich weiß nicht, ob die Umbenennung zu `xhshop_display` erwünscht ist)

**Comment by XHalbert** [comment]
> einer der Bestätigungsmail anzuhängenden Datei 

sehr begrüßenswert

**Comment by frase-git** [comment]
Also:
Fix hat geholfen.
Seite läuft wieder.
TEST.pdf in `xhshop\templates\frontend\confirmation_email\` gelegt.
Bestellung durchgezogen.
Mail komt an (bei Kunden) mit Anhang TEST.pdf.
Super!

Bitte an @cmb69 
Lösche mal in deiner Inst. deine shop-contact E-Mail.
Ziehe mal eine Bestellung durch und lies die Fehlermeldung.
Das kann nicht gut sein.

**Comment by cmb69** [comment]
> Lösche mal in deiner Inst. deine shop-contact E-Mail.
Ziehe mal eine Bestellung durch und lies die Fehlermeldung.
Das kann nicht gut sein.

Das ist mir seit dem Entfernen der voreingestellten E-Mail-Adresse schon mehrfach passiert. Aber ich sehe das Problem immer noch nicht, es sei denn, es ginge um die Reihenfolge in der Bestätigungs- und Benachrichtigungsmail versendet werden – die sollte vielleicht besser geändert werden.

**Comment by frase-git** [comment]
> Pardon! Obgleich eine E-Mail-Bestätigung an Sie versandt wurde, wurde Ihre Bestellung nicht an unseren Shop übermittelt!

Das ist OK.

> Bitte informieren Sie uns per E-Mail:

Woher soll hier eine E-Mail-Adresse kommen? (Doppelpunkt!)

> Fehlermeldung: You must provide at least one recipient email address.

Diese Meldung sollte nicht der User erhalten **sondern** der Betreiber!

**Comment by cmb69** [comment]
> Woher soll hier eine E-Mail-Adresse kommen?

Na ja, den Fall einer nicht eingetragenen E-Mail-Adresse können wir doch wohl hoffentlich ignorieren (dank Doku und Systemprüfung). Schlägt der Mailversand aber aus anderen Gründen fehl, dann ist die Angabe der Adresse hier sinnvoll, finde ich, damit der Kunde nicht erst das Impressum suchen muss, sondern einfach den `mailto:` Link klicken kann. Wenn du das ausprobieren willst, dann einfach eine E-Mail-Adresse eintragen und [hier](https://github.com/cmsimple-xh/xhshop/blob/778e89114869f46e0c89bed248f7946035935cd1/classes/FrontEndController.php#L490) oder [hier](https://github.com/cmsimple-xh/xhshop/blob/778e89114869f46e0c89bed248f7946035935cd1/classes/FrontEndController.php#L501) das Ausrufezeichen entfernen.

> Diese Meldung sollte nicht der User erhalten sondern der Betreiber!

Okay, das geht aber nur per Log; siehe #101. Da mach ich mich mal dran, und entferne dann die Fehlermeldung.

**Comment by cmb69** [comment]
> Da mach ich mich mal dran, und entferne dann die Fehlermeldung.

Okay, erledigt: f7f624d. Ich denke, damit kann man erst mal gut leben.

**Comment by frase-git** [comment]
So wie ich das sehe, könnte das hier geschlossen werden - oder?
E-Mail-Anhang ist erledigt und [im Wiki beschrieben](https://github.com/cmsimple-xh/xhshop/wiki/Sprache#abschnitt-config).

Alle anderen hier angesprochenen Probleme sind auch an andere Stelle erledigt.
