### ISSUE TITLE
<b> to <strong>

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#161]
Ich habe gerade im alten Safari noch einen Fall entdeckt.
customersData.tpl Zeile 35.

Früher habe ich das nie gesehen, aber gerade im Safari fällt der Unterschied zwischen `<b>` und `<strong>` erheblich auf (das ist natürlich templateabhängig).

**Comment by cmb69** [comment]
Ich finde 8 `<b>`s in der Codebase. Soll ich alle ändern?

**Comment by frase-git** [comment]
Das wäre sehr nett von dir.
Eigentlich meine Aufgabe - aber ich kann das immer noch nicht fürs mergen hochladen.

**Comment by cmb69** [comment]
> Eigentlich meine Aufgabe - aber ich kann das immer noch nicht fürs mergen hochladen.

Kein Problem :)
