### ISSUE TITLE
languages: Shipping countries

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#164]
Unter `Sprache: Shipping countries:` könnten wir evtl. die Länder mit einer Zeilenschaltung versehen.
Habe das gerade probiert und finde es übersichtlicher (analog zu Forwarding expenses).
Das sieht bei mir in der Sprachdatei (de) dann so aus:

`$plugin_tx['xhshop']['config_shipping_countries']="DE=Deutschland;\r\nAT=Österreich;\r\nCH=Schweiz;\r\nFR=Frankreich";`

**Comment by frase-git** [comment]
Auweia!
Das habe ich lokal gemacht und - zum ersten Mal - ist es auch gleich online eingefügt worden.
Schlimm?
Revert?

**Comment by cmb69** [comment]
> Schlimm?
Revert?

Schlimm nicht, aber ich habe trotzdem reverted. Die Zeilenumbrüche finde ich in Ordnung, aber dann würde ich auf die Strichpunkte verzichten, und das würde kleine Anpassungen am Code erfordern.

**Comment by cmb69** [comment]
Habe die Doku unter https://github.com/cmsimple-xh/xhshop/wiki/Sprache auch gleich angepasst.

**Comment by frase-git** [comment]
Danke!
