### ISSUE TITLE
Shipping Country: Platzhalter in billtemplate

### ISSUE THREAD

**Issue by XHalbert** [cmsimple-xh/xhshop#165]
bevor ichs wieder vergesse:
in billtemplate sollte auch ein Platzhalter für Shipping Country enthalten sein.
Die Paketdienste erwarten für "Lieferland" nicht den sprachabhängigen Namen des Landes, sondern ein internationales Kürzel, z.B. "DE". Da wir auch Kürzel verwenden, sollte es ohne großen Aufwand möglich sein, das Kürzel in der billtemplate mit zu übermitteln

**Comment by frase-git** [comment]
Hm, schwierig.
Unter `Shipping countries` ist zurzeit alles möglich eintragbar. Wegen individueller Möglichkeiten.
Auch zum Beispiel: `Spanien-ohne Inseln + 11,77 € Versandkosten`
und die zugehörigen Kürzel sind frei wählbar.
Damit werden die Paketdienste nichts anfangen können.

**Comment by cmb69** [comment]
> Auch zum Beispiel: Spanien-ohne Inseln + 11,77 € Versandkosten

Dann meckert die Systemprüfung aber: "Prüfe, dass die Versandländer plausibel sind … Fehler"

> und die zugehörigen Kürzel sind frei wählbar.

Genau. Daher denke ich auch, dass es nicht unbedingt viel bringt, wenn das Kürzel exportiert wird.

**Comment by XHalbert** [comment]
> nicht unbedingt viel bringt, wenn das Kürzel exportiert wird.

doch es ist eigentlich sogar dringend erforderlich!
Ich arbeite ja z.Zt. ohne Länderkürzel. Beim Paketdienst ist daher fest "DE" eingestellt, auch bei Auslandsbestellungen, geht ja nicht anders. Bei der Adressvalidierung beim Paketdienst gibt es dann eine Fehlermeldung, die ich anschließend korrigieren muss.
Natürlich ist es möglich, in der Exeldatei "Deutschland" in "DE" umzurechnen...

Aber warum soll das Kürzel denn nicht übermittelt werden?

> und die zugehörigen Kürzel sind frei wählbar.

nein eigentlich nicht.
Es kann ruhig jedem selbst überlassen werden, wenn er da Kokolores reinschreiben will... das wird er aber nicht tuen!
Im Shop steht meines Wissens derzeit:
DE=Deutschland;AT=Österreich; usw.
Bei der Adresse in der Email steht weiterhin "Deutschland", und zusätzlich (im Austauschformat) "DE"
was spricht dagegen?

> Auch zum Beispiel: Spanien-ohne Inseln + 11,77 € Versandkosten

das war einmal.
Jetzt steht:
DE: 1=4.50; 3= 6.25; 6= 9.75; 0
AT: 1=9.00; 3=12.50; 6=19.50; 48.00

**Comment by cmb69** [comment]
Ich habe nun `%COUNTRY_CODE%` als ersetzbaren Parameter für die "Bills" hinzugefügt. Soll dieser gleich noch in den `billtemplate`s eingefügt werden? Wenn ja, wo?

**Comment by frase-git** [comment]
in CSV hinter PLZ Ort, als neue Zeile
```
...
;;;;;Ort;%ZIP% %CITY%
;;;;;Land;%COUNTRY_CODE% - %COUNTRY%
...
```

**Comment by cmb69** [comment]
> in CSV hinter PLZ Ort, als neue Zeile

Erledigt.
