### ISSUE TITLE
Remove order time from step 3

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#166]
Frage:
Welche Rolle spielt die ZEIT einer Bestellung?

Es wird eine Zeit in Step 3 angezeigt.
Bis zum Absenden könnte viel Zeit vergehen.
In der Bestätigungsmail wird eine neue Zeit festgelegt.
Die beiden Zeiten könnten also verschieden sein.
(evtl. Screenshot und Mail)
Vorschlag:
In Step 3 entfernen.

**Comment by cmb69** [comment]
> Welche Rolle spielt die ZEIT einer Bestellung?

Gute Frage. Ich denke, diese ist höchstens dafür interessant, damit man mehrere Bestellung vom selben Kunden am gleichen Tag unterscheiden kann. Da dieser Fall aber doch wohl nur selten vorkommt, kann die Zeitangabe IMHO entfallen. Dann könnte das Datumsformat auch gemäß `Bill dateformat` lokalisiert werden.

> Die beiden Zeiten könnten also verschieden sein.

Selbst wenn wir die Zeitangabe entfernen, könnte das Datum abweichen (Mitternachtsbestellung). Ich denke wir sollten bei Schritt 3 die Datums- (und Zeit-)angabe komplett streichen.

**Comment by frase-git** [comment]
Stimmt. Das Datum könnte ja auch verschieden werden.
Also: In Step 3 Zeit und Datum weg.
