### ISSUE TITLE
kurzer Hilfetext in Sprachdatei

### ISSUE THREAD

**Issue by XHalbert** [cmsimple-xh/xhshop#167]
ist mir doch glatt entfallen...
So gehts wohl vielen, auch wenn sie das Wiki aufmerksam gelesen haben...

Aktuell meine Frage.
Email attachment : **Was hier reinschreiben?**

ich denke hier wäre eine kleine Hilfestellung sinnvoll, da in dem Feld nichts voreingestellt ist.

Nachtrag:
habs auch mit diesem Hilfetext nicht hingekriegt:

> Die zu verschickende Datei muss im Ordner xhshop/templates/frontend/confirmation_email/ vorhanden sein. Es können hier also sprachabhängige Dateien angehängt werden. Voreinstellung leer (kein Eintrag)

**Comment by cmb69** [comment]
> Email attachment : Was hier reinschreiben?

Dabei geht es um einen benutzerdefinierten Anhang für die Bestell-Benachrichtigungs-E-Mail (#16). Soll beispielsweise Wiederrufsbelehrung.pdf verschickt werden, dann muss die entsprechende Datei in xhshop/templates/frontend/confirmation_email/Wiederrufsbelehrung.pdf hinterlegt werden, und bei Email attachment `Wiederrufsbelehrung.pdf` eingetragen werden.

**Comment by XHalbert** [comment]
Aha, also ohne Pfad einfach die Datei eintragen...
gut, 
klappt nicht mit .eml, aber muss ja auch nicht

**Comment by frase-git** [comment]
mit *.eml:
Die Datei wird zwar angehangen und kommt auch an, hat aber irgendwie ein falsches Format.
Beim Öffnen mit Thunderbird scheint sie leer zu sein. Schaut man sich den Quelltext an, sieht man aber, dass sie nicht leer ist.
Aber, wie schon gesagt, das wird wohl nicht gebraucht - an den Kunden

**Comment by frase-git** [comment]
[Wiki](https://github.com/cmsimple-xh/xhshop/wiki/Sprache#abschnitt-config) angepasst.
Besser verständlich?

**Comment by cmb69** [comment]
> Die Datei wird zwar angehangen und kommt auch an, hat aber irgendwie ein falsches Format.

Siehe https://github.com/cmsimple-xh/xhshop/issues/21#issuecomment-320904387 (2. Teil).

> Aber, wie schon gesagt, das wird wohl nicht gebraucht - an den Kunden

Ich denke auch, dass man dem Kunden lieber kein .eml zusenden sollte. Auch sonst besser kein zu spezielles Format, da der Kunde es sonst vielleicht nicht mal lesen kann.
