### ISSUE TITLE
Add shipping cost notice

### ISSUE THREAD

**Issue by XHalbert** [cmsimple-xh/xhshop#17]
Meines Wissens ist für gewerbliche Verkäufe zwingend notwendig, **bei jedem Artikel** auf evtl. Versandkosten hinzuweisen. Im Shop, auf Detailseiten und im AddToCartButton
Es muss eine CMSimple-Seite z.B. "Versand" geben, auf die bei jedem Artikel mit "Versandkosteninfo" verlinkt wird, sie kann versteckt sein.
M.W. zulässig ist z.B. "66,- € inkl. MwSt., zzgl. Versand (Versand als Link)

ich habe mich aber für folgende zwei Zeilen entschieden (Platz ist genug):
inkl. MWSt. 19 %, zzgl. Versandkosten
Versandkosteninfo (als Link)

Ehrlich und transparent

**Comment by frase-git** [comment]
http://cnlpa.de/?CNLPA-Shop&wrsProduct=p5548635728891
Da habe ich das so gemacht.

Im Cart-Button ist es schon drin - aber noch nicht verlinkt:
http://fhs.bplaced.net/xhshop-demo/?Test

**Comment by XHalbert** [comment]
Klasse!

**Comment by frase-git** [comment]
Ich habe jetzt mal den Cart-Button mit Link zu Versandkosten gemacht.
Den Link habe ich nur in der de.php eingefügt.
http://fhs.bplaced.net/xhshop-demo/?Test
Das müsste dann noch irgendwie bei den Produkt-Details geschehen.

**Comment by XHalbert** [comment]
Daumen hoch!

**Comment by frase-git** [comment]
### Zusammenfassung ToDo:
**Variante 1:**
Alles lassen, wie es ist.
Doku: Betreiber muss in der Sprachdatei unter `price_info_shipping` den Link zur Versandseite händisch einfügen.

**Variante 2** (empfohlen):
Unter: `Sprache -> Config` wird als dritter Punkt eingeführt `Shippingcosts page`.
Systemcheck: Prüfen, wenn Versandkosten eingeschaltet sind.

In `addToCartButton.tpl` den Link zur Versandkostenseite einfügen.
Ebenso in `productDetails.tpl`.
Evtl. auch in `catalog.tpl` - hätte ich nicht gerne - abstimmen.

Der Link soll am Ende ungefähr so aussehen:
 `zzgl. <a class="zoom_i" target="_blank" href="?Shop/Versandkosten&print">Versandkosten</a>`
also: inkl. `&print`, `zoom_i` und `_blank`.

**Comment by cmb69** [comment]
> Variante 2 (empfohlen):

Dann schaut mal bitte ob 22e8f45 in Ordnung ist. Falls ja, dann bitte mal vergleichen mit der AGB Verlinkung. Dort taucht im Sprachtext "AGB" auf, und wird durch `labels_gtc_name` gefunden, damit es durch den Link ersetzt werden kann. Bei den Versandkosten habe ich es mit einem Platzhalter `%s` gelöst, was ich etwas sauberer finde. Beide Varianten sind aber auf jeden Fall möglich, und sollten angeglichen werden.

> Evtl. auch in catalog.tpl - hätte ich nicht gerne - abstimmen.

Habe ich erst mal nicht gemacht, weil dort nicht mal die MwSt ausgewiesen wird. IMHO müsste aber beides auch hier erfolgen; ansonsten könnte es doch auch an den anderen Stellen weggelassen werden, da man ja alles nur über den Katalog (Übersicht) bestellen kann.

**Comment by frase-git** [comment]
Bin leider etwas in Eile.

> Dann schaut mal bitte ob 22e8f45 in Ordnung ist.

Sieht für mich sehr gut aus. Gut gemacht!
Angleichen: einverstanden. Wie AGB? Überlasse ich dir: beides gut.

catalog.tpl - weglassen.
(Das hatte ich heimlich gehofft. ;-)

**Comment by frase-git** [comment]
Eine Bitte in diesem Zusammenhang:
im stylesheet.css ab Zeile 364:
`span.xhsPrdPriceLabel` und `span.xhsPrdPriceNum`
**beiden** Klassen bitte anfügen:
`vertical-align: middle;`

**Comment by frase-git** [comment]
Danke!

**Comment by cmb69** [comment]
> beiden Klassen bitte anfügen:

Gemacht (adfe94a).

> Angleichen: einverstanden. Wie AGB? Überlasse ich dir: beides gut.

Ehrlich gesagt gefällt mir beides nicht weil in beiden Fällen zwei Sprachtexte aneinander gekoppelt sind. Ich denke 245077c ist zumindest besser.

**Comment by frase-git** [comment]
Gefällt mir gut. Sogar mit passendem Icon!

`Price info shipping zzgl. %sVersandkosten%s`
Aus User-Sicht mag ich sowas eigentlich gar nicht, weil man nie weiß, was `%s` an dieser Stelle gerade ist.

**Comment by cmb69** [comment]
> Gefällt mir gut. Sogar mit passendem Icon!

Schön, dass dir das Icon gefällt. War wirklich aufwendig, da ein passendes zu finden. ;) (ich habe einfach `.xhsCosLnk` verwendet)

> Aus User-Sicht mag ich sowas eigentlich gar nicht, weil man nie weiß, was %s an dieser Stelle gerade ist.

Aus Nutzersicht mag ich es auch nicht. War für mich mal der Hauptgrund für Translator_XH wo es die translations-hints gab. Die hat aber kaum ein Plugin angeboten, und da auch keine Nachfragen diesbezüglich kamen habe ich die Funktionalität entfernt. Vorübergehend habe ich dann sprechendere Platzhalter verwendet (in der Art `Guten Tag {ANREDE} {VORNAME} {NACHNAME}`), aber das passt nicht wirklich gut zu den Views (aka. Templates) wie ich sie mir vorstelle.

Außer dir hat sich aber auch noch niemand beschwert, wenn ich nichts vergessen habe – ich würd's daher einfach mal lassen.

**Comment by frase-git** [comment]
> ich würd's daher einfach mal lassen.

Klar!
Ich bin doch kein User ;-)

**Comment by XHalbert** [comment]
ups, jetzt vermisse ich aber was

(s.o.) Meines Wissens ist es zwingend notwendig, bei jedem Artikel auf evtl. Versandkosten und Mehrwertsteuer hinzuweisen. Im Shop-Catalog, auf Detailseiten und im AddToCartButton... 
denn jede dieser Seiten kann alleine gegoogled und für einen Kauf genutzt werden.

Im Warenkorb sehe ich keinen MwSt.-Hinweis mehr

Nebenbei... Ich dachte, wir hätten uns auf "MwSt." geinigt statt "USt"
(siehe #14)   (cmb) "Soweit ich weiß, heißt es aus Sicht des Käufers MwSt. ..."

**Comment by frase-git** [comment]
Hast du den aktuellen Master getestet?

**Comment by XHalbert** [comment]
nein stimmt, irgendwie alt geupdatet - machs nochmal

**Comment by frase-git** [comment]
Im Warenkorb Step 1 gab es noch nie die MwSt.
(allerdings habe ich in schon oft erwähntem Shop in Step 1 immer drunter stehen:
"Alle Preisangaben inkl. Mehrwertsteuer.")

Im AddToCartButton (übrigens: falscher Name) und bei Details ist das jetzt alles drin.

Im Catalog nicht.
Falls das nötig ist, dann muss im Catalog zu jedem Artikel der MwSt.-Satz (oder die MwSt. ???) plus der Spruch "zzgl. Versandkosten".
Ich fände das nicht gut - aber nur Bauchgefühl - kein Wissen!
Die Überlegung ist:
Der Katalog ist eine Voransicht mit Preisangabe.
Es gibt den Button "Artikel-Details" - wo es alle Infos gibt.
Dass man dort auch in den Korb legen kann ... pfh!

**Comment by XHalbert** [comment]
> Im Warenkorb Step 1 gab es noch nie die MwSt.

geht aber nicht ohne
in wellrad war so:
Zwischensumme | 27,90 €
Versandkosten            (250 VsE.) | 5,90 €
Rechnungssumme | 33,80 €
Enthaltene MWSt.: 19% | 5,40 €

und in XH-Shop (dachte ich) hatte ich das bisher so gesehen wie hier Step3

![](https://user-images.githubusercontent.com/24246330/27764599-6595665a-5e9d-11e7-89ac-b6687ef09630.png)

**Comment by XHalbert** [comment]
> im Catalog zu jedem Artikel der MwSt.-Satz (oder die MwSt. ???) plus der Spruch "zzgl. Versandkosten".

nein es reicht: "inkl. MwSt."  "zzgl. Versandkosten"(mit Link)

**Comment by frase-git** [comment]
dann werden wir das wohl so machen müssen.

'nabnd

**Comment by XHalbert** [comment]
> Im Warenkorb Step 1 gab es noch nie die MwSt.

hab den "alten" wellrad grad nochmal angesehen - hast Recht, und (s.o.) hatte ich mir wohl nachträglich reingebastelt, weil es rechtlich nicht ohne geht (evtl. würde reichen: "Endpreise incl. MwSt.").

**Comment by cmb69** [comment]
> Falls das nötig ist, dann muss im Catalog zu jedem Artikel der MwSt.-Satz (oder die MwSt. ???) plus der Spruch "zzgl. Versandkosten".

Hatte ich ja auch schon angemerkt. Aber der Grund das nicht zu machen ist vermutlich nur die Übersichtlichkeit? Falls ja, dann könnte der Add-To-Cart-Button im Katalog (aka. Artikelübersicht) auch einfach gar nicht angezeigt werden. Dann muss zwar der Kunde etwas mehr klicken, aber das macht den Kohl nicht fett – von einer One-Klick-Bestellung sind wir sowieso weit entfernt.

> weil es rechtlich nicht ohne geht (evtl. würde reichen: "Endpreise incl. MwSt.").

Ist das im ersten Schritt wirklich erforderlich? Immerhin steht da nichts von "jetzt kaufen" und das passiert ja auch erst am Ende des dritten Schritts (wenn überhaupt), wo alles ordnungsgemäß ausgewiesen wird.

Übrigens: gibt es eigentlich auch ein Gesetz, dass man beim Verkauf von Regenjacken ausdrücklich darauf hinweisen muss, dass diese bei Sonnenschein zwar genutzt werden können, aber nichts bringen? 🙄

**Comment by frase-git** [comment]
Leider habe ich auch keine Patentlösung - bin auch nicht der XH-Justiziar ;-)
Wie alles, was wir hier machen, ist es sehr verzwickt.

#### Shop-Übersicht (Katalog):
1. Den "in den Warenkorb"-Button auf der Katalogseite können wir nicht entfernen. Es kann Artikel **ohne Detailseite** geben. Die könnte man dann nicht mehr bestellen.
2. MwSt. und Versandkostenhinweis
    2.1 (mein Favorit) Entweder oben und unten auf der Übersichtsseite allgemeine Hinweise:
Alle Preisangaben inkl. MwSt. Alle Preisangaben zzgl. Versandkosten. (jeder Satz nur, wenn konfiguriert)
    2.2 Oder diese beiden Sätze zu jedem Artikel (sehr unschön).

#### Step 1
`['hints_edit_cart']="Haben Sie das Gewünschte in gewünschter Stückzahl in Ihrem Warenkorb?";`
Diesen Hinweis ersetzen durch "Alle Preisangaben inkl. MwSt." (nur was kommt da hin, wenn ausgeschaltet?)
Plus, je nachdem wie #4 ausgeht bzw. ob Versandkosten in Step1 ausgewiesen werden:
"Alle Preisangaben zzgl. Versandkosten."

Was meint ihr?

BTW:
Habe mir das mal bei ammas00n angeschaut.
**Übersichtsseiten** (Katalog) haben keine MwSt.- und Versandkostenhinweise - aber auch keinen Warenkorb-Button.
**Detailseiten** haben unter dem Preis stehen:
"Alle Preisangaben inkl. USt" (**USt** ohne Punkt! nicht MwSt. - so wie bei uns!)

**Comment by XHalbert** [comment]
> Habe mir das mal bei ammas00n angeschaut.
Übersichtsseiten (Katalog) haben keine MwSt.- und Versandkostenhinweise - aber auch keinen Warenkorb-Button.

wär vielleicht nich dumm, das auch so zu machen: Katalog ist Übersicht, aber nicht zum Bestellen. Bei der Gelegenheit könnte mann vielleicht die Übersicht auch mehrspaltig machen, wie man es immer öfter sieht...

> Es kann Artikel ohne Detailseite geben. Die könnte man dann nicht mehr bestellen.

dann muss eben jeder Artikel eine haben...

> 2.1 (mein Favorit) Entweder oben und unten auf der Übersichtsseite allgemeine Hinweise:

und wer zahlt die Abmahnkosten? (solange man dort auch bestellen kann)

Was ist denn so schlimm daran, beim Artikel zu schreiben "incl. MwSt. zuzügl. Versand" ?

> (nur was kommt da hin, wenn ausgeschaltet?)

mit ausgeschaltet meinst du Kleinunternehmer = 0% ?
dann steht in catalog, AddToCart u. Detailseite: "Endpreis zuzügl. Versand" und im Warenkorb, in Step 3 sowie in der Email der Hinweis auf Kleinunternehmer.

nochmal:  in catalog, AddToCart u. Detailseite **muss was beim Artikel stehen**
ein allgemeiner Hinweis oben oder unten kann weggescrollt sein in der aktuellen Ansicht, daher nicht zulässig, gibt ein Gerichtsurteil dazu...

**Comment by cmb69** [comment]
> dann muss eben jeder Artikel eine [Detailseite] haben...

Wäre zumindest technisch machbar. Im Zweifel steht dort eben das selbe wie im Katalog.

Rein programmiertechnisch wäre es auf jeden Fall begrüßenswert, wenn alle Add-To-Cart-Buttons vom selben Code erzeugt werden – sonst schleichen sich im Lauf der Zeit voraussichtlich unerwünschte Abweichungen ein.

Grundsätzlich könnte der Add-To-Cart-Button im Katalog auch per Konfigurationsoption gesteuert werden (on/off). 

> Bei der Gelegenheit könnte mann vielleicht die Übersicht auch mehrspaltig machen, wie man es immer öfter sieht...

Ich denke, mehrspaltig ist je nach Template sogar wichtig, weil kurze Teaser sich schwerlich zum "Breitziehen" eigenen. Das könnte man aber eben auch dem Webdesigner überlassen.

**Comment by frase-git** [comment]
Mehrspaltigkeit ist templateabhängig und sollte wirklich dem Seitengestalter überlassen werden.
Ist übrigens ganz einfach (schnelles Beispiel):

```css
article.xhsOverviewPrds {
    ...
    float: left;
    margin: 0 .5em .5em 0;
    width: 45%;
}
```

**Comment by cmb69** [comment]
> Ist übrigens ganz einfach (schnelles Beispiel):

Sieht aber hässlich aus, falls die article unterschiedlich hoch ausfallen. Sinngemäß [so](https://github.com/cmb69/realblog_xh/blob/e403ad19400ea227d5b5678c1ded4b75a2ae655f/css/stylesheet.css#L119-L153) sollte eher passen. Tipps fürs Wiki?

**Comment by frase-git** [comment]
Ich würde das Thema lieber gar nicht erwähnen.
Es können ja auch Shop-Templates von Dritten angeboten werden.

**Comment by cmb69** [comment]
> Es können ja auch Shop-Templates von Dritten angeboten werden.

Guter Punkt!
