### ISSUE TITLE
%VAT_HINT% in bills formats reduced rate as currency

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#171]
Während der MwSt.-Hinweis im dritten Schritt des Checkout korrekt angezeigt wird, wird in den "Bills" (zurzeit nur bei `bill.rtf`) der reduzierte MwSt-Satz als Währung ausgezeichnet (`7 €` statt `7 %`).

**Comment by frase-git** [comment]
Auweia, das ist schon 'ne ganze Weile so.
(alte Mail vom 27.07.)
Und niemandem ist das aufgefallen ...

**Comment by lck-git** [comment]
> Und niemandem ist das aufgefallen ...

Doch, mir gerade, wollte es gerade posten, aber cmb69 war schneller :1st_place_medal:
