### ISSUE TITLE
Country select is suppressed if shipping countries are empty

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#172]
Obgleich die `shipping countries` nicht leer sein sollten (wird von der Systemprüfung bemängelt), sollte in diesem Fall dennoch eine Länderauswahl-Selectbox angezeigt werden (eben nur mit einem leeren Eintrag).

**Comment by frase-git** [comment]
Ich frage mich, ob bei schwerwiegenden Fehlern der Shop nicht besser in den Wartungsmodus versetzt werden sollte.
Da ist nur die Frage: Was ist alles schwerwiegend?

**Comment by cmb69** [comment]
> Ich frage mich, ob bei schwerwiegenden Fehlern der Shop nicht besser in den Wartungsmodus versetzt werden sollte.

Ich habe gewisse Zweifel, dass Shopbetreiber damit besser zurecht kommen ("warum ist der Shop im Wartungsmodus; ich habe ihn doch veröffentlicht?"), und bin auch nicht ganz glücklich bezüglich des zusätzlichen Laufzeitaufwands (allerdings ist die Performance des Shop sowieso sehr suboptimal), aber habe mal den [unpublish-on-fail Branch](https://github.com/cmsimple-xh/xhshop/tree/unpublish-on-fail) aufgemacht. Dort werden nun alle Systemprüfungsfehlschläge (rot) als schwerwiegender Fehler behandelt, und der Shop in den Wartungsmodus versetzt. Wenn das so gemacht wird, dann sollten vermutlich noch die Produktpreise und -gewichte auf ein korrektes Format (Dezimalpunkt) überprüft werden, und Fehlschläge ebenfalls als schwerwiegende Fehler behandelt werden.

**Comment by frase-git** [comment]
Performance-Probleme bemerke ich nicht. Das wäre doch auch nur im Admin-Modus wirksam - oder?

Der Shop-Betreiber muss eben solange fummeln, bis kein ROT mehr erscheint.
Finde ich gut.
Viel schlimmer wäre eine Bestellung, die nicht abgeschossen werden kann oder nicht ankommt.

> Wenn das so gemacht wird, dann sollten vermutlich noch die Produktpreise und -gewichte auf ein korrektes Format (Dezimalpunkt) überprüft werden, und Fehlschläge ebenfalls als schwerwiegende Fehler behandelt werden.

Ich dachte, das wird schon geprüft?
Falls nicht, neige ich auch dazu.

Und vielleicht sollte wirklich irgendwo ein deutlicher Hinweis **permanent** sichtbar sein, solange irgendein Fehler vorhanden ist/ bzw. der Shop im Wartungsmodus ist. (Ich meine nur im Adminmodus)

**Comment by cmb69** [comment]
> Performance-Probleme bemerke ich nicht.

Ich auch nicht, aber der Shop macht jede Menge unnötige Dinge (beispielsweise wird `catalog.php` immer geladen, auch wenn der Shop nicht involviert ist).

> Das wäre doch auch nur im Admin-Modus wirksam - oder?

Nein, denn sonst könnte ja ein Kunde bestellen, auch wenn der Admin glaubt, der Shop sei im Wartungsmodus.

> Ich dachte, das wird schon geprüft?
Falls nicht, neige ich auch dazu.

Das wird bisher nur beim Speichern der Artikeldetails geprüft. Ich habe diesbezüglich nun noch eine Systemprüfung ergänzt (unpublish-on-fail Branch).

> Und vielleicht sollte wirklich irgendwo ein deutlicher Hinweis permanent sichtbar sein, solange irgendein Fehler vorhanden ist/ bzw. der Shop im Wartungsmodus ist. (Ich meine nur im Adminmodus)

Na ja, diese immer anzuzeigen finde ich problematisch, weil der Shop ja unter Umständen gar nicht im Spiel ist (hinter den Kulissen aber schon). Ich habe im unpublish-on-fail Branch nun aber die Meldung, dass der Shop im Wartungsmodus ist, für den Adminmodus verbessert, falls dies aufgrund schwerwiegender Fehler erfolgt ist.

**Comment by frase-git** [comment]
> Das wäre doch auch nur im Admin-Modus wirksam - oder?
>> Nein, denn sonst könnte ja ein Kunde bestellen, auch wenn der Admin glaubt, der Shop sei im Wartungsmodus.

Hier meinte ich nur die Performance-Probleme.

> Das wird bisher nur beim Speichern der Artikeldetails geprüft. Ich habe diesbezüglich nun noch eine Systemprüfung ergänzt (unpublish-on-fail Branch).

Sehr gut. Man weiß nie, was die User so alles anstellen.

> Na ja, diese immer anzuzeigen finde ich problematisch, weil der Shop ja unter Umständen gar nicht im Spiel ist (hinter den Kulissen aber schon). Ich habe im unpublish-on-fail Branch nun aber die Meldung, dass der Shop im Wartungsmodus ist, für den Adminmodus verbessert, falls dies aufgrund schwerwiegender Fehler erfolgt ist.

Was ist denn daran problematisch?
Wir haben doch jetzt den Schlamassel: Die Forums-Tester haben immer gleich zielsicher die schlimmsten Fehler produziert. Ginge ein solcher Shop online, wäre das eine Katastrophe.
Dann lieber irgendwo deutlich ein Hinweis. Es könnte ja auch nur ein FA-Symbol in Rot sein, das darauf hindeutet, dass es noch Fehler gibt (Link zum Systemcheck). Ich sehe das mehr aus der Anwender-Sicht. Man schaut nicht ständig nach dem Check - weil man glaubt, alles richtig gemacht zu haben. Und der geänderte Wartungsmodus-Text hilft auch nicht wirklich. Ich bin dafür. solange zu nerven, bis alles stimmt.

Es wird immer deutlicher, dass der Shop wirklich nicht gerade simpel ist. Mal schnell ausprobieren is nich!

**Comment by cmb69** [comment]
> Wir haben doch jetzt den Schlamassel: Die Forums-Tester haben immer gleich zielsicher die schlimmsten Fehler produziert. Ginge ein solcher Shop online, wäre das eine Katastrophe.

Aber genau das ist mit den Änderungen im unpublish-on-fail Branch doch gar nicht mehr möglich.

Und letztlich kann ein Anwender trotz aller Prüfungen immer noch einen Shop veröffentlichen, der ihn Kopf und Kragen kosten kann. Z.B. weil er sich beim Artikelpreis vertippt, und 10 statt 100 Euro angibt. Oder weil er falsche MwSt-Sätze angibt. Oder weil er sich bei der E-Mail-Adresse vertippt, und keine Bestellbenachrichtigung erhält. Oder weil die Bestellbenachrichtigungen von seinem Spamfilter aussortiert werden. Oder, oder, oder …

Aber okay, ich habe im unpublish-on-fail Branch noch eine zusätzliche Warnmeldung ergänzt.

> Es wird immer deutlicher, dass der Shop wirklich nicht gerade simpel ist.

Was halt zu nicht geringen Teilen an der Komplexität der Materie Online-Shop liegt.

**Comment by frase-git** [comment]
> Aber okay, ich habe im unpublish-on-fail Branch noch eine zusätzliche Warnmeldung ergänzt.

Ja. So hatte ich mir das gedacht.
Wenn es auch `xh_fail` (rot) sein und den Hinweis auf den Wartungsmodus enthalten könnte.
Ausgelöst wird es ja auch nur bei "roten" Warnungen im Check?
Ich denke, entgegen meinen sonstigen Überzeugungen, müssen wir den User hier richtig nerven, damit er sich kümmert. Und das passiert mit der Meldung.
Dass mir die XH-Meldungen vom Styling her nicht besonders gefallen, ist Nebensache. Vielleicht machen wir uns irgenwann mal daran - und an die Plugin-Menüs. Ich glaube, das hattest du dir mal gewünscht.

Es ist klar, dass wir nicht alles abfangen können.
Aber so ist es sicherer, soweit wir es beeinflussen können.

Noch eine kleine Kritik, die mir allerdings nicht ganz so wichtig ist:

> XH-Shop-Fehler gefunden. Details finden Sie in der Systemprüfung.

Mich stört das "Sie", was du ja konsequenterweise überall verwendest. Das Wiki und die Hilfe sind nun aber in "du". Vorschlag:

> XH-Shop-Fehler gefunden. Details siehe Systemprüfung.
***
Was mir gerade durch den Kopf ging:
Was hieltest du davon, statt der Meldung das FA-Cart-Icon in Rot zu zeigen, solange der Shop im Wartungsmodus ist. Ist er online, dann in Grün.
Dabei wäre es unerheblich, ob ein Fehler vorliegt, oder ob der User den Shop in den Wartungsmodus versetzt hat.
Schaltet er online und das Icon bleibt rot (oder vielleicht durch-ge-ikst), dann weiß er, dass noch ein Fehler vorliegt.
Bitte als alternativen Vorschlag betrachten - nicht als dringenden Wunsch.

**Comment by cmb69** [comment]
> Wenn es auch xh_fail (rot) sein und den Hinweis auf den Wartungsmodus enthalten könnte.

Zu `xh_fail` geändert.

> Mich stört das "Sie", was du ja konsequenterweise überall verwendest. 

Ja, da sollte ich mal umdenken. Fürs Frontend halte ich "Sie" noch immer für sinnvoll, aber im Backend ist das "du" wohl passender.

> Was hieltest du davon, statt der Meldung das FA-Cart-Icon in Rot zu zeigen, solange der Shop im Wartungsmodus ist. Ist er online, dann in Grün.

Ich finde es so wie es jetzt ist, schon zu viel, und würde das ungern noch ausbauen. Wenn das Beispiel Schule macht, dann ist bald der Bildschirm voll von irgendwelchen Warnungen und/oder Hinweisen über irgendwelche aktiven oder nicht aktiven Pluginfunktionalitäten. Und konkret beim Shop besteht halt die Gefahr, dass ein User das Hirn abschaltet, und nur noch schaut, dass die Fehlermeldung weg ist, statt wirklich zu prüfen, ob **alles** okay ist.

Was ich gut fände, wäre eine zusammengefasste Systemprüfung aller Plugins, aber da müsste man sich auf eine API einigen, und die Plugins müssten mitspielen – da habe ich wenig Hoffnung, dass das mittelfristig erfolgen würde.

Allerdings halte ich die Prüfungen auf plausible Einstellungen in der Systemprüfung sowieso nur für einen Workaround wegen mangelnder Features der Konfigurationsformulare und bezüglich alter `catalog.php` Dateien. Idealerweise sollten Formulare beim Submit validiert werden, und falls irgendetwas nicht passt, dann gar nicht erst akzeptiert werden, sondern mit möglichst gut platzierten Fehlermeldungen zurück an den Absender gehen. Auf diese Weise können überhaupt keine fehlerhaften Daten ins System kommen (außer jemand bearbeitet die Dateien von Hand; dann ist er halt auf sich selbst gestellt). Okay, ein paar Dinge sind auch dann problematisch, beispielsweise Seitenzuordnungen, wenn eine zugeordnete Seite später umbenannt oder gelöscht wird, aber diesbezüglich könnte irgendwann eine API eingeführt werden, so dass ein Plugin darauf reagieren kann.

**Comment by frase-git** [comment]
Ja. Sehr gut. Bin zufrieden ;-)

Bei allen aufgeführten Argumenten sind einige dabei, die mich überzeugen - andere weniger.

Macht nix. So, wie es jetzt ist find ich gut und praktikabel.
Auf Albert warten?

**Comment by cmb69** [comment]
> Auf Albert warten?

Bin unsicher. 1.0rc1 ist eigentlich zum Testen kaum brauchbar, v.a. wegen #170, und dem nicht brauchbaren PATCH. Vielleicht doch besser den unpublish-on-fail Branch mergen, und gleich 1.0rc2 (ohne PATCH, also nur Vollversion) veröffentlichen. Wäre schön, wenn sich noch der ein oder andere Tester findet; Bugs wie #171 gibt es bestimmt noch ein paar.

**Comment by frase-git** [comment]
mergen 👍 und RC2
Mit Aufruf zum Testen.

Evtl. mit Erklärung für bisherige Tester, dass der Katalog bestehen bleiben kann. (Die config auch?)

**Comment by cmb69** [comment]
> Evtl. mit Erklärung für bisherige Tester, dass der Katalog bestehen bleiben kann. (Die config auch?)

Guter Punkt. `config.php` sollte ersetzt werden, da zumindest `shop_bill_format` nicht mehr gültig ist, was leicht verwirren kann. Ich kann aber gerne einen Patch anbieten, bei dem nur der Katalog inkl. Demo-Bildern fehlt – spart auf jeden Fall Bandbreite.
