### ISSUE TITLE
Default label for selectboxes

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#173]
Die beiden Selects (für Anrede und Land) im Kundendatenformular sind per Voreinstellung leer. Es ist zu überlegen, ob dort statt dessen etwas wie "bitte auswählen:" angezeigt werden soll; siehe https://cmsimpleforum.com/viewtopic.php?f=16&t=12956&start=40#p61711.

**Comment by frase-git** [comment]
"Bitte wählen"
Wenn das nicht sehr aufwendig ist: JA.
