### ISSUE TITLE
step 3: Sorry! Your message could not be sent.

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#175]
Keinerlei andere Meldungen.

**Comment by frase-git** [comment]
Das scheint nur unter PHP 7.1 so zu sein.
Unter PHP 5.6.x ging gerade eine Mail durch.
Ich teste mal weiter.

**Comment by frase-git** [comment]
Mehrere Tests mit verschiedenen Browsern.
5.6.x geht - 7.1 geht nicht

**Comment by cmb69** [comment]
> Das scheint nur unter PHP 7.1 so zu sein.

Kann ich bestätigen. Ich gehe mal debuggen.

**Comment by cmb69** [comment]
Hm, kann es sein, dass bei dir einfach der E-Mail-Versand nicht richtig konfiguriert ist (`sendmail_path` oder was auch immer)? Bei mir klappt es dann nämlich. Und zumindest bei deutscher Sprache sollte in der Log-Datei von CMSimple_XH auch der Grund für den Fehler gemeldet werden: "Could not instantiate mail function." In der englischen Sprachdatei ist ein kleiner Fehler, den ich gleich korrigiere.

**Comment by frase-git** [comment]
> Could not instantiate mail function.

Stimmt. Das steht im Log.
Bisher hat aber der Versand funktioniert.
Das denke ich zumindest.
Ich überprüfe das nochmal.

**Comment by cmb69** [comment]
> Bisher hat aber der Versand funktioniert.

Dann probier doch mal das CMSimple_XH Mailformular aus.

**Comment by frase-git** [comment]
geht auch nicht.
Wo wird nochmal das mailoutput-verzeichnis eingestellt?

**Comment by cmb69** [comment]
> Wo wird nochmal das mailoutput-verzeichnis eingestellt?

Das ist sekundär. Wichtig ist folgender Eintrag in der php.ini:
````
sendmail_path ="C:\xampp71\mailtodisk\mailtodisk.exe"
````
(oder eben irgendein anderer `sendmail_path` oder passende SMTP Einstellungen)

**Comment by frase-git** [comment]
Das Alter - Die Zeiten ... Alles Gründe für Ausfälle.
Ich hätte schwören können, dass es schonmal unter 7.1 lief.
Irrtum.
Jetzt geht es. Danke!
Kann man diesen Kram hier irgendwie löschen?

Ich bin aber trotzdem sehr froh, dass es **nur an mir** lag. ;-)

Nachtrag:
Typo in diesem Zusammenhang gefunden in EML-Datei:
"... Ich hoffe, daß die Ware Ihnen gefallen wird ..."
besser "dass"

**Comment by cmb69** [comment]
> Ich bin aber trotzdem sehr froh, dass es nur an mir lag. ;-)

Na ja, nicht nur. In der englischen Sprachdatei war ein Fehler, der durch diese Meldung gefunden, und behoben wurde. (dd4b0a4) 

> Typo in diesem Zusammenhang gefunden in EML-Datei:
"... Ich hoffe, daß die Ware Ihnen gefallen wird ..."
besser "dass"

Gefixt in 4755c50.
