### ISSUE TITLE
Alternative bill formats

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#18]
Derzeit wird in der Bestellinfomail eine vorbereitete Rechnung im RTF-Format als Anhang `bill.rtf` versandt. In gewissem Rahmen kann das Aussehen des RTF-Dokuments durch Änderungen an `bills/template.rtf` angepasst werden. Mit dieser Rechnung scheinen aber einige Anwender nichts anfangen zu können, außer sie bedingt zum Copy&Paste in die eigene Auftragsverwaltung zu verwenden. Ebenfalls ist zu bedenken, dass es sich bei RTF um ein proprietäres Format handelt.

Es stellt sich die Frage, ob alternative oder zusätzliche Formate unterstützt werden sollten, wobei es nicht umbedingt um eine vollständige Rechnung gehen muss, sondern durchaus auch reine Datenaustauschformate interessant sein könnten, und falls ja, welche.

Siehe dazu https://github.com/cmsimple-xh/xhshop/issues/10#issuecomment-312438788 ff, wo bereits einige Diskussion zu diesem Thema stattfand.

**Comment by cmb69** [comment]
Es scheint, dass zumindest derzeit die Rechnung nicht richtig mit UTF-8 klarkommt. Ich habe gerade den `Universal-XH-Screwdriver „CMB“` bestellt, und in der Rechnung steht `Universal-XH-Screwdriver ?CMB?`.

**Comment by frase-git** [comment]
Stimmt.
Wobei aber Umlaute sauber ankommen.

**Comment by XHalbert** [comment]
Artikel in backend erstellt (Variante mit 2mal " geschrieben):
testprodukt - löst keinen Kauf aus!!! äüß"%& "rot"

> Screwdriver ?CMB?

bei mir werden " richtig behandelt, nicht aber ß

Im Shop angezeigt:
testprodukt - löst keinen Kauf aus!!! äüss"%& "rot"

wenn ich das kopiere und z.B. in Email einfüge wird daraus:
testprodukt - löst keinen Kauf aus!!! äüß"%& "rot"

im Warenkorb und Schritt 3
testprodukt - löst keinen Kauf aus!!! äüss"%& "rot"

in der **Email und bill.rtf** ist alles richtig:
testprodukt - löst keinen Kauf aus!!! äüß"%& "rot"

PS: mich störts nicht, aber vllt. hilfts

**Comment by frase-git** [comment]
> testprodukt - löst keinen Kauf aus!!! äüß"%& "rot"

läuft völlig sauber durch - von E-Mail bis Rechnung alles OK
das mit ß -> ss ist bei mir nicht

Nur „CMB“ läuft nicht:
Überall richtig, außer in bill.rtf -> ?CMB?

**Comment by XHalbert** [comment]
> Universal-XH-Screwdriver „CMB“

wenn ich in franks Demoshop kaufe, werden die " auch in der Email richtig behandelt (bill weiß ich ja nicht)

hab in meinem Shop nochmal editiert:
testprodukt - löst keinen Kauf aus!!! äüß "cmb" %& "rot"
auch hierbei sieht "cmb" immer richtig aus, sowohl in der bill, die im demoshop ist, als auch mit meiner eigenen bill.rtf

**Comment by frase-git** [comment]
teste mal „CMB“ (von hier kopieren) nicht "cmb"
Das sind andere Anführungszeichen.

**Comment by XHalbert** [comment]
ja auch bei mir ?CMB? 

> Das sind andere Anführungszeichen.

verbieten lassen!

**Comment by cmb69** [comment]
Problem gefunden: in template.rtf wird `\ansi\ansicpg1252`  angegeben, und im Billwriter entsprechend `utf8_decode()` aufgerufen. Ergo sind nur Zeichen von CP-1252 (~ ISO-8859-1) möglich. Statt dessen müssten zumindest Zeichen, die nicht in CP-1252 enthalten sind, wohl als Escape-Sequenz (z.B. `\u8222`) geschrieben werden.

> verbieten lassen!

In Deutschland und einigen anderen Ländern kommt man auch heute noch weit mit CP-1252, aber andere können damit wenig anfangen.

**Comment by cmb69** [comment]
@frase-git Da `bill.rtf` nun doch deutlich verbessert wurde, stellt sich die Frage ob wir alternative Lösungen auf 2.0 verschieben sollen. Mir wäre das ganz lieb.

**Comment by XHalbert** [comment]
nichts dagegen

**Comment by frase-git** [comment]
Schließen?
Denke ja.
Wird in #107 abgehandelt.
Milestone 2.0 entfernen.

**Comment by cmb69** [comment]
Ja, ich mach's mal zu. Bei Bedarf kann ja auch wieder ein neues Ticket geöffnet werden; dann am besten nicht ganz so allgemein gehalten, sondern konkret für ein bestimmtes Bill-Format.
