### ISSUE TITLE
Age "verification" necessary?

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#183]
Braucht der Shop ein oder mehrere Felder, wo der Besteller sein Alter bzw. Geburtsdatum eintragen muss, was dann auf ein zu konfigurierendes Mindestalter geprüft wird? Mir geht es hier weniger um den Jugendschutz (Verkauf von Alkohol oder Zigaretten etc.), sondern um die Rechtswirksamkeit des Vertrags (gerade bei Rechnungszahlung).

**Comment by frase-git** [comment]
Ist mir bei anderen (normalen) Shops bisher noch nicht aufgefallen.

Bestellt ein Unmündiger, müssen die Erziehungsberechtigten dafür geradestehen - oder ein Gericht entscheidet etwas anderes.

**Comment by cmb69** [comment]
> Ist mir bei anderen (normalen) Shops bisher noch nicht aufgefallen.

Ist mir gerade bei https://flipperteile.de/de/ passiert (Geburtsdatum musste eingegeben werden).

> Bestellt ein Unmündiger, müssen die Erziehungsberechtigten dafür geradestehen - oder ein Gericht entscheidet etwas anderes.

Ich glaube es ist gerade andersherum, siehe https://www.e-recht24.de/artikel/ecommerce/6271-onlineshop-alterskontrolle-alkohol-tabak-jugendschutz.html, Punkt 3. Dort wird aber auch erwähnt, dass eine Altersabfrage datenschutzrechtlich bedenklich ist.

**Comment by frase-git** [comment]
Na ja, Flipperteile zählen sicher zu Geldspielautomaten ...
Bist du ein Flipperer?
Ich spiele manchmal noch einen Uralt-Android-Flipper in der DOS-Box.

> Ich glaube es ist gerade andersherum, siehe https://www.e-recht24.de/artikel/ecommerce/6271-onlineshop-alterskontrolle-alkohol-tabak-jugendschutz.html, Punkt 3. Dort wird aber auch erwähnt, dass eine Altersabfrage datenschutzrechtlich bedenklich ist.

Da geht es ja gerade um jugendgefährdende Dinge.
Bedenklichkeit:
1. Datenschutzgründe
2. Eingabe ist nicht überprüfbar

Falls ein XH-Shop-Betreiber nun aber doch solche Dinge anbieten will, sollte es vielleicht wirklich eine Config-Option "Alter abfragen" geben?

@XHalbert ?

**Comment by XHalbert** [comment]
Also ich habe Altersabfrage noch nicht vermisst.
Rechnungskauf machen die meisten Shopbetreiber wohl entweder "auf Vertrauen"  bzw. erst beim wiederholten Einkauf - nicht bei Erstkunden (ich z.B.) oder sie wickeln Rechnungskauf über paypalplus ab, da trägt paypal das Risiko und schreibt dem Shopbetreiber den Betrag sofort gut.

Nebenbei: Wie würdest du denn die Richtigkeit der Altersangabe prüfen? Ich selbst gebe bei Abfragen NIE mein tatsächliches Geburtsdatum an.

Ich denke also, das braucht XH-Shop nicht, aber wenn es doch mal gewünscht werden sollte, dann wirklich nur mit Config-Option.

**Comment by cmb69** [comment]
> Bist du ein Flipperer?

Nicht wirklich. Ich habe für eine Bekannte, die einen High-Speed hat, Ersatzteile bestellt.

> Falls ein XH-Shop-Betreiber nun aber doch solche Dinge [jugendgefährdend] anbieten will, sollte es vielleicht wirklich eine Config-Option "Alter abfragen" geben?

Ich denke diesen Fall brauchen wir nicht speziell zu berücksichtigen, weil das noch viel komplexer wäre. Der Käufer dürfte erst auf die Shopseite gelangen können, nachdem ein Alternachweis erbracht wurde.

> Also ich habe Altersabfrage noch nicht vermisst.

Gut, dann schließe ich dieses Ticket.

> Ich selbst gebe bei Abfragen NIE mein tatsächliches Geburtsdatum an.

Hm, das könnte allerdings den Kaufvertrag nichtig machen, wegen falscher Angaben. ;)
