### ISSUE TITLE
Don't remove line breaks from annotation

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#19]
Die Angaben im Feld "Anmerkungen" werden an irgendeiner Stelle "bereinigt" und erscheinen anschließend nur noch als "Fließtext" hintereinander (Zusammenfassung, Mails ...)
Ich meine, dass vom User eingegebene Zeilenumbrüche wieder hergestellt/erhalten/umgewandelt werden sollten -> nl2br ?

**Comment by XHalbert** [comment]
Fließtext gut

**Comment by cmb69** [comment]
> Ich meine, dass vom User eingegebene Zeilenumbrüche wieder hergestellt/erhalten/umgewandelt werden sollten -> nl2br ?

Finde ich auch. Das Problem ist hier tatsächlich das fehlende `nl2br(`)` – in der Textmail stimmt nämlich alles. PR #22 würde das beheben.
