### ISSUE TITLE
Add to cart fails miserably when Cookies are disabled

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#192]
Siehe https://cmsimpleforum.com/viewtopic.php?f=16&t=12956&start=120#p62359.

**Comment by cmb69** [comment]
Ich denke, PR #224 löst das ganz akzeptabel. Wäre natürlich schöner, wenn ohne Cookies die Add-To-Cart-Buttons erst gar nicht angezeigt würden (und statt dessen gleich eine entsprechende Meldung), aber das wäre frickeliger, und letztlich werden die meisten User wohl ohnehin Sitzungscookies akzeptieren. Vielleicht könnte aber der Meldungstext noch verbessert werden?

**Comment by frase-git** [comment]
Geht so. Auch der Text ist OK.
(Das wird normalerweise sowieso nur selten vorkommen.)

Wo und in welcher Form wird der Text angezeigt? (Habe jetzt nicht getestet.)

**Comment by cmb69** [comment]
> Wo und in welcher Form wird der Text angezeigt?

Ganz einfach im Content-Bereich, oberhalb der restlichen Shop-Ausgaben, also etwa:
![Anmerkung 2020-06-21 133816](https://user-images.githubusercontent.com/2306138/85223633-98fe8380-b3c4-11ea-9b6d-993242ef4329.gif)

**Comment by frase-git** [comment]
Gut so.
(Oder doch lieber .xhWarning statt .xhInfo bzw. .xh_warning statt .xh_info?)

**Comment by cmb69** [comment]
> Oder doch lieber .xhWarning statt .xhInfo bzw. .xh_warning statt .xh_info?

Bin nicht sicher. Der Vorteil der Info wäre wohl, dass man dem User weniger stark suggeriert, dass er Cookies erlauben soll. Was denken andere darüber?

**Comment by cmb69** [comment]
Ich hab's mal bei der Info belassen. Können wir natürlich noch in eine Warnung ändern.
