### ISSUE TITLE
link to xhs.min.js wrong

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#194]
index.php Zeile 57
`$hjs .= '<script src="'.$pth['folder']['plugins'].'/xhshop/js/xhs.min.js"></script>';`
muss heißen
`$hjs .= '<script src="'.$pth['folder']['plugins'].'xhshop/js/xhs.min.js"></script>';`

Wieso funktioniert das trotzdem?

**Comment by cmb69** [comment]
Danke fürs raussuchen. :)

> Wieso funktioniert das trotzdem?

Siehe cmsimple-xh/cmsimple-xh#282.
