### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by gtbu** [cmsimple-xh/xhshop#199]
Since not everybody knows how to work with composer (as with putty etc . in Mediawiki) it would be an idea to implement composer in Cmsimple XH like in Pageview2(github) , where plugins are installed automatic with composer which resides in a subdirectory(of course the normal pluginloader should be kept)

**Comment by cmb69** [comment]
> Since not everybody knows how to work with composer […]

The XHShop plugin (as well as CMSimple_XH) uses composer only to install some *development* requirements; besides that I assume that PHP developers know the basics of using composer (or could educate themselves on that topic), it is not even *necessary* to use any of the dev-requirements. Setting up a demo shop could be done with setup.bat (or manually, if need be).

Some composer integration for cmsimple-xh/cmsimple-xh may make sense, but should be requested there (or in the CMSimple_XH forum). And frankly, while composer may solve some problems, I'm afraid it would cause even more new issues in the context of CMSimple_XH.
