### ISSUE TITLE
Add system check

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#2]
Sollte eine Prüfung auf XH Version ab 1.7.x stattfinden?
Oder mindestens auf das FA-Plugin?

**Comment by cmb69** [comment]
> Sollte eine Prüfung auf XH Version ab 1.7.x stattfinden?

Wenn nur XH ≥ 1.7 unterstützt werden soll, dann würde ich sagen, ja. Fa_XH sollte auf jeden Fall geprüft werden.

Die Frage ist halt wann die Prüfung erfolgen, und was bei einem Fehlschlag passieren soll.

**Comment by frase-git** [comment]
Ich glaubte, deine Anpassungen für 1.7 schließen 1.6 aus?
Wenn dem nicht so ist, umso besser.
Dann nur prüfen auf FA. Meldung ähnlich wie beim fhs_adminmenu - oder viel einfacher: Meldung auf weißer Seite, sobald das Plugin installiert wird und FA nicht da ist.

**Comment by cmb69** [comment]
> Ich glaubte, deine Anpassungen für 1.7 schließen 1.6 aus?

Sollte eigentlich nicht sein. Zumindest XH ≥ 1.6.3 kann man ganz gut unterstützen. Ist halt die Frage, ob es sinnvoll ist, da XH 1.6 eigentlich schon gestern sein Lebensende erreicht hat.

> oder viel einfacher: Meldung auf weißer Seite, sobald das Plugin installiert wird und FA nicht da ist.

Ich selbst finde das Verhalten okay, aber es gab auch schon Kritik daran ("zerschösse die Installation"). Allgemein neige ich eher zu einem System-Check wo halt auch Warnungen angezeigt werden können, die das Plugin nicht komplett unbrauchbar machen, aber eben nicht alle Features erlauben. Allerdings kann es passieren, dass der User gar nicht erst zum System-Check kommt, weil vorher z.B. eine Funktion aufgerufen wird, die nicht verfügbar ist; dann hilft nur noch der Debug-Modus (oder das Lesen der Dokumentation).

**Comment by frase-git** [comment]
Wenn ich es richtig überschaue, wären bei fehlendem FA nur die Icons nicht zu sehen bzw. falsch dargestellt.
Funktion sollte gewährleistet sein.
Hilft das weiter?

**Comment by cmb69** [comment]
> Wenn ich es richtig überschaue, wären bei fehlendem FA nur die Icons nicht zu sehen bzw. falsch dargestellt.
Funktion sollte gewährleistet sein.

Ja. :)

**Comment by frase-git** [comment]
Systemcheck. Super!

Frage: `data/` muss nicht beschreibbar sein?

**Comment by cmb69** [comment]
> Frage: data/ muss nicht beschreibbar sein?

Oh, doch! Danke! Gleich nachgeholt: 7ac8876.

**Comment by frase-git** [comment]
Oh Mann, ich werde/bin alt.
Was ist mit `classes\paymentmodules\paypal\tmp_orders\`

**Comment by cmb69** [comment]
> Was ist mit classes\paymentmodules\paypal\tmp_orders\

Sehr gut, "alter" Mann! :) 

Wie das gelöst wird, hängt allerdings von #64 ab. Wenn nämlich die Payment-Module unabhägig bleiben sollen, dann darf diese Prüfung nicht direkt in `XHS_system_check_service.php` erfolgen, sondern im Paypal-Payment-Modul (bzw. von dort müsste der zu prüfende Dateipfad erfragt werden).

Ich öffne das Ticket wieder, damit diese Sache nicht vergessen geht.

**Comment by cmb69** [comment]
> Was ist mit classes\paymentmodules\paypal\tmp_orders\

Erledigt: 8b32e7e.
