### ISSUE TITLE
Paypal-Problem

### ISSUE THREAD

**Issue by XHalbert** [cmsimple-xh/xhshop#20]
es gibt da noch das alte Paypal-Problem. Wurde bei mir NIE gelöst, trat z.B. im Mai wieder paarmal auf. Frage ist, ob das bei einem von euch auch auftritt oder ob das ein Serverproblem ist (Strato). Immerhin habe ich auch das Updatecheckproblem wie wolgang_58.

https://cmsimpleforum.com/viewtopic.php?f=16&t=4100&start=10
1. Variante
Der Kauf wird ausgelöst, paypal klappt, Kunde und ich kriegen vom Shop die email -
aber: der Warenkorb bleibt voll und kommt nicht der Shopbildschirm mit "... email verschickt etc. ..."
Dann aber oh Wunder kommt der Bildschirm doch, wenn ich erneut auf Warenkorb klicke...

2. Variante
Kauf klappt, Paypal klappt, aber Warenkorb bleibt voll, kein ThankYou und **keine Bestätigungsemail**
Datei in temp_orders wird nicht gelöscht (hier kann man die Bestelldaten auslesen)
es wird kein Cookie für die Bewertung gesetzt.
Es entsteht kein Schaden durch unbearbeitete Bestellung, weil paypal eine eigene Zahlungsemail sendet, die ankommt.

Beim Testen: Beide Varianten kommen natürlich nur vor, wenn man tatsächlich mit paypal bezahlt. Wenn man nicht mit paypal bezahlt, also abbricht, oder die Bezahlung nicht klappt (z.B. falsche emailadresse eingegeben), ist es ja gewollt, dass man ja in den immer noch vollen Warenkorb zurück kommt, um eine andere Zahlungsart wählen zu können.

**Comment by frase-git** [comment]
paypal habe ich bisher immer abgeschaltet. Zu viele Probleme (siehe deine Hinweise im Forum und hier).
Habe auch kein Konto, mit dem ich testen könnte.

**Comment by XHalbert** [comment]
ich kann auf paypal nicht verzichten, viele Kunden nutzen das.

z.Z. tritt immer Variante 1 ein, d.h. es gibt Emails, aber kein ThankYou, Warenkorb bleibt voll, 
aber vor ein paar Wochen war auch wieder mal Variante 2.

Wer testen will (wie gesagt, das Problem wurde nie gelöst):
Habe das Testprodukt wieder aktiviert: https://www.natur-und-handgemacht.de/?Shop&wrsCategory=left_overs

**Comment by cmb69** [comment]
> ich kann auf paypal nicht verzichten, viele Kunden nutzen das.

Ich denke auch, dass Zahlung per PayPal unbedingt unterstützt werden muss.

Da das Problem anscheinend unregelmäßig auftritt, könnte ich mir vorstellen, dass es mit der [IPN](https://developer.paypal.com/docs/classic/products/instant-payment-notification/) zu tun hat, und zwar damit, dass diese erst mit [zeitlicher Verzögerung eintrifft](https://developer.paypal.com/docs/classic/products/instant-payment-notification/#using-ipn-in-your-checkout-flow):

> Although PayPal usually processes IPN messages immediately, IPN is not synchronized with actions on your website. Internet connectivity is not always 100% reliable and IPN messages can be lost or delayed. The IPN service automatically resends messages until the listener acknowledges them. The service resends messages for up to 4 days.

Kann der Shop nicht auch selbst bei PayPal anfragen, ob die Zahlung getätigt wurde, statt sich auf die IPN zu verlassen?

**Comment by frase-git** [comment]
Okay, hier muss ich mich raushalten.

Frage:
Es gibt "neue" Paypal-Logos : https://www.paypal.com/de/webapps/mpp/logo-center

Soll ich im Demo Shop eines davon reinsetzen (bei Auswahl Zahlungsart)?
Welches?

Übrigens:
Im Demoshop ist im Button "mit Paypal bezahlen" schon ein neueres PP-Logo aus FA drin.

**Comment by XHalbert** [comment]
> "neue" Paypal-Logos

nimm doch einfach was dir am besten gefällt

PS bin jetzt mal OFF

**Comment by frase-git** [comment]
> nimm doch einfach was dir am besten gefällt

Im Demo-Shop gemacht.
Änderungen:
\plugins\xhshop\classes\paymentmodules\paypal\paypal.php Zeile 56:

`return '<img src="' . XHS_BASE_PATH . 'classes/paymentmodules/paypal/images/de-pp-logo-100px.png">`

Und unter \plugins\xhshop\classes\paymentmodules\paypal\images\ das Bild einfügen:

![de-pp-logo-100px](https://user-images.githubusercontent.com/24246330/27769773-b652447a-5f31-11e7-9f6b-b3f283b014c6.png)

**Comment by cmb69** [comment]
> `return '<img src="' . XHS_BASE_PATH . 'classes/paymentmodules/paypal/images/de-pp-logo-100px.png">`

Wäre da ein generischer Name nicht sinnvoller? Also etwa `paypal-logo.png`. Dann kann man die Datei einfach durch eine andere ersetzen (klar geht auch wenn sie `de-pp-logo-100px.png` heißt, aber das finde ich eher verwirrend).

**Comment by frase-git** [comment]
Habe einfach den Original-Namen von Paypal verwendet.
Kannste nach Belieben ändern - oder?

**Comment by cmb69** [comment]
> Kannste nach Belieben ändern - oder?

Ja. Erledigt.

**Comment by XHalbert** [comment]
> Kann der Shop nicht auch selbst bei PayPal anfragen, ob die Zahlung getätigt wurde, statt sich auf die IPN zu verlassen?

Das weiss ich so nicht. 
paypal ohne ipn geht zwar auch. Aber dann müsste der Shopbetreiber dem Kunden wohl irgendwie eine paypal-Zahlungsaufforderung schicken. Sowas geht, aber ob das auch automatisch geht weiss ich nicht, außerdem sind die Kunden es gewöhnt, dass man gleich "mit einem Klick" bezahlt, anstatt Emails abrufen, sich einloggen usw.

Übrigens gibt es ja jetzt auch paypalPlus mit allen möglichen Zahlmethoden, auch Rechnungsversand (paypal streckt sozusagen das Geld vor). Wenn, dann sollten wir das nur zusätzlich einbauen oder wahlweise. paypalPlus ist teuer für den Shopbetreiber. Für mich kommt derzeit nur das normale paypal in Frage, ist schon teuer genug.

Es gibt ja die Entwicklerseite von paypal:
https://www.paypal.com/de/webapps/mpp/partners-and-developers
Integration in Shopsysteme
... Schritt-für-Schritt-Anleitungen ...

Oder Developer-Portal https://developer.paypal.com/
Es gibt auch eine Sandbox, aber schon das war mir damals zu hoch. Martin meinte ja, dass sein ipn fehlerfrei sei und bei ihm, egal ob in Sanbdbox oder in echt, einwandfrei arbeite. Aber einbilden tue ich mir die Sache ja nicht, und auch wenn es ein Stratoproblem sein sollte, wäre es nötig, das zu umgehen. Bei Strato sind ja einige XH-ler.

PS was bedeutet es eigentlich wenn ein issue closed ist?

**Comment by frase-git** [comment]
> PS was bedeutet es eigentlich wenn ein issue closed ist?

Dann hat das Problem den Status "erledigt". Wenn noch offen, dann wird immer mal wieder nachgeschaut, was man tun kann. Sozusagen eine ToDo-Liste.
Geschlossene können aber auch wieder geöffnet werden ;-)

**Comment by cmb69** [comment]
So wie ich es sehe, müsste das gesamte Paypal-Handling gründlich geprüft und zumindest modernisiert werden. Zum einen ist `fsockopen()` zu low-level (z.B. müssten Redirects manuell behandelt werden; cURL scheint hier die sinnvollere Alternative), dann werden zwar verschiedene potentielle Fehler abgefragt, aber nicht wirklich behandelt (z.B. [hier](https://github.com/cmsimple-xh/xhshop/blob/511f697243f3760013747f8429867a39930fd86e/classes/paymentmodules/paypal/paypal.php#L230-L232)), und dass die gesamte Session in ein nicht explizit geschütztes Verzeichnis serialisiert wird, finde ich auch problematisch. Zumindest muss für `tmp_orders/` die Verzeichnisauflistung deaktiviert sein.

**Comment by XHalbert** [comment]
> die Verzeichnisauflistung deaktiviert sein.

was ist das?

**Comment by frase-git** [comment]
Verzeichnisauflistung:
Wer die Adresse des Ordners kennt, könnte ihn sich anzeigen lassen und evtl. fröhlich Daten einsehen oder sonstwas.

**Comment by cmb69** [comment]
> Wer die Adresse des Ordners kennt, könnte ihn sich anzeigen lassen und evtl. fröhlich Daten einsehen oder sonstwas.

Genau. Ohne Verzeichnisauflistung müsste man die Session-ID erraten, und wenn man das schafft, dann gibt's noch ganz andere Probleme.

Zur konkreten Konfiguration siehe https://ppfeufer.de/apache-verzeichnisinhalte-vom-webserver-nicht-anzeigen-lassen/.

**Comment by cmb69** [comment]
Zumindest ein echtes Problem habe ich bereits gefunden: die an Paypal übergebenen [URLs werden aus $_SERVER[HTTP_REFERER]](https://github.com/cmsimple-xh/xhshop/blob/fd6eff0ce53aa5e5001e7e01f200fd475a192ccb/classes/payment/Paypal.php#L63-L65) gebildet; das ist aber nicht notwendigerweise gesetzt. In diesem Fall kann die IPN nicht zugestellt werden. Das ist vermutlich auch der Grund, warum die Paypal-Bezahlung seit einiger Zeit gar nicht mehr funktioniert, eben weil sich die URLs geändert haben.

**Comment by XHalbert** [comment]
> seit einiger Zeit gar nicht mehr funktioniert, 

an referer hatte damals Martin einiges versucht... sogar fest meine url eintragen löste das damalige Problem (s.o.) bis heute nicht.
Aber jetzt ist wohl was anderes. Komischerweise passierte gestern (und auch heute zur Kontrolle noch zweimal) bei einem echten Paypal-kauf folgendes: Zahlung wird ganz normal bei paypal verbucht, und paypal-Benachrichtigung kommt an. Also müsste wohl die Kommunikation funktionieren. Shop zeigt Dankeschönseite, Warenkorb leer, soweit gut - nur kommt keine Mail vom Shop, keine Datei in temp_orders ( bei dem alten Problem blieb eine .temp übrig). 
Hatte zunächst den paypal-EC branch benutzt, jetzt wieder den aktuellen master, beides gleich.
Jetzt Probekauf zum Vergleich gemacht: Kauf mit "Vorkasse" klappt ohne Probleme.

**Comment by cmb69** [comment]
> Aber jetzt ist wohl was anderes.

Kann gut sein, dass durch die Änderungen Paypal derzeit nicht benutzbar ist. Ich habe das bisher einfach nicht auf dem Schirm gehabt. Bin nun aber dran. Also bitte noch etwas Geduld, und derweil keine weiteren Paypal-Tests. :)

**Comment by XHalbert** [comment]
> derweil keine weiteren Paypal-Tests

ok bin jetzt sowieso bis Di. Abend weg

**Comment by cmb69** [comment]
> ok bin jetzt sowieso bis Di. Abend weg

Schade. Gerade eben ist es mir zum ersten Mal gelungen erfolgreich per Paypal zu bestellen – und die Mails vom Shop kommen an! Ich mach mal einen Pull-Request fertig.

**Comment by XHalbert** [comment]
Zeit hat grade noch für einmal testen gereicht (bevor ich Ärger krieg ;) - echter Kauf
UND ES KLAPPT !!! Jippiiiiiiiiiiii
- cmb heißt übersetzt: der kann was der Christph
danke danke danke

(Dankeschön-Seite, Warenkorb weg, Emails und Anhang i.O.)

**Comment by cmb69** [comment]
Danke fürs Testen! Ich schließe dieses Ticket dann endlich.

**Comment by XHalbert** [comment]
mein üblicher echter paypal Testkauf ist diesmal fehlgeschlagen.
Das Testprodukt kostet 0,01 €.
![paypal-error](https://user-images.githubusercontent.com/29812782/29135120-6106f742-7d39-11e7-8cfa-6a11c90b7c58.JPG)
cart wär empty!
Ist jetzt Mind.Bestellwert 1 €?

**Comment by XHalbert** [comment]
selbe Errormeldung bei Testkauf mit 1,- €

**Comment by cmb69** [comment]
> Ist jetzt Mind.Bestellwert 1 €?

Vorgegeben sind 20,00€, aber wenn diese unterschritten sind, dürfte man erst gar nicht zu Schritt 2 (geschweige denn weiter) kommen.

Ich denke, ich habe das Problem gefunden, will's aber erst im Sandkasten ausprobieren, bevor da noch weiteres Geld verbraucht wird. Da ich gleich weg muss, wird das noch etwas dauern. Danke auf jeden Fall für den Test und die Meldung.

**Comment by XHalbert** [comment]
ja eilt ja nicht :)

> Vorgegeben sind 20,00€

den hab ich auf 0 gesetzt.

PS: Wenn error kommt kostet nix
ansonten sind immer 35 ct als fester Anteil weg, der prozentuale Anteil wird zurückerstattet. Insofern würd mich mind.Bestellwert 1,- € auch zum testen nicht stören...

**Comment by cmb69** [comment]
Okay, das Paypal-Problem sollte mit f26a660 behoben sein. (Ich habe übrigens den eml-bill Branch in master gemerget und gelöscht – also wieder mit master testen.)

> Insofern würd mich mind.Bestellwert 1,- € auch zum testen nicht stören...

Nimm am besten `0.01` € – einen Rechnungsbetrag von 0,00 € mag Paypal vielleicht nicht, und sonst ändert sich ja nichts, wenn du einen Testartikel für 0,01 € kaufst.

PS: das mit `0.01` € ist natürlich Quatsch, da man ohne Artikel gar nicht zum Warenkorb kommt, und [`0.00` € Artikel nicht sein sollten](https://github.com/cmsimple-xh/xhshop/wiki/Artikel-bearbeiten#artikel-bearbeiten).

**Comment by XHalbert** [comment]
Es klappt wieder (getestet mit 0,01 € ). Alles gut. Prima!
