### ISSUE TITLE
Add hi_fancybox to catalogue images in catalog.tpl?

### ISSUE THREAD

**Issue by manu37** [cmsimple-xh/xhshop#211]
Frage an die xhshop Cracks:
Ist es möglich, die hi_fancybox auch bei den preview Bildern im catalog.tpl anzuwenden? Ich hatte gehofft, dies im productDetails.tpl abzugreifen. Aber so einfach ist es wohl nicht.
Antworten gerne willkommen.

**Comment by frase-git** [comment]
Darüber hat es eine lange Diskussion gegeben (https://github.com/cmsimple-xh/xhshop/issues/28 und https://github.com/cmsimple-xh/xhshop/issues/40). Denn ursprünglich war das genau so.

An welcher Stelle Christoph dann letztendlich geändert hat, weiß ich jetzt nicht. Mal sehen, ob ich das noch finde.

**Comment by manu37** [comment]
Anscheinend hab Ihr [hier](https://github.com/cmsimple-xh/xhshop/issues/28#issuecomment-316412586) diese Möglichkeit definitiv ausgetrieben, schade. Aber wenn doch alles so schön template-basiert ist, sollte das doch möglich sein. Im template habe ich Zugriff auf die FrontEndController Instanz. Aber von da ab verliert sich die Spur, wie ich zum image link komme.

**Comment by frase-git** [comment]
Vielleicht kommst du [mit dieser Funktion](https://github.com/cmsimple-xh/xhshop/blob/master/classes/View.php#L207) weiter?
Ich verstehe Code nicht ansatzweise :(

**Comment by manu37** [comment]
Ja das wäre schön, aber an den href resp. an das Detailbild komme ich nicht ran. Zumindest im catalog.tpl in den products Eigenschaften nicht.
> Ich verstehe Code nicht ansatzweise :(

Na ja. OOP und Abstrahierung ist ja ok. Aber komplett ohne Dokumentation ist das schon ein Irrgarten.

Ich finde den xhshop ein irre gutes plugin, bin aber in den templates etwas enttäuscht, wie eingeschränkt auf die dynamischen Daten zugegriffen werden kann. Aber das wurde wohl aus guten Gründen so designed und ist gut so.

Mein Vorschlag wäre:
Wenn keine Detailseite, aber ein Detailbild vorhanden ist, dann im Katalog das previewbild mit Detailbild mit zoom verlinken. Das wäre dann irgendwo [hier ](https://github.com/cmsimple-xh/xhshop/blob/7dc4d6c36704423b87b44476145f71fad0d7d800/classes/Controller.php#L184) zu erweitern, oder ein zusätzliche Product Eigenschaft ('preview with zoom') mitzugeben.

**Comment by frase-git** [comment]
> Mein Vorschlage wäre: ...

Schön, da wirst du aber auf cmb warten oder es selbst machen müssen.
Bei mir reicht's dazu nicht ;-)

**Comment by frase-git** [comment]
Sorry, hatte den falschen Button erwischt und ge"closed".

**Comment by manu37** [comment]
Hier mein [PR](https://github.com/cmsimple-xh/xhshop/pull/212)

**Comment by frase-git** [comment]
> Hier mein PR

Super. Funktioniert bei mir einwandfrei.

**Comment by manu37** [comment]
Da hier kein BC Break zu erwarten ist, würde ich diese Erweiterung gerne im 1.1 sehen.
