### ISSUE TITLE
Varianten mit Bildern

### ISSUE THREAD

**Issue by XHalbert** [cmsimple-xh/xhshop#23]
vielleicht wirklich zuviel verlangt - aber schön wärs doch 
(hatte jahrelang gehofft, dass Martin hier was machen würde...)

Nur auf Detailseiten:
Varianten werden abgebildet, können durch Anklicken des Thumb (nicht notwendig) oder im Dropdown ausgewählt werden. Das ausgewählte wird dann vergrößert gezeigt.
![neu-8](https://user-images.githubusercontent.com/29812782/27769429-36897d88-5f29-11e7-8252-993ac73b017b.jpg)

Auch wenn viele eShops dazu übergehen, keine Varianten sondern für jede Farbe einen Artikel einzustellen, möchte ich nicht ohne Varianten auskommen müssen. Ich habe z.T. sehr viele Varianten und das würde die Listenansicht sprengen.
Wäre es viel Arbeit, das zu realisieren?

**Comment by frase-git** [comment]
Bin nicht sicher, ob ich richtig verstand.
Varianten mit mehreren Bildern gehen ja schon -> auf CMSimple-Seiten die versteckt sind oder auch nicht.
Demnächst wird es auch auf "normalen"-Shop-Detailseiten möglich sein, mehrere Bilder zu haben.

Was ich mir derzeit nicht vorstellen kann, ist, dass bei Klick auf ein Bild eine Variante ausgewählt wird. Das geht nur über die select-Box.
Was definitiv auch nicht gehen wird, ist: Mehrere Varianten mit **unterschiedlichen** Preisen als EIN Artikel.

Zur vergrößerten Ansicht:
siehe Beispiel -> 3 Varianten in der Groß-Ansicht zum Durchblättern:
http://fhs.bplaced.net/xhshop-demo/?Test

**Comment by cmb69** [comment]
> Wäre es viel Arbeit, das zu realisieren?

Irgendwie schon. Derzeit sind die Varianten ja extrem minimalistisch: einfach nur ein Textfeld, dass bei Semikolons gesplittet wird. Sollen den Varianten auch noch Bilder zugeordnet werden, müsste das allein schon in der Produktadministration aufbereitet werden (oder sollen Bild und Vorschaubild einfach ebenfalls manuell eingetippt werden?)

Aber wenn das umgesetzt wird, dann dauert es vermutlich nicht lange, bis auch noch weitere Details bei den Varianten hinzukommen sollen (z.B. individueller Preis; Verfügbarkeit; an eine Variante-Matrix mag ich gar nicht erst denken). Daher sollten wir, falls wir die Varianten ausbauen,  das auch gleich richtig machen (und eben nicht einfach alles in einem Input irgendwie notieren lassen, sondern eben richtige Formulare anbieten). Und das ist halt leider doch etwas mehr Aufwand (da fehlt noch immer vernünftige Unterstützung durch CMSimple_XH).

Insgesamt müssen wir uns überlegen, was alles in Version 1.0 integriert werden soll. Je mehr das ist, umso länger wird es dauern bis diese Version fertig ist. Vermutlich ist es sinnvoll, einige Verbesserungen schon frühzeitig für eine spätere Version einzuplanen.

> Was ich mir derzeit nicht vorstellen kann, ist, dass bei Klick auf ein Bild eine Variante ausgewählt wird. Das geht nur über die select-Box.

Ah, da kommt mir die Idee für einen Workaround. Wenn die Zuordnung der Bildnamen zu der jeweiligen Variante eindeutig ist, dann könnte man hier ein wenig JavaScript nutzen, um beim Anklicken (Doppelklick?) des Bildes eben die Select-Box entsprechend umzuschalten. Nicht perfekt, da User ohne JS das nicht nutzen können, aber vielleicht ein brauchbarer Workaround. Ein solches JS Skipt sollte aber vielleicht nicht Teil von XHShop sein, sondern könnte auch separat verfügbar gemacht werden (so als optionales Addon).

**Comment by XHalbert** [comment]
> sollen Bild und Vorschaubild einfach ebenfalls manuell eingetippt werden?

von mir aus gerne

> um beim Anklicken (Doppelklick?) des Bildes eben die Select-Box entsprechend umzuschalten. 

das würde mich glücklich machen (sollte aber mögl. auch auf android funzen).
lieber Einfachklick

**Comment by frase-git** [comment]
> Ein solches JS Skipt sollte aber vielleicht nicht Teil von XHShop sein, sondern könnte auch separat verfügbar gemacht werden (so als optionales Addon).

Und genau das denke ich auch.
Ball flach halten. Konzentration aufs Wesentliche. Im Moment geht doch schon so viel!
Wir werden mit den vorhandenen Mitteln keinen Profi-Shop hinkriegen und uns nur verzetteln - und es wird gar nichts fertig.
Extra/Spezial-Lösungen können (in einem Extra-Shop-Forum?) später entwickelt werden.

**Comment by cmb69** [comment]
> Extra/Spezial-Lösungen können (in einem Extra-Shop-Forum?) später entwickelt werden.

Sollte es keine separate Homepage für den XHShop geben, dann könnten wir das [hiesige Wiki](https://github.com/cmsimple-xh/xhshop/wiki) nutzen.

**Comment by XHalbert** [comment]
> Extra/Spezial-Lösungen können (in einem Extra-Shop-Forum?) später entwickelt werden.

gut, ok

> Daher sollten wir, falls wir die Varianten ausbauen, das auch gleich richtig machen (und eben nicht einfach alles in einem Input irgendwie notieren lassen, sondern eben richtige Formulare anbieten). 

Ich finde Varianten sehr wichtig. Die jetzige Lösung (nur text-dropdown) reicht aber nicht. Auswahl durch Vorschaubilder sollte sein.
Aber wie ich ganz oben gesagt habe:

> vielleicht wirklich zuviel verlangt - aber schön wärs doch
(hatte jahrelang gehofft, dass Martin hier was machen würde...)

Also: diesen Vorschlag für eine spätere Version vormerken (und evtl. ein workaround im forum besprechen)

**Comment by cmb69** [comment]
> Also: diesen Vorschlag für eine spätere Version vormerken (und evtl. ein workaround im forum besprechen)

Die Lösung ist eigentlich ganz einfach, wenn die Vorschaubilder entsprechend präpariert werden. Beispiel https://www.natur-und-handgemacht.de/?einzelne_Produkte:Schulter-Nacken:Bunt. Die Vorschaubilder (rechts) enthalten eine CSS-Klasse (z.B. preview_image) und ein `data` Attribut, das die Variantennummer enthält, also etwa statt:
````
<img style="border: black 1px solid;" title="Stoff Nostalgie Herzen" src="./userfiles/images/Stoffe/Nostalgie/Nostalgie-Herzen-rot.jpg" alt="Stoff Nostalgie Herzen" width="255" height="142">
````
dann:
````
<img class="preview_image" data-variant="0" style="border: black 1px solid;" title="Stoff Nostalgie Herzen" src="./userfiles/images/Stoffe/Nostalgie/Nostalgie-Herzen-rot.jpg" alt="Stoff Nostalgie Herzen" width="255" height="142">
````
Dann tut es im Prinzip schon folgendes jQuery:
````
jQuery(function ($) {
    $(".preview_image").on("click", function () {
        $("select[name=wrsVariant]").val($(this).data("variant"));
    });
});
````

**Comment by XHalbert** [comment]
Danke dir, verstehe ich aber leider noch nicht:
jedes Bild erhält dieselbe class="preview_image" und eine eigene Variantennummer, also jedes Bild eine andere Nummer oder wie? Muss ich die Nummer dann auch im Shop hinterlegen?

das jQuery schreibe ich wohin?

**Comment by cmb69** [comment]
> jedes Bild erhält dieselbe class="preview_image" und eine eigene Variantennummer, also jedes Bild eine andere Nummer oder wie? Muss ich die Nummer dann auch im Shop hinterlegen?

Ja, immer die gleiche CSS-Klasse (wie genau diese lautet ist egal; sie darf aber sonst nirgends vorkommen), und immer eine individuelle Variantennummer. Diese entspricht der Position der Variante angefangen mit 0. Also bei den Varianten `rot;grün;blau` gibt es die Nummern `0` für rot, `1` für grün, `2` für blau.

> das jQuery schreibe ich wohin?

Eigentlich ziemlich egal. Du kannst es zum Beispiel ins Template schreiben, direkt vor dem `</body>`; dort muss es noch in ein Script-Element eingebettet werden:
````
<script>
jQuery(function ($) {
    $(".preview_image").on("click", function () {
        $("select[name=wrsVariant]").val($(this).data("variant"));
    });
});
</script>
````

**Comment by XHalbert** [comment]
danke, sehr gut erklärt - prima klappt

... und wenn man jetzt das ausgewählte Bild noch hervorheben könnte ...  ?

**Comment by cmb69** [comment]
> ... und wenn man jetzt das ausgewählte Bild noch hervorheben könnte ... ?

Dazu könnte man dem ausgewählten eine zusätzliche CSS-Klasse verpassen (z.B. `preview_image_selected`), die gestylt werden kann, aber die müsste dann bei den anderen Bildern auch wieder gelöscht werden. Du kannst mal folgendes probieren:
````
<script>
jQuery(function ($) {
    $(".preview_image").on("click", function () {
        $(".preview_image_selected").removeClass("preview_image_selected");
        $("select[name=wrsVariant]").val($(this).data("variant"));
        $(this).addClass("preview_image_selected");
    });
});
</script>
````

**Comment by XHalbert** [comment]
sollte lauten: **[name=xhsVariant]**
Klappt prima soweit. Nur ist mir jetzt aufgefallen, dass das vorher angeklickte Bild vergrößert beibt, als wenn es ausgewählt wäre, wenn man im Textfeld-Dropdown was anders auswählt, was natürlich dann nur verwirrt.

**Comment by cmb69** [comment]
> Nur ist mir jetzt aufgefallen, dass das vorher angeklickte Bild vergrößert beibt, als wenn es ausgewählt wäre, wenn man im Textfeld-Dropdown was anders auswählt, was natürlich dann nur verwirrt.

Stimmt! Also:
````
<script>
jQuery(function ($) {
    $(".preview_image").on("click", function () {
        $(".preview_image_selected").removeClass("preview_image_selected");
        $("select[name=xhsVariant]").val($(this).data("variant"));
        $(this).addClass("preview_image_selected");
    });
    $("select[name=xhsVariant]").on("change", function () {
        $(".preview_image_selected").removeClass("preview_image_selected");
        $(".preview_image").eq(this.value).addClass("preview_image_selected");
    });
});
</script>
````

**Comment by frase-git** [comment]
Das ist alles "dolle".
Ist das nun nur eine Spezial-Hilfe für Albert oder soll das als Standard rein?

**Comment by cmb69** [comment]
> Ist das nun nur eine Speziel-Hilfe für Albert oder soll das als Standard rein?

Halb-Halb. Allgemein ist das nicht wirklich nutzbar, weil es ja nur funktioniert, wenn die Detailseiten CMSimple_XH-Seiten sind, und entsprechend strukturiert aufgebaut werden. Wir könnten aber im [Wiki](https://github.com/cmsimple-xh/xhshop/wiki) einen Artikel anlegen, der nicht nur das Skript zeigt, sondern auch die Voraussetzungen für die Funktion erklärt.

Bezüglich einer Standardlösung: da sollten wir die gesamte Variantenlösung noch mal vollständig überdenken. Martin hatte mir diesbezüglich vor kurzem geschrieben:

>Abgesehen von den Mängeln, die ihr entdeckt habt, krankt das Produkt-Datenmodel einfach an den aufgpfropften Varianten. Das "Produkt" sollte besser einfach ein Container für mindestens eine Variante sein. Preis, Steuersatz, Gewicht, ... – das sind Dinge, die bei der oder den Varianten gespeichert werden sollten, nicht beim "Produkt" selbst. Der Schritt macht dann vieles einfacher. 

Da hat er vermutlich recht, aber das würde ich für Version 1 lieber außen vor lassen. Und bis es grundsätzlich überarbeitet wird, ist eine manuelle Lösung für viele vermutlich akzeptabel.

**Comment by frase-git** [comment]
> Wir könnten aber im Wiki einen Artikel anlegen, der nicht nur das Skript zeigt, sondern auch die Voraussetzungen für die Funktion erklärt.

:thumbsup:

> aber das würde ich für Version 1 lieber außen vor lassen. Und bis es grundsätzlich überarbeitet wird, ist eine manuelle Lösung für viele vermutlich akzeptabel.

:thumbsup:

**Comment by XHalbert** [comment]
> für Version 1 lieber außen vor lassen

klar.

Ich bastel grad[ hier](http://test-natu-1-7.natur-und-handgemacht.de/?einzelne_Produkte:Schulter-Nacken:Karo%2BStreifen)

**Comment by frase-git** [comment]
> Ich bastel grad hier

Super. Das ist ausbaufähig.
Aber: Bitte auch mal mit 320px Breite anschauen und eine Variante auswählen (die unter dem Artikel).

Und was mir gerade auffiel: Es ändern sich **beide** Select-Boxen ?

**Comment by XHalbert** [comment]
Christoph, ich bin mal wieder sprachlos, was du alles kannst. Danke!
PS: Ich finds immer wieder witzig, wenn du so klitzekleine Stolpersteine einbaust, damit unsereins wenigstens ein minimales Bißchen den Grips bemühen muss (warn Scherz ... gemeint ist  " .addClasse " )

Ach ja... gibt es eine Möglichkeit, das ganze div zu verbergen, wenn der Seitenbesucher kein Java hat?

**Comment by cmb69** [comment]
> PS: Ich finds immer wieder witzig, wenn du so klitzekleine Stolpersteine einbaust, […]

Ist keine Absicht – war nur zu faul das überhaupt zu testen. :) (Hab's jetzt oben korrigiert, falls es ins Wiki oder wohin auch immer übernommen wird.)

> Ach ja... gibt es eine Möglichkeit, das ganze div zu verbergen, wenn der Seitenbesucher kein Java hat?

Hm, meinst du die Vorschaubilder? Die sind aber doch auch ohne JavaScript sinnvoll.

**Comment by frase-git** [comment]
> Christoph, ich bin mal wieder sprachlos, was du alles kannst. Danke!

👍 

> PS: Ich finds immer wieder witzig, wenn du so klitzekleine Stolpersteine einbaust, damit unsereins wenigstens ein minimales Bißchen den Grips bemühen muss ...

:stuck_out_tongue: Ich vermute auch, dass er das von Zeit zu Zeit macht - und find's gut.
Bei mir sind die kleinen und großen Fehler nur Unvermögen.

**Comment by XHalbert** [comment]
> Hm, meinst du die Vorschaubilder? Die sind aber doch auch ohne JavaScript sinnvoll.

nicht nur sinnvoll sondern unabdingbar. Der Kunde sucht sich einen Stoff aus, merkt sich den Namen und wählt in dropdown aus.  
Aber da rätsele ich noch. Ich würde die rechte Spalte gern wegkriegen, weil die auf smartphone nach unten rutscht. 

> das ganze div zu verbergen, wenn der Seitenbesucher kein Java hat

hat sich vorerst erledigt. Meine jetzige Vorstellung ist, die Variantenbilder samt Namentexten in irgendeiner Scrollbox anzuzeigen. Da würde beides klappen, mit oder ohne Java.

**Comment by frase-git** [comment]
@XHalbert 
Nur ein kleiner Tipp am Rande:
Wenn du hier auf Github eingeloggt bist, dann klicke mal ganz oben rechts auf "Watch".
Dann erhältst du immer wenn hier was geschrieben wird eine Mail mit Thema, Wer und einem Link zum Beitrag.
Tschuldigung, falls du das bewusst nicht gemacht hast ;-)

**Comment by XHalbert** [comment]
Tipps sind mit immer willkommen, danke. Aber, doch ich watche und kriege Mails.
? hab ich was verpasst ? (ich bin halt auch nicht immer online, z.B. gleich bin ich weg bis spät abends, und ob ich dann den PC nochmal anmache weiss ich nicht...)
Nebenbei: gibt es eine Möglichkeit, von der aktuellen Version (master wohl?) nur ein Update runterzuladen statt alles Dateien?

**Comment by frase-git** [comment]
> Aber, doch ich watche und kriege Mails.

Ich hatte auf die Zahl neben "Watch" geklickt und dort deinen Namen nicht gefunden.
Wahrscheinlich erhältst du nur Mails, wenn jemand in einem Beitrag @XHalbert schreibt.

> Nebenbei: gibt es eine Möglichkeit, von der aktuellen Version (master wohl?) nur ein Update runterzuladen statt alles Dateien?

Das ist wohl nicht so ohne Weiteres möglich. Ich hole mir den gesamten Master und kopiere dann meine eigene `catalog.php` rein. Vielleicht hat Christoph bessere Tipps?

**Comment by XHalbert** [comment]
> wenn jemand in einem Beitrag @XHalbert schreibt

ob ichs jetzt richtig habe?

**Comment by frase-git** [comment]
Willkommen im Club!
😁

**Comment by cmb69** [comment]
> Wahrscheinlich erhältst du nur Mails, wenn jemand in einem Beitrag @XHalbert schreibt.

Genau erklärt wird das [hier](https://help.github.com/articles/about-notifications/). Normalerweise erhält man Mails wenn man explizit erwähnt wird, und auch für alle Tickets, bei denen man schon mal einen Kommentar verfasst hat.

> Nebenbei: gibt es eine Möglichkeit, von der aktuellen Version (master wohl?) nur ein Update runterzuladen statt alles Dateien?

Das geht mit einem Git-Client. Ich selbst kann [TortoiseGit](https://tortoisegit.org/) empfehlen, aber [Github Desktop](https://desktop.github.com/) ist vielleicht noch einfacher zu bedienen. Ein bisschen Eingewöhnungszeit kosten aber beide auf jeden Fall.

**Comment by frase-git** [comment]
Der Desktop nützt nichts, weil man dann nichts auf dem eigenen Rechner ändern kann (synch).
Mit eigenem Fork - Christoph?
Ich habe das nicht hingekriegt.

**Comment by cmb69** [comment]
> Der Desktop nützt nichts, weil man dann nichts auf dem eigenen Rechner ändern kann (synch).

Na ja, du kannst temporäre Änderungen machen; die müssen halt vor jeder Synchronisierung rückgängig gemacht, und dann erneut durchgeführt werden.

> Mit eigenem Fork - Christoph?

Das ist möglich, aber nicht ganz trivial. Wenn es sich im wesentlichen nur um `catalog.php` handelt, dann ist es vermutlich einfacher das manuell zu erledigen. Vielleicht hilft auch diese [SO-Frage](https://stackoverflow.com/questions/32088751/discard-all-changes-at-once-using-github-desktop).

**Comment by frase-git** [comment]
Zusammenfassung:
Hier wird eine optionale Erweiterung besprochen, die nicht unbedingt allgemeingültig ist.
Vorschlag: Schließen.
@XHalbert 
Entweder im Wiki unter Tipps einen Artikel verfassen
oder
später eine Variante mit Code ausarbeiten und im Forum als AddOn veröffentlichen.

**Comment by cmb69** [comment]
> Hier wird eine optionale Erweiterung besprochen, die nicht unbedingt allgemeingültig ist.
Vorschlag: Schließen.

Ja, sehe ich inzwischen auch so. Ein entsprechend aufbereiteter Tipp im Wiki oder Forum wäre schön, aber bzgl. der Varianten muss man sich mittelfristig was einfallen lassen, weil diese sowieso zu simpel gehalten sind (einfach nur ein beliebiger Begriff), wohingegen das Produkt zu komplex ist. Es wäre durchaus denkbar die Bilder an die Varianten zu hängen, und dann wäre hierfür eine allgemeinere Lösung denkbar – aber alles viel später.

**Comment by XHalbert** [comment]
> Entweder im Wiki unter Tipps einen Artikel verfassen
oder
später eine Variante mit Code ausarbeiten und im Forum als AddOn veröffentlichen.

wahrscheinlich beides
aber die oben angesprochene Java-Lösung löst die Aufgabenstellung nicht wirklich.

> Es wäre durchaus denkbar die Bilder an die Varianten zu hängen, 

können wir das nicht explizit in den Plan für später aufnehmen? 
"Varianten mit Bildern und/oder unterschiedlichen Preisen."

Die Variantenlösung wie sie ist ist wirklich nicht befriedigend...

**Comment by cmb69** [comment]
> können wir das nicht explizit in den Plan für später aufnehmen?
"Varianten mit Bildern und/oder unterschiedlichen Preisen."

Ich habe #118 eingereicht und als 2.0 Thema markiert, damit es nicht vergessen geht.
