### ISSUE TITLE
shipping_graded - missing in language file (['hints'])

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#24]
Diese Meldung (siehe Überschrift) kommt bei der Bearbeitung der Versandkosten **im deutschen Backend**.

XH 1.7.0 / xhshop-master

**Comment by cmb69** [comment]
Das eingentliche Problem ist ein [blöder Tippfehler](https://github.com/cmsimple-xh/xhshop/blob/f503f0e0bcda3160d133215c85dc863747ee17f1/languages/de.php#L96) eingeführt mit e207e07.

Erzeugt wird die Meldung dann [hier](https://github.com/cmsimple-xh/xhshop/blob/f503f0e0bcda3160d133215c85dc863747ee17f1/classes/app/xhs_view.php#L256) (daher immer englisch). Ob hier eine Fehlermeldung sinnvoll ist, ist ein bisschen fraglich. Es schadet aber nicht. `function heading` und `function button` darunter werden allerdings wohl nie aufgerufen; das sollte noch mal überprüft werden, und dann könnten sie entfernt werden.

**Comment by frase-git** [comment]
> Das eingentliche Problem ist ein ...

Ich habe ewig darauf gestarrt - und nicht gemerkt, dass da nur ein h fehlt. :(
