### ISSUE TITLE
Products without detail-image

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#25]
Werden Artikel/Produkte nur mit einem Vorschaubild aber **ohne** Bild (für Detailansicht) angelegt, gibt es Probleme:
Klickt man in der Shop-Übersicht auf dieses Vorschaubild, erscheint das Shop-Bilder-Verzeichnis(!!!) in der Fancybox.
zur Demo 1. Artikel: http://fhs.bplaced.net/xhshop-demo/?Shop

Mein Wunsch:
Bei Auswahl von "kein Bild" (an 2 Stellen) in der Artikelbearbeitung, sollte automatisch "no_image.jpg" verwendet werden.
Damit werden auch gleich ein paar Layoutprobleme behoben, die ich neulich feststellte.
Der `<div>` wird nämlich **immer** erzeugt und nimmt Platz weg, auch wenn gar kein Bild angezeigt wird.

Oder: `no_image.jpg` als default-Wert für jeden neuen Artikel.
Die Option "kein Bild" in der Selectbox damit ganz weg.
Wem das no_image nicht gefällt, kann es ja tauschen oder ein "weißes" hinlegen.

**Comment by cmb69** [comment]
> Werden Artikel/Produkte nur mit einem Vorschaubild aber ohne Bild (für Detailansicht) angelegt, gibt es Probleme:
Klickt man in der Shop-Übersicht auf dieses Vorschaubild, erscheint das Shop-Bilder-Verzeichnis(!!!) in der Fancybox.

Kann ich lokal nicht reproduzieren, und auch nicht, wenn ich mir den [relevanten Code anschaue](https://github.com/cmsimple-xh/xhshop/blob/633fb806e61a7c2076eea6ecc54a87f542e20369/classes/app/xhs_frontend_controller.php#L602-L607) – entweder wird hier ein "best picture" gefunden, und dieses dann für Vorschau wie auch Verlinkung genutzt (was natürlich fraglich ist), oder es wird gar kein Bild angezeigt. Interessant ist auf jeden Fall, dass bei mir auch die `width` und `height` Attribute gesetzt werden (im Code durch `$info[3]` bezeichnet), was für das `<a>` Element aber nicht sinnvoll ist; bei dir aber nicht. Und bei mir wird weder ein `title` noch ein `alt` Attribut gesetzt. Hast du da Individualanpassungen gemacht?

**Comment by frase-git** [comment]
Hm,
das ist mal wieder ziemlich verwirrend.
Zunächst: es gibt auch noch [diesen relevanten Code](https://github.com/cmsimple-xh/xhshop/blob/633fb806e61a7c2076eea6ecc54a87f542e20369/classes/app/product.php#L82).
In der Demo habe ich noch 1.7rc1 und den älteren shop-master.
Local habe ich 1.7.0 und den shop-master kurz nachdem ich gemerged hatte.
Beide mit PHP 5.6.x.
Auf beiden ist der Effekt gleich.
In der Artikelübersicht vermutet man, dass dein Codebeispiel zuträfe, in der Produktansicht sieht meiner eher passend aus. Es scheint aber genau umgekehrt zu sein ???
Ich kann mich nicht erinnern, dass ich an diesen Stellen irgendwas geschraubt hätte (ich meine nachdem wir hier auf Github sind). Lediglich die Kommastellen hatte ich händisch zurückgesetzt, weil das da noch nicht im Master war.
Wieso kannst du das nicht nachvollziehen???
Aber du siehst das Verzeichnis - oder?

**Comment by cmb69** [comment]
> Zunächst: es gibt auch noch diesen relevanten Code.

`getImage()` wird soweit ich sehen kann nur im Back-End verwendet. Hier geht es aber doch ums Front-End, oder?

> Wieso kannst du das nicht nachvollziehen???
Aber du siehst das Verzeichnis - oder?

In deinem Demo-Shop sehe ich das schon, aber eben nicht in meiner Testumgebung. Bei dir online kann ich aber nicht debuggen (selbst wenn ich FTP-Zugang hätte, dann nur suboptimal).

**Comment by frase-git** [comment]
Vielleicht ist [dieser Code](https://github.com/cmsimple-xh/xhshop/blob/633fb806e61a7c2076eea6ecc54a87f542e20369/classes/app/xhs_controller.php#L115) zuständig?
So ist das halt, wenn man keine Ahnung hat.

Rumwienum, mein Wunsch bleibt:
Default jedem neuen Artikel (oder Artikeln ohne Bildern) "no_image.jpg" zuweisen.
Somit wäre gewährleistet, dass in dem img-DIV (div class="xhsPrevPic") immer ein Bild ist.
Wie es jetzt aussieht kannst du [hier sehen](http://test-natu-1-7.natur-und-handgemacht.de/?Shop).
Den Artikeln sind keine Detailbilder zugeordnet -> Fancybox hat Probleme.
Und ganz ganz unten "testprodukt -1ct- für paypal-Testkauf" zeigt, wie das aussieht, wenn in dem DIV nichts drin ist.

**Comment by cmb69** [comment]
Oh mann – jetzt hab ich's – es geht um die Produktübersichtsliste, nicht um die Detailseiten. Upps!

Und konkret liegt das Problem [hier](https://github.com/cmsimple-xh/xhshop/blob/7c9a6e726fb0e4c5b85f465e875792de8c59b313/classes/app/product.php#L128) – da wird zwar geprüft, ob ein Vorschaubild definiert wurde, aber es wird einfach davon ausgegangen, dass es ein Produktbild gibt. Ändere mal diese Zeile zu:
````
            $img = !empty($this->image) ? $this->image : 'no_image.jpg';
            $image = '<a href="' . XHS_IMAGE_PATH.$img . '" alt="' . $this->getName(XHS_LANGUAGE) . ' - Preview"  title="' . $this->getName(XHS_LANGUAGE) . '" class="zoom"><img src="'. XHS_PREVIEW_PIC_PATH . $this->previewPicture. '" alt="' .$this->getName(XHS_LANGUAGE) .' - Preview"  title="'.$this->getName(XHS_LANGUAGE). '"></a>';
````
Ist es das, was du meinst?

Ich denke aber, das es wenig sinnvoll ist, ein Bild zu verlinken, wenn es eigentlich keines gibt. Sprich, eben in diesem Fall auf den Link verzichten.

> Und ganz ganz unten "testprodukt -1ct- für paypal-Testkauf" zeigt, wie das Aussieht, wenn in dem DIV nichts drin ist.

Okay, hier gibt es nicht mal ein Vorschaubild. Da könnte man sich mit `no_image.jpg` behelfen. Hier mal die gesamte Funktion wie ich sie mir vorstellen könnte (da liegt allerdings noch mehr im Argen):
````
    function getPreviewPicture(){
        if((isset($this->previewPicture)) && ($this->previewPicture <> '')) {
            if (!empty($this->image)) {
                $image = '<a href="' . XHS_IMAGE_PATH.$this->image . '" alt="' . $this->getName(XHS_LANGUAGE) . ' - Preview"  title="' . $this->getName(XHS_LANGUAGE) . '" class="zoom">';
            }
            $image .= '<img src="'. XHS_PREVIEW_PIC_PATH . $this->previewPicture. '" alt="' .$this->getName(XHS_LANGUAGE) .' - Preview"  title="'.$this->getName(XHS_LANGUAGE). '">';
            if (!empty($this->image)) {
                $image .= '</a>';
            }
            return $image;
        }
        return '<img src="'. XHS_PREVIEW_PIC_PATH . 'no_image.jpg'. '" alt="' .$this->getName(XHS_LANGUAGE) .' - Preview"  title="'.$this->getName(XHS_LANGUAGE). '">';
    }
````

**Comment by frase-git** [comment]
> Ist es das, was du meinst?

Das denke ich schon.
Ich werde das mal durchtesten - das kann aber dauern.

Ich hatte an diesen Stellen im (Shop)Template schonmal eine Bedingung reingeschrieben:
Wenn kein Bild, dann den DIV nicht anzeigen.
Das hat in catalog.tpl geklappt.
Aber in in productDetails.tpl steht da nur `%IMAGE%`.
Ich wusste nicht, wie die Bedingung da aussehen könnte.
Und es gab Probleme, wenn nur eines der beiden Bilder definiert war.

**Comment by frase-git** [comment]
> Ich denke aber, das es wenig sinnvoll ist, ein Bild zu verlinken, wenn es eigentlich keines gibt. Sprich, eben in diesem Fall auf den Link verzichten.

Hm. wahrscheinlich hast du Recht.
Ich habe jetzt mal deine beiden Varianten durchgetestet. Macht zwar (in etwa) das, was ich wollte - hat aber Haken. Deshalb: Will ich das noch?

Ich versuche nochmals, das Problem zu beschreiben.
In den tpl (productDetails.tpl und catalog.tpl) packe ich die Bildausgabe jeweils in einen DIV:
`<div class="xhsPrevPic">~~~ ?></div>`
Der hat eine Breite von 33% (responsive/adaptive) und das ausgegebene Bild nimmt darin 100% ein.
Ist kein Bild definiert, erscheint dieser DIV trotzdem und nimmt halt eine Zeile (ein Block) mit Breite 33% ein. Es gibt ein "Lücke".
Wahrscheinlich wäre es tatsächlich besser alles zu lassen, wie es ist und nur die DIV-Ausgabe von der Existenz eines Bildes abhängig zu machen (mein letzter Post).

**Comment by cmb69** [comment]
> Wahrscheinlich wäre es tatsächlich besser alles zu lassen, wie es ist und nur die DIV-Ausgabe von der Existenz eines Bildes abhängig zu machen (mein letzter Post).

Man könnte hier wohl auch einfach den [:empty Pseudo-Selektor](https://developer.mozilla.org/en-US/docs/Web/CSS/:empty) verwenden, um das `div` dann eben keinen Platz verschwenden zu lassen.

**Comment by frase-git** [comment]
Ich bin ein :older_man: (Emoji = older_man)

``` css
div.xhsPrevPic:empty {
	display: none;
}
```
Einfach und effektiv. Manchmal brauche ich nicht nur einen Klaps auf den Hinterkopf, sondern eher einen kräftigen Schlag. Danke Christoph.
Möchtest du das in das CSS nach Zeile 401 einfügen, oder soll ich dir die Datei schicken?

Die Codes oben sind damit erledigt.

**Comment by cmb69** [comment]
> Möchtest du das in das CSS nach Zeile 401 einfügen

Erledigt.

**Comment by frase-git** [comment]
master 04.07.2017 20:30 inkl. mods
local, xampp, php 5.6.11 OHNE intl

Erhält ein Artikel ein Vorschaubild (für Übersichtsseite), und kein Bild für Detailseite, dann:
Klick auf Bild in der Übersicht zeigt das Bilderverzeichnis in der Fancybox.
(Das hatten wir schon, aber jetzt habe ich mit dem neuen Master getestet.)
**Außerdem wird auf der Detailseite** - trotz Einstellung "kein Bild" das Vorschaubild von der Übersichtsseite angezeigt. Man kann es anklicken - in der Fancybox wird es einfach nochmal gezeigt.
Das - so vermute ich - liegt wohl daran, dass nach einem "best image" gesucht wird.
Das mit dem "best image" könnte wohl raus - oder?
