### ISSUE TITLE
Remove support for catalogue.inc

### ISSUE THREAD

**Issue by XHalbert** [cmsimple-xh/xhshop#26]
meines Wissens war es so, dass wellrad "catalog.inc" nur verwendet, wenn keine catalog.php vorhanden ist.

Da catalog.php sich besser mit einem editor bearbeiten lässt, kann meines Erachtens catalog.inc entfallen.

Ebenso die Fehlermeldung:

Fehler:
Pardon! Noch ist der xhshop-Shop nicht betriebsbereit.
    Datei nicht gefunden: ./plugins/xhshop/data/catalogue.inc

**Comment by frase-git** [comment]
Lies mal Shop->Hilfe->Was ist neu: 1. Absatz
Ich weiß nicht, wie nützlich oder überflüssig das ist.
Zumindest, muss das Verzeichnis, in dem die Datei liegt, geschützt werden. Das hat Christoph schon bemängelt.

**Comment by XHalbert** [comment]
> Hilfe->Was ist neu: 1. Absatz

danke für den Hinweis, habe "Was ist neu" glatt übersehen, weil zuerst "Start" angezeigt wird.
Also catalog.inc als Importfunktion... soll also bleiben.
Du kannst dieses issue löschen

**Comment by cmb69** [comment]
> Du kannst dieses issue löschen

Ich denke nicht. Es sollte schon eine Entscheidung getroffen werden, welches Format bevorzugt wird, und dann könnte der Support für das alte Format im Lauf der Zeit entfallen bzw. gleich nur noch ein Import möglich sein.

Mir ist es letztlich egal; `catalogue.inc` ist halt nicht manuell bearbeitbar, dafür aber effizient und leicht zu programmieren. Vor fremden Augen geschützt werden könnte die Datei leicht dadurch, dass man sie in CMSimple_XHs `content/` Ordner speichert (was ich sowieso empfehlen würde, damit man alles zusammen hat).

Das derzeitge `catalog.php` ist okay, aber vermutlich lässt sich JSON oder XML noch besser bearbeiten.

**Comment by cmb69** [comment]
> Mir ist es letztlich egal; catalogue.inc ist halt nicht manuell bearbeitbar, dafür aber effizient und leicht zu programmieren.

Hat aber den großen Nachteil, dass dort gespeicherte Klassen nicht ohne weiteres umbenannt werden können (zumindest nicht, wenn Autoloading verwendet wird). Daher denke ich inzwischen, es ist das beste catalogue.inc inklusive dem gesamten Support dafür zu entfernen. Wer tatsächlich noch mit dieser Variante arbeitet, müsste halt *vor* dem Wechsel zu XHShop als catalog.php speichern lassen, was prima funktioniert wenn man [auf 'array' umstellt](https://github.com/cmsimple-xh/xhshop/blob/910fa173003756be15573cb88188d1e813b3b7f2/help/de/whatsNew.html#L9-L10), und dann einen einzigen Artikel (egal welchen) speichert.

**Comment by cmb69** [comment]
Ich schlage vor PR #53 zu mergen.
