### ISSUE TITLE
Configuration of XHS_IMAGE_PATH in back-end

### ISSUE THREAD

**Issue by XHalbert** [cmsimple-xh/xhshop#27]
wellrad verwendet  /images für Bilder, XH-Shop jetzt /images/shop
das finde ich sehr gut!

Für ehem. Wellrad nutzer:
wenn man die Bilder in /images nicht herausfiltern und verschieben will oder kann, kann man ja den Pfad ändern (required_classes.php).
Vllt. wäre es sinnvoll, das in der Hilfe zu erklären
(und falls einmal eine Konfigurierung im backend kommt, das aufzunehmen)

**Comment by XHalbert** [comment]
XH-Shop sagt: Sorry, no pictures found in ./userfiles/images/shop/!

kommt der Pfad noch in config?

**Comment by cmb69** [comment]
> kommt der Pfad noch in config?

Ich würde sagen, ja.

**Comment by XHalbert** [comment]
> Ich würde sagen, ja.

gut
