### ISSUE TITLE
Link preview image to product details

### ISSUE THREAD

**Issue by XHalbert** [cmsimple-xh/xhshop#28]
bei Klick auf den Artikelnamen wird auf die Detailseite verlinkt, ist richtig.
bei Klick auf auf das Priviewpicture:
http://test-natu-1-7.natur-und-handgemacht.de/userfiles/images/  --- ERROR
Ich hatte noch kein hi_fancybox 4.0 installiert.
Gemacht. 
Jetzt kommt: Fehler: The requested content cannot be loaded.
Einstellung in required_classes ist   
define('XHS_PREVIEW_PIC_PATH', $pth['folder']['images']);
(bei XHS_IMAGE_PATH klappt das)

Muss ich doch ein  Verzeichnis   /images/shop    verwenden?
Oder in hi_fancybox irgendwelche Einstellung ändern?

**Comment by frase-git** [comment]
> Jetzt kommt: Fehler: The requested content cannot be loaded.

Das passiert, wenn dem Artikel kein Detailbild zugeordnet ist.
Ist das so?

Wir besprechen [diesen Fall gerade hier](https://github.com/cmsimple-xh/xhshop/issues/25).

**Comment by XHalbert** [comment]
> wenn dem Artikel kein Detailbild zugeordnet ist

ist auf CMSimple-Seite verlinkt-
also ja, kein Detailbild verlinkt

**Comment by frase-git** [comment]
> ist auf CMSimple-Seite verlinkt-
> also ja, kein Detailbild verlinkt

Dann verlinke mal testweise ein Bild für Detailansicht (klar = überflüssig)
Der Link zur CMS Seite bleibt wie er ist.
Nur in der Shop-Übersicht geht die Fancybox auf.

Wir arbeiten dran.

**Comment by XHalbert** [comment]
mit Bild klappt wie vorgesehen.

Weiß aber nicht, ob das überhaupt sinnvoll ist. 
Ich hatte bisher in Wellrad das Preview-Pic wie den Artikelnamen auf die Detailseite verlinkt. Also Klick entweder auf Namen oder auf pic. Dort wird dann ja ein größeres Bild samt Beschreibung angezeigt. Wozu also vorher das Preview-Pic per fancybox vergrößern?

**Comment by frase-git** [comment]
Gemach! ;-)
Wir suchen ja noch eine gute Lösung.

[Zum Beispiel hier](http://test-natu-1-7.natur-und-handgemacht.de/?Shop)

Klappt beim ersten Artikel.

Der 3. Artikel "bio Hirsespelzen 50 Liter"
Das geht doch so nicht. (wie es jetzt dort ist)
Da könnte man ein schönes kleines quadratisches Bild oder einen Detailausschnitt zeigen.
Bei Klick darauf könnte (schon bevor man die Detailseite ansteuert) ein richtig großes gezeigt werden.
Ich fände das gut.
In der Shop-Gesamtübersicht können eben nun mal nur kleinere Bilder gezeigt werden (Smartphones usw. hier muss man %-Angaben machen - keine feste Größe)
Die Artikelüberschrift führt zur Detailseite UND der Button "Artikel-Details".

Für dich heißt das aber konkret, dass du wahrscheinlich auch größere Bilder brauchen wirst. :(
Wenn bei dir eine Modernisierung ansteht - darum wirst du wahrscheinlich eh nicht rumkommen - dann könntest du auch gleich einige Bilder erneuern.

**Comment by frase-git** [comment]
Mal noch ein Tipp:
Falls dir die ganzen Orange-Elemente nicht gefallen:
In der Plugin-stylesheet.css einfach nach allen "#f60" suchen und mit deiner Lieblingsfarbe ersetzen ;-)

**Comment by frase-git** [comment]
@XHalbert 
Frage: Wie findest du den AGB-Aufruf bei Schritt 2?

**Comment by cmb69** [comment]
> Falls dir die ganzen Orange-Elemente nicht gefallen:
In der Plugin-stylesheet.css einfach nach allen "#f60" suchen und mit deiner Lieblingsfarbe ersetzen ;-)

Ich neige ja bei Plugins eher zu minimalistischem Styling, hätte also nichts dagegen, das Stylesheet abzuspecken. :)

**Comment by XHalbert** [comment]
Ups, sehe grad, dass die Preview-Pics mit einer festen Breite angezeigt werden. Einige werden jetzt ordentlich vergrößert. Bei Wellrad wurden sie immer in der Originalgröße angezeigt.

Stimmt, das geht so wirklich nicht!

Habe jetzt in css gefunden:
div.xhsPrevPic img
width: 100%;    /***disable this for pictures with different sizes ***/
( darauf sollte später irgendwo hingewiesen werden. )

[Aber so gehts denke ich](http://test-natu-1-7.natur-und-handgemacht.de/?Shop) 
Ist etwa wie in wellrad auch war. Dass der Artikelname jetzt direkt über dem Bild linksbündig steht ist besser als wellrad.

> Bei Klick darauf könnte (schon bevor man die Detailseite ansteuert) ein richtig großes gezeigt werden.

Ich habe von allen Artikeln auch große Bilder, das ist nicht das Problem. Aber irgendwie find ich die direkte Verlinkung auf Details besser. Bin ich zu konservativ? Jedenfalls finde ich wichtig, dass potentielle Kunden möglichst umgehend auf die Detailseiten gehen (schon wegen der Variantenbilder), und weil die Artikel erklärungsbedürftig sind (viele verwechseln da was, was auch ein größeres Bild nicht vermitteln kann). Auf Details sehen sie ja dann das größere Bild auch.

Dennoch finde ich deine Version schön, und andere vllt. auch. Kann von mir aus so bleiben. 
**Aber ich werds **bei mir** wahrscheinlich ändern.**

> AGB-Aufruf

gratuliere sehr gut gemacht
Nur der Text ist mir wie gesagt zu dürftig
 Ich habe die AGB und den in ihnen enthaltenen Hinweis auf mein Widerrufsrecht gelesen und bin einverstanden.
Ich willige in die Speicherung meiner Daten laut Datenschutzerklärung dieser Seite sowie die Weitergabe meiner Anschrift an den beauftragten Paketdienst ein,
bei Bezahlung mit Paypal willige ich auch in die Übermittlung der Daten an PayPal ein, die für die Zahlungsabwicklung erforderlich sind. 

> orange-Elementen 

Guter tipp mit den orange-Elementen (aber die gefallen mir im Moment ganz gut...)

**Comment by frase-git** [comment]
> Ich neige ja bei Plugins eher zu minimalistischem Styling, hätte also nichts dagegen, das Stylesheet abzuspecken. :)

@cmb69 
Glaub mir bitte: Das hatte ich auch vor.
Dann begann ich zu testen mit fhs-simple, lck-overlay und richu ...
Katastrophe!
Das ist auch der Grund, warum so viel Style-Code und so viel `!important`.
Sehr bedauerlich - aber nötig!
Es sollte ja einigermaßen zu allen Templates passen. Und siehe; Bei Albert geht's ja beinahe.

**Comment by frase-git** [comment]
@XHalbert 
Dennoch finde ich deine Version schön, und andere vllt. auch. Kann von mir aus so bleiben.
Aber ich werds bei mir wahrscheinlich ändern.

Wir reden ja noch!
;-)

**Comment by cmb69** [comment]
> Dann begann ich zu testen mit fhs-simple, lck-overlay und richu ...
Katastrophe!
Das ist auch der Grund, warum so viel Style-Code und so viel !important.

Dann stimmt grundsätzlich was nicht. Kann doch irgendwie nicht sein, dass jedes Plugin nun eine Styleorgie absolvieren muss, damit es in diversen Templates noch ordentlich aussieht. Zumindest bin ich mir sicher: je mehr Plugins gestylt werden, umso mehr Probleme gibt es mit Templates unter denen nicht getestet wurde.

**Comment by frase-git** [comment]
> Dann stimmt grundsätzlich was nicht. Kann doch irgendwie nicht sein, dass jedes Plugin nun eine Styleorgie absolvieren muss, damit es in diversen Templates noch ordentlich aussieht.

Du wirst es erleben.
Das geht los mit den Überschriften. Man möchte, dass ein Artikel auf der Detailseite eine h1-Überschrift hat.
Das ist immerhin das wichtigste Element. In der Übersichtsseite Ähnliches. Die Artikel brauchen eine wertige Überschrift - und du weißt nicht, was der Templateur da definiert hat - also übertrumpfen. Mit Bildern das Gleiche. Und mit Realblog wird das noch schlimmer werden ...

**Comment by cmb69** [comment]
> Das geht los mit den Überschriften. Man möchte, dass ein Artikel auf der Detailseite eine h1-Überschrift hat.
Das ist immerhin das wichtigste Element. In der Übersichtsseite Ähnliches. Die Artikel brauchen eine wertige Überschrift - und du weißt nicht, was der Templateur da definiert hat - also übertrumpfen.

Sehe ich nicht so. Und ja, als ich zuletzt an Realblog_XH weiterentwickelt hatte (unter XH 1.6.7 mit mini1), fand ich die verlinkten Überschriften absolut grauenhaft, aber ich denke, dass sollte dennoch dem Webdesigner/Webmaster überlassen werden. Ansonsten kommt es am Ende zu einem Wettrüsten zwischen Templatedesignern und Pluginentwicklern, weil jeder meint, es besser zu wissen.

Das ist aber nur meine Meinung, und beim XHShop kann das gerne anders gehandhabt werden – ist schließlich kein 1-Man-Project. :)

**Comment by frase-git** [comment]
> ... und beim XHShop kann das gerne anders gehandhabt werden ...

Ich denke, da wird am Ende sowieso einges rausfallen. Es ist ja auch noch vieles für das Backend drinnen und das wird sich ja evtl. auch komplett ändern. Also - kurz vor alpha1 werde ich da nochmal ran müssen. es wird sicher ein Kompromiss zwischen deinem minimal und meinem overkill ;-)

Aber zurück zum Thema:
Bei Albert führt ein Klick auf das Vorschaubild in der Übersicht auf die Detailseite.
Meine jetztige Version zeigt ein vergrößertes/anderes Bild in der Fancybox.
( - Ich kann mich an die Realblog-Entwicklung erinnern. Da haben wir mal diskutiert, den gesamten Block auf der Übersichtsseite inkl. Text und Bild als Link zum Artikel zu machen. - )
Albert hat seine Argumente genannt - und die sind nicht von der Hand zu weisen.
Also: Wofür entscheiden wir uns?

**Comment by frase-git** [comment]
Jetzt fällt mir gerade wieder ein, warum ich das Vorschaubild als Link zur Fancybox gemacht habe:

Schaut euch mal [diese Seite](http://test-natu-1-7.natur-und-handgemacht.de/?Shop) bei 320x700px an.
Da hier das Bild sehr klein wird und kaum etwas zu erkennen ist, hilft die Fancybox (zumindest etwas).

**Comment by XHalbert** [comment]
Ich finde das ein gutes Argument für meine Auffassung. Das Minibildchen wird schon neugierig machen, aber mehr wohl nicht.
Auch das fancybild wird möglicherweise nicht sonderlich viel Aufschluss geben - ein Klick auf das Bild aber schon eher.
Leider sind noch nicht alle Detailseiten so wie ich es mir wünsche und leider ist in 1.7 noch was mit den Umlauten, daher schaut doch mal auf https://www.natur-und-handgemacht.de/?Shop  den Artikel "Baby-Hörnchen Hirse 24x30 cm"

**Comment by XHalbert** [comment]
das im backend konfigurierbar zu machen wär wohl too much im Moment? obwohl ich mir vorstellen könnte, dass es einige Shopnutzer geben könnte, denen entweder die eine oder die andere Lösung besser gefallen würde...
da fällt mir grad ein:
wie wärs denn, wenn das fancybild bei klick weiter auf die Detailseite leitet? Oder würde das zu sehr verwirren?

**Comment by frase-git** [comment]
> Leider sind noch nicht alle Detailseiten so wie ich es mir wünsche und leider ist in 1.7 noch was mit den Umlauten

Vergleiche mal in beiden XH-Installationen die "URL-Zeichen Ersetzung" in Einstellungen - Sprachdatei.

**Comment by frase-git** [comment]
Um auch dieses Thema zu einem Erfolg zu bringen, schlage ich eine Abstimmung vor.
Albert hat schwerwiegende Gründe aus Marketingsicht gebracht, denen ich mich wohl beugen muss.

Also Frage:
Klick aufs Vorschaubild in der Shop-Übersicht führt zur Detailseite ->
JA = 👍
NEIN = 👎 

Bitte abstimmen!

**Comment by XHalbert** [comment]
> schwerwiegende Gründe

sehen andere bestimmt anders...

aber was ist mit meinem Kompromissvorschlag:
erst fancybild , nächster klick weiter auf die Detailseite

**Comment by cmb69** [comment]
> Um auch dieses Thema zu einem Erfolg zu bringen, schlage ich eine Abstimmung vor.

Ich denke, wir könnten das auch konfigurierbar machen, so wie [von Albert vorgeschlagen](https://github.com/cmsimple-xh/xhshop/issues/28#issuecomment-312800722).

**Comment by frase-git** [comment]
> Ich denke, wir könnten das auch konfigurierbar machen, so wie von Albert vorgeschlagen.

Na, aber gerne - sofern du mit "wir" "ich" meinst, im Sinne von "cmb69" 😆

**Comment by frase-git** [comment]
Ähm, was ist, wenn Fancybox nicht installiert ist?

Selbst beantwortet: Dann ist das Vorschaubild **immer** ein Link zu Details ???

**Comment by cmb69** [comment]
> Selbst beantwortet: Dann ist das Vorschaubild immer ein Link zu Details ???

Ich würde das nicht von Fancybox abhängig machen. Diese ist eigentlich nur ein progressive Enhancement für das Öffnen des Detailsbilds (in einem anderen Tab).

**Comment by frase-git** [comment]
> Ich würde das nicht von Fancybox abhängig machen.

Ich ja auch nicht. Wenn aber Alberts Kompromissvorschlag kommt: Klick auf Vorschau -> Fancy -> zweiter Klick -> Details
Das funktioniert dann nicht ohne Fancy.
Aber vielleicht bin ich nur durcheinander, wegen #40 ???

**Comment by cmb69** [comment]
> Ich ja auch nicht. Wenn aber Alberts Kompromissvorschlag kommt: Klick auf Vorschau -> Fancy -> zweiter Klick -> Details

Hm, ich weiß nicht ob das überhaupt eine gute Idee wäre, weil ja dann die Fancybox selbst einen Klick-Handler bekommen müsste – und ja, ohne JS ginge sowieso nichts.

**Comment by XHalbert** [comment]
Kompromisse sind immer doof, ich sags ja...
Konfigurierbar wäre natürlich toll.
Ansonsten:
Entscheidet ihr, meine Meinung habe ich ja schon gesagt.

**Comment by XHalbert** [comment]
ich möchte nochmal hierdran erinnern:
> Habe jetzt in css gefunden:
div.xhsPrevPic img
width: 100%; /***disable this for pictures with different sizes ***/
( darauf sollte später irgendwo hingewiesen werden. )

oder vllt. sogar konfigurierbar? (später...) - neues Ticket?

und noch hierdran:
> Kann doch irgendwie nicht sein, dass jedes Plugin nun eine Styleorgie absolvieren muss, damit es in diversen Templates noch ordentlich aussieht

ich habe z.B. ein anderes template spez. für den Shop, weil ich dort andere Überschriften und Linkformat haben wollte als im nomalen Content. Das template wird jetzt komplett überschrieben (was mich nebenbei nicht stört, es gefällt mir so und ich könnte ja alles ändern). Aber ob das für andere sinnvoll ist?



Nochmal hierzu:
Klick auf Vorschaubild  -> Details - statt fancybox
> Albert hat seine Argumente genannt - und die sind nicht von der Hand zu weisen.
Also: Wofür entscheiden wir uns?

hab ich die folgenden Argumente schon genannt?
1. Ich habe sämtliche Vorschaubilder im Miniformat erstellt, auch um bits beim Laden zu sparen. Müsste ich nicht bei "Klick auf Vorschaubild  -> fancybox"  alle Bilder durch größere ersetzen oder was in fancybox machen?
2. wäre es in fancybox nicht so, dass **immer alle Vorschaubilder in derselben Größe** angezeigt werden? Für mich wäre das nicht günstig, weil ich schon allein durch die Größe des Vorschaubildes einen ersten Eindruck von den tatsächlichen Größenunterschieden machen wollte. Z.B. sähen "Großes Hörnchen" und "Babyhörnchen" nahezu identisch aus. Klar könnte man das bei gleicher Bilgröße umgehen, indem man bei kleinen Objekten mehr Hintergrund zeigt als bei großen, aber (neue Bilder machen...)

Es spricht auch einiges für immer gleich große Vorschaubilder, das wirkt ordentlicher, übersichtlicher, und sähe auch 2-spaltig gut aus (mir scheint der Trend geht zu mehr-spaltig je nach Bildschirmbreite).

@frase-git ich weiß wie schmerzhaft das sein kann, wenn jemand auf einer Lösung, auf die man mit Recht stolz ist und die einem genial erscheint, immer wieder herumhackt. Das habe ich aber so nicht gemeint, ehrlich. Ich finde "deinen" Shop ja super und ich kann mit deiner fancyboxlösung sehr gut leben, ich fand sie beim ersten Anschauen sogar richtig toll und vielleicht würde auch ich sie mit der Zeit besser finden. Man müsste halt "unbedarfte Testpersonen" fragen wie sie was finden...

**Comment by frase-git** [comment]
```css
div.xhsPrevPic {
	width: 33%;
	max-width: 33%;
	float: left;
	margin: 0 1em 1em 0;
}
div.xhsPrevPic img {
	...
	max-width: 100% !important;
	width: 100%; /*** disable this for pictures with different sizes ***/
	min-width: 100%; /*** disable this for pictures with different sizes ***/
	height: auto !important;
}
```
Zur Erklärung:
Tatsächlich habe ich das gemacht, damit die Vorschaubilder immer die gleiche Breite haben, links stehen und der Text umfließt.
Der DIV, in dem sich die Bilder befinden, nimmt 33% der content-Breite ein (änderbar)
Die Bilder darin sollen diese 33% nutzen (100%).
Wenn die Vorschaubilder zu klein sind, werden sie hochskaliert - was nicht schön ist.
Deshalb habe ich die Hinweise eingefügt. Werden die beiden Zeilen auskommentiert, dann werden die Bilder in ihrer tatsächlichen Größe angezeigt. Das sieht dann allerdings komisch aus, weil der Abstand zum Text unregelmäßg wird. Der DIV bleibt ja auf 33%.
Am Ende ist das so, weil ich irgendein Aussehen vorgeben **muss** - und es sollte für die meisten Templates passen.  Das kann man 1:1 übernehmen - oder das Plugin-CSS anpassen = konfigurierbar.

> ich habe z.B. ein anderes template spez. für den Shop, weil ich dort andere Überschriften und Linkformat haben wollte als im nomalen Content. Das template wird jetzt komplett überschrieben (was mich nebenbei nicht stört, es gefällt mir so und ich könnte ja alles ändern). Aber ob das für andere sinnvoll ist?

Tja, dieses Template hast du aber speziell für den **alten** Shop gemacht. Jetzt ist einiges neu. Kann schon sein, dass dann einiges nicht mehr passt. Das ist bedauerlich, aber wohl nicht zu vermeiden. Es hat sich ja nicht nur am Layout was geändert. Es sind auch verschiedene Dinge hinzugekommen und andere weggefallen.

**Comment by frase-git** [comment]
> 1. Ich habe sämtliche Vorschaubilder im Miniformat erstellt, auch um bits beim Laden zu sparen. Müsste ich nicht bei "Klick auf Vorschaubild -> fancybox" alle Bilder durch größere ersetzen oder was in fancybox machen?

Nein. Bei Fancybox wird bei Klick auf das Vorschaubild die größere Version angezeigt - sofern eine größere Version vorhanden ist. Aber, wahrscheinlich wird es sowieso so, dass, wenn wie bei dir kein größeres Bild da ist (keine Detailseite), der Klick zu deiner CMS-Detailseite führt - keine Fancybox.

**Comment by frase-git** [comment]
> wäre es in fancybox nicht so, dass immer alle Vorschaubilder in derselben Größe angezeigt werden? Für mich wäre das nicht günstig, weil ich schon allein durch die Größe des Vorschaubildes einen ersten Eindruck von den tatsächlichen Größenunterschieden machen wollte. Z.B. sähen "Großes Hörnchen" und "Babyhörnchen" nahezu identisch aus. Klar könnte man das bei gleicher Bilgröße umgehen, indem man bei kleinen Objekten mehr Hintergrund zeigt als bei großen, aber (neue Bilder machen...)
> 
> Es spricht auch einiges für immer gleich große Vorschaubilder, das wirkt ordentlicher, übersichtlicher, und sähe auch 2-spaltig gut aus (mir scheint der Trend geht zu mehr-spaltig je nach Bildschirmbreite).

Großes Hörnchen und kleines Hörnchen nur über die Bildgröße optisch zu unterscheiden - na ja, kann man machen. Dazu gibt es die Möglichkeit wie weiter oben beschrieben (CSS).
Bei kleineren Viewports könnte man das Vorschaubild auch noch in der gesamten Breite anzeigen lassen (1-spaltig). Dazu wäre aber **noch mehr** CSS nötig.

**Comment by cmb69** [comment]
> wäre es in fancybox nicht so, dass immer alle Vorschaubilder in derselben Größe angezeigt werden? 

Das hat IMO wenig mit Fancybox zu tun, sondern letztlich gerade auch mit responsive Design – feste Bildgröße in Pixel passt zumindest heutzutage einfach nicht mehr.

> Aber, wahrscheinlich wird es sowieso so, dass, wenn wie bei dir kein größeres Bild da ist (keine Detailseite), der Klick zu deiner CMS-Detailseite führt - keine Fancybox.

Fände ich wohl nach wie vor sinnvoll.

**Comment by frase-git** [comment]
> Fände ich wohl nach wie vor sinnvoll.

Ich auch.
Also, ihr Lieben. Jetzt mal Butter bei die Fische.
Vorschaubild -> Klick -> **immer** Detaliseite

Dazu muss wohl in `product.php` nur in Zeile 128 der Link geändert werden.
`class="zoom"` raus
Statt Link zum Bild -> Link zur Detailseite (was eben gerade definiert ist)
`title` evtl. der Text, der auch im Button "Artikel Details" steht.

Ich habe mal bei anderen Shops geguckt. Das handelt jeder anders. Mal geht ein größeres Bild auf - aber häufiger ist es ein Link zu den Details.

Abgemacht?

Winziger Nachteil:
In Produkt bearbeiten war nach Auswahl des Vorschaubildes ein Klick auf dasselbe möglich - mit Fancybox. Fällt damit weg. Nichsoschlimm.

**Comment by frase-git** [comment]
Also ist auch hier alles geklärt:
Style-Probleme sind Sache von Tipps im Wiki.
Geändert werden sollte jetzt definitiv:
Klick auf Vorschaubild im Katalog (Shop-Übersicht) führt zur Detailansicht.
Auf geht's!

**Comment by cmb69** [comment]
> Geändert werden sollte jetzt definitiv:
Klick auf Vorschaubild im Katalog (Shop-Übersicht) führt zur Detailansicht.

Okay, mach ich.

**Comment by cmb69** [comment]
> Dazu muss wohl in product.php nur in Zeile 128 der Link geändert werden.

Ganz so einfach war es nicht möglich, weil der entsprechende Code auch im Back-End genutzt wurde, wo diese Verlinkung wenig sinnvoll wäre. Ich habe daher in 51d5626 etwas umfangreicher "aufgeräumt". Abgesehen vor der gewünschten Änderung haben sich möglicherweise ein paar Kleinigkeiten geändert. Also bitte testen. Unklar ist, was passieren soll, wenn es kein Bild gibt. Ich habe das fürs erste mal einfach gelöst: [dann wird nichts angezeigt](https://github.com/cmsimple-xh/xhshop/blob/51d56261b5308994aa02ece2ffd720e9644c2a4c/classes/View.php#L247-L249). Man könnte hier aber auch `no_image.jpg` verwenden, falls vorhanden.

**Comment by frase-git** [comment]
HMMM,
ich hatte jetzt keine Zeit ausgiebig zu testen.
Hier liegt wohl ein Missverständnis vor.
Ich dachte eigentlich so:
In der Shop-Übersicht erhalten alle Bilder den gleichen Link, wie der Button `Artikel-Details` oder die Überschrift. Mehr nicht.
Fancybox (zoom) soll bei den Preview-Bildern nicht mehr genutzt werden.

Wenn kein Bild da ist, dann auch gar nichts anzeigen.
Falls gewollt, kann der Betreiber no-image.jpg reinsetzen - muss aber nicht.

**Comment by cmb69** [comment]
> Ich dachte eigentlich so:
In der Shop-Übersicht erhalten alle Bilder den gleichen Link, wie der Button Artikel-Details oder die Überschrift. Mehr nicht.

So ist es doch jetzt.

**Comment by cmb69** [comment]
> Fancybox (zoom) soll bei den Preview-Bildern nicht mehr genutzt werden.

Ah, jetzt hab ich's verstanden (ich teste noch immer ohne Fancybox). Sollte mit ee99a4d erledigt sein.

**Comment by frase-git** [comment]
> (ich teste noch immer ohne Fancybox)

ja, und mails empfängst du als Text ... ich weiß

Jetzt ist _beinahe_ alles gut.
Bei Artikeln, die kein Bild **und** keine Detailseite haben erscheint ein Link zu `index.php?`
Der sollte noch weg.

Ich sehe auch noch anderes. Muss ich aber noch genauer testen.
Bitte warten.

**Comment by frase-git** [comment]
Also,
wenn ein Artikel ein Vorschaubild hat, **aber keine Detailseite**, dann linkt es auch zum `?`

**Comment by cmb69** [comment]
Müsste jetzt passen.

**Comment by frase-git** [comment]
Du bist und bleibst der Größte!

@XHalbert dürfte begeistert sein - ich auch!

**Comment by XHalbert** [comment]
schließe ich mich an: Du bist und bleibst der Größte!
Und ja, ich bin begeistert!!!

Überhaupt wirkt das alles sehr gut

**Comment by cmb69** [comment]
> Du bist und bleibst der Größte!

Weil ich eine Verbesserung programmiert habe, die ihr beide ausbaldowert habt? Wer ist größer: der Erfinder oder der Handwerker? :)

**Comment by frase-git** [comment]
Antwort auf Queenisch:
We Are the Champions, Weeeeee Are the Champions ...
;-)))
