### ISSUE TITLE
F5 after ordering throws fatal error

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#29]
Nach einem erfolgreichen Bestellvorgang, führt das Aktualisieren (F5) des Browsers zu einem fatalen PHP Fehler:
````
Fatal error: Uncaught Error: Call to a member function getVat() on null in …
````

**Comment by XHalbert** [comment]
war in wellrad und 1.6x auch schon

**Comment by cmb69** [comment]
Das Problem ist, dass beim anzeigen der Dankeschön-Seite der Kunde und die Bestellung, die in der Session gespeichert waren, [gelöscht werden](https://github.com/cmsimple-xh/xhshop/blob/7c9a6e726fb0e4c5b85f465e875792de8c59b313/classes/app/xhs_frontend_controller.php#L560-L561) (was gut ist). In [`writeBill()`](https://github.com/cmsimple-xh/xhshop/blob/7c9a6e726fb0e4c5b85f465e875792de8c59b313/classes/app/xhs_frontend_controller.php#L434) wird aber auf diese Variablen zugegriffen, ohne zu prüfen, ob sie gesetzt sind. Und eigentlich braucht `writeBill()` erst gar nicht aufgerufen zu werden, sondern man könnte [`finishCheckOut()`](https://github.com/cmsimple-xh/xhshop/blob/7c9a6e726fb0e4c5b85f465e875792de8c59b313/classes/app/xhs_frontend_controller.php#L412) gleich wieder verlassen, wenn die Session-Variablen nicht mehr gesetzt sind. Dann erzeugt der Shop in diesem Fall zwar keine Ausgabe, aber das finde ich immer noch besser als einen White Screen of Death. Und wenn später hoffentlich mal auf das PRG Pattern umgestellt wird, ist dieses Problem sowieso hinfällig.

**Comment by frase-git** [comment]
> aber das finde ich immer noch besser als einen White Screen of Death

👍

**Comment by XHalbert** [comment]
> Dann erzeugt der Shop in diesem Fall zwar keine Ausgabe

in welchem Fall?

Könnte es sein, dass hier das Problem ist, das ich immer mit dem paypal-redirect habe? Wir hatten ja früher lediglich gerätselt, ob das mit "referer" zusammenhängt. Siehe #20.

Übrigens: paypal verlangt nach erfolgter Zahlung mit ipn (instant pay notify oder ähnlich) ausdrücklich eine Dankeschön-Seite, auf der die erfolgte Zahlung "quittiert" wird.

(Hoffentlich hab ich mich jetzt nicht blamiert, vllt. meintest du was ganz anderes...)

**Comment by cmb69** [comment]
> Hoffentlich hab ich mich jetzt nicht blamiert, vllt. meintest du was ganz anderes...

Ich meinte zwar etwas anderes, aber blamiert hast du dich nicht. Die Info, dass nach IPN ene Dankeschön-Seite *verlangt* wird, könnte noch sehr hilfreich sein, um das PayPal-Problem zu lösen (ein bisschen habe ich die Hoffnung, das es das aber vielleicht noch von selbst tut).

Hier geht es einfach darum: Bestellung abgeschlossen (egal welche Zahlungsmethode), dann kommt die Dankeschön-Seite. Drückte man nun F5, gab es eine weiße Seite (500 Internal Server Error). Nun wird die CMSimple_XH-Seite auf der der Shop platziert ist (`display_shop()`) angezeigt, ohne allerdings irgendeine Ausgabe des Shops (also so, als ob dort `display_shop()` gar nicht stünde).

Natürlich wäre es schöner, wenn dann wieder die Produkübersicht angezeigt wird, aber das lasse ich lieber mal für später.

**Comment by XHalbert** [comment]
danke, jetzt hab ich verstanden

> (paypal-Problem) ... die Hoffnung, das es das aber vielleicht noch von selbst tut

die hatte ich in den ersten Jahren auch, und mich dann damit abgefunden. Immerhin verliert man damit keine Kunden, nur Nerven, aber man verstößt eben auch gegen paypal-Richtlinien (richtiger: paypal verlangt bei Nutzung von ipn ...), und zeitweilig, als es besonders häufig vorkam, hatte paypal mich auch abgestraft (ipn deaktiviert).
