### ISSUE TITLE
Prüfung auf hi_fancybox

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#3]
Prinzipiell funktioniert alles auch ohne Fancybox. Man kann die Bilder anklicken, sie werden (in der großen Version angezeigt) - dann muss man aber mit dem Browser-Zurück-Button zurückschalten. Geht so.
Nur im 2. Schritt im Bestellvorgang, bei Klick auf AGB gibt es ein Problem. Da hier schon Daten übertragen werden, meldet der Browser beim Zurückschalten: "Dokument erloschen ...") und man muss reloaden.
Sollte man das Plugin von hi_fancybox abhängig machen? Also prüfen, ob installiert?

**Comment by cmb69** [comment]
> Nur im 2. Schritt im Bestellvorgang, bei Klick auf AGB gibt es ein Problem. Da hier schon Daten übertragen werden, meldet der Browser beim Zurückschalten: "Dokument erloschen ...")

Das hat eigentlich mit der Fancy-Box nur bedingt zu tun. Insgesamt ist dieses Verhalten unschön, zumindest für erfahrene Surfer, und v.a. für Entwickler. Grundsätzlich bietet sich das [PRG Pattern](https://de.wikipedia.org/wiki/Post/Redirect/Get) als Lösung an. (Schritt "1. Warenkorb" bräuchte nicht mal ein POST zu sein.)

Alternativ könnte der Warenkorb auch abhängig von bereits eingegeben Informationen funktionieren; wenn also mit den Waren alles stimmt, und bereits Kontaktinformationen eingegeben wurden, könnte beim Aufruf gleich Seite 3 angezeigt werden.

Entscheidend, wie man es nun macht, sind vermutlich rechtliche Dinge – da kenne ich mich bei e-Shops aber nicht wirklich aus.

**Comment by frase-git** [comment]
Wenn hi_fancybox installiert ist, gibt es gar keine Probleme.
Nur, wenn die Fancybox nicht da ist, macht der AGB-Link Ärger.
Das Einfachste wäre also die Fancybox vorauszusetzen - ist auch für die Bilder schöner.
Wahrscheinlich ist eine solche Abhängigkeit aber nicht gut?

**Comment by cmb69** [comment]
> Wahrscheinlich ist eine solche Abhängigkeit aber nicht gut?

Nicht unbedingt.

Aber worum es mir geht: ein erfahrener Surfer benutzt auf Seite 2 des Warenkorbs den Back-Button des Browsers statt des Zurück-Buttons des Shops – WTF?

**Comment by frase-git** [comment]
Missverständnis?
Mir geht es nicht um "zurück zu Schritt 1".
Im zweiten Schritt gibt es den Link zu den AGB, falls diese in der Shop-Konfiguration verlinkt wurden.
Ist die Fancybox **nicht** da, wird bei Klick darauf diese Seite (AGB/C.O.S.) angezeigt.
Um wieder zu Schritt 2 zu kommen, muss man den Browser-Button nehmen - und dann RELOAD.
**Mit Fancybox** gibts das nicht.
Also: Fancybox voraussetzen/prüfen?

**Comment by cmb69** [comment]
> Missverständnis?

Nein, kein Missverständnis. Mir ist schon klar worum es dir geht, aber mir geht es darum, dass der Zurück-Schalter des Browsers auch in anderen Fällen funktionieren sollte. Und: ist ja schön und gut, die Fancybox zu erfordern, aber was ist, wenn beim User kein JavaScript läuft – das ist das gleiche, als wäre Fancybox nicht installiert.

Ich arbeite mal einen minimalen PR aus.

**Comment by frase-git** [comment]
> ... aber was ist, wenn beim User kein JavaScript läuft – das ist das gleiche, als wäre Fancybox nicht installiert.

Ja, dann müsste der Link zu den AGB statt `class="zoom_i"` auch noch `target="_blank"` erhalten.
Eben abhängig von Fancybox bzw. von JS.
Bei Bildern ist das egal (ob JS oder nicht).

**Comment by cmb69** [comment]
> Ja, dann müsste der Link zu den AGB statt class="zoom_i" auch noch target="_blank" erhalten.
Eben abhängig von Fancybox bzw. von JS.

Kann man nicht `target="blank"` immer setzen? Sprich, ich glaube das stört die Fancybox nicht.

**Comment by frase-git** [comment]
> Kann man nicht `target="blank"` immer setzen? Sprich, ich glaube das stört die Fancybox nicht.

Probiere ich bald mal. Melde mich.

**Comment by frase-git** [comment]
> Probiere ich bald mal. Melde mich.

Gute Nachricht:
`xhs_frontend_view.php` Zeile 94 ändern zu:
`$link = "<a href=\"$cos_url&print\" class=\"zoom_i xhsCosLnk\" target=\"_blank\">$name</a>";`
Das funktioniert mit Fancybox.
Ohne Fancybox bzw. auch ohne JS öffnet eine neue Seite.
War doch so gewollt - oder?

**Comment by cmb69** [comment]
> War doch so gewollt - oder?

Ja. Ist bereits integriert: eeb485e. Damit kann dieses Ticket eigentlich geschlossen werden, oder?

**Comment by frase-git** [comment]
Yep.
