### ISSUE TITLE
Smash shopsettings.php

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#30]
Der ursprüngliche Wellrad-Shop bemüht sich um Unabhängigkeit vom Trägersystem – das macht meiner Meinung nach wenig Sinn für den XHShop. Besonders `shopsettings.php` verursacht einigen Mehraufwand, da die Konfigurationsformulare manuell vom Plugin anstatt automatisch von CMSimple_XH erstellt werden. Ich schlage daher vor, `shopsettings.php` zu zerschlagen. Im Einzelnen:
* [x] Einstellungen → Shop (noch unklar)
* [x] Einstellungen → Kontakt wandert nach `config.php`
* [x] Einstellungen → Steuern wandert nach `config.php`
* [x] Einstellungen → Versand wandert nach `config.php` (bzw. Sprachdateien)
* [x] Einstellungen → Zahlweisen speichert nicht in `shopsettings.php`, und ist daher nicht Gegenstand dieses Vorschlags, sondern von #64
* [x] Artikel → Kategorien → Einstellungsformular wandert nach `config.php`

**Comment by cmb69** [comment]
PR #31 verschiebt Einstellungen → Kontakt nach `config.php`, und deutet die Vereinfachung an (12 zusätzliche Zeilen Code – 67 Codezeilen entfernt). Na ja, vielleicht kommen noch Hilfstexte für die Konfiguration hinzu, aber allein schon der Verzicht auf `contactSettings.tpl` zeigt die willkommene Vereinfachung.

**Comment by frase-git** [comment]
Das klingt sehr vernünftig, auch wenn ich die Folgen nich ganz überblicke.
Das sieht zunächst nach Aufwand aus - sollte sich aber bei der weiteren Pflege auszahlen - oder?
Mir macht Sorge, wie das dann in der Praxis ist. Haben wir dann eine ellenlange Konfiguration, oder lässt sich das auf einzelne Seiten unterteilen? Sorry - mein Unwissen ...
Aber, selbst wenn alles in einer Seite wäre, wäre das wohl nur Gewöhnungssache für Wellrad-Nutzer.
Ich schlage vor, du mergest mal den PR und wir sehen weiter. Im Notfall müssen wir zurückrudern - was ich aber nicht glaube. Ich möchte das gerne mal live sehen.

**Comment by XHalbert** [comment]
> klingt sehr vernünftig

dito

**Comment by cmb69** [comment]
> Mir macht Sorge, wie das dann in der Praxis ist. Haben wir dann eine ellenlange Konfiguration, oder lässt sich das auf einzelne Seiten unterteilen? Sorry - mein Unwissen ...

Der PR betrifft derzeit nur die 6 Kontakt-Einstellungen; die Konfiguration ist also sehr überschaubar. Ich denke aber, dass auch wenn der Rest der nach `config.php` passt dorthin verschoben wird, die Konfiguration hinreichend überschaubar bleibt – und zumindest kann sie ja ähnlich wie jetzt gruppiert werden (halt keine eigenen Seiten, aber zumindest eigene `fieldsets`).

> Ich möchte das gerne mal live sehen.

Du kannst dir Branches jederzeit auschecken; dazu einfach den [Branch aufrufen](https://github.com/cmsimple-xh/xhshop/tree/settings-contact), dann findest du unter "Clone or download" (grüner Schalter) die entsprechenden Möglichkeiten.

**Comment by cmb69** [comment]
Ich habe PR #31 nun in den master gemerge't.

**Comment by cmb69** [comment]
> Das sieht zunächst nach Aufwand aus - sollte sich aber bei der weiteren Pflege auszahlen - oder?

Ja, darum geht es vor allem.  Der Shop hatte zunächst 5 eigene Formulare für die Einstellungen. D.h. jedesmal wenn eine Einstellung hinzugefügt oder entfernt wird, muss auch das zugehörige Formular angepasst werden, anstatt einfach eine Zeile in `config.php` zu ergänzen (und vielleicht noch Hilfetexte und ein Eintrag in `metaconfig.php`). Dazu kommt, dass die Shop-Navigation suboptimal ist, weil fast alles per POST erfolgt. Es dürfte vermutlich etwas leichter werden, das zu ändern, wenn es erst mal weniger solcher Navigationen gibt.

Okay, und hier der zweite Streich: PR #36. Das ist nicht mehr ganz so elegant wie zuvor (eben keine numerischen Inputs für die Steuersätze), aber ich denke damit kann man leben (und vielleicht sollte in CMSimple_XH ein [numerischer Konfig-Typ eingeführt](https://github.com/cmsimple-xh/cmsimple-xh/issues/269) werden – dann könnte beim Shop nachgebessert werden).

**Comment by frase-git** [comment]
Merge mal alles.
Prüfen kann ich frühestens des nächtens.

**Comment by cmb69** [comment]
> Merge mal alles.

Erledigt.

**Comment by frase-git** [comment]
Danke!

~~starke Bedenken:
`$plugin_mcf['xhshop']['taxes_vat_default']="enum:full,reduced";`
Das gibt Protest.~~

Sehe gerade, full und reduced sind ja änderbar.

**Comment by cmb69** [comment]
Zu `$plugin_mcf['xhshop']['taxes_vat_default']="enum:full,reduced";`: da sollte vermutlich noch in den Hilfstexten übersetzt werden.

**Comment by cmb69** [comment]
Ich habe mir nun die Shop-Settings angeschaut. Die können ebenfalls alle in die Konfiguration wandern, bis auf die AGB-Seite, die halt in die Spracheinstellungen müsste. Dort hätte man aber keine Auswahlliste – ist das ein Problem? @frase-git @XHalbert

**Comment by cmb69** [comment]
> Sehe gerade, full und reduced sind ja änderbar.

Wenn diese in `metaconfig.php` geändert werden, dann funktioniert die Logik aber nicht mehr.

**Comment by XHalbert** [comment]
denke Auswahlliste für AGB braucht man nicht, die muss wohl immer AGB heißen

**Comment by cmb69** [comment]
> denke Auswahlliste für AGB braucht man nicht, die muss wohl immer AGB heißen

Für Deutschland passt das, aber auch für andere Länder?

**Comment by frase-git** [comment]
> Die können ebenfalls alle in die Konfiguration wandern, bis auf die AGB-Seite, die halt in die Spracheinstellungen müsste. Dort hätte man aber keine Auswahlliste – ist das ein Problem?

Hm, Komfortverlust. Das war im Wellrad praktisch. Bei richtiger Dokumentation aber gangbar.
In diesem Zusammenhang:
Wir brauchen das Gleiche auch für die Versandkosten-Seite - namlich für den Zusatz: "zzgl. Versandkosten" bei der Cart-Box und auf den Detailseiten ([Beispiel](http://fhs.bplaced.net/xhshop-demo/?Test) händisch eingefügt in Sprache).

**Comment by frase-git** [comment]
> Wenn diese in metaconfig.php geändert werden, dann funktioniert die Logik aber nicht mehr.

(Ich will ja nicht schon wieder russisch anfangen) Wieso?

**Comment by cmb69** [comment]
> Hm, Komfortverlust. Das war im Wellrad praktisch. Bei richtiger Dokumentation aber gangbar.

Toll finde ich das auch nicht. Allerdings gibt es solche sprachabhängigen Seitenangaben auch bei einigen anderen Plugins (z.B. Realbog's Blogseite); vielleicht sollten wir die Sprachkonfiguration mal aufbohren.

> (Ich will ja nicht schon wieder russisch anfangen) Wieso?

Siehe z.B. [hier](https://github.com/cmsimple-xh/xhshop/blob/3b417551fa5fc91e4c79c6c6cb27581f10e698d7/classes/app/xhs_frontend_controller.php#L601). Da wird eben `vat_full` oder `var_reduced` genommen, je nachdem was die Voreinstellung ist. `vat_voll` und `vat_reduziert` sind aber nicht bekannt. Wie oben schon erwähnt, könnte das aber auch in den Hilfstexten noch übersetzt werden; vgl. [Themeswitcher](https://github.com/cmb69/themeswitcher_xh/blob/1.0beta2/languages/de.php#L7). Alternativ könnte man auch umarbeiten, und eine Checkbox anbieten (etwa "Soll der volle Umsatzsteuersatz voreingestellt sein?").

PS: Versandkosten besser in #17 abhandeln.

**Comment by frase-git** [comment]
> ... vielleicht sollten wir die Sprachkonfiguration mal aufbohren ...

Roadmap ab 1.8

> Alternativ könnte man auch umarbeiten, und eine Checkbox anbieten (etwa "Soll der volle Umsatzsteuersatz voreingestellt sein?").

👍

**Comment by cmb69** [comment]
Okay, der dritte Streich: PR #41. Bitte [mal prüfen](https://github.com/cmsimple-xh/xhshop/tree/config-shop). Die `cos_page` (AGB-Seite) ist nun in der Sprachdatei, und kann daher weder Auswahlliste noch Hilfetext haben – das müsste also explizit in der Hilfedatei (aka. Benutzerhandbuch) dokumentiert werden. Nicht schön, aber IMO dennoch sinnvoll, weil das manuelle Formular-Handling einfach zu komplex ist (zumindest solange dafür kein Framework existiert und auch genutzt werden kann).

**Comment by XHalbert** [comment]
$plugin_tx['xhshop']['config_cos_page']="?Shop/AGB";

Ich glaube nicht, dass "AGB" eine Unterseite von Shop sein darf

**Comment by frase-git** [comment]
Wenn der Shop eine Unterseite ist, dann auch die AGB - siehe  Demo.

**Comment by frase-git** [comment]
> Okay, der dritte Streich: PR #41. Bitte mal prüfen.

Mit den besprochenen Nachteilen, scheint es OK zu sein.
Wollen wir vor dem Mergen nicht gleich noch eine `shippingcost_page` hinzutun?
siehe [hier](https://github.com/cmsimple-xh/xhshop/issues/17)

EDIT:
Sorry, eben entdeckt.
In Step 2:

> NOTICE: Undefined index: cos_page
> ..\plugins\xhshop\classes\app\xhs_frontend_controller.php:258

xhs_frontend_view.php: 85?

**Comment by XHalbert** [comment]
> shippingcost_page hinzutun?

meinst du eine Infoseite über die Kosten?

Ich würde beide (AGB und Shippingcost) als normale CMS besser finden, einfach auch schon deshalb, weil man hier gestalten kann.

**Comment by frase-git** [comment]
Ich meine, der Link zur Versandkosten-Seite sollte [wie hier besprochen](https://github.com/cmsimple-xh/xhshop/issues/17)  automatisch eingefügt werden. (Wie der AGB-Link in Step 2 - der in PR #41 nicht funktioniert, siehe oben.)
AGB und Versandkosten bleiben normale Seiten.

**Comment by XHalbert** [comment]
> AGB und Versandkosten bleiben normale Seiten.

und wie sie heißen steht in der Sprachdatei.
(hab ich jetzt richtig verstanden?)
Wird es irgendwo einen Hinweis geben, wenn die Seiten nicht erreichbar sind , z.B. anders heißen?

**Comment by frase-git** [comment]
> und wie sie heißen steht in der Sprachdatei

Nicht, wie sie heißen, sondern der Link dorthin.
z.B.:
`$plugin_tx['xhshop']['config_cos_page']="?Shop/AGB";`

> Wird es irgendwo einen Hinweis geben, wenn die Seiten nicht erreichbar sind , z.B. anders heißen?

Da wird es wohl eine Fehlermeldung geben.

**Comment by XHalbert** [comment]
> Nicht, wie sie heißen, sondern der Link dorthin.

ja meinte ich auch
Sollte aber doch wohl eher ... ="?AGB";  lauten?

**Comment by frase-git** [comment]
Es gibt auch Websites, die ganz allgemeine (Firmen)Infos haben PLUS einen Shop. (Beispiel [CNLPA](http://cnlpa.de/))
Das sähe dann so aus, wie in der Demo. Der Shop ist dann eine Seite auf Level 1 - aber nicht die Startseite (semantisch eine Unterseite).
In solchen Fällen muss es für die Firmen-Seite ein Impressum geben (Deutschland). Ist die Shop-Seite geöffnet, muss es dort direkten Zugang zu AGB, Versandkosten und **Shop-Impressum** (also extra) geben.

Bei dir ist das zurzeit anders (auch richtig!). Deine gesamte Seite ist _nur der Shop_ - du hast AGB, Versandkosten und Impressem permanent sichtbar - wie gesagt: das ist richtig.

**Comment by cmb69** [comment]
> NOTICE: Undefined index: cos_page

Danke. Habe ich nun behoben (83018c8).

> Wird es irgendwo einen Hinweis geben, wenn die Seiten nicht erreichbar sind , z.B. anders heißen?

Ja, das wäre gut. Aber ich denke, dazu sollte ein eigenes Ticket geöffnet werden, da dieses nur dem Umbau der `shopsettings.php` gilt, und bisher eine solche Prüfung auch nicht durchgeführt wurde (es wurde nur geprüft, ob überhaupt etwas eingetragen wurde, und andernfalls die fehlende AGB-Seite bemängelt – was aber wenig hilft, wenn die AGB-Seite später umbenannt oder entfernt wird). 

> Sollte aber doch wohl eher ... ="?AGB"; lauten?

Ich denke, über die Voreinstellung kann man lange diskutieren (vielleicht mag jemand lieber ?Allgemeine-Geschäftsbedingung oder was auch immer). Ich würd's zumindest erst mal so lassen (war auch vor diesem PR schon so); wichtig ist, dass das gut dokumentiert wird.

#17 würde ich ebenfalls aus diesem Ticket raushalten.

**Comment by cmb69** [comment]
Ich habe PR #41 gemerge't.

**Comment by cmb69** [comment]
Der nächste Streich: PR #68. Ich habe die Staffelung für den Versand in andere Länder noch nicht integriert; das gehört zu #4 und kann dann ja noch kommen.

**Comment by frase-git** [comment]
Default currency = €
Currency code = EUR

Ich vermute mal, dass der Code für PayPal benötigt wird - oder?
Frage:
Die beiden Eingaben müssen überinstimmen - oder?
Wird das geprüft?

**Comment by frase-git** [comment]
oben erster Post, vorletzter Punkt; 
> Artikel → Kategorien → Einstellungsformular wandert nach `config.php`

Hast du schon Vorstellungen, wie das aussehen soll?
Sortiererei?

**Comment by cmb69** [comment]
> Ich vermute mal, dass der Code für PayPal benötigt wird - oder?

Ja genau. War vorher in den Paypal-Einstellungen.

> Die beiden Eingaben müssen überinstimmen - oder?
Wird das geprüft?

Ja, sie müssen übereinstimmen, aber geprüft wird das nicht. Vorher gab es einen eher minimalistischen Check für €, $, £ und ¥, aber das deckt ja nur ein paar Fälle ab (was ist mit CHF, z.B.?) Im Zweifel dokumentieren, dass das richtig einzustellen ist (in den Hilfstexten habe ich schon drauf hingewiesen). Oder halt eine umfassende Tabelle integrieren, so dass nur noch der Code eingetragen werden muss, und dann das Symbol automatisch ermittelt wird.

Hm, da fällt mir gerade auf, dass die Währungssymbole nicht unbedingt eindeutig sind; `$` wird für unterschiedliche Währungen verwendet (z.B. AUD und USD) – müssen wir da was tun?

> Hast du schon Vorstellungen, wie das aussehen soll?
Sortiererei?

Nicht die eigentlichen Katergorien, sondern nur die beiden ja/nein Einstellungen sollen in die `config.php`.

**Comment by frase-git** [comment]
Default currency = AU$  oder A$ Austr.
Default currency = C$ Canad.
So etwa in der Art muss der Betreiber die Währung angeben.

Currency code -> dann immer nach ISO

**Comment by cmb69** [comment]
> So etwa in der Art muss der Betreiber die Währung angeben.

Okay.

Ich habe den nächsten Streich fertig: PR #69.

**Comment by frase-git** [comment]
Ich merge mal immer fleißig - richtig so?
Ich kann eh erst richtig prüfen, wenn es drin ist.
Früher habe ich mir die Änderungen händisch eingefügt und erst getestet - geht nicht mehr.

**Comment by frase-git** [comment]
Aufgefallen:
in den Sprachdateien geht es fröhlich durcheinander mit " " und ' '.
Du musstest jetzt escapen. Wäre nicht nötig, wenn alles konsequent ' ' wäre.

**Comment by cmb69** [comment]
> Du musstest jetzt escapen. Wäre nicht nötig, wenn alles konsequent ' ' wäre.

Wenn aus dem Backend gespeichert wird, werden die Texte in doppelte Anführungszeichen eingeschlossen. Das würde ich eigentlich auch gleich so ausliefern – zumindest habe ich es bisher immer so gemacht. Und doppelte Anführungszeichen haben den Vorteil, dass auch Zeichen, die eigentlich nicht dargestellt werden können als Escapesequenz enthalten sein können, was aber bei UTF-8 vermutlich nicht mehr wirklich relevant ist (na ja, vielleicht braucht man hier und da mal einen Tab).
