### ISSUE TITLE
nur Info: Umlautersetzung - keine Änderung nötig

### ISSUE THREAD

**Issue by XHalbert** [cmsimple-xh/xhshop#32]
interessant: die neue Umlautersetzung.
bisher war der link zur Detailseite im catalog so:
array('einzelne_Produkte:Bez%C3%BCge:Bez%C3%BCge_StillKis', ) und wurde jetzt nicht mehr gefunden.
habe im backend neu verlinkt, jetzt sieht es so aus
array('einzelne_Produkte:Bezuege:Bezuege_StillKis', )
gut, das ich catalog.php mit dem editor bearbeiten kann...

**Comment by cmb69** [comment]
> array('einzelne_Produkte:Bez%C3%BCge:Bez%C3%BCge_StillKis', ) und wurde jetzt nicht mehr gefunden.
habe im backend neu verlinkt, jetzt sieht es so aus
array('einzelne_Produkte:Bezuege:Bezuege_StillKis', )

Hm, sieht mir so aus als ob das eigentlich nichts mit dem Shop zu tun hat, sondern mit [urichar_org/new](http://www.cmsimple-xh.org/wiki/doku.php/de:special_characters_in_headings). @XHalbert Bitte mal prüfen, ob die alten Links funktionieren würden, wenn Umlaute in urichar_org/new nicht ersetzt werden. Falls das so ist, dann kann dieses Ticket geschlossen werden. Ansonsten sollten wir die Änderung (was auch immer das verursacht hat) dokumentieren.

**Comment by frase-git** [comment]
Ich hatte [hier](https://github.com/cmsimple-xh/xhshop/issues/28#issuecomment-312794985) schon geantwortet - und Albert schreibt ja auch in der Überschrift: - keine Änderung nötig.

Das Problem war/ist, dass bei der neuen 1.7.0 Installation urichar_org/new eben anders ist als in der alten.
Offensichtlich gefallen Albert die Daten in der catalog.php in der neuen Form besser (ist ja auch lesbarer).
Ticket kann zu.
