### ISSUE TITLE
nicht lieferbar - andere Farbe

### ISSUE THREAD

**Issue by XHalbert** [cmsimple-xh/xhshop#33]
habe grad die Shop-Übersicht im backend bearbeitet. Dabei ist mir aufgefallen, dass ich es gut fände, wenn  "nicht lieferbar" in einer anderen Farbe z.B. grün erscheinen würde

**Comment by frase-git** [comment]
Das ist interessant.
Es können da ja mehrere Meldungen erscheinen:
- keine Preisangabe
- nicht lieferbar
- keine Kurzbeschreibung
- keine Artikelseite

Da "keine Preisangabe" wahrscheinlich ein echter Eingabe-Fehler ist, kommt das in Orange.
Für die anderen Punkte sind keine Error-Klassen vorgesehen. Das sind nur allgemeine Infos.

**Comment by cmb69** [comment]
> Es können da ja mehrere Meldungen erscheinen:

Hier fände ich es eigentlich schön, wenn diese Meldungen nicht eine Zeile belegen, sondern es einfach für jeden der Fälle eine schmale Spalte gäbe, mit Häkchen oder X oder ähnlich. Das macht die Liste übersichtlicher und eine Paginierung weniger dringlich. Und man könnte die Tabelle irgendwann mal sortierbar gestalten, so dass man sich mit wenigen Klicks die Artikel ohne Preisangabe (z.B.) gleich oben in der Tabelle anzeigen lassen könnte.

Einziger Nachteil, den ich sehe: die Tabelle wird zu breit für schmale Viewports, aber da könnte man vielleich mit etwas CSS nachhelfen (hatten wir ja schon diverse Male im Forum).

**Comment by frase-git** [comment]
Noch mehr Spalten fände ich überhaupt nicht gut.
So wie es ist geht doch.
Sortieren nach den Meldungen wird Wahnsinn und scheint unnötig.
Was sagt unser Praktiker @XHalbert ?

**Comment by XHalbert** [comment]
> Und man könnte die Tabelle irgendwann mal sortierbar gestalten, so dass man sich mit wenigen Klicks

das wäre die rosige Zukunft :)
die Tabelle ist ein ständiger Greuel. Versuch mal, Artikel von Position 0 auf Position 35 zu bringen...
(und das konnte ich bisher eben nicht in der php per Editor machen, wegen "sortindex"). der Fall ist gar nicht so theoretisch. Stell dir vor, du hast 40 Artikel eingestell beim ersten Mal, so hab ich das damals gemacht. Dann kommen vllt. 3 neue Artikel dazu, die thematisch auf pos. 35 gehören. Das wird lustig. Nach dieser Erfahrung habe ich bei weiteren Artikeln immer eine ausreichende Anzahl Artikel "NN  - nicht lieferbar " dazwischen gesetzt für später.

Aber wenn es nur um "nicht lieferbar" geht, kann das ruhig so bleiben. War nur sone spontane Idee. Wer will könnte z.B. in der Sprache schreiben "!!!  n i c h t lieferbar  !!!" und schon würde es sich deutlicher abheben.

Sortierbar und Häkchen wird vllt. irgendwann kommen und jeder würde sich freuen.

**Comment by frase-git** [comment]
Sortierbar: Da bin ich auch für.
Aber nicht nach den Meldungen, das wäre wohl zu viel.

Mit der Verschieberei hast du Recht. Sehr lästig.
Mir kam da schon die Idee, die ID (sortindex bzw. Rangfolgezahl, oder wie das heißt) als Eingabefeld zu machen. Da müsste dann aber nach jeder Änderung alles umsortiert und gespeichert werden. @cmb69 ???

**Comment by cmb69** [comment]
> Mit der Verschieberei hast du Recht. Sehr lästig.

Das ist ein grundlegendes Problem im Web; mir ist jedenfalls keine rein serverseitige Lösung für diesen Anwendungsfall bekannt, der auch vernünftig bedienbar ist. Die jetztige Lösung ist eine Katastrophe (wenn die Sortierung relevant ist), und Franks Vorschlag, den `sortIndex` manuell eingeben zu können, ist auch nur ein nicht unproblematischer Workaround.

An dieser Stelle bleibt mir nur eine rein (oder jedenfalls primär) clientseitige Lösung vorzuschlagen. Mit JS lassen sich solche Listen vergleichsweise einfach per Drag&Drop umsortieren. jQueryUI bietet [sortable](http://jqueryui.com/sortable/), aber das wäre overkill; ich schau mich mal nach was leichtgewichtigerem um.

**Comment by cmb69** [comment]
> Mit JS lassen sich solche Listen vergleichsweise einfach per Drag&Drop umsortieren.

Allerdings müsste danach die Produkttabelle als ein Formular versendet werden, und das würde heftige Umbauten erfordern. Vielleicht bietet sich fürs erste doch eine minimalistischere Lösung an, nämlich diese Request als Ajax-Requests zu verschicken. Das habe ich in PR #54 mal umgesetzt. Bitte mal anschauen.

**Comment by frase-git** [comment]
PR #54 meldet:
This branch has conflicts that must be resolved
???

**Comment by cmb69** [comment]
> This branch has conflicts that must be resolved

Passt jetzt wieder. :)

**Comment by frase-git** [comment]
@XHalbert 
Schau dir jetzt mal die Verschieberei mit dem aktuellen Master an!
Genial! Und schon um vieles einfacher!

@cmb69 
Danke!

**Comment by XHalbert** [comment]
sehe ich keine Änderung - hab alles gelöscht und neuen master rein

**Comment by frase-git** [comment]
Na, dann gehe mal bei 100 Artikeln nach ganz unten und verscheibe den letzten nach oben.
Bisher wurde die Seite jedesmal neu geladen, man war wieder ganz oben und musste den gerade verschobenen Artikel unten wieder suchen, um ihn weiter zu verschieben.
Jetzt bleibt die Seite dort stehen, wo man gerade war.
Eine entscheidende Verbesserung, wie ich finde.
(Evtl. mal Cache leeren oder Browser schließen und wieder öffnen.)

**Comment by XHalbert** [comment]
> Schau dir jetzt mal die Verschieberei

wow blitzschnell

**Comment by cmb69** [comment]
> Schau dir jetzt mal die Verschieberei mit dem aktuellen Master an!
Genial! Und schon um vieles einfacher!

Na ja, optimal finde ich es nicht – ist halt ein Kompromiss. Aber habt ihr auch mal besonders bei vielen Artikel schnelle Verschiebeoperationen getestet – ich könnte mir vorstellen, dass es da vielleicht mal durcheinander gibt (glaube nicht, aber ich will's auch nicht ausschließen).

**Comment by frase-git** [comment]
Wenn du ein Prog schreibst, das Mouseclicks im 1/1000 Sekundentakt abfeuert, bringst du jede Software zum Krachen.

**Comment by cmb69** [comment]
> Wenn du ein Prog schreibst, das Mouseclicks im 1/1000 Sekundentakt abfeuert, bringst du jede Software zum Krachen.

Ganz so doll muss man es ja nicht treiben. Es halt jetzt halt so, dass die Artikel im Browser getauscht werden, und ein Ajax-Request an den Server erfolgt (dessen Antwort allerdings gar nicht mehr berücksichtigt wird). Wenn diese Requests nicht sequentiell abgearbeitet werden (was sie allerdings wegen der geöffneten Session müssten), dann müsste es durcheinander geben. Und es kann auch sein, dass ein Ajax-Request gar nicht ausgeführt wird, z.B. weil der Server zu busy ist – dann wird zwar im Browser die gewünschte Reihenfolge angezeigt, aber `catalog.php` bekommt davon nichts mehr mit.

Wenn aber bisher keine Probleme aufgefallen sind, dann passt vielleicht alles, und wenn später doch noch Probleme auftreten, dann kann man immer noch mal schauen.

**Comment by cmb69** [comment]
> Aber wenn es nur um "nicht lieferbar" geht, kann das ruhig so bleiben.

Okay, dann schließe ich das Ticket mal.
