### ISSUE TITLE
Automatic backup - catalog.php

### ISSUE THREAD

**Issue by XHalbert** [cmsimple-xh/xhshop#34]
sicher wünschenswert - muss aber nicht sofort!
bisher mach ich das vor jeder Änderung händisch

**Comment by cmb69** [comment]
Wann soll das Backup erstellt werden: (a) beim Logout oder (b) bei jedem Speichern?

Soll es immer nur ein Backup geben, oder gleich eine bestimmte Menge (wie bei CMSimples content Backups).

**Comment by frase-git** [comment]
> Wann soll das Backup erstellt werden: (a) beim Logout oder (b) bei jedem Speichern?

Idealerweise bei Klick auf Produkt bearbeiten ;-)
Quatsch!
Ich denke beim Speichern von Produkt-Änderungen.
Drei Versionen?

**Comment by XHalbert** [comment]
> Ich denke beim Speichern von Produkt-Änderungen.
Drei Versionen?

Wenn man zehn Produkte ändert und erst dann merkt, dass alles falsch ist?
Ich fänd bei logout wohl besser.

**Comment by frase-git** [comment]
nix dagegen

**Comment by cmb69** [comment]
> Ich fänd bei logout wohl besser.

Da reicht es im einfachsten Fall schon folgendes [hier](https://github.com/cmsimple-xh/xhshop/blob/3b417551fa5fc91e4c79c6c6cb27581f10e698d7/index.php#L70) einzufügen:
````
if ($f === 'xh_loggedout') {
    copy(XHS_BASE_PATH . 'data/catalog.php', XHS_BASE_PATH . 'data/catalog.bak.php');
}
````
Multi-Backups sind schon ein "wenig" aufwendiger. Vielleicht reicht ein Backup für Version 1.0?

**Comment by XHalbert** [comment]
für Version 1.0 allemal

**Comment by frase-git** [comment]
Jo.
