### ISSUE TITLE
Insufficient date localization

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#35]
Das Rechnungsdatum wird nur [halbherzig lokalisiert](https://github.com/cmsimple-xh/xhshop/blob/7c9a6e726fb0e4c5b85f465e875792de8c59b313/classes/app/xhs_frontend_controller.php#L439-L443), und zwar wie man sehen kann explizit nur für Deutsch, in welchem Fall aber `setlocale()` aufgerufen wird, was andere Plugins durcheinander bringen könnte.

Zu beachten ist weiterhin, dass `$datum` gar nicht wirklich verwendet wird, sondern das Datum [weiter unten](https://github.com/cmsimple-xh/xhshop/blob/7c9a6e726fb0e4c5b85f465e875792de8c59b313/classes/app/xhs_frontend_controller.php#L484) erneut formatiert wird, und per `utf8_encode()` nach UTF-8 konvertiert wird. Das würde aber nur für diejenigen Locales klappen, die ISO-8859-1 kompatibel sind.

Jedenfalls sollten wir überlegen, ob wir hier nicht einfach [`XH_formatDate()`](http://www.cmsimple-xh.org/dev-doc/php/functions_8php.html#a1cfa31881de948815c8b9d61edc337ec) verwenden. Das sollte dann immer so aussehen wie bei [`lastupdate()`](http://www.cmsimple-xh.org/dev-doc/php/tplfuncs_8php.html#a49883c93c2b6515e9a1790102310f2da) was zumindest okay ist, und falls ext/intl verfügbar eigentlich sehr gut passt.

**Comment by frase-git** [comment]
Klingt gut.
BTW: auf bplaced habe ich die intl.
Auf meinem "echten" Webspace nicht.

**Comment by cmb69** [comment]
> Klingt gut.

Ist es aber leider nicht wirklich. Ich hatte übersehen, dass XH_formatDate() je nach Einstellung auch die Uhrzeit mit anzeigt, und die will man in der Rechnung (und nur um diese geht es) nicht als Teil des Datums haben. Kommt natürlich drauf an, was nun tatsächlich mit der Rechnung gemacht wird – im Zweifel sollten wir hier mal den Ausgang von #18 abwarten.

> BTW: auf bplaced habe ich die intl.
Auf meinem "echten" Webspace nicht.

Erstaunlich! Hast du mal bei deinem Provider nachgefragt, ob er die Intl-Extension freischalten kann (falls du das im Control-Panel nicht selbst machen kannst).

**Comment by frase-git** [comment]
> Hast du mal bei deinem Provider nachgefragt

Ich denke, mit einem Anruf wird das erledigt sein - aber: Bin ich dann "Standard" oder ein Außenseiter?

**Comment by cmb69** [comment]
> aber: Bin ich dann "Standard" oder ein Außenseiter?

Ich habe mal ein bisschen recherchiert, und es sieht so aus als ob die Konkurrenz (zumindest WordPress, Drupal, Kirby) ext/intl nicht erfordert (weiß nicht, ob es zumindest optional unterstützt wird). So gesehen ist es vermutlich besser ext/intl auch beim XHShop höchstens optional zu verwenden.

**Comment by TN03** [comment]
> So gesehen ist es vermutlich besser ext/intl auch beim XHShop höchstens optional zu verwenden.

Aktuell bei mir (allinkl.com) ist ext/intl aktiv. Bei 1&1, wo ich vorher mit dem Board war, war es definitiv nicht aktiv. Und das war auch nicht das billigste Paket ( € 10,- monatlich ).

**Comment by cmb69** [comment]
Interessant! Danke, Holger. Ich frage mich halt, wie ohne ext/intl diverse Aufgaben gelöst werden, z.B. Sortierung von UTF-8 Texten und IDN-Konvertierung, um nur mal zwei Beispiele zu nennen.
