### ISSUE TITLE
Doubtful special treatment of bots

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#37]
At the beginning of `index.php` there is a [special treatment for some bots](https://github.com/cmsimple-xh/xhshop/blob/3b417551fa5fc91e4c79c6c6cb27581f10e698d7/index.php#L3-L5). This is apparently there to prevent PHP's URL rewriting for these bots. However, we already recommend to switch `session.use_trans_sid` off, and if this is the case, the code is actually a no-op. Furthermore, for this purpose `url_rewriter.tags` has been superseeded by `session.trans_sid_tags` as of PHP 7.1 so we would have to cater to this, if we want to cater to `session.use_trans_sid` on.

TL;DR: I suggest to remove these three lines.

**Comment by frase-git** [comment]
я не понимаю

**Comment by cmb69** [comment]
> я не понимаю

Beim URL-Rewriting geht es darum, dass Clients die keine Cookies akzeptieren, die Session-ID in der URL oder in versteckten Formularfeldern übermitteln können, damit die Session eben auch dort funktioniert. Das ist aber aus Sicherheitsgründen nicht unbedenklich – schnell teilt man versehentlich mal eine solche URL die `PHPSESSID` oder ähnlich enthält, und dann kann ein böswilliger User die Session übernehmen. Daher empfehlen wir schon lange, [diesen Mechanismus zu unterbinden](https://cmsimpleforum.com/viewtopic.php?f=36&t=7076). Wenn User sich an diese Empfehlung halten (falls nicht, wird es in der Systemprüfung angemahnt), dann bringen die drei genannten Zeilen sowieso nichts.

**Comment by frase-git** [comment]
Да, теперь я понимаю.
(Kann man meine Sozialisation geografisch erkennen? ;-) )

**Comment by cmb69** [comment]
> Kann man meine Sozialisation geografisch erkennen?

Ja. Und sorry, dass ich das Ticket auf englisch gestartet habe; bin's einfach so gewöhnt.

**Comment by frase-git** [comment]
> Und sorry, dass ich das Ticket auf englisch gestartet habe; bin's einfach so gewöhnt.

Dafür solltest du dich keinesfalls entschuldigen - das ist Standard.
Und _verstehen_ tu' ich English ganz gut.
(besser als Französisch und Russisch, was ich mehrere Jahre gelernt habe.)
Ich hatte eher ein fachliches Verständnisproblem.
Alles ist gut.
