### ISSUE TITLE
Improve config help texts

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#38]
Ich bin eher dafür, so viel wie möglich Erklärungen zu Konfigurations-Optionen zu geben.

Vorschlag Hilfetexte für Kontakt-Konfiguration (de):
```php
$plugin_tx['xhshop']['cf_contact_order_email']='E-Mail-Adresse, an die die Bestellungen verschickt werden';
$plugin_tx['xhshop']['cf_contact_company_name']='Shop-Name oder Firmen-Name';
$plugin_tx['xhshop']['cf_contact_name']='Name des Shop-Betreibers. Dieser Name wird u.A. unter die Bestätigungsmail gesetzt.';
$plugin_tx['xhshop']['cf_contact_street']='Shop-Adresse: Straße Nr.';
$plugin_tx['xhshop']['cf_contact_zip_code']='Shop-Adresse: Postleitzahl';
$plugin_tx['xhshop']['cf_contact_city']='Shop-Adresse: Ort';
```
Entsprechend übersetzt für EN.

Weiterin Änderung für taxes:
```php
$plugin_tx['xhshop']['cf_taxes_vat_full']="volle Umsatzsteuer - Eingabe mit Dezimalpunkt";
$plugin_tx['xhshop']['cf_taxes_vat_reduced']="ermäßigte Umsatzsteuer - Eingabe mit Dezimalpunkt";
```
Das ist wichtig, sonst gibt es in Step 3 wieder (bei Komma):

> NOTICE: A non well formed numeric value encountered
> ..\plugins\xhshop\classes\app\xhs_view.php:234

**Comment by cmb69** [comment]
Finde ich grundsätzlich gut. Bei `cf_taxes_vat_*` würde ich noch die gewünschte Einheit mit angeben, also "… Umsatzsteuer in Prozent – Eingabe mit Dezimalpunkt".
