### ISSUE TITLE
Step 2 - debug notices

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#39]
master 04.07.2017 20:30 inkl. [mods](https://github.com/cmsimple-xh/xhshop/issues/38)
local, xampp, php 5.6.11 **OHNE intl**

Debug-Modus meldet:
> NOTICE: Undefined index: street
> ..\plugins\xhshop\classes\app\xhs_frontend_view.php:25
> NOTICE: Undefined index: zip_code
> ..\plugins\xhshop\classes\app\xhs_frontend_view.php:25
> NOTICE: Undefined index: city
> ..\plugins\xhshop\classes\app\xhs_frontend_view.php:25

Die entsprechenden Felder haben **kein Label**.
**Alle** Felder sind  `type="text"` und haben `step="0.01"` !!!

Nachtrag:
unter xampp, php 7.1.1 **mit intl**  =  identisches Bild

**Comment by cmb69** [comment]
Upps! Da ich war ich in 4419e4e zu vorschnell, und habe Sprachtexte gelöscht, die noch benötigt werden.
