### ISSUE TITLE
Artikel ohne Detailbild

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#40]
master 04.07.2017 20:30 inkl. mods
local, xampp, php 5.6.11 OHNE intl

Erhält ein Artikel ein Vorschaubild (für Übersichtsseite), und **kein Bild** für Detailseite, dann:
Klick auf Bild in der Übersicht zeigt **das Bilderverzeichnis in der Fancybox**.
(Das hatten wir schon, aber jetzt habe ich mit dem neuen Master getestet.)
Außerdem wird auf der Detailseite - trotz Einstellung "kein Bild" das Vorschaubild von der Übersichtsseite angezeigt. Man kann es anklicken - in der Fancybox wird es einfach nochmal gezeigt.
Das - so vermute ich - liegt wohl daran, dass nach einem "best image" gesucht wird.
Das mit dem "best image" könnte wohl raus - oder?

**Comment by cmb69** [comment]
Siehe https://github.com/cmsimple-xh/xhshop/issues/25#issuecomment-312687999.

**Comment by cmb69** [comment]
Ich mach dieses Ticket mal wieder auf; das wurde inhaltlich zwar schon in #25 besprochen, aber dort hatten wir uns letztlich auf eine reine CSS-Lösung geeinigt, um das `<div>` dann leer zu lassen.

> Das - so vermute ich - liegt wohl daran, dass nach einem "best image" gesucht wird.
Das mit dem "best image" könnte wohl raus - oder?

Das "best image" wird derzeit für die Artikelübersicht und die Artikeldetails verwendet (wenn's denn überhaupt so ist – zumindest wird die entsprechende Funktion aufgerufen). Dabei wird bevorzugt das Detailbild, und nur falls nicht vorhanden, das Vorschaubild genommen.

Ich frage mich, ob wir es nicht so handhaben können, dass immer nur das Vorschaubild direkt angezeigt wird, und das Detailbild nur darüber verlinkt wird (Fancybox), falls vorhanden. Falls es kein Detailbild gibt, könnte in der Artikelübersicht direkt auf die Detailsseite verlinkt werden, was dann auch gleich #28 lösen würde. Würde das passen? Übersehe ich was?

**Comment by frase-git** [comment]
> Ich frage mich, ob wir es nicht so handhaben können, dass immer nur das Vorschaubild direkt angezeigt wird, und das Detailbild nur darüber verlinkt wird (Fancybox), falls vorhanden.

👍

> Falls es kein Detailbild gibt, könnte in der Artikelübersicht direkt auf die Detailsseite verlinkt werden, was dann auch gleich #28 lösen würde.

Na ja, zumindest im Falle, wenn es kein Detailbild gibt.
Ach so, in anderen Fällen konfigurierbar?
Dann 👍

**Comment by cmb69** [comment]
> Na ja, zumindest im Falle, wenn es kein Detailbild gibt.
Ach so, in anderen Fällen konfigurierbar?

Wenn es ein Detailbild gibt, dann ist der Sprung auf die Detailseite vielleicht nicht mehr so wichtig, weil man auch dort zunächst nur das Vorschaubild sähe. Zumindest im Fall von @XHalbert gibt es aber kein Detailbild. Sprich, wenn wir das so machen (können), dann würde ich auf eine Konfigurationsoption verzichten.

**Comment by cmb69** [comment]
Ich schließe dies mal als Duplikat von #28.
