### ISSUE TITLE
Max. Bestellmenge pro Artikel

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#42]
Wäre es nicht sinnvoll, bei `Artikel->Artikel bearbeiten` eine maximale Bestellmenge anzugeben?
Beispiel: Ein chinesisches Unternehmen will Alberts Dinkelkissen weltweit vertreiben und bestellt 100.000 Stück (unrealistisches Beispiel - illustriert aber, was ich meine).
Dieser Wert müsste dann dem Eingabefeld für die Bestellmenge als `max="XXX"` zugefügt werden.
Außerdem müsste auch hier` step="XXX"` individuell festgelegt werden. Ein 0.01 Stück Kissen kann man nicht bestellen - aber 0.75kg Hirse.
Momentan haben **alle** Textfelder `step="0.01"` - das dürfte auch nicht ganz richtig sein.

**Comment by cmb69** [comment]
Hm, max. Bestellmenge pro Artikel vs. Höchstbetrag für die gesamte Bestellung. Eins von beidem sollte wohl sein.

> Dieser Wert müsste dann dem Eingabefeld für die Bestellmenge als max="XXX" zugefügt werden.

Ja, das genügt aber nicht; es muss auch serverseitig unbedingt geprüft werden, ob die Bestellmenge nicht überschritten wurde.

> Außerdem müsste auch hierstep="XXX" individuell festgelegt werden. Ein 0.01 Stück Kissen kann man nicht bestellen - aber 0.75kg Hirse.

Kommt das in der Praxis vor bzw. ist es wirklich relevant? Ich denke es wird für alle einfacher, wenn wir uns hier auf ganze Zahlen beschränken können. Der Shop-Betreiber kann die Einheit ja entsprechend festlegen (50g, 250g, oder wie auch immer).

**Comment by frase-git** [comment]
> Hm, max. Bestellmenge pro Artikel vs. Höchstbetrag für die gesamte Bestellung. Eins von beidem sollte wohl sein.

Wer sagt denn: Ich möchte maximal 100 € verdienen - auf keinen Fall mehr!
Also wohl eher max. Bestellmenge pro Artikel.

> Kommt das in der Praxis vor bzw. ist es wirklich relevant? Ich denke es wird für alle einfacher, wenn wir uns hier auf ganze Zahlen beschränken können. Der Shop-Betreiber kann die Einheit ja entsprechend festlegen (50g, 250g, oder wie auch immer).

Da habe ich mich wohl etwas verrannt. Es wird wohl in der Praxis eher feste Packungsgrößen bzw. Stückzahlen geben. Sorry.
(Bei Tante Emma: Gehm se mir doch ma ä Vierdl Läberwurschd.)

**Comment by cmb69** [comment]
> Wer sagt denn: Ich möchte maximal 100 € verdienen - auf keinen Fall mehr!
Also wohl eher max. Bestellmenge pro Artikel.

Da hast du nicht unrecht. Aber die max. Bestellmenge pro Artikel muss halt auch gepflegt werden, und auch hier wird es dem Shop-Betreiber vermutlich nicht leicht fallen, eine entsprechende Beschränkung festzulegen.

**Comment by frase-git** [comment]
> hier wird es dem Shop-Betreiber vermutlich nicht leicht fallen, eine entsprechende Beschränkung festzulegen.

Ginge es denn als "kann-Option" für max. Bestellmenge?
Wenn nicht - dann nicht, oder "0" = keine Grenze als default?
@XHalbert
 Und hier fragen wir nochmal unseren Praktiker Albert, ob es nicht ausreicht, in die AGB zu schreiben: Abgabe nur in handelsüblichen Mengen - oder ob eine Obergrenze nötig wäre.

**Comment by cmb69** [comment]
> Ginge es denn als "kann-Option" für max. Bestellmenge?

Ja klar. Falls nichts eingetragen, dann keine Obergrenze.

**Comment by XHalbert** [comment]
>auf ganze Zahlen beschränken 

ja klar, man bestellt immer x Stck. von dem Artikel.

Obergrenze:
Ich bin nicht CSU - habe Obergrenzen nie vermißt. Wenn wirklich Jemand 100 Stck. bestellen will, dann fragt er vorher nach einem Großhandelspreis oder Rabattabzug. Also: ich brauch keine Obergrenze. Aber wenn, dann optional ("... "0" = keine Grenze als default..."

**Comment by frase-git** [comment]
Dann sollten wir uns diese Chose sparen.
Ich wollte das nur erwähnt haben.
Gut, dass wir Albert haben :wink:

**Comment by cmb69** [comment]
> Dann sollten wir uns diese Chose sparen.

+1

> Momentan haben alle Textfelder step="0.01" - das dürfte auch nicht ganz richtig sein.

Aber hier müssten wir nachbessern, wenn das wirklich so ist. Allerdings habe ich bei den Mengeneingabefeldern nur solche gefunden, die `min=1`, `max=100` und `step=1` haben. Das erscheint mir aber nicht wirklich richtig: zum einen bedeutet `min=1` dass man einen Artikel nicht leicht aus dem Warenkorb entfernen kann, und `max=100` wirkt etwas willkürlich. Und, um noch weiter abzuschweifen: ist es Absicht, dass wenn man bereits einen bestimmten Artikel im Warenkorb hat, und dann diesen Artikel noch einmal in den Warenkorb legt, die Mengen *nicht* aufsummiert werden?

**Comment by frase-git** [comment]
Die **Text**felder mit `step="0.01"` finden sich unter "Shop edit".
Das _könnte_ sich automatisch erledigen, wenn alles in die config wandert. (?)
`max="100"` war von mir willkürlich gewählt, und könnte nach dieser Runde raus.
`min="1"` tät ich drinlassen um Späßlemacher zu verhindern. Entfernen kann/soll man mit dem Button.
`step="1"` ganzzahlige Bestellmengen sind doch nun auch gut - oder?

> ist es Absicht, dass wenn man bereits einen bestimmten Artikel im Warenkorb hat, und dann diesen Artikel noch einmal in den Warenkorb legt, die Mengen nicht aufsummiert werden?

Das war schon immer so - und ich bin mir nicht sicher, ob das gut oder _bad_ ist.

**Comment by cmb69** [comment]
> Die Textfelder mit step="0.01" finden sich unter "Shop edit".

Hm, um welche Felder geht es konkret? Dass man bei der Versandkostenstaffelung Kommazahlen eingeben kann ist doch okay, genauso wie beim Gewicht eines Artikels.

> max="100" war von mir willkürlich gewählt, und könnte nach dieser Runde raus.

Okay, ~~mach ich.~~ erledigt (6cf801a).

> Entfernen kann/soll man mit dem Button.

Stimmt, den gibt's ja auch – upps! Was hältst du davon für die Lösch-Buttons (auch für Produkt löschen) `trash-o` zu verwenden?

> step="1" ganzzahlige Bestellmengen sind doch nun auch gut - oder?

Ja, auf jeden Fall!

**Comment by frase-git** [comment]
> Was hältst du davon für die Lösch-Buttons (auch für Produkt löschen) `trash-o` zu verwenden?

Da können wir jetzt tagelang streiten :confused:
Mir persönlich gefällt der Trash nicht - der fällt auch imAussehen ein bisschen aus den FA-Icons raus. Ich verwende da lieber konsequent `fa-remove`.
Lasse mich gerne überstimmen - mit mindestens 0.01 Stimmen mehr :wink:

**Comment by cmb69** [comment]
> Da können wir jetzt tagelang streiten

Nö – da gebe ich gerne klein bei. :)

**Comment by frase-git** [comment]
> Hm, um welche Felder geht es konkret?

Shop edit -> Versand -> Versandkostenberechnung nach

Und ich merke gerade, dass da kaum noch Textfelder da sind. Wie gesagt, dass erldigt sich wohl von selbst.

**Comment by cmb69** [comment]
> Shop edit -> Versand -> Versandkostenberechnung nach

Ah! Da wirkt das `step` aber sowieso nicht, weil es `type=text` ist. Und ja, ich denke das wandert sowieso bald in die Konfiguration.

Jedenfalls kann dieses Ticket wohl nun geschlossen werden.
