### ISSUE TITLE
dont deal with taxes: messages

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#43]
Wenn:
`$plugin_cf['xhshop']['taxes_dont_deal_with_taxes']="true";`
Dann erscheint in Step 3 trotzdem die MwSt. hinter den einzelnen Artikeln.

`$plugin_tx['xhshop']['hints_price_info_no_vat']="Endpreis.<br />USt wird nach &sect;&nbsp;19 UStG.<br>(Kleinunternehmerregelung)<br>nicht erhoben.";`
Diesen Text konnte ich (bei dieser Konstellation) überhaupt nicht finden.

**Comment by cmb69** [comment]
> Wenn:
$plugin_cf['xhshop']['taxes_dont_deal_with_taxes']="true";
Dann erscheint in Step 3 trotzdem die MwSt. hinter den einzelnen Artikeln.

Stimmt. Ausnahmsweise mal kein Refactoring-Bug – ist wohl "immer" schon so gewesen. :) Das Problem liegt [hier](https://github.com/cmsimple-xh/xhshop/blob/511f697243f3760013747f8429867a39930fd86e/templates/frontend/finalConfirmation.tpl#L41) – da braucht's noch ein `if`.

> $plugin_tx['xhshop']['hints_price_info_no_vat']="Endpreis.<br />USt wird nach &sect;&nbsp;19 UStG.<br>(Kleinunternehmerregelung)<br>nicht erhoben.";
Diesen Text konnte ich (bei dieser Konstellation) überhaupt nicht finden.

Das wird in den Artikeldetails angezeigt.

**Comment by frase-git** [comment]
> Ausnahmsweise mal kein Refactoring-Bug – ist wohl "immer" schon so gewesen. :) Das Problem liegt hier – da braucht's noch ein if.

Nein, das war nicht immer so. Die Anzeige der MwSt. an dieser Stelle stammt nämlich von einem gewissen "Herrn Frank", der das hätte wissen müssen ;-)

> Das wird in den Artikeldetails angezeigt.

Ja, und gewisser "Herr Frank" scheint auch noch blind zu sein ;-)
Aber: Sollte dieser Spruch nicht auch nochmal unter Step 3 stehen?
(Etwas versäubert.)

**Comment by cmb69** [comment]
> Nein, das war nicht immer so.

Also doch ein Refactoring-Bug. So ist das halt, wenn man ohne automatisierte Tests arbeitet. :)

> Aber: Sollte dieser Spruch nicht auch nochmal unter Step 3 stehen?

Schaden dürfte es nicht, und vielleicht ist es rechtlich sogar notwendig.

**Comment by frase-git** [comment]
> und vielleicht ist es rechtlich sogar notwendig.

Ich fürchte: Ja.

**Comment by frase-git** [comment]
Vorschlag für den Text (ohne die `<br>`s):

`$plugin_tx['xhshop']['hints_price_info_no_vat']="MwSt. wird nach &sect;&nbsp;19 UStG. nicht erhoben.";`

(Da ist der Konflikt: MwSt. und USt in einem Satz)

Dann wird noch eine Bedingung fällig (`if`) in `productDetails.tpl` Zeile 23: `%VATRATE% %`

**Comment by cmb69** [comment]
> Vorschlag für den Text (ohne die <br>s):

Gefällt mir – ich mag kein HTML-Markup in Sprachtexten.

> (Da ist der Konflikt: MwSt. und USt in einem Satz)

Ich habe das Umsatzsteuergesetzt nicht gelesen, aber ich kann mir gut vorstellen, dass dort auch der Begriff Mehrwertsteuer auftaucht.

> Dann wird noch eine Bedingung fällig (if) in productDetails.tpl Zeile 23: %VATRATE% %

Wieso? Wenn `taxes_dont_deal_with_taxes`aktiviert ist, wird der USt-Satz angezeigt, andernfalls eben `hints_price_info_no_vat`. Passt das nicht?

**Comment by frase-git** [comment]
![vat-info-screen](https://user-images.githubusercontent.com/24246330/27866115-69ba595c-6195-11e7-9236-523a062b5289.png)
Im Beispiel:
`$plugin_cf['xhshop']['taxes_dont_deal_with_taxes']="true";`
Also, wenn ich nicht mit taxes deale, dann sollte dort auch kein MwSt.-Satz (rot) stehen.
Verstehe ich da was falsch?

Kleine Nebensächlichkeit:
`$plugin_cf['xhshop']['taxes_dont_deal_with_taxes']="false";`
zeigt den Spruch trotzdem. Erst "" hilft.

**Comment by cmb69** [comment]
> Also, wenn ich nicht mit taxes deale, dann sollte dort auch kein MwSt.-Satz (rot) stehen.

Upps – natürlich hast du recht!

> Kleine Nebensächlichkeit:
$plugin_cf['xhshop']['taxes_dont_deal_with_taxes']="false";
zeigt den Spruch trotzdem. Erst "" hilft.

Das ist normal; eigentlich ist weder `true` noch `false` jemals sinnvoll gewesen, und `1` und `0` wären zumindest inzwischen die saubere Lösung, aber aus Gründen der Abwärtskompatibilität mit Plugins scheiben wir bei Booleschen Feldern halt `"true"` oder `""`.
