### ISSUE TITLE
Separate shop output from page content

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#47]
`.xhsLft` und `.xhsRght` floaten, und das passt nicht unbedingt gut für nachfolgenden Text:

![floating-buttons](https://user-images.githubusercontent.com/2306138/27889346-1f631d1a-61ec-11e7-897b-f3cab42f0da2.png)

Ich denke, hier fehlt ein `clear` oder ein [Block formatting context](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Block_formatting_context).

**Comment by frase-git** [comment]
> Ich denke, hier fehlt ein ...

rrrrrrrr

Änderungen Frontend:

---
`cart.tpl` neu ab Zeile 107 bis Ende ersetzen:
```php
<p>&nbsp;</p>
</section>
```
---
`customersData.tpl` neu ab Zeile 57 bis Ende ersetzen:
```php
<input type="hidden" name="xhsCheckout" value="checkCustomersData">
<button class="xhsShopButton xhsRght xhsInl"><?php $this->label('next'); ?> <span class="fa fa-arrow-circle-right fa-fw"></span></button>
</form>
<form action="" method="post">
<input type="hidden" name="xhsCheckout" value="cart">
<button class="xhsShopButton xhsInl"><span class="fa fa-arrow-circle-left fa-fw"></span> <?php $this->label('previous'); ?></button>
</form>
<p>&nbsp;</p>
</section>
```
---
`finalConfirmation.tpl` neu ab Zeile 94 bis Ende ersetzten:
```php
<form action="" method="post">
<input type="hidden" name="xhsCheckout" value="finish">
<button class="xhsShopButton xhsRght"><?php $this->label('send_order'); ?></button>
</form>
<form action="" method="post">
<input type="hidden" name="xhsCheckout" value="customersData">
<button class="xhsShopButton"><span class="fa fa-arrow-circle-left fa-fw"></span> <?php $this->label('previous'); ?></button>
</form>
<?php if($this->payment->orderSubmitForm() === false){ ?>
<?php
} else {
	echo $this->payment->orderSubmitForm();
} ?>
<p>&nbsp;</p>
</section>
```
---
`thankYou.tpl` nur zwei Zeilen am Ende anfügen:
```php
</section>
<p>&nbsp;</p>
```
---
`cosed.tpl` komplett neu:
```php
<div class="xhsClosed">
    <?php echo $this->hint('sorry_we_are_closed'); ?>
</div>
<p>&nbsp;</p>
```

---
Passt das so?
Ich merke gerade, da muss ich im Backend auch noch was machen.
Folgt später (evtl. mit Erinnerung durch dich/euch).

**Comment by frase-git** [comment]
Hier die Backend-Änderungen:

---
`productEdit.tpl` neu ab Zeile 58 bis Ende ersetzten:
```php
			<input type="hidden" name="xhsProductID" value="<?php echo $this->product_ID; ?>">
			<input type="hidden" name="xhsTaskCat" value="product_tasks">
			<input type="hidden" name="xhsTask" value="saveProduct">
			<button class="xhsShopButton xhsRght"><span class="fa fa-save fa-fw"></span> <?php $this->label('save_settings'); ?></button>
	</form>
	<p class="xhsClearB">&nbsp;</p>
</section>
```
---
`categories.tpl` neu ab Zeile 86 bis Ende ersetzten:
```php
	</form>
	<?php } ?>
	<p>&nbsp;</p>
</section>
```
---
`catalog.tpl` neu ab Zeile 79 bis Ende ersetzten:
```php
	<p>&nbsp;</p>
</section>
```

**Comment by cmb69** [comment]
Danke, Frank!

Das hat mich dazu gebracht mal den Warenkorb (erste Seite) validieren zu lassen: sieht nicht gut aus – ein solch lange Liste an Fehlern und Warnungen habe ich schon eine Weile nicht mehr gesehen.

**Comment by frase-git** [comment]
Hi ha ho!!!
Schön bunt!
Hast du die Demo validiert?
Egal - soweit war ich noch nicht.
Sieht nach Kleinigkeiten aus. Meist ein " in select und option, ein paar "alt" zu viel und ein paar "actions".
Das ist so, wenn man uralten Code übernimmt.
Ich mache neue Dateien - wenn/wann ich kann.
Bis dahin mal nichts mergen.

>  cmb69 closed this in 7c8d338 5 minutes ago

sorry

**Comment by cmb69** [comment]
> Ich mache neue Dateien - wenn/wann ich kann.
Bis dahin mal nichts mergen.

Ich bin schon dran; das sind weniger Probleme in den Templates, sondern diesen wird bereits fehlerhaftes HTML übergeben.

**Comment by cmb69** [comment]
> Ich bin schon dran;

Siehe PR #52.

> Das hat mich dazu gebracht mal den Warenkorb (erste Seite) validieren zu lassen

War allerdings gar nicht der Warenkorb, wegen der POSTerei. Das, und auch die leeren `action` Attribute muss an anderer Stelle gemacht werden.

**Comment by frase-git** [comment]
Danke.
Muss jetzt mal weg.

**Comment by frase-git** [comment]
Im neuen Maste a mini-Bug gefunden:
Datei `customersData.tpl` Zeile 57
```html
<div class="xhsRght">
```
... muss noch raus.

**Comment by cmb69** [comment]
Erledigt.

**Comment by frase-git** [comment]
Sorry, bin's schon wieder.
Der [Nu Checker](https://validator.w3.org/nu/?showoutline=yes&doc=http%3A%2F%2Ffhs.bplaced.net%2Fxhshop-demo%2F%3FShop) meckert im aktuellen Master immer noch überflüssige `action=""` an.
Habe ich da was falsch gemacht?

PS:
Könntet ihr mal 'ne Bestellung durchziehen mit Feedback wegen der Mail?

**Comment by cmb69** [comment]
> Der Nu Checker meckert im aktuellen Master immer noch überflüssige action="" an.

Ja, ich weiß. Ich dachte, das erledigt sich von selbst, wenn einige Formulare auf GET umgestellt werden, aber das ist natürlich Quatsch. Ich denke, das sauberste und CMSimple typischste ist dort $sn zu verwenden; schau ich mir an.

**Comment by frase-git** [comment]
Und jetzt noch ein Änderungswunsch - der sich gerade beim Testen ergeben hat:

In `xhs_frontend_controller.php` in Zeile 608 bitte 
`class="zoom"` ändern zu `class="zoom_g"`.
Begründung [siehe hier](http://fhs.bplaced.net/xhshop-demo/?Shop&xhsProduct=p595e69e48c4e4).

**Comment by cmb69** [comment]
> class="zoom" ändern zu class="zoom_g".

Erledigt (78a46e2)

**Comment by cmb69** [comment]
> Ich denke, das sauberste und CMSimple typischste ist dort $sn zu verwenden; 

Ist natürlich nicht ausreichend, um ein leeres action Attribut zu ersetzen. Bevor's in Aufwand ausartet, habe ich nun einfach die leeren action Attribute entfernt: 4d97ee1 und 6a088e9.

**Comment by frase-git** [comment]
Danke Christoph.
Hätte ich dir gerne abgenommen. Da warst du aber schneller. (Kann man denn hier nicht mal 'ne Pause machen? 😁 )
