### ISSUE TITLE
no-taxes info missing from emails and bill

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#48]
`$plugin_cf['xhshop']['taxes_dont_deal_with_taxes']="true";`
**Nur bei "true"**:
Ist die Bestellung abgeschlossen (Seite thank you) meldet debug:

> NOTICE: Undefined index: no_vat_bill
> ..\plugins\xhshop\classes\app\xhs_frontend_controller.php:474

**Comment by cmb69** [comment]
Da fehlt `$plugin_tx['xhshop']['hint_no_vat_bill']`. Ich habe mal nachgestöbert, und im Wellrad 1.2.1 ist es auskommentiert in der Sprachdatei (`langs/de.php`) – eventuell fehlen uns da noch weitere Sprachtexte.

**Comment by frase-git** [comment]
Wird denn das **nach Bestellabschluss** überhaupt benötigt?

**Comment by cmb69** [comment]
> Wird denn das nach Bestellabschluss überhaupt benötigt?

Es wird in der Rechnung (bill.rtf) verwendet; solange noch nicht klar ist, was damit passiert, sollte es besser korrigiert werden. Und ich frage mich, ob diese MWSt Hinweise nicht auch in der Bestellbestätigung auftauchen sollten/müssten. Jedenfalls lautete der Text "Alle Preise sind Endpreise. Die Umsatzsteuer wird gem. &sect; 19 UStG (Kleinunternehmerregelung) nicht erhoben." Da könnten wir allerdings auch [hints_price_info_no_vat](https://github.com/cmsimple-xh/xhshop/blob/25a330c1dd311e74a007bdd20962dc075b046d50/languages/de.php#L165) verwenden, wenn wir eine allgemeine Lösung für das `&nbsp;` finden.

Übrigens: bin zufällig auf `$plugin_tx['xhshop']['hints_no_vat_export_bill']="Ausfuhrumsatzsteuer: 0%"` das wohl gar nicht verwendet wird. Muss bezüglich dieser "Ausfuhrumsatzsteuer" was gemacht werden?

**Comment by frase-git** [comment]
> Und ich frage mich, ob diese MWSt Hinweise nicht auch in der Bestellbestätigung auftauchen sollten/müssten.

Oh ja, das vermute ich stark.

> Da könnten wir allerdings auch hints_price_info_no_vat verwenden, wenn wir eine allgemeine Lösung für das `&nbsp;` finden.

Da wäre ich sehr dafür.
Ich vermute, dass du das `&nbsp;` eingefügt hast, um Trennung zu vermeiden.
Der Satz ist jetzt so schön kurz und knackig - der wird praktisch nie zu lang. Und wenn - auch egal.

> Muss bezüglich dieser "Ausfuhrumsatzsteuer" was gemacht werden?

Ich denke: löschen.
@XHalbert ?

**Comment by cmb69** [comment]
> Ich vermute, dass du das `&nbsp;` eingefügt hast, um Trennung zu vermeiden.

Es war schon vorher da, aber ich habe es eben deshalb gelassen.

> Der Satz ist jetzt so schön kurz und knackig - der wird praktisch nie zu lang. Und wenn - auch egal.

Ja, hast recht.

**Comment by cmb69** [comment]
> Muss bezüglich dieser "Ausfuhrumsatzsteuer" was gemacht werden?

Da gibt es ebenfalls [hints_no_vat_export](https://github.com/cmsimple-xh/xhshop/blob/25a330c1dd311e74a007bdd20962dc075b046d50/languages/de.php#L166), das auch nicht verwendet wird. Wenn ich mir den Text anschaue, könnte ich heulen.

**Comment by cmb69** [comment]
Die Diskussion um die Ausfuhrumsatzsteuer habe ich nach #51 verlegt.

Dieses Ticket kann nun geschlossen werden (b1226a2).
