### ISSUE TITLE
help files

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#49]
Ich werde wohl die Help-Files basteln - so nach und nach.
Damit ich nicht in die ganz falsche Richtung laufe, bitte ich euch, von Zeit zu Zeit mal [hier zu schauen](http://fhs.bplaced.net/xhshop-demo/plugins/xhshop/help/help_de.htm).
Falls euch etwas auffällt, was nicht stimmt, oder nicht geht, dann bitte melden.
Achtung: Jetzt und in den nächsten Tagen müsst ihr noch **nicht lesen**, sondern **nur gucken**!
Der Inhalt ist nämlich noch Dummy!

**Comment by frase-git** [comment]
[xhshop-help2.zip](https://github.com/cmsimple-xh/xhshop/files/1132981/xhshop-help2.zip)

Ich denke mal, das mit den help-files besprechen wir hier weiter.
Da Christoph gerade gemerged hat, ist das ein bisschen bedauerlich.
Ich habe nämlich in den letzten Tagen weiter gebastelt.
Und ich bin immer noch nicht fertig.

Die Dateien (im ZIP) sind aber etwas aktueller. CSS weiter verallgemeinert (nur sans-serif als Schriftart).
Navigation zugefügt.

Was ich festgestellt habe:
Den ganzen Kram, mit Cart-Button, Toc und ... kann man einfach nicht sinnvoll in **einer** Hilfedatei unterbringen. Deshalb habe ich mich entschlossen, extrem zu kürzen. Es sind nur noch allgemeine Hinweise drin, um zu installieren und loszulegen.
Im Abschnitt "Weitere Hilfe" möchte ich dann erläutern, wo es mehr Hilfe und Anleitung gibt.
- evt. eine Demo-Seite mit allen Erklärungen (wo, wer?)
- evtl. nur eine Demoseite
- evtl. Wiki hier. Da tu ich mich schwer - kann ich noch nicht. Diese Lösung wäre allerdings sicher die beste, da zukunftssicher
- evtl. Wiki hier plus Demoseite

**Comment by cmb69** [comment]
> Da Christoph gerade gemerged hat, ist das ein bisschen bedauerlich.
Ich habe nämlich in den letzten Tagen weiter gebastelt.
Und ich bin immer noch nicht fertig.

Ist doch kein Problem. Das kann alles nach und nach verbessert werden – wichtig ist mir halt die alte Menüführung so schnell wie möglichst auszudünnen, damit auf eine CMSimple_XH typischere umgestellt werden kann.

> Die Dateien (im ZIP) sind aber etwas aktueller. CSS weiter verallgemeinert (nur sans-serif als Schriftart).
Navigation zugefügt.

Danke. Eingespielt (3d89897).

> evtl. Wiki hier. Da tu ich mich schwer - kann ich noch nicht. Diese Lösung wäre allerdings sicher die beste, da zukunftssicher

Ich denke auch, dass das eine gute Lösung wäre. Selbst wenn es eine Demo-Site gäbe, dann wäre dort die Zusammenarbeit nicht einfach (halt CMSimple). Und kompliziert scheint das nicht wirklich zu sein: ich habe mal schnell zwei Seiten zur Testzwecken erstellt, und von der Homepage auf die zweite Seite verlinkt. Zu beachten ist, dass das Github-Wiki verschiedene Markupsprachen anbietet – ich würde der Einfachheit halber bei Markdown bleiben – also das was auch in den Comments hier verwendet wird.

Ansonsten gibt es auch ausführliche [Hilfe zu Github-Wikis](https://help.github.com/categories/wiki/).

**Comment by frase-git** [comment]
https://github.com/cmsimple-xh/xhshop/wiki

**Comment by frase-git** [comment]
[xhshop-help-rc1.zip](https://github.com/cmsimple-xh/xhshop/files/1133651/xhshop-help-rc1.zip)

Das wäre jetzt mein Kandidat für eine erste Version.
Die englische Version ist noch deutsch ;-) - muss noch übersetzt werden.
Dank an Martin ist drin. Unklar, wohin der Link führen soll. Habe zeichenkombinat genommen.
Link zum Wiki ist drin.
Lizenz ist drin.

Bitte mal gegenlesen.
Funktion der Nav in verschiedenen Browsern und Viewports testen.

**Comment by XHalbert** [comment]
wow sehr gute Arbeit.

eine Kleinigkeit ist mir aufgefallen

> Einen Shop eröffnen
Erstelle zunächst mit dem Pagemanager (Adminmenü ⇒ Seiten) eine neue Seite für deinen Shop. Der „normale“ Aufruf für den XH-Shop lautet:

Ich würde ergänzen:
**Logge dich in CMSimple_XH ein und** erstelle mit dem Pagemanager (Adminmenü ⇒ Seiten) eine neue Seite, **die du z.B. "Shop" nennen kannst**
(ich weiß noch, wie unsicher ich damals war... sowas kann helfen, auch wenn andere das vllt. überflüssig finden)

**Comment by cmb69** [comment]
> Das wäre jetzt mein Kandidat für eine erste Version.

Sehr gelungen! Danke!

> Die englische Version ist noch deutsch ;-) - muss noch übersetzt werden.

Ich schau mal…

> Dank an Martin ist drin. Unklar, wohin der Link führen soll. Habe zeichenkombinat genommen.

Ich denke, das passt.

> neue Seite, die du z.B. "Shop" nennen kannst

Ich denke, der Hinweis, dass die Seite Shop heißen soll, ist gut – andernfalls muss ja der Seitenname in den Spracheinstellungen geändert werden.

**Comment by frase-git** [comment]
Neue Datei?

**Comment by cmb69** [comment]
> Neue Datei?

Was auch immer für dich einfacher ist. :)

**Comment by frase-git** [comment]
[xhshop-help-03.zip](https://github.com/cmsimple-xh/xhshop/files/1133743/xhshop-help-03.zip)
Mit englisch, geänderter CSS aber wenigstens ohne Bild. ;-)

**Comment by cmb69** [comment]
Eingespielt (9e47005).

Ich weise das Ticket mal mir zu, damit ich an die englische Übersetzung denke.

**Comment by cmb69** [comment]
> Ich weise das Ticket mal mir zu, damit ich an die englische Übersetzung denke.

Aus Zeitgründen ganz pragmatisch Open-Source-Like: 37b9603 und #97.
