### ISSUE TITLE
Add customer name to subject of confirmation mail

### ISSUE THREAD

**Issue by XHalbert** [cmsimple-xh/xhshop#5]
Betreff: Ihre Bestellung - Vorname Nachname  - XH-Shop DEMO

**Comment by frase-git** [comment]
Wärest du auch zufrieden, mit:
"Ihre Bestellung bei XH-Shop DEMO"
also ohne Namen?
Im Text steht ja dann die personalisierte Anrede mit Namen.
Dann müsste man nur die de.php (en.php) ändern.
Oder weißt du auf die Schnelle, wo man den Namen einfügen muss? (xhs_frontend_controller.php?)

**Comment by XHalbert** [comment]
Wo würde man denn jetzt Code eintragen?

in lang/de.php
$lang['mail']['notify'] = "Ihre Bestellung bei... - %s";

dazu frontendcontroller in function sendEmails($bill)

// pesonalisierter Betreff
		//  statt bisher      $mail->Subject = $this->viewProvider->mail['notify'];
$mail->Subject = sprintf($this->viewProvider->mail['notify'], $customerName );

**Comment by cmb69** [comment]
> Betreff: Ihre Bestellung - Vorname Nachname - XH-Shop DEMO

Hm, der Name ist doch schon als Empfänger der Mail gesetzt, und sollte auch vom E-Mail-Client entsprechend angezeigt werden.

**Comment by XHalbert** [comment]
eben nicht...
![neu-2](https://user-images.githubusercontent.com/29812782/27761857-8a88af7c-5e65-11e7-8c75-25fb06c9bb5e.JPG)
Ich bin Empfänger und Absender
Der Kunde steht nur in der Mail selber

**Comment by cmb69** [comment]
Ah, es geht um die E-Mail an den Shopbetreiber! Die finde ich aber sowieso fraglich, weil dort ebenfalls der Kunde angesprochen wird, und nicht der Betreiber. Zumindest den Anfang dieser Mail sollte man anders formulieren. Schön wäre es, wenn bei dieser Mail der Kunde als Absender fungiert, aber diese Mails gehen nicht bei allen Providern durch, was hier natürlich fatal wäre. Von daher wäre es vielleicht sinnvoll den Namen im Betreff mit anzugeben, und vielleicht auch als Reply-To zu setzen (falls der Shopbetreiber direkt nachfragen will). Bin aber nicht ganz sicher, ob es mit Reply-To nicht auch wieder Probleme geben kann.

**Comment by frase-git** [comment]
![mail-shop](https://user-images.githubusercontent.com/24246330/27761905-c3b5a4e8-5e66-11e7-94ac-c402ed310950.png)
Auch mit der vorgeschlagenen Code-Änderung steht bei mir im Betreff kein Name.

**Comment by cmb69** [comment]
> Auch mit der vorgeschlagenen Code-Änderung steht bei mir im Betreff kein Name.

Hast du auch `$lang['mail']['notify'] = "Ihre Bestellung bei... - %s";` entsprechend angepasst?

Ich würde es aber wohl eher so formulieren: "Bestellung von %s bei XH-Shop DEMO".

**Comment by frase-git** [comment]
Geht ja ganz schön durcheinander hier.

in de.php:
```
$lang['mail']['email_subject']='Ihre Bestellung bei ';
$lang['mail']['notify'] = "Bestellung von %s bei XH-Shop DEMO eingegangen!";
```
in xhs_frontend_controller.php:
```
//$mail->Subject = $this->viewProvider->mail['notify'];
$mail->Subject = sprintf($this->viewProvider->mail['notify'], $customerName );
```
Ergibt:
![mail-shop3](https://user-images.githubusercontent.com/24246330/27762235-6729c738-5e6e-11e7-82de-b3e311b03db9.png)

Sieht schon ganz gut aus.
Der Betreiber sieht von WEM und kann auch später danach suchen.
Der Kunde braucht seinen Namen nicht im Betreff.

**Comment by cmb69** [comment]
> `$lang['mail']['notify'] = "Bestellung von %s bei XH-Shop DEMO eingegangen!";`

Hier könnte der Name des Shops zwecks Vermeidung von Duplikation auch aus den Shop-Settings geholt werden, also
````
$lang['mail']['notify'] = "Bestellung von %1\$s bei %2\$s eingegangen!";
````
und
````
$mail->Subject = sprintf($this->viewProvider->mail['notify'], $customerName, $this->settings['company_name']);
````

**Comment by frase-git** [comment]
> Hier könnte der Name des Shops zwecks Vermeidung von Duplikation auch aus den Shop-Settings geholt werden, also ...

Beide Änderungen passen hervorragend und funktionieren auch in meiner Demo.

**Comment by cmb69** [comment]
> Beide Änderungen passen hervorragend und funktionieren auch in meiner Demo.

Fein. Welche Variante nehmen wir nun? @XHalbert ?

**Comment by frase-git** [comment]
Albert, als der Erfahrenere, sollte hier schon mitreden.
Hartmut evtl. auch?

**Comment by XHalbert** [comment]
> $lang['mail']['notify'] = "Bestellung von %1\$s bei %2\$s eingegangen!";

find ich klasse

> Der Kunde braucht seinen Namen nicht im Betreff

aber wenn er seinen Namen sieht, weiß er dass es kein Spam ist -
In der Mail an den Kunden: der Name ist mir aber eigentlich egal, Hauptsache welcher Shop steht drin

**Comment by cmb69** [comment]
> aber wenn er seinen Namen sieht, weiß er dass es kein Spam ist -

Nur mal **ein** Beispiel-Betreff aus meinem Papierkorb:
````
Christoph, beginne 2017 mit deinem Gratistipp für 23 Millionen Euro
````

**Comment by XHalbert** [comment]
ok ok
also mail an Schopbetreiber: Vorname, Name und Shopname
an Kunde: Shopname

**Comment by cmb69** [comment]
Dann mach ich das mal so. :)

**Comment by frase-git** [comment]
>  cmb69 added this to the 1.0alpha1 milestone

Da hätte ich mal eine Frage:
Könnten wir solche Sachen nicht gleich in den aktuellen Master übernehmen?
Ich möchte nämlich die Online-Demo auch gleich zum Testen nutzen. Da wäre es schön, wenn da beschlossene Sachen schon drin wären. Wenn ich das händisch einfüge, ist es bei der nächste Master-Änderung wieder weg.
Ab alpha1 können wir ja dann den "normalen" Weg gehen.

**Comment by cmb69** [comment]
> Könnten wir solche Sachen nicht gleich in den aktuellen Master übernehmen?

Das ist schon im master (siehe b074574). Den Milestone setze ich, damit man auch gleich ein Changelog über relevante Änderungen hat, siehe https://github.com/cmsimple-xh/xhshop/milestone/1?closed=1.

**Comment by frase-git** [comment]
> Das ist schon im master (siehe b074574).

Wahrscheinlich bin ich blind.
[Hier](https://github.com/cmsimple-xh/xhshop/blob/master/languages/de.php) zm Beispiel, finde ich es nicht :(

**Comment by cmb69** [comment]
> Hier zm Beispiel, finde ich es nicht :(

Du hast recht! Der Commit hatte langs/de.php geändert, aber bei der Umstellung auf languages/de.php ist das vergessen worden. Ich schau mir's an.

**Comment by cmb69** [comment]
So, müsste nun passen. @frase-git Bitte gegenprüfen.

**Comment by frase-git** [comment]
Sollte [das](https://github.com/cmsimple-xh/xhshop/blob/master/languages/de.php#L7) nicht heißen:
`Ihre Bestellung bei`(Leerzeichen)

**Comment by cmb69** [comment]
> Ihre Bestellung bei(Leerzeichen)

War mir auch schon aufgefallen. Vielleicht sollte es aber besser [hier](https://github.com/cmsimple-xh/xhshop/blob/9e4139572034577ad6c5687e8d6d3108f5631fe1/classes/app/xhs_frontend_controller.php#L526) korrigiert werden? Oder auch wieder mit `sprintf()`, und dann in der Sprachdatei "%1\$s – %2\$s"?

**Comment by frase-git** [comment]
> War mir auch schon aufgefallen. Vielleicht sollte es aber besser [hier](https://github.com/cmsimple-xh/xhshop/blob/9e4139572034577ad6c5687e8d6d3108f5631fe1/classes/app/xhs_frontend_controller.php#L526) korrigiert werden? Oder auch wieder mit sprintf(), und dann in der Sprachdatei "%1$s – %2$s"?

Na, auf jeden Fall müssen beide "-" weg.
Am Ende soll der Betreff heißen:
"Ihre Bestellung bei [Firma/Shopname]" (ohne Klammern)
`%1$s – %2$s` - was kommt denn dabei raus?

**Comment by cmb69** [comment]
> "Ihre Bestellung bei [Firma/Shopname]" (ohne Klammern)

Ja, hast eigentlich recht. Dann macht man es am besten so:
````
sprintf($this->viewProvider->mail['email_subject'], $this->settings['company_name']);
````
Und in de.php:
````
$plugin_tx['xhshop']['mail_email_subject']='Ihre Bestellung bei %s';
````

**Comment by frase-git** [comment]
> Dann macht man es am besten so:

Könntest du "man" übernehmen? :smirk:

**Comment by cmb69** [comment]
Jupp: 3b41755.
