### ISSUE TITLE
Add to cart behavior is unintuitive

### ISSUE THREAD

**Issue by XHalbert** [cmsimple-xh/xhshop#50]
es tauchte ja schon mal die Frage auf, warum wellrad es ignoriert, wenn jemand denselben Artikel ein zweites Mal in den Warenkorb legen will.
Das ist Absicht und soll versehentliches Doppelbestellen vermeiden. Tut es auch und finde ich sinnvoll. 
Einen weitenen Artikel mit einer anderen Variante nimmt er ja. 

Aber das stillschweigende Ignorieren eines identischen Artikels führt zu Verwirrung.

Wäre es nicht besser, eine Abfrage einzuführen, etwa: 
"Der Artikel befindet sich schon im Warenkorb. Wollen Sie einen weiteren bestellen. Ja? - Nein?

PS: muss nicht in vers. 1

**Comment by cmb69** [comment]
> Aber das stillschweigende Ignorieren eines identischen Artikels führt zu Verwirrung.

Zur Klärung: immer das letzte "in den Warenkorb" gewinnt.

> Wäre es nicht besser, eine Abfrage einzuführen, etwa:
"Der Artikel befindet sich schon im Warenkorb. Wollen Sie einen weiteren bestellen. Ja? - Nein?

Wie handhaben das andere Shopsysteme?

**Comment by frase-git** [comment]
Meine Denke:
Lassen, wie es ist.

**Comment by XHalbert** [comment]
> Zur Klärung: immer das letzte "in den Warenkorb" gewinnt.

du meinst programmiertechnisch. Aber da beide identisch heißen, merkt man es nicht.

> frase-git: Lassen, wie es ist.

ok kann man mit leben
finde mit Abfrage wäre benutzerfreundlicher

**Comment by cmb69** [comment]
> du meinst programmiertechnisch. Aber da beide identisch heißen, merkt man es nicht.

Kommt auf die Anzahl an. Lege ich erst 1 bestimmten Artikel in den Warenkorb, und dann 2 Stück vom selben, dann werden im Warenkorb 2 angezeigt. Legt man erst zwei und dann einen Artikel in den Warenkorb, dann wird dort 1 angezeigt.

> finde mit Abfrage wäre benutzerfreundlicher

Da stimme ich zu. Das ist aber wohl leider nicht einfach umzusetzen – ich denke eher etwas für eine spätere Version. Ich setze den Milestone für diesen Feature-Request mal auf `2.0` – bitte ändern, falls das nicht so sein sollte.

**Comment by XHalbert** [comment]
> Kommt auf die Anzahl an.

sehr clever, wusst ich noch nicht

> für eine spätere Version

gut

**Comment by cmb69** [comment]
Hat sich diese Anfrage durch 5dd2060 erledigt?

**Comment by frase-git** [comment]
Von meiner Seite: JA.

**Comment by cmb69** [comment]
Okay, closed in 5dd2060.
