### ISSUE TITLE
variants in catalog.php - blanks

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#56]
`$products['p595e69e48c4e4']['variants']['de'] = array('neutral', '--------rot', '--------grün', '--------blau', );`
Die "-" habe ich als Ersatz für"Leerzeichen" hier zur Darstellung eingefügt.
Bei jedem Speichern kommt ein Blank hinzu. Nicht bei der **ersten** Variante.
Sichtbar wird das eigentlich nur bei "Produkt bearbeiten".

**Comment by XHalbert** [comment]
> Bei jedem Speichern kommt ein Blank hinzu

hab mich oft gefragt, wo immer die Leerzeichen herkommen, und dann auch noch unterschiedlich viele

**Comment by cmb69** [comment]
> Bei jedem Speichern kommt ein Blank hinzu. Nicht bei der ersten Variante.
Sichtbar wird das eigentlich nur bei "Produkt bearbeiten".

Stimmt. Das Problem ist, dass für das Varianteneingabefeld *zwischen* den Varianten `;_` (Leerzeichen statt Unterstrich) eingefügt wird. Das zusätzliche Leerzeichen wird beim Speichern aber einfach mit abgespeichert.
