### ISSUE TITLE
Require explicit configuration of shop page

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#58]
Szenario:
Habe einen zweiten Shop in einer Installation angelegt.
D.h., einfach neue Seite angelegt, `<div>{{{display_shop();}}}</div>` in den Quellcode geschrieben, gespeichert. Shop wird problemlos angezeigt.
Da das natürlich Quatsch ist, habe ich diese (neue) Seite wieder gelöscht.
Noch im Pagemanager habe ich F5/reload gemacht, damit die gelöschte Seite aus dem Menü verschwindet.
Plötzlich meldet der Herr Debug:

> XH-NOTICE: XHS_CMSimple_Bridge::getHeadingOfUrl($url) - xxx does not exist.
> ..\plugins\xhshop\XHS_CMS_Bridge.php:38

"xxx" ist der Seitenname der gelöschten Seite.
Man kann jetzt im Pagemanager (ohne die Seite zu verlassen) machen was man will - neue Seiten anlegen, löschen ... - die Debug-Meldung bleibt.
Erst, wenn man mal den PM verlässst, geht's weg.

**Comment by XHalbert** [comment]
> Da das natürlich Quatsch ist, 

hat mich aber an eine alte Idee von mir erinnert... siehe #59

**Comment by cmb69** [comment]
> Erst, wenn man mal den PM verlässst, geht's weg.

Mir ist etwas in dieser Richtung auch schon aufgefallen; ich habe nämlich den Aufruf des Shops auf der Seite "Languages", und wenn ich master auschecke, dann geht im Frontend erst mal gar nichts. Erst nach dem Login kann der Shop genutzt werden. Offensichtlich macht der Shop automatisch Änderungen an `shopsettings.php` – vielleicht sollten wir diesen Automatismus entfernen, und es dem Shopbetreiber überlassen, das entsprechend zu konfigurieren.
