### ISSUE TITLE
Shop-Aufruf nur einzelne Kategorie

### ISSUE THREAD

**Issue by XHalbert** [cmsimple-xh/xhshop#59]
soweit ich weiß kann man nur einen Shop pro CMS-Installation haben.

Bei einem großen Sammelsurium an unterschiedlichsten Artikeln wäre es vielleicht sinnvoll, quasi mehrere Teilshops zu haben, aber nur einen Shop pflegen zu müssen.

ist es möglich oder machbar, bei nur einem Shop verschiedene Shop-Aufrufe zu machen, wobei dann nur eine bestimmte Kategorie (oder mehrere) so im Shop erscheinen, als wenn es nur diese geben würde? Und natürlich auch nur die dazugehörigen Artikel angezeigt werden.

Was als link geht (...?Shop&wrsCategory=...) ist was anderes, weil hier zwar die verlinkte Kategorie ausgewählt wird, aber alle anderen Kategorien auch vorhanden sind und in der Shop-toc angezeigt werden.

**Comment by cmb69** [comment]
> ist es möglich oder machbar, bei nur einem Shop verschiedene Shop-Aufrufe zu machen, wobei dann nur eine bestimmte Kategorie (oder mehrere) so im Shop erscheinen, als wenn es nur diese geben würde? Und natürlich auch nur die dazugehörigen Artikel angezeigt werden.

Ich denke, das passt nicht, weil es eben letztlich nur einen Shop mit einem gemeinsamen Warenkorb gibt.

> Was als link geht (...?Shop&wrsCategory=...) ist was anderes, weil hier zwar die verlinkte Kategorie ausgewählt wird, aber alle anderen Kategorien auch vorhanden sind und in der Shop-toc angezeigt werden.

Hier sehe ich das Ausblenden der Shop-TOC bzw. des Kategorie-Select eher als eine Annehmlichkeit für den potentiellen Kunden. So gesehen könnte man das auch per CSS machen. Tipp fürs Wiki?

**Comment by cmb69** [comment]
> Bei einem großen Sammelsurium an unterschiedlichsten Artikeln wäre es vielleicht sinnvoll, quasi mehrere Teilshops zu haben, aber nur einen Shop pflegen zu müssen.

Wenn ich darüber nachdenke, dann fände ich das eigentlich keine wirkliche Hilfe. Ob man nun auf verschiedenen Seiten jeweils eine Kategorie darstellt, oder den User auf einer Seite eine Kategorieauswahl bietet, nimmt sich eigentlich nichts.

Bei einer größeren Artikelauswahl (die letztlich durch die Art der Datenhaltung sowieso beschränkt ist), halte ich die Suchfunktion sowieso für sinnvoller. Die ist derzeit ein bisschen Schwach, aber vielleicht hilft eine Google-Sitesearch. Vielleicht kann später auch mal die eingebaute Suchfunktion verbessert werden.

Ansonsten wären vielleicht auch Verlinkungen zu ähnlichen Artikeln sinnvoll; evtl. auch ein "Kunden, die diesen Artikel gekauft haben, kauften auch …"

Diese Anfrage würde ich als WONTFIX schließen.

**Comment by XHalbert** [comment]
> WONTFIX 

einverstanden
