### ISSUE TITLE
CMSimple_XH native Internationalisierung

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#6]
Derzeit wird die Lokalisierung über Dateien in `langs/` durchgeführt, die zwar ein sehr ähnliches Format wie die nativen CMSimple_XH Lokalisierungsdateien in `languages/` haben, aber eben ein bisschen anders sind. Außer wenn der Shop auch unter anderen Systemen funktionieren soll (was ich für irrelevant halte), dann wäre es sinnvoll auf native CMSimple_XH Lokalisierung umzustellen, was den Vorteil hätte, dass mit wenigen Zeilen Code die Bearbeitung der Sprachtexte im Back-End ermöglicht werden könnte.

**Comment by cmb69** [comment]
PR #7 setzt das um.

**Comment by XHalbert** [comment]
> Außer wenn der Shop auch unter anderen Systemen funktionieren soll 

denke da gibt es noch viel mehr Sachen, die so sind, weil Martin wellrad für verschiedene CMS tauglich halten wollte...

**Comment by cmb69** [comment]
> denke da gibt es noch viel mehr Sachen, die so sind, weil Martin wellrad für verschiedene CMS tauglich halten wollte...

Ich werte das mal als Zustimmung, und werde PR #7 mergen.
