### ISSUE TITLE
Negative billing amounts are possible

### ISSUE THREAD

**Issue by XHalbert** [cmsimple-xh/xhshop#60]
wenn man für 1,- einkauft (keine Mindestbestellmenge) und Nachlass 3,- ist, wird der Kaufpreis negativ. Martin hatte da eine Sperre drin, die ist wohl rausgeflogen?

Bez. mit paypal - 3. Schritt 
- rechts unten: "Jetzt kaufen" ergibt Fehlermeldung
- links unten: "mit paypal bez." 
... ist das Absicht so ?

**Comment by frase-git** [comment]
> Martin hatte da eine Sperre drin, die ist wohl rausgeflogen?

Tja, keine Ahnung - sollte wohl eine da sein.

> ... ist das Absicht so ?

Garantiert nicht.
Ich schau mal, ob ich was finden kann.

**Comment by frase-git** [comment]
[finalConfirmation.zip](https://github.com/cmsimple-xh/xhshop/files/1131733/finalConfirmation.zip)

Kannste mal mit dieser Datei testen?
Gehört in:
\plugins\xhshop\templates\frontend\

**Comment by cmb69** [comment]
> wenn man für 1,- einkauft (keine Mindestbestellmenge) und Nachlass 3,- ist, wird der Kaufpreis negativ. Martin hatte da eine Sperre drin, die ist wohl rausgeflogen?

Was meinst du mit Sperre? Sollte die Rechnungssumme nicht einfach niemals negativ sein (sprich in diesem Fall halt 0)?

Letztlich halte ich einen so konfigurierten Shop aber für fehlkonfiguriert. Man sollte schon drauf achten, dass man nicht mehr Nachlass gewährt, als den Mindestbestellwert.

> rechts unten: "Jetzt kaufen" ergibt Fehlermeldung
links unten: "mit paypal bez."
... ist das Absicht so ?

Da stimmt was überhaupt nicht. Ich habe auf "jetzt kaufen" geklickt, und dann kommt prompt die Dankeschön-Seite inklusive Bestellbestätigung – ohne irgendwas bei Paypal gemacht zu haben. Müsste bei Paypal-Zahlungen "jetzt kaufen" nicht ausgeblendet sein, so dass man "mit Paypal bezahlen" klickt?

**Comment by frase-git** [comment]
> Da stimmt was überhaupt nicht.

Hast du mit meiner "neuen" Datei getestet?

**Comment by cmb69** [comment]
> Hast du mit meiner "neuen" Datei getestet?

Ah, das sieht besser aus! Gleich eingespielt (b45010c).

Das Problem mit der negativen Rechnungssumme schau ich mir an.

**Comment by frase-git** [comment]
Ich fürchte, da ist einiges passiert, als ich dir Code hier bei den Issues geliefert habe.
In Zukunft werde ich wohl lieber "ganze" Dateien schicken.

Übrigens sollten wir vielleich warten, bis Albert getestet hat?

**Comment by XHalbert** [comment]
> Man sollte schon drauf achten, dass man nicht mehr Nachlass gewährt, als den Mindestbestellwert.

man kann Mindestwert 0 haben (ich z.B.)

**Comment by XHalbert** [comment]
neu getestet, echter paypal Kauf, schön: "mit Paypal bezahlen" steht rechts unten, statt "Jetzt kaufen"

PS: das paypal-Problem ist weiterhin: kein ThankYou, Warenkorb voll. Nach aktualisieren: kommt ThankYou, Warenkorb bleibt, auf Warenkorb geklickt: Warenkorb verschwindet

**Comment by frase-git** [comment]
@XHalbert 
Klappt das denn jetzt mit dem Paypal-Button?

**Comment by XHalbert** [comment]
> Martin hatte da eine Sperre drin

ups stimmt nicht, dachte ich nur

man kann Mindestwert 0 haben (ich z.B.)
Ja, aber normal habe ich das 1ct-Testprodukt "nicht lieferbar" und das billigste Produkt kostet mehr als der Nachlass, also taucht diese Sache normal nicht auf.

Kann so bleiben

**Comment by cmb69** [comment]
> man kann Mindestwert 0 haben (ich z.B.)
Ja, aber normal habe ich das 1ct-Testprodukt "nicht lieferbar" und das billigste Produkt kostet mehr als der Nachlass, also taucht diese Sache normal nicht auf.

Man kann es auch sehen, dass der Mindestbestellwert eigentlich immer wenigstens der Preis des billigsten Produkts im Shop ist (man muss ja wenigstens eins bestellen), und man sollte halte keinen höheren Nachlass definieren – in der Praxis sollte der Höchstnachlass immer (deutlich) kleiner sein als der Mindestbestellwert/das billigste Produkt; ansonsten zahlt man doch drauf. Das derzeitige Verhalten könnte leicht angepasst werden (Nachlass wird so reduziert, dass die Rechnungssumme nie kleiner 0 ist), aber dann gibt es die Inkonsitenz, dass auf Seite 2 ein Nachlass genannt wird, der auf Seite 3 plötzlich kleiner ausfällt. Ich würde das so lassen, und das Zusammenspiel, wenn überhaupt, dokumentieren. 

Jedenfalls ist das hier behandelte Paypal-Problem vom Tisch, und als zwischenzeitlich Regression braucht es auch keinen eigenen Changelog-Eintrag. Daher ändere ich mal den Ticket-Titel und stufe es als Dokumentationsproblem ein – ein WONTFIX soll mir aber auch recht sein.

**Comment by frase-git** [comment]
Ich muss euch nochmals bitten meine Textfabkrikate zu prüfen.
Zu diesem Thema habe ich ~~[was in's Wiki](https://github.com/cmsimple-xh/xhshop/wiki/80-%E2%80%93-Tipps#nachl%C3%A4sse-rabatte--und-mindestbestellwert)~~ geschrieben.
Stimmt das so?
Edit:
neuer [Link](https://github.com/cmsimple-xh/xhshop/wiki/Tipps#nachl%C3%A4sse-rabatte--und-mindestbestellwert)

**Comment by cmb69** [comment]
> Stimmt das so?

Im Prinzip schon. Aber "dass die Summe aller gewährten Nachlässe nicht größer werden kann" finde ich etwas unglücklich formuliert. Vielleicht besser "dass der Bestellwert durch die aufsummierten Nachlässe niemals 0 oder gar kleiner werden kann"?
