### ISSUE TITLE
cart button missing on start page

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#61]
vergl. Demo:

Produkt in Warenkorb.
Cart Button erscheint auf allen CMS-Seiten.
Klick auf das XH im Header -> Startseite erscheint - aber ohne Cart Button ???

**Comment by XHalbert** [comment]
bei mir ist der Cart Preview auch auf der Srartseite

**Comment by frase-git** [comment]
http://test-natu-1-7.natur-und-handgemacht.de/
Lege mal etwas in den Korb und rufe dann **genau** diese Adresse wieder auf - also ohne ?Shop oder sonstiges mit Fragezeichen.

**Comment by XHalbert** [comment]
ja stimmt hab ich auch (ich hatte vorher auf "home" geklickt)
Ist das das "Seite Null" Problem. Ich hatte mal im Forum wegen http://www.stillkissen-shop.de/ angefragt. Da wurde der AddToCartButton nicht angezeigt auf der Startseite, zumindest nicht beim ersten Aufruf.

Kein Cart auf Startseite finde ich aber nicht schlimm

**Comment by cmb69** [comment]
> Ist das das "Seite Null" Problem.

Ja, genau. Wenn der Shop die Ausgabe des Cart-Button auf der Startseite nicht explizit unterdrücken würde, dann würde CMSimple(_XH) den Inhalt der Startseite nicht anzeigen.

Ich denke, es genügt, wenn das in der Hilfe kurz erwähnt wird, wo auch das manuelle Platzieren des Cart-Buttons im Template erklärt wird, was ich bei einem richtigen Shop sowieso machen würde.

**Comment by frase-git** [comment]
erledigt [im Wiki](https://github.com/cmsimple-xh/xhshop/wiki/Bekannte-Probleme#startseite-ohne-warenkorb-button)
