### ISSUE TITLE
Inconsistency regarding shipping units

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#62]
In den Versandkosten-Einstellungen kann die Versandkosteneinheit gewählt werden (z.B. `kg`). Dies wird sprachspezifisch in `shopsettings.php` gespeichert. Für ein Produkt kann die Menge dieser Einheit aber *nicht* sprachspezifisch eingestellt werden. Wählt man also unterschiedliche Versandkosteneinheiten für verschiedene Sprachen (z.B. `kg` für `de` und `lb` für `en`), so gibt es Durcheinander (wiegt die Milch nun 1 kg oder 1 lb?)

Entweder wird die Menge der Versandkosteneinheit für jedes Produkt sprachspezifisch gespeichert, oder die Versandkosteneinheit kann nicht mehr sprachspezifisch eingestellt werden. Letzteres macht es für alle Beteiligten einfacher, denke ich. Oder übersehe ich etwas?

**Comment by frase-git** [comment]
> oder die Versandkosteneinheit kann nicht mehr sprachspezifisch eingestellt werden. Letzteres macht es für alle Beteiligten einfacher, denke ich.

👍 
Auch Amis und Royals könnten langsam mal auf SI umschwenken - damit sie sich auf dem Mars nicht mehr verfliegen 😆 

SI = Internationales Einheitensystem

**Comment by XHalbert** [comment]
wie die Einheit heißt ist eigentlich egal

**Comment by frase-git** [comment]
> wie die Einheit heißt ist eigentlich egal

No, Sir.

`10lb sind umgerechnet 4,5359kg`

Wenn deine Versandkosten auf kg basieren und du verkaufst nach lb, wirds schwierig.

**Comment by XHalbert** [comment]
das verstehe ich jetzt nicht. Ich ordne jedem Artikel ein Gewicht zu, egal ob es nun kg oder lb ist. Aus der Summer der Gewichte aller Artikel werden die Versandkosten berechnet. Die Summe ändert sich nicht, wenn ich die Versandeinheit umbenenne.

**Comment by frase-git** [comment]
Beispiel:
Du betreibst einen Shop in Deutsch und in Englisch.
In den Spracheinstellungen legst du fest:
Deutsch = Versandkostenberechnung nach: kg
Englisch = Versandkostenberechnung nach: lb

Du legst in Deutsch einen Artikel an:
Hirse 1kg á 1,00 €
In Englisch erscheint der Artikel:
Millet 1lb á 1.00 €
Das wäre schon mal ein Gewinn für dich, denn 1lb sind (rund) nur 0,5kg.

Da denkt man: Okay, ändere ich den Preis  in Englisch
1.0lb á 0.50 € oder:
0.5lb á 1,00 €

Und genau das geht nicht. Preis und Anzahl/Einheit ändern sich in allen Sprachen mit.

Ähnlich geht das bei den Versandkosten:
Deutsch:
0,0 bis 1,0kg => 1,00 €
1,0 bis 2,0kg => 2,00 €
2,0 bis 3,0kg => 3,00 €

Ergibt in Englisch:
0.0 bis 1.0lb => 1.00 €
1.0 bis 2.0lb => 2.00 €
2.0 bis 3.0lb => 3.00 €

Und wie oben: Änderst du hier in Englisch was, dann ändert es sich in Deutsch mit.

Gut. Ich habe mein Beispiel genau falsch herum aufgezogen - denn bei dieser Rechnung würdest du nur gewinnen 😁 
Falsch bleibt es aber doch.

Christoph schlägt nun vor, dass `Versandkostenberechnung nach` **immer und für alle Sprachen** gilt.
Also: DE kg -> EN auch kg
Damit ist der ganze Kuddelmuddel erledigt.

Uff, jetzt bin ich ferdsch.

**Comment by cmb69** [comment]
> wie die Einheit heißt ist eigentlich egal

Danke, das hatte ich übersehen! Ein Weinhändler verkauft vielleicht in Flaschen oder Kästen, und da ist die Internationaliserung (bottles, boxes) natürlich ein gutes Feature. Ich denke, das ist eine kleine Erwähnung in der Dokumentation wert, mehr nicht (sprich, die Internationalisierung bleibt).

Ergo: "it's not a bug, it's a feature!" :)

**Comment by frase-git** [comment]
> Ein Weinhändler verkauft vielleicht in Flaschen oder Kästen, und da ist die Internationaliserung (bottles, boxes) natürlich ein gutes Feature. Ich denke, das ist eine kleine Erwähnung in der Dokumentation wert, mehr nicht (sprich, die Internationalisierung bleibt).

Stimmt auch wieder.
Verständnisfrage:
Was müsste dokumentiert werden?
**geht:** Flaschen - Bottles | Stück - pieces
**geht nicht:** kg - lb | l (Liter) - gal (Gallonen)

Richtig verstanden?

**Comment by cmb69** [comment]
> Richtig verstanden?

Ja. Die Einheiten müssen halt für alle Sprachen den selben Wert/die selbe Größe haben, dürfen aber unterschiedlich heißen. Anders ausgedrückt: es darf hier wirklich nur übersetzt werden.

**Comment by XHalbert** [comment]
Ich verstehe die ganze Diskussion nicht.
Wir hatten uns doch darauf geeinigt, dass "1" im Warenkorb bedeutet "1Stück dieses Artikels".
Der Weinhändler hat einen Artikel: "1 Flasche Roter" und einen weitern Artikel: "Angebot: 3 Liter vom Fass", ein weiterer "1 kg Weinhefe".
Wenn ein Kunde 5 Flaschen Roter haben will, muss er "5" bestellen, wenn er 3 Liter vom Fass haben will, muss er "1" bestellen usw..
In diesen Fällen ist doch der N a m e der Gewichtseinheit, die n u r für die Versandkostenberechnung herangezogen wird, völlig irrelevant.

**Comment by cmb69** [comment]
> In diesen Fällen ist doch der N a m e der Gewichtseinheit, die n u r für die Versandkostenberechnung herangezogen wird, völlig irrelevant.

Das kommt halt drauf an, welche Einheit für die Versandkosten gewählt wird. Die Voreinstellung ist `kg.`, und in diesem Fall darf man nicht nach `lb.` "übersetzen". Ist die Gewichtseinheit "Stück" oder "Flasche", dann ist eine Übersetzung natürlich zulässig und sinnvoll.

**Comment by frase-git** [comment]
Mal noch einfacher:

Deutsch: Kilogramm kg (=1000g)
Klingonisch: Galikromm gk (=1000g)
DAS GEHT!

Englisch: Pfund lb (~500g)
DAS GEHT NICHT!
Man muss dann für Englisch **unbedingt auch kg** einstellen.

**Comment by XHalbert** [comment]
> Man muss dann für Englisch unbedingt auch kg einstellen.

ich glaube wir reden andauernd aneinander vorbei - wieso soll denn überhaupt die Einheit, die zur Berechnung der Versandkosten dient, übersetzt und/oder mehrsprachig sein? Was auch immer der Shopbetreiber wählt (ich habe sie z.B. "VsE." genannt) dient doch nur dazu, die Versandkostenstaffel zu kalkulieren und eine entsprechende Zahl beim Artikel einzugeben.
Aber egal - ihr werdet das schon richtig machen

**Comment by cmb69** [comment]
> Was auch immer der Shopbetreiber wählt (ich habe sie z.B. "VsE." genannt) dient doch nur dazu, die Versandkostenstaffel zu kalkulieren und eine entsprechende Zahl beim Artikel einzugeben.

Da hast du nun wieder nicht unrecht. Allerdings wird diese Einheit ja auch im Warenkorb anzeigt: "Versandkosten (2.00 kg)". In deinem Fall steht dann da "Versandkosten (2.00 VsE.)" – ist das gut genug?

**Comment by XHalbert** [comment]
bei mir steht "VsE." aus historischen Gründen. früher war ich bei Hermes. Da wird nicht nach Gewichtsklassen, sondern nach Kartongrößen berechnet (Gewicht egal). Nun habe ich Körnerkissen, die sind klein und schwer, und Spelzenkissen, die sind groß und leicht. Also habe ich eine einigermaßen passende Mischkalkulation aufgestellt, und die wollte ich weder "Liter"" noch "kg" nennen, es war ja beides enthalten. Bin bei DHL jetzt, da wird nach Gewichtsklassen berechnet (Größe egal). Aber ich verkaufe ja auch Bezüge, die wiegen kaum was, kosten aber je nach Größe 1,45 oder 2,40 Porto. Also bleibe ich bei VsE.

> In deinem Fall steht dann da "Versandkosten (2.00 VsE.)"

stimmt. Ich glaube rechtlich ist das wurscht. Ich habe es aber nochmal ganz genau in den AGB erklärt.

**Comment by XHalbert** [comment]
nochmal hierzu:
> Ich glaube rechtlich ist das wurscht

meines wissens gibt es keine Vorschrift, die besagt, wie hoch der Shopbetreiber seine Versandkosten ansetzen darf. Bleibt ihm überlassen, muss nicht mit den von ihm bezahlten Kosten übereinstimmen.

Aber er m u s s die berechneten Kosten deutlich v o r Kaufabschluss nennen.

**Comment by cmb69** [comment]
> bei mir steht "VsE." aus historischen Gründen. […] Also habe ich eine einigermaßen passende Mischkalkulation aufgestellt […]

Vielleicht ist Mischkalkulation hier wirklich das Stichwort; das wird vermutlich bei den meisten Shopbetreibern so sein müssen[1]. Und da wäre eine abstrakte Einheit vielleicht wirklich sinnvoll. Deren Anzeige im Warenkorb ist ja gar nicht mal nötig, da sie auch im Frontend in den Produktdetails nicht unbedingt angegeben wird. Von mir aus könnte also alles raus, außer eben das Eingabefeld für die Menge der VsEs beim Produkt, und deren implizite Verwendung in der Versandkosten-Konfiguration und -Berechnung.

[1] Man denke nur an die ausgelieferte Artikelliste. Milch dürfte teurer werden, weil sie gekühlt versendet werden muss; Kaffee wird vermutlich richtig teuer, weil er eiligst ausgeliefert werden muss, sonst ist er kalt. ;)

**Comment by XHalbert** [comment]
> Anzeige im Warenkorb ist ja gar nicht mal nötig,

stimmt nicht nötig und für den Kunden irrelevant. Was zählt ist der Preis.
Es könnte aber bei der Erstellung einer "Mischkalkulation" für den Shopbetreiber nützlich sein, wenn sie im Warenkorb bleibt wie bisher.

**Comment by XHalbert** [comment]
> wenn sie im Warenkorb bleibt wie bisher.

PS: gern mit vom Shop vorgegebener "abstrakter Einheit" oder einer vom Shopbetreiber gewählten Einheit wär mir egal

**Comment by cmb69** [comment]
> Es könnte aber bei der Erstellung einer "Mischkalkulation" für den Shopbetreiber nützlich sein, wenn sie im Warenkorb bleibt wie bisher.

Okay. Ist aber letztlich auch alles egal, denn auch wenn diese Einheit nur für die Artikel-Bearbeitung angezeigt würde, müsste sie dennoch internationalisiert sein; sprich, es bleibt alles beim alten. Einzig sollte vielleicht `config_shipping_unit` in `labels_shipping_unit` geändert werden; das macht es vielleicht etwas klarer, dass es eben keine Konfiguration sondern nur ein Text ist. Zusätzliche Doku ist dennoch sinnvoll.

**Comment by frase-git** [comment]
erledigt [im Wiki](https://github.com/cmsimple-xh/xhshop/wiki/Sprache#abschnitt-config)
`Shipping unit`
