### ISSUE TITLE
shipping costs in cart - missing i10n

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#63]
Bei der ganzen Erklärerei ist mir aufgefallen:
Der Schraubendreher ist mit Gewicht 0,1kg eingetragen.
In der Demo ergibt das in Step 1 für 1 Stück:

`Versandkosten (0.1 kg) | 4,50 €`

Seit dem letzen (oder vorletzen) Update erhalte ich (local):

`Versandkosten (1.1 kg) | 6,25 €`

Erhöhe ich die Stückzahl auf z.B. "4", erhalte ich:

`Versandkosten (1.4 kg) | 6,25 €`

Da ist ein Fehler **vor** dem Komma (bzw. an dieser Stelle ist es immer noch ein Punkt!)
Sieht aus, als ob immer genau 1,0 addiert wird.

**Comment by cmb69** [comment]
> Seit dem letzen (oder vorletzen) Update erhalte ich (local):
>
> `Versandkosten (1.1 kg) | 6,25 €`

Kann ich mit dem aktuellen master (7ac8876) hier nicht reproduzieren. Lösch mal die Cookies – stimmt dann alles?

**Comment by frase-git** [comment]
Ich hätte schwören können, dass ich das gemacht habe. Aus Zeitgründen kann ich mich jetzt aber nicht **mit mir** rumstreiten.
Stimmt. Die eigenartige Addierung ist weg.

Die Gewichtsangabe in Step 1 hat aber trotzdem einen Punkt statt Komma.

**Comment by cmb69** [comment]
> Stimmt. Die eigenartige Addierung ist weg.

Ich denke, wir sollten das mal im Hinterkopf behalten. Mir waren da auch schon mal Unregelmäßigkeiten aufgefallen, die ich aber nicht weiter verfolgt hatte, weil ich immer an was anderem dran war.

> Die Gewichtsangabe in Step 1 hat aber trotzdem einen Punkt statt Komma.

Stimmt. Hier fehlt ein `formatFloat()`, obwohl das immer auf zwei Nachkommastellen rundet, was bei aufs Gramm genauen Gewichtsangaben problematisch sein könnte. Wird aber wohl nicht wirklich relevant sein.
