### ISSUE TITLE
Move payment module settings and lang to plugin level

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#64]
Der Shop ist so konzipiert, dass jederzeit Payment-Module entfernt oder hinzugefügt werden können, ohne weitere Änderungen am Code. Um dies zu ermöglichen, speichert der Shop Einstellungen (`settings.php`) und Sprachtexte (`lang.php`) der Payment-Module in den jeweiligen Modulordnern unter `classes`. 

Payment-Module als Addons verteilen zu können ist eigentlich eine sehr gute Idee, aber ich habe große Zweifel, dass davon Gebrauch gemacht wird. Daher sollten wir überlegen, ob wir `settings.php` und `lang.php` nach `config.php` und `languages/xy.php` verschieben.

**Comment by frase-git** [comment]
Nichts dagegen, wenn es dir hilft.
Wird es dadurch schwieriger, evtl. andere online-Bezahlsysteme hinzuzufügen?

**Comment by cmb69** [comment]
> Wird es dadurch schwieriger, evtl. andere online-Bezahlsysteme hinzuzufügen?

Wenn diese direkt in der Code-Base hinzugefügt werden (also nicht als eigenständiges Modul ausgeliefert), dann wird es eigentlich sogar einfacher, weil das Payment-Modul das Konfigurationsformular nicht selbst programmieren muss, was schon [eine ganze Menge Code](https://github.com/cmsimple-xh/xhshop/blob/49261c8f8a425720df2ef5be61688a4703975f6b/classes/paymentmodules/paypal/paypal.php#L60-L192) sein kann.

**Comment by cmb69** [comment]
Ich schlage vor PR #65 zu mergen.

**Comment by frase-git** [comment]
Habe gemerged.
Kleiner Stolperer:
Paypal config: die Mail-Adresse muss unter "Business" eingetragen werden.
Da wird es wieder Gemecker geben ;-)

**Comment by cmb69** [comment]
> Paypal config: die Mail-Adresse muss unter "Business" eingetragen werden.

Vergleiche diesbezüglich mal den [englischen](https://github.com/cmsimple-xh/xhshop/blob/95ad2fded6566d1f042dd71f4b0573f6c061daa0/languages/en.php#L204) und den [deutschen](https://github.com/cmsimple-xh/xhshop/blob/95ad2fded6566d1f042dd71f4b0573f6c061daa0/languages/de.php#L204) Hilfetext. Die habe ich so ungeändert übernommen – da stimmt sowieso was nicht.

**Comment by frase-git** [comment]
Na ja, ich weiß nicht ob ID oder Mail-Adresse ... keine Ahnung.
Oder beides?
Oder entweder oder?
@XHalbert

**Comment by frase-git** [comment]
Keine Ahnung von PayPal.
@XHalbert fragen

Wenn das geklärt ist, dann vielleicht statt `cf_paypal_business` -> `cf_paypal_contact` ?

**Comment by cmb69** [comment]
> Keine Ahnung von PayPal.

Ich auch nicht wirklich. Aber mir scheint, der Shop ist diesbezüglich nicht auf der Höhe der Zeit: https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/

Wenn wir darauf umstellen, dann ist die E-Mail-Adresse wohl irrelevant; statt dessen braucht man [eine ID](https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/client-side-REST-integration/#get-your-client-id).

**Comment by frase-git** [comment]
oder hier in deutsch:
https://www.geld-online-blog.de/tipps-infos/zahlungssysteme/paypal-button-in-blog-oder-website-einbinden-tutorial/

**Comment by cmb69** [comment]
Es gibt mindestens zwei Möglichkeiten Paypal zu integrieren: einmal das von mir verlinkte Express-Checkout ([Demo](https://developer.paypal.com/demo/checkout/#/pattern/client)) und die von die verlinkten Buttons ([Demo](https://demo.paypal.com/us/demo/navigation?flow=flow1&device=desktop&merchant=beauty&locale.x=en_US)). Ich bin nicht sicher, ob die derzeitige Paypal-Integration über (2) läuft oder eine ältere API verwendet. Express-Checkout scheint mir aber sowohl für die Integration als auch für den Shop-Betreiber einfacher.

**Comment by frase-git** [comment]
> Express-Checkout (Demo)

👍 
Wobei mir in der Demo der Button am besten gefällt, der erscheint, wenn man links auf "Button Styles"->"Button Styles" klickt.
```
        style: {
            label: 'pay', // checkout | credit | pay
            size:  'small',    // small | medium | responsive
            shape: 'rect',     // pill | rect
            color: 'blue'      // gold | blue | silver
        },
```
Wie wird das mit den Sprachen?

**Comment by cmb69** [comment]
> Wie wird das mit den Sprachen?

Darauf hat man wohl keinen Einfluss – vermutlich wird hier automatisch gemäß dem Accept-Language Header des Browsers lokalisiert. Finde ich okay.

**Comment by XHalbert** [comment]
>     Keine Ahnung von PayPal.

> Ich auch nicht wirklich. Aber mir scheint, der Shop ist diesbezüglich nicht auf der Höhe der Zeit: 

Ich glaube, dass Express-Checkout die neuere und bessere Lösung ist - wenn du die hinkriegst wär sicher gut

> Vergleiche diesbezüglich mal den englischen und den deutschen Hilfetext

ich kenne keine paypal-ID, hab jedenfalls keine. Läuft alles über die Emailadresse.

**Comment by cmb69** [comment]
> Ich glaube, dass Express-Checkout die neuere und bessere Lösung ist

Und das beste daran: man braucht keine IPN mehr zu behandeln. :) Ich werde das bei Gelegenheit mal als alternatives Payment-Modul ausarbeiten, so dass man danach in Ruhe vergleichen kann.

> ich kenne keine paypal-ID, hab jedenfalls keine. Läuft alles über die Emailadresse.

Okay, danke! Dann gehe ich mal davon aus, dass der deutsche Hilfetext richtiger als der englische ist (wäre nicht das erste mal, dass das beim Shop so ist), und stelle auf `email` um.

**Comment by cmb69** [comment]
> und stelle auf email um.

Erledigt: 01abeda
