### ISSUE TITLE
Check email address

### ISSUE THREAD

**Issue by XHalbert** [cmsimple-xh/xhshop#71]
bei ungültiger Emailadresse kommt in "ThankYou" ein Error

(die Meldung sehe ich zum ersten Mal)
_Sorry! Your message could not be sent.
Please inform us by email: kaufbestaetigung@natur-und-handgemacht.de
Mailer Error: You must provide at least one recipient email address._

Kunde ist verwirrt und weiß nicht was er tuen soll.
Also wichtig: Errormeldung ändern, z.B.
"Sorry, die von Ihnen eingegebene Emailadresse scheint nicht korrekt zu sein! Bitte klicken Sie wieder auf "Shop oder "alles anzeigen". Der Warenkorb ist noch vorhanden. Mit Klick auf "weiter gelangen sie wieder zur Eingabe der Kontaktangaben. Dort bitte die Emailadresse ändern und fortfahren."

Wäre es nicht besser, wenn eine Prüfung, ob die Emailadresse geht, schon in Schritt 2 oder 3 erfolgen würde?

Ich habe getestet:
Leerzeichen werden ignoriert: info@albert-wilhelm .de - geht
falsch geschrieben geht nicht, z.B. info@albert-wilhelm,de

PS: Kommt oft vor, dass die Emailadresse falsch eingegeben wird. Wellrad hat sich daran aber nie gestört und an die falsche Emailadresse gemailt. Beim Shopbetreiber kam dann  " MAILER-DAEMON@post.webmailer.de " an, was natürlich schlimm ist, denn nicht jedesmal kann man erraten, wo der Fehler ist. Tel. Rückruf geht auch oft nicht, weil die Tel.Nr. ebenfalls falsch sein kann.

**Comment by cmb69** [comment]
> Wäre es nicht besser, wenn eine Prüfung, ob die Emailadresse geht, schon in Schritt 2 oder 3 erfolgen würde?

Ja, wobei eine vollumfängliche syntaktische Prüfung praktisch nicht machbar ist. Und selbst wenn, dann heißt das noch lange nicht, dass es die E-Mail-Adresse auch tatsächlich gibt. Auf jeden Fall sollten wir das E-Mail-Eingabefeld zu `<input type="email">` ändern; hilft schon mal viel mit wenig Aufwand.

**Comment by XHalbert** [comment]
wäre das eine Prüfung auf xxx@xxx.xxx ?
Würde in den allermeisten Fällen erfahrungsgemäß vollkommen ausreichen.

**Comment by XHalbert** [comment]
wenn einer "@t_online.de" oder "t-online.com" schreibt, kann man oft erraten was gemeint ist.

**Comment by cmb69** [comment]
> wäre das eine Prüfung auf xxx@xxx.xxx ?

Bin nicht sicher wie das genau spezifiziert und in einzelnen Browsern implementiert ist, aber so in etwa. Das Problem bei E-Mail-Adress-Prüfungen ist halt, dass solche Adressen fast alles mögliche sein können, und prüft man zu lax, dann werden viele Fehler nicht abgefangen, aber prüft man zu streng, dann werden gültige Adressen zurück gewiesen. Verlässt man sich zunächst mal auf den Browser, dann wären zu strenge Prüfungen nicht ganz so problematisch, weil der Benutzer das bei seinem Browser wohl schon kennt.

Zum Vergleich: [dies](https://github.com/cmsimple-xh/cmsimple-xh/blob/1.7.0/cmsimple/classes/Mail.php#L93-L113) ist die E-Mail-Validerungsroutine vom Mailformular von CMSimple_XH 1.7.0. Die weist schon eine ganze Reihe gültiger `local-part`s zurück, und die Domainprüfung ist auch nicht wirklich verlässlich, weil es eben viele gültige Domains gibt.

> wenn einer "@t_online.de" oder "t-online.com" schreibt, kann man oft erraten was gemeint ist.

Das würde ich nicht machen – höchstens vielleicht in einer Fehlermeldung ("meinten Sie vielleicht @t-online.de?"), aber auch das erscheint mir zu komplex bzw. speziell.

**Comment by XHalbert** [comment]
> wenn einer "@t_online.de" oder "t-online.com" schreibt, kann man oft erraten was gemeint ist.

so meinte ich das nicht, sondern:
wenn die Prüfung so lax ist, dass sie sowas durchlässt, soll es mir recht sein. Lieber zu lax als zu streng.

> eine Prüfung auf xxx@xxx.xxx

damit meinte ich: eine Prüfung, ob (Buchstaben/Minuszeichen und/oder Zahlen) gefolgt von @ gefolgt von (Buchstaben/Minuszeichen und/oder Zahlen) gefolgt von Punkt gefolgt von irgendwas
- das wäre für die meisten Fälle schon ausreichend

> die E-Mail-Validerungsroutine vom Mailformular

ups chinesisch
ich meine, eine laxe Prüfung, die lediglich abfängt, wenn einer was ganz offensichtlich falsches schreibt, wäre schon besser als nichts, und müsste uns hier ausreichen.

**Comment by cmb69** [comment]
> damit meinte ich: eine Prüfung, ob (Buchstaben/Minuszeichen und/oder Zahlen) gefolgt von @ gefolgt von (Buchstaben/Minuszeichen und/oder Zahlen) gefolgt von Punkt gefolgt von irgendwas

Dummerweise ist z.B. "karl klammer"@example.com` auch eine (syntaktisch) gültige E-Mail-Adresse. Und `postmaster@localhost` auch.

Egal, du kannst unter https://www.wufoo.com/html5/types/1-email.html schnell testen, wie dein(e) Browser reagieren.

**Comment by XHalbert** [comment]
und das ist erst witzig
nein vergessen, ist nicht aktuell

**Comment by XHalbert** [comment]
Ups, auf preview macht er komische Sachen:

> Fatal error: Xhshop\FrontEndController::collectCartItems(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition "XHS_Order" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition in /mnt/web003/e2/81/5746881/htdocs/test-natu-1-7/plugins/xhshop/classes/FrontEndController.php on line 151 

da hatte ich vor dem Updaten des Masters schon Kontaktdaten eingegeben, also gab es eine session...
Ausgeloggt, alles Fenster geschlossen, alles ok.

**Comment by XHalbert** [comment]
und das ist erst witzig!
Genau 1,- € macht er richtig, das (noch) nicht:
![neu-4](https://user-images.githubusercontent.com/29812782/28084758-f43f3762-6679-11e7-80a7-55e81942beda.JPG)

**Comment by cmb69** [comment]
> und das ist erst witzig!
Genau 1,- € macht er richtig, das (noch) nicht:
[image]

Das wäre aber ein dickes Ding! Ich kann es allerdings nicht reproduzieren.

**Comment by XHalbert** [comment]
das war aber gestern der aktuelle master.
Es war wirklich so: bei 100 Stck. = Summe 1,- € , Versandkosten = 0  zeigte er diese Meldung nicht, und rechts unten "weiter".

Werd bei Gelegenheit nochmal aktualisieren und neu testen.

**Comment by XHalbert** [comment]
> dickes Ding!

nochmal getestet nach erneutem Update:
Jetzt ist gut (weiß nicht was da war...)

**Comment by frase-git** [comment]
Schließen?
