### ISSUE TITLE
Mindestbestellwert

### ISSUE THREAD

**Issue by XHalbert** [cmsimple-xh/xhshop#72]
Shop getestet.
Testprodukt 1,- € ausgewählt

Warenkorb Hinweis:
Bestellungen mit einem Wert unter 1,00 € (Mindestbestellwert) können wir leider nicht entgegennehmen!

Wohl genauso falsch gerechnet wie "Versand frei ab 50,-€"

**Comment by cmb69** [comment]
> Wohl genauso falsch gerechnet wie "Versand frei ab 50,-€"

In [dieser Zeile](https://github.com/cmsimple-xh/xhshop/blob/f6776c6dcbd1ae43d255533c17548fafd63e6850/classes/app/xhs_frontend_controller.php#L238) müsste wohl `<` statt `<=` stehen.

**Comment by cmb69** [comment]
Hm, Kommando zurück! Das `<=` ist korrekt, und ich kann das Problem auch nicht nachvollziehen. @XHalbert Ist bei dir ein Nachlass im Spiel? (Der Mindestbestellwert bezieht sich auf den Bestellbetrag, nicht den Warenwert.) Ansonsten mal Cookies löschen und noch mal ausprobieren.

**Comment by frase-git** [comment]
`['hints_minimum_order']="( Mindestbestellwert = Warenwert + Versandkosten )";`

Gebühren werden - glaube ich - nicht berücksichtigt.

**Comment by cmb69** [comment]
Aber en: "(incl. shipping and fees)" Und das ist zumindest das, was derzeit implementiert ist, da mit [Order::getTotal()](https://github.com/cmsimple-xh/xhshop/blob/b141042e05b144ccd2f943837077800ec5d1a6ed/classes/Order.php#L135) verglichen wird.

Ist natürlich die Frage, ob Gebühren und Versandkosten hier wirklich sinnvoll sind. Von den Versandkosten hat der Shopbetreiber ja nichts.

**Comment by frase-git** [comment]
Der deutsche Text stammt von mir (!)
Ich hatte das ganz am Anfang ausgiebig getestet und bin darauf gekommen.
(Irrtum?)
Was ich jetzt noch festgestellt habe, es reicht nicht, `Charge for shipping` auszuschalten. Die Versandkosten werden trotzdem berechnet.
Man muss auch noch `Forwarding expenses up to` auf `0` setzen.
Dann erscheint in Step 1 immer noch;
`Versandkosten (1,00 kg) | 0,00 €`

Hier sollte uns @XHalbert nochmal über genaue Tests berichten.

**Comment by cmb69** [comment]
> Der deutsche Text stammt von mir (!)
Ich hatte das ganz am Anfang ausgiebig getestet und bin darauf gekommen.
(Irrtum?)

Bin noch nicht sicher; müsste getestet werden. In diesem Fall am besten automatisiert, so dass es schnell reproduziert werden kann (Stichwort Regressionstest).

Aber: Mindestbestellwert `0.89`, keine Versandkosten, 1x Kirschen bestellt: "Bestellungen mit einem Wert unter 0,89 € (Mindestbestellwert) können wir leider nicht entgegennehmen!"

Klar, das ist float Arithmetik (sollte bei ganzen Zahlen kein Problem sein, aber eben bei Bruchzahlen).

> Was ich jetzt noch festgestellt habe, es reicht nicht, Charge for shipping auszuschalten. Die Versandkosten werden trotzdem berechnet.

Ja, da stimmt was nicht. Da es sich um eine Regression durch die Umstellung auf `config.php` handelt, braucht es kein extra Ticket fürs Changelog. Daher per d605ee8 erledigt.

> Dann erscheint in Step 1 immer noch;
Versandkosten (1,00 kg) | 0,00 €

Sollte das nicht so sein? Immerhin wird dem Kunden dann explizit vermittelt, dass keine Versandkosten anfallen. Und die Versandkosten von 0,00 € werden ja auch in Schritt 3 und den Mails aufgeführt.

Ach so, weil wieder gerade fleißig getestet wird: e0003d1 kann Fehler verursachen falls schon was im Warenkorb ist; bei Problemen also Cookies löschen.

**Comment by frase-git** [comment]
> Sollte das nicht so sein? Immerhin wird dem Kunden dann explizit vermittelt, dass keine Versandkosten anfallen. Und die Versandkosten von 0,00 € werden ja auch in Schritt 3 und den Mails aufgeführt.

Okay.

Weil du gerade Kirschen erwähnst:
In der Demo sind für die Kirschen 0 kg festgelegt (was wahrscheinlich sowieso Unsinn ist).
Bestellt:
Kirschen 1 x 0,89
In Step 1:
`Versandkosten (0,00 kg) | 4,50 €`
Das ist zwar eigentlich richtig weil: `1=4.50`
Sieht aber sehr komisch aus.

**Comment by cmb69** [comment]
> In der Demo sind für die Kirschen 0 kg festgelegt (was wahrscheinlich sowieso Unsinn ist).

Ja, das ist Quatsch. 100 oder 200 g erscheinen hier angebrachter.

Ein Problem wären nur sehr leichte Waren (im Grammbereich, aber eben nicht Waren, die nichts wiegen) wegen der Rundung auf zwei Nachkommastellen. Diese können aber eigentlich gar nicht erst eingegeben werden – kann von mir aus also so bleiben.

**Comment by frase-git** [comment]
Soll ich nochmal eine `catalog.php` mit sinvollen Werten machen?

BTW: Wenn ja, mit "HOL / GER"?

**Comment by cmb69** [comment]
> Soll ich nochmal eine catalog.php mit sinvollen Werten machen?

Allzu viel Arbeit würde ich in die Demo `catalog.php` nicht stecken, aber wenn unsinnige Werte auffallen, sollten diese besser korrigiert werden.

> BTW: Wenn ja, mit "HOL / GER"?

Weiß nicht wirklich, was du da vorhast, aber mach ruhig mal – ich finde, du bist da immer sehr kreativ. :)

**Comment by frase-git** [comment]
[HOL / GER](http://fhs.bplaced.net/xhshop-demo/?Shop&xhsProduct=p595e69e48c4e4)

**Comment by cmb69** [comment]
Ach ja, der Splitter. Rein damit! :)

**Comment by frase-git** [comment]
Du hast es so gewollt ;-)

[distro-catalog-01.zip](https://github.com/cmsimple-xh/xhshop/files/1135942/distro-catalog-01.zip)

**Comment by cmb69** [comment]
> Du hast es so gewollt ;-)

Danke, eingespielt: 240e7f7

**Comment by cmb69** [comment]
Hm, den Kirschen-Fehler kann ich nicht mehr reproduzieren, aber hier ein anderes schönes Beispiel:

* Schraubendreher reduziert auf 9,20€
* Die Brötchen verderben bald, also Dumpingpreis von 0,02€
* keine Versandgebühr
* Mindestbestellwert 9,22€

Ergebnis: Summe = 9.22€; "Bestellungen mit einem Wert unter 9,22 € (Mindestbestellwert) können wir leider nicht entgegennehmen!"

Otto Normalverbraucher denkt dann wohl "WTF?" Wer sich mit Floating-Point-Problemen auskennt, denkt allerdings "klar 9.22 > 9.20 + 0.02; da kaufe ich lieber nicht mehr ein".

Mit BC Math wäre das nicht passiert,  denn `bccomp('9.22', bcadd('9.20', '0.02', 2), 2)` ergibt `0` (signalisiert Gleichheit).

@frase-git @XHalbert Könnt ihr mal bitte auf euren Webspace nachschauen, ob dort die `bcmath` Extension verfügbar ist (Einstellungen → Info → PHP-Info)?

Ach ja: weitere Problemfälle sind im [PHP-Bug-Tracker](https://bugs.php.net/search.php?cmd=display&search_for=floating+point&boolean=1&direction=DESC&limit=30&0=Array&status=Not+a+bug&reorder_by=ts2) zu finden.

**Comment by frase-git** [comment]
fhseidel dot dä = BCMath support enabled
bplaced = BCMath support enabled

**Comment by XHalbert** [comment]
BCMath support | enabled
bcmath.scale | 0

> klar 9.22 > 9.20 + 0.02; 

hä? Höhere Mathematik, irrationale Zahlen oder was?
Aber egal. Wenn es dem Shop nicht möglich ist, was vernünftiges auszurechnen, würde ich vorschlagen, die Mindestbestellmenge (vorerst) einfach wegzulassen. Ich war nie ein Freund davon.

**Comment by cmb69** [comment]
> hä? Höhere Mathematik, irrationale Zahlen oder was?

Das sind typische Probleme der so genannten Fließkommaarithmetik von Computern. Siehe http://www.floating-point-gui.de/ für Details.

> Wenn es dem Shop nicht möglich ist, was vernünftiges auszurechnen, würde ich vorschlagen, die Mindestbestellmenge (vorerst) einfach wegzulassen.

Das betrifft zumindest potentiell nicht nur die Mindestbestellmenge, sondern auch andere Währungskalkulationen. Frank hatte wohl tatsächlich mal eine Differenz von 1 Cent bei der Umsatzsteuerberechnung.

Danke fürs Prüfen des BCMath-Support. Ich mach mich dann bald an die Umstellung.

**Comment by frase-git** [comment]
Schließen?
