### ISSUE TITLE
in config

### ISSUE THREAD

**Issue by XHalbert** [cmsimple-xh/xhshop#73]
Shop getestet.
kommt das noch in config?

1. css:
width: 100%; /*** disable this for pictures with different sizes ***/
min-width:100%; /*** disable this for pictures with different sizes ***/

2. link zur AGB-Seite: Pfad konfigurierbar machen

PS: Ihr habt wirklich sehr gute Arbeit gemacht!!! Finde die Lösung mit der config vielleicht sogar besser als in wellrad. Denke da wird jeder gut mit zurechtkommen

**Comment by frase-git** [comment]
zu 2.:
xhshop -> Sprache

Das Gleiche hätte ich gern für die Versandkosten, damit wir dann "zzgl Versandkosten" automatisch verlinken können.

**Comment by cmb69** [comment]
Zu 1: CSS halte ich eigentlich lieber raus aus der Konfiguration.

> Das Gleiche hätte ich gern für die Versandkosten, damit wir dann "zzgl Versandkosten" automatisch verlinken können.

Ja, macht Sinn.

**Comment by cmb69** [comment]
Ich schließe dieses Ticket mal. AGB-Seitenkonfiguration gibt's ja schon, Versandkostenverlinkung gehört zu #17.

@XHAlbert wenn dir die CSS-Konfigurationsoption ein Herzenswunsch ist, dann öffne das Ticket einfach wieder. :)
