### ISSUE TITLE
Help texts for payment methods in config

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#74]
Die Überschrift sagt es: Da fehlt noch was.
Ist zwar Tipparbeit, sollte aber nicht kompliziert sein - oder?
Bei "Fee" evtl.: "Gebühr &ndash; negative Werte möglich".

Und &ndash; ich bin mir nicht sicher &ndash; vielleicht bei jedem `Is active` in der Hilfe angeben, was es in der jeweiligen Sprache betrifft.
Also z.B. bei `Cash-in-advance`:
(?) Is active -> Text für Fragezeichen: "Soll Vorauszahlung angeboten werden?"

**Comment by cmb69** [comment]
Ja, sollte so gemacht werden. :)

**Comment by XHalbert** [comment]
> Gebühr – negative Werte möglich

ich würde ergänzen.
Gebühr – negative Werte für Nachlass
