### ISSUE TITLE
Remove template_1.rtf and junk_shopToc.tpl

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#75]
Haben diese beiden Dateien noch irgendeine Relevanz? Ansonsten sollten sie gelöscht werden.

**Comment by frase-git** [comment]
`template_1.rtf` kann gelöscht werden.

`junk_shopToc.tpl` - da muss ich mal bei Gelegenheit nachschauen. War wohl eine alternative Navigation ?
Bitte zurückstellen.

**Comment by cmb69** [comment]
> Bitte zurückstellen.

Okay. (Allerdings kann man bei Git (und anderen Versionsverwaltungen) auch ruhig eine Datei löschen, und sie bei Bedarf später wieder hinzufügen.)

**Comment by frase-git** [comment]
Ich habe mir die `junk_shopToc.tpl` angeschaut.
Offensichtlich ist das ein Relikt aus früheren Shop-Zeiten.
Man kann sie umbenennen zu `shopToc.tpl` - so war es sicher ursprünglich geplant. Es erscheint dann an alternativer Stelle (in der Demo in der Newsbox) ein Link: `Shop`.  Und es sollten wohl noch Unterseiten angezeigt werden, was bei mir aber nicht funktioniert. Vielleicht war es aus Zeiten, da es noch keine Pseudo-Kategorien gab?
Ich würde vorschlagen, diese Datei zu entfernen.
Sie ist ja nicht wirklich weg - bei Bedarf könnten wir sie reaktivieren ;-)

**Comment by XHalbert** [comment]
> Ich würde vorschlagen, diese Datei zu entfernen.

ja weg damit (junk_shopToc.tpl), hab mich schon öfter gefragt, was das soll.
Ist die template1.rtf nicht identisch mit template.rtf? Kann also auch weg.
