### ISSUE TITLE
All fractional values have to be entered with decimal point

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#76]
Das ist eigentlich nur eine Frage und könnte nach Antwort gleich geschlossen werden:

Die Plugin-Konfiguration über die XH-typische config.php zu machen ist super.
Die XH-typischen Felder sind aber nicht `type="number"`.
Die Frage also:
Ist es egal, wie man z.B. die Gebühr für "per Rechnung" eintippt - mit Komma oder Punkt?
Habe beides ausprobiert. Es wird in der config.php gespeichert wie getippt.
Soweit ich es übersehe wird auch **richtig** gerechnet.

Nachtrag:
Habe mal Gebühr für Rechnung: xxx eingegeben.
In Step 2 erscheint Radiobutton Rechnung ohne Gebührenangabe (richtig).
In Step 3 erscheint `Gebühr | 0,00 €` - das is ja dann auch richtig.

Also ist das kein wirkliches Problem.
Könnte das an anderer Stelle Probleme verursachen?

**Comment by cmb69** [comment]
> Also ist das kein wirkliches Problem.
Könnte das an anderer Stelle Probleme verursachen?

Gibt mal Nachkommastellen an (also nicht ,00). Die werden wenigstens ignoriert. In `config.php` muss immer der Dezimalpunkt verwendet werden. Bei einigen Optionen wird das auch im Hilfstext erwähnt; bei den anderen sollte es nachgeholt werden.
