### ISSUE TITLE
System check succeeds even though Fa_XH is not installed

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#77]
Testweise unter XH 1.6.10 installiert.
Plugin-Systemprüfung meldet unter Anderem:

> Prüfe, dass das CMSIMPLE_XH Plugin 'fa' installiert ist … OK

FA ist aber gar nicht da!

Mit nachinstalliertem FA scheint alles ganz gut zu funktionieren. Unter "mini1"!

**Comment by cmb69** [comment]
Autsch – dicker Bug! Da [rächt sich](https://github.com/cmb69/pagemanager_xh/issues/55) mein Copy&Paste.

> Mit nachinstalliertem FA scheint alles ganz gut zu funktionieren. Unter "mini1"!

Das wiederum ist erfreulich. :)

**Comment by frase-git** [comment]
Mit der geänderten Zeile ist die FA-Meldung jetzt rot.
👍 
Das ist mir in 1.7 nicht aufgefallen, weil in diesem Fall fhs-simple schon meckert.

Sorry, jetzt musst du alle Plugins durchsehen - wie ich gerade bemerke.
