### ISSUE TITLE
xhshop distribution: published or not?

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#79]
Während ich am Wiki bastele - eine tödliche Aufgabe - kommen mir immer mehr Fragen, die beantwortet werden wollen.

Den Shop veröffentlicht ausliefern - JA oder NEIN?

Wenn ein (unerfahrener) Nutzer sofort damit auf seinen Server geht, dann hat er einen Shop online mit Dummy-Artikeln! Finde ich zumindest problematisch.
Viele haben kein xampp o.Ä.

**Comment by frase-git** [comment]
Nachtrag:

> Pardon! Noch ist der xhshop-Shop nicht betriebsbereit.

Dieser Text in der Sprachdatei könnte helfen. Ich weiß aber nicht, an welcher Stelle er auftauchen soll.

Vorschlag:
Auslieferung ohne `Order email` (zurzeit: example@example.com).
Dann müsste immer geprüft werden, ob da was drinsteht.
Wenn nicht, dann die Meldung.
Das wäre zumindest eine minimale Vorsorge.

**Comment by cmb69** [comment]
> Während ich am Wiki bastele - eine tödliche Aufgabe - kommen mir immer mehr Fragen, die beantwortet werden wollen.

Geht mir bei der Arbeit am Quellcode auch so. :)

> Dieser Text in der Sprachdatei könnte helfen. Ich weiß aber nicht, an welcher Stelle er auftauchen soll.

Wenn der Shop nicht veröffentlicht ist, dann erscheint dieser Text anstelle des Shops (im Frontend/Ansichtsmodus).

> Den Shop veröffentlicht ausliefern - JA oder NEIN?

Ich würde sagen, die Voreinstellung sollte NEIN sein.

**Comment by frase-git** [comment]
> Wenn der Shop nicht veröffentlicht ist, dann erscheint dieser Text anstelle des Shops (im Frontend/Ansichtsmodus).

Nö. Dann erscheint:
`hints_sorry_we_are_closed` = Wir bitten um Entschuldigung! Der Shop wird gerade überarbeitet. ...

Der oben zitierte Text steht unter: `hints_sorry_errors`
Und da ist mir nicht klar, ob der überhaupt erscheint.

**Comment by cmb69** [comment]
> Nö. Dann erscheint:
hints_sorry_we_are_closed = Wir bitten um Entschuldigung! Der Shop wird gerade überarbeitet. ...

Stimmt. Tatsächlich wird dieser Sprachtext seit 69efebe nicht mehr verwendet. Zuvor wurde er verwendet, wenn eine der relevanten Dateien nicht vorhanden war oder keine Schreibrechte hatte, was dann nur im Backend angezeigt wurde. Dafür haben wir ja nun die Systemprüfung.

`hints_sorry_errors` kann also weg, aber `hints_sorry_we_are_closed` könnte wie auch immer angepasst werden.

**Comment by XHalbert** [comment]
> Den Shop veröffentlicht ausliefern - JA oder NEIN?

> Ich würde sagen, die Voreinstellung sollte NEIN sein.

und da sucht und sucht und sucht der Neuling... verdammt, warum klappt das denn nicht...
Ich finde "Ja"
(dass nur irgendwelches Obst drin ist, wird er dann ja sehen...)
Übrigens Obst. Warum sind das denn so Megadateien?

**Comment by frase-git** [comment]
Genau in dem Moment, in dem er den Shop auf den Server lädt, bietet er die Dummy-Produkte an - die dann auch **sofort bestellt** werden könnten!
[siehe auch hier](https://github.com/cmsimple-xh/xhshop/wiki/3-%E2%80%93-Konfiguration#den-shop-konfigurieren)

> Warum sind das denn so Megadateien?

Damit man sich Details anschauen kann. Zum Beispiel in der Fancybox.
Es gibt nicht nur "bunte Kissen" ;-)

**Comment by XHalbert** [comment]
> Genau in dem Moment, in dem er den Shop auf den Server lädt, bietet er die Dummy-Produkte an - die dann auch sofort bestellt werden könnten!

ok hast recht

**Comment by cmb69** [comment]
@frase-git Hast du noch einen besseren Vorschlag für `hints_sorry_we_are_closed`? "Pardon! Noch ist der xhshop-Shop nicht betriebsbereit." ist zwar für die Einrichtungsphase sinnvoll, aber nicht für spätere Wartungsphasen. Ware vielleicht (auch) ein "Baustellenschild" sinnvoll, oder ist das out?

**Comment by frase-git** [comment]
Confuuuuusion !?!?!?

1. Baustellenschild = super OUT.

2. IST:
`hints_sorry_we_are_closed` = "Wir bitten um Entschuldigung! Der Shop wird gerade überarbeitet &hellip;"

3. WAR:
`hints_sorry_errors` = "Pardon &hellip;" - Das ist entfernt.

Bitte mal den Shop in den Wartungsmodus setzen und aufrufen.

**Comment by cmb69** [comment]
> Bitte mal den Shop in den Wartungsmodus setzen und aufrufen.

Sieht bei mir so aus:
![unpublished](https://user-images.githubusercontent.com/2306138/28111132-bf0fdb0c-66f4-11e7-8d7b-7825ca9f4ba9.png)

**Comment by frase-git** [comment]
Nicht gut?

**Comment by cmb69** [comment]
> Nicht gut?

Ich finde es okay, aber du hattest doch Bedenken, oder irre ich mich?

**Comment by frase-git** [comment]
Großes Misunderstood.
Ich habe es ja gebaut.
Post 2 bezieht sich auf eine mögliche Prüfung, ob der Shop schon vom Betreiber bearbeitet wurde.
Die Idee war, ohne E-Mail-Adresse auszuliefern. Solange da nichts drinsteht = Shop unbearbeitet, sollte evtl. die Error-Meldung erscheinen, als Hinweis, dass man noch nicht online gehen kann.
Nur ein Gedankenspiel.

**Comment by XHalbert** [comment]
der Hinweis "Wartungsmodus" sieht ja wohl spitze aus

**Comment by cmb69** [comment]
> Die Idee war, ohne E-Mail-Adresse auszuliefern. Solange da nichts drinsteht = Shop unbearbeitet, sollte evtl. die Error-Meldung erscheinen, als Hinweis, dass man noch nicht online gehen kann.

Das finde ich nicht wirklich ausreichend. U.U. trägt dann jemand eine E-Mail-Adresse ein, und denkt, nun sei gut. Den Shop per Voreinstellung im "Wartungsmodus" auszuliefern gefällt mir da besser. Aber mein Herz hängt nicht dran → reopen.

**Comment by frase-git** [comment]
> Das finde ich nicht wirklich ausreichend.

Ich ja auch nicht. Und das Thema hat sich ja nun erledigt mit "unveröffentlicht".
Kann also wieder zu.
Mach ich gleich.
