### ISSUE TITLE
Bildeinfügen in den Produktbeschreibungen funktioniert nicht

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#8]
Genau gesagt, funktioniert das Einfügen wie gewünscht, aber beim Speichern wird das Bild verstümmelt. Nach dem Einfügen z.B.:
````
<img src="./userfiles/images/test1.jpg" alt="" width="150" height="150">
````
Nach dem Speichern dann:
````
<img src="\&quot;userfiles/images/test1.jpg\&quot;" alt="\&quot;\&quot;" width="\&quot;150\&quot;" height="\&quot;150\&quot;">
````

**Comment by cmb69** [comment]
PR #8 should fix this and some related bugs.

**Comment by frase-git** [comment]
Genau.
Und in der `catalog.php` landet es so:
`<img src=\\\"userfiles/images/shop/no_image.jpg\\\" width=\\\"100\\\" height=\\\"100\\\">`

Übrigen: Wieso liegen deine Bilder in "userfiles"?
Ich hatte das geändert in "userfiles/shop" zur besseren Auffindbarkeit und zur Unterscheidung von anderen Content-Bildern.

**Comment by cmb69** [comment]
> Übrigen: Wieso liegen deine Bilder in "userfiles"?

Ich hatte hier kein Shop-Bild ausgewählt, sondern eines aus der XH-Entwicklungsumgebung. Es ging mir nur um die grundsätzliche Beschreibung des Problems.

**Comment by frase-git** [comment]
Habe den Branch "no-stripslashes-addslashes" mit der Korrektur für den Filebrowser getestet.
Funktioniert offensichtlich einwandfrei. In Teaser und Produktdetails können beliebige Bilder eingefügt werden.
(Ich weiß nicht, was ich jetzt schreibe:) 
https://github.com/cmsimple-xh/xhshop/pull/9 könnte wohl gemerged werden.
