### ISSUE TITLE
Move catalog.php to content/ folder of CMSimple_XH

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#80]
Das wurde unter https://github.com/cmsimple-xh/xhshop/issues/67#issuecomment-314146315 ff bereits besprochen. Ich öffne dieses Ticket nur fürs Changelog.

**Comment by frase-git** [comment]
System-Check meldet:

> Prüfe, dass './content/xhshop/tmp_orders/' schreibbar ist … Warnung

Der Ordner ist noch im Plugin-Ordner.

**Comment by cmb69** [comment]
> Der Ordner ist noch im Plugin-Ordner.

Danke. Gefixt mit 975a4b9.

Die Umstellung hat übrigens einen Vorteil an den ich wohl noch nicht gedacht hatte: aktualisiert man den bestehenden Clone, dann bleibt die eigene `catalog.php` unangetastet.

**Comment by frase-git** [comment]
Ja, stimmt.
Für den "schnellen User" aber unhandlich.
Aber: egal ;-)

**Achtung: eben gemerkt!**
Der Ordner muss auch noch in `content/xhshop/`

**Comment by frase-git** [comment]
> Checking that '../content/xhshop/tmp_orders/' is writable … warning

Der Ordner ist immer noch nicht da, wo er hin soll !
(aktueller master)

**Comment by cmb69** [comment]
> Der Ordner ist immer noch nicht da, wo er hin soll !

Dann führe mal `setup.bat` aus (geht mit Doppelklick, aber dann muss derzeit noch explizit `V` angegeben werden).

**Comment by frase-git** [comment]
Hm.
Ich hatte versucht aus dem Demo-Ordner händisch zu kopieren.
Da war er nicht.
Dass du in der .bat `mkdir` stehen hast ... ;-)

Was machen denn nun die nicht-Windowsler?
Und wer löscht wann den demo-Ordner?

**Comment by cmb69** [comment]
> Was machen denn nun die nicht-Windowsler?

Siehe https://github.com/cmsimple-xh/xhshop/#developers.

> Und wer löscht wann den demo-Ordner?

Dazu ~~schreibe~~ schrieb ich gleich ein `build` target für Phing: 429b152.

Wenn du selbst builden willst, dann muss du [Composer](https://getcomposer.org/) installieren, eine Eingabeaufforderung (`cmd.exe`) im XH-Shop-Pluginverzeichnis öffnen und folgende Befehle eingeben:
````
composer install
phing -Dversion=1.0-dev-frase123 build
````
Das Ergebnis sollte XHShop-1.0-dev-frase123.zip sein.
