### ISSUE TITLE
english demo content: images path wrong

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#81]
Der Bilderpfad für die Detailseite HOL / GER ist in "english" falsch.
(Bilder im Text)

**Comment by cmb69** [comment]
> Der Bilderpfad für die Detailseite HOL / GER ist in "english" falsch.

War mir auch aufgefallen. Aber das kann nicht allgemein gelöst werden, da es darauf ankommt, welches die Haupt- und welches die Zweitsprache ist. Bei mir ist i.d.R. `en` die Hauptsprache. Ich dachte mir daher es wird das beste sein, die Demo einfach so zu belassen, dass sie primär für einsprachige Websites passt, egal ob nun `en` oder `de`.

Okay? Falls ja, dann könnte man das im Wiki kurz erwähnen.
