### ISSUE TITLE
Deliver demo content as separate package

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#82]
In https://github.com/cmsimple-xh/xhshop/issues/79#issuecomment-314523070 kam die Frage auf

> Übrigens Obst. Warum sind das denn so Megadateien?

Eine gute Demo darf nicht geizen – und ich finde die jetzige schon sehr gelungen (großes Lob an Frank!)

Allerdings ist die Frage nicht unbegründet, weil die Demo-Bilder derzeit schon fast 4 MB umfassen. Der eigentliche Plugin-Ordner ist komprimiert nur 135 KB groß. Ich denke, wir sollten die späteren Download-Pakete aufteilen, und das Plugin und den Demo-Content getrennt anbieten. Gerade diejenigen, die nur eine bestehende Installation aktualisieren wollen, können so eine Menge Bandbreite sparen. Ein bisschen doof ist das für diejenigen, die nur mal schnell ausprobieren wollen. Na ja, vielleicht können auch diese mit zwei Downloads leben. Falls das ein Problem ist, dann könnten wir auch ein Kombi-Paket (Plugin + Demo-Content) zusätzlich anbieten, und vielleicht dafür kein separates Demo-Content-Paket.

**Comment by XHalbert** [comment]
Ja "großes Lob an Frank", dem schließe ich mich an.
Die Bilder sind gestochen scharf und wirken sehr ansprechend.

So schlimm finde ich die Bildgrößen nun auch wieder nicht, dass dafür ein separater Download nötig wäre. Mir fällt halt vor allem beim Upload auf, dass es recht lange dauert. Ich habe eine 16k-Leitung. Handy noch wesentlich langsamer.
Ich hatte aber vor allem an den Seitenaufbau gedacht beim Testen.
Google Page Speed meldet:
![neu-1](https://user-images.githubusercontent.com/29812782/28103882-83309d18-66d8-11e7-97cb-f353018e9c8f.JPG)

Bei Klick von der Startseite http://fhs.bplaced.net/xhshop-demo  auf Shop  dauert es auf meinem Handy 5 sec.
Sorry, ich mecker ja nicht, will nur helfen.

> mit zwei Downloads

die Bilder sind ja nur bei Erstinstallation ein Thema. Später wird es wohl Updates ohne Bilder geben?

**Comment by frase-git** [comment]
Tja, da sprecht ihr (für mich) heikle Themen an.

**Zu Bildgrößen**
Meine Überlegungen:
Will man Interesse wecken, muss es (einigermaßen) gut aussehen. Der alte wellrad hatte mini-Bilder, die mir von Anfang an aufgestoßen sind. Nutzer mit riesigen Bildschirmen fangen (im günstigsten Fall) an zu lachen, wenn sie die Fancybox anklicken und es erscheint ein Bild in Fliegenschissgröße.
Andererseits könnte es sein, dass es in Bezug auf die Kompressionsrate mit mir etwas durchgegangen ist. Ich werde mal schauen, ob ich da noch runterschrauben kann. (Google Page-Speed wirst du nie zufrieden stellen können)

Das zweite heikle Thema: **getrennte Downloads**
Meine Überlegungen:
Wir müssen uns von dem Gedanken verabschieden, dass der Nutzer sich der Technik unterordnen muss. Diese Philosphie zieht nicht mehr. Alles soll "mit einem Klick" passen - aus User-Sicht. Und das wird demnächst noch schlimmer, wenn die User nur noch mit ihrem Rechner "sprechen" wollen und nicht mehr tippen, wischen oder gar klicken. (Alexa, Siri & Co)
Deshalb mein Vorschlag, der im Wesentlichen euren Vorschlägen (oben) entspricht:
1. Starter-Download = alles inklusive (für Neulinge und Schnell-Tester)
2. Update-Download = nur Plugin (für alte Hasen)
3. Demo-Content-Download

Bleibt die Frage, ob im Update ein config-Ordner sein soll.
Oder die `config.php` auch noch in den XH-Content-Ordner?

**Comment by frase-git** [comment]
Gesagt - getan.
unkomprimiert: vorher 3,5MB / nachher 2,1MB

[demo-images.zip](https://github.com/cmsimple-xh/xhshop/files/1141173/demo-images.zip)

**Comment by XHalbert** [comment]
Kompliment

**Comment by cmb69** [comment]
> unkomprimiert: vorher 3,5MB / nachher 2,1MB

Super! Eingespielt: d769393.

> Bleibt die Frage, ob im Update ein config-Ordner sein soll.
Oder die config.php auch noch in den XH-Content-Ordner?

Das geht schon technisch nicht, weil `config.php` von CMSimple_XH im Pluginordner erwartet wird. Bezüglich Updates könnten wir es aber so machen wie bei CMSimple_XH: es werden Patches ausgeliefert, die nur geänderte Dateien enthalten, aber auf keinen Fall config.php, Sprachdateien (außer default.php) und stylesheet.css.

> Deshalb mein Vorschlag, der im Wesentlichen euren Vorschlägen (oben) entspricht:
[3 Downloads]

Soll mir recht sein. Wir müssen dann nur gut dokumentieren, wohin die unterschiedlichen Pakete entpackt werden müssen (root vs. `plugins/`) oder auch das reine Plugin-Zip so gestalten, dass es ebenfalls ins Root entpackt werden muss.

Da nun die Bilder doch deutlich kleiner geworden sind, und wenn wir später Update-Pakete anbieten, dann sind unterschiedliche Downloads aber vielleicht auch gar nicht mehr so sinnvoll. Gerade Franks Argument, dass alles mit einem Klick passen soll, zieht vielleicht auch hier: der User will gar nicht lange lesen, was er nun herunter laden soll.

**Comment by frase-git** [comment]
Dann:
nur 2 Downloads:
1. alles
2. Updates

**Comment by cmb69** [comment]
> nur 2 Downloads:
>
> alles
Updates

Okay. Es gibt jetzt `build` und `build-patch` für Phing, [analog zu CMSimple_XH](http://www.cmsimple-xh.org/wiki/doku.php/development_environment#building). Ich denke, dieses Ticket kann geschlossen werden.
