### ISSUE TITLE
Improve folder help texts in configuration

### ISSUE THREAD

**Issue by XHalbert** [cmsimple-xh/xhshop#84]
habe eben auf demo-content umgestellt. 
In config hatte ich früher den Pfad zum imagefolder gelöscht. Was jetzt reinschreiben?
Hilfetext unter dem Fragezeichen:
"Ein Ordner relativ zum Bilderordner von CMSimple_XH, in dem die Artikel-Bilder gespeichert sind. Leer lassen, um den Bilderordner selbst zu verwenden."

Musste einiges rumprobieren bis es klappte.

Vllt. sollte es heißen:
""Ein Ordner relativ zum Bilderordner von CMSimple_XH, in dem die Artikel-Bilder gespeichert sind. 
Im  Format  " ./shop/  " oder " shop/"  . 
Leer lassen, um den Bilderordner selbst zu verwenden.""

**Comment by cmb69** [comment]
> Im Format " ./shop/ " oder " shop/" .

Guter Punkt! `./shop/` funktioniert zwar, aber ist unnötig aufwendig; `shop/` ist zu bevorzugen.

**Comment by XHalbert** [comment]
aber ohne " / " hinten geht nicht...

**Comment by cmb69** [comment]
> aber ohne " / " hinten geht nicht...

Nein, könnte aber geändert werden. Wäre das hilfreich?

**Comment by XHalbert** [comment]
Bestimmt, wär mir aber egal, wenn es unter dem Fragezeichen steht

**Comment by cmb69** [comment]
> Bestimmt, wär mir aber egal, wenn es unter dem Fragezeichen steht

Okay, dann beschränke ich es fürs erste auf den verbesserten Hilfetext.
