### ISSUE TITLE
AddToCartButton Hilfetext

### ISSUE THREAD

**Issue by XHalbert** [cmsimple-xh/xhshop#88]
die Frage: 

> aceaccis wrote:
also Anwählen = verlinken ok und wenn ich es nicht mehr möchte ? Ich finde keine Möglichkeit des abwählens .

tauchte schon öfters im Forum auf.
Wäre es nicht sinnvoll, direkt im Formular für "Artikel bearbeiten" oberhalb vom Feld für die Seitenauswahl einen kurzen Text einzufügen, etwa:
"Auswählen mit Klick, Abwählen und Mehrfachauswahl mit STRG Klick" ? (aber wie auf Handy?)

**Comment by frase-git** [comment]
Das sind Standard-Funktionen des Browsers und haben nichts mit dem Shop zu tun.
Aber 'ne kurze Hilfe ???

Jaaa, wie händeln die mobile-Browser das eigentlich?

**Comment by XHalbert** [comment]
> Das sind Standard-Funktionen des Browsers

die aber Viele nicht kennen

**Comment by frase-git** [comment]
Kurze Hilfe wäre gut - aber was hinschreiben? Ist ja nicht mehr einheitlich wie in der ddr, sondern jeder macht's anders ;-)))

Evtl.:

> Bestell-Button anlegen auf (Mehrfachauswahl möglich):

UND:

> Kategorien (Mehrfachauswahl möglich):

Der Hinweis auf Mehrfachauswahl sollte genügen. Da erinnert man sich an seine Browserfunktionen - oder muss in der Hilfe nachsehen - auch für's Abwählen.

FF unter Android gibt bei Mehrfachauswahl eine komplette Liste aus, in der man Häkchen setzen kann.
Das ist sehr gut!

Eben getestet: Chrome unter Android bietet ebenfalls die komplette Liste mit Häkchen.

**Comment by cmb69** [comment]
> Das sind Standard-Funktionen des Browsers und haben nichts mit dem Shop zu tun.

Und vor allem funktioniert das auf verschiedenen Browsern möglicherweise völlig unterschiedlich. 

> Jaaa, wie händeln die mobile-Browser das eigentlich?

Möglicherweise so: https://ux.stackexchange.com/questions/84233/multiple-selection-on-ipad

Vielleicht sollten wir uns aber von den Multi-Selects ganz verabschieden, und statt dessen Checkboxen anbieten?

**Comment by frase-git** [comment]
Mobiles: siehe meinen Post vor deinem.

> Vielleicht sollten wir uns aber von den Multi-Selects ganz verabschieden, und statt dessen Checkboxen anbieten?

Schwierig. Das eine ist eine Auswahl aller vorhandenen Seiten im CMS. Das könnten schonmal sehr viele werden.
Und auch Kategorien könnten viele sein.

**Comment by cmb69** [comment]
> Mobiles: siehe meinen Post vor deinem.

Ja, hatte ich schon. :) Ist halt unklar, ob es andere auch so elegant machen.

> Das eine ist eine Auswahl aller vorhandenen Seiten im CMS. Das könnten schonmal sehr viele werden.

Na ja, das Markup wird deutlicher umfangreicher, aber die sichtbare Größe kann wie jetzt auch beschränkt werden. Und man könnte auch ein Multi-Select ausgeben, dieses aber per JS zu einer Liste mit Checkboxen machen.

Ich kann aber auf jeden Fall mit den Multiselects leben. Als Hilfetext würde ich aber nur erwähnen, dass Mehrfachauswahl möglich ist. Weitere Erklärungen dann im Wiki.

**Comment by frase-git** [comment]
> Ich kann aber auf jeden Fall mit den Multiselects leben.

Und alle anderen sicher auch.

> Als Hilfetext würde ich aber nur erwähnen, dass Mehrfachauswahl möglich ist.

Genau.

> Weitere Erklärungen dann im Wiki.

Immer auf mich ... ;-)))

**Comment by cmb69** [comment]
> Als Hilfetext würde ich aber nur erwähnen, dass Mehrfachauswahl möglich ist.

Erledigt.

> Immer auf mich ... ;-)))

Selbst schuld. :p

**Comment by frase-git** [comment]
[dokumentiert](https://github.com/cmsimple-xh/xhshop/wiki/Artikel-bearbeiten/_edit#artikel-bearbeiten)

**Comment by XHalbert** [comment]
sehr schön, mann da steckt ja jede Menge Arbeit drin...

> Bitte beachten: Es ist zurzeit nicht möglich kostenlose Artikel (Einzelpreis = 0,00) über den Shop abzugeben.

ist das so? (bei mir gehts, oder hab ich ein update verpasst)

**Comment by cmb69** [comment]
> ist das so? (bei mir gehts, oder hab ich ein update verpasst)

Man kann kostenlose Artikel anbieten, aber dann stimmt u.U. die Mehrwertsteuerberechnung der Versandkosten und Gebühr nicht mehr, siehe https://github.com/cmsimple-xh/xhshop/issues/121#issuecomment-317035214. Sollte man also besser nicht tun.

**Comment by frase-git** [comment]
Das war deine eigene Feststellung (Albert).
https://github.com/cmsimple-xh/xhshop/issues/121#issuecomment-317092860

**Comment by XHalbert** [comment]
na nicht ganz... verboten und nicht möglich ist ein Unterschied
na ich will nicht wieder der Besserwisser sein, obwohl bin ich ja, trotzdem fänd ich besser, kurz auf die Problematik "durchschnittlicher Mehrwertsteuersatz bei kostenlosen Artikeln" einzugehen.

**Comment by cmb69** [comment]
> trotzdem fänd ich besser, kurz auf die Problematik "durchschnittlicher Mehrwertsteuersatz bei kostenlosen Artikeln" einzugehen.

Wartet da noch mal ab. Vielleicht bekomme ich das noch in den Griff. Die ganze Logik muss sowieso überarbeitet werden, wenn wir uns von `floats` verabschieden wollen (#114).
