### ISSUE TITLE
Error handling of bill writing is broken

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#89]
Wenn beim Kauf ein Fehler beim Erstellen der Rechnung auftritt, dann soll eine [Fehlermeldung ausgegeben, und die weitere Behandlung abgebrochen](https://github.com/cmsimple-xh/xhshop/blob/d7693933ae762cb5a4b80283e3f4fa70eb7dd757/classes/FrontEndController.php#L429-L432) werden (also keine Emails; keine Bestellung).

Nun ist es aber so, dass der einzige Fall, bei dem das Erstellen der Rechnung fehlschlägt, das [Nichtvorhandensein von `template.rtf`](https://github.com/cmsimple-xh/xhshop/blob/d7693933ae762cb5a4b80283e3f4fa70eb7dd757/classes/FrontEndController.php#L514) ist. In diesem Fall wird aber eine Fehlermeldung als Zeichenkette zurück geliefert, so dass die oben geschilderte Fehlerbehandlung nie greift ([`$bill`](https://github.com/cmsimple-xh/xhshop/blob/d7693933ae762cb5a4b80283e3f4fa70eb7dd757/classes/FrontEndController.php#L427) ist immer wahr).

Es werden also die E-Mails verschickt, aber `bill.rtf` enthält nur den Text "template for bill not found".

Da `bill.rtf` für die Bestellung nicht unbedingt erforderlich ist, finde ich dieses Verhalten eigentlich viel besser, als den Bestellvorgang einfach abzubrechen, wie wohl ursprünglich vorgesehen war. Ich würde daher die [Fehlerbehandlung](https://github.com/cmsimple-xh/xhshop/blob/d7693933ae762cb5a4b80283e3f4fa70eb7dd757/classes/FrontEndController.php#L427-L433) komplett entfernen, und nur die Meldung "template for bill not found" internationalisieren.

**Comment by frase-git** [comment]
Das überblicke ich technisch nicht ganz.

Eben getestet in der Online-Demo:
Im Ordner bills die rtf entfernt.
Bestellt.
Step 3: Jetzt kaufen.

> Fatal error: Class 'Xhshop\BillWriter' not found in ... /xhshop-demo/plugins/xhshop/classes/FrontEndController.php on line 448

**Comment by cmb69** [comment]
> Fatal error: Class 'Xhshop\BillWriter' not found in ... /xhshop-demo/plugins/xhshop/classes/FrontEndController.php on line 448

Da stimmt dann aber was anderes nicht. Bist du unter XH 1.6 oder 1.7?

**Comment by frase-git** [comment]
XH 1.7
PHP 5.6.x
Eben nochmal den aktuellen master aufgespielt.
Jetzt Meldung:

> Fatal error: Class 'Xhshop\BillWriter' not found in /users/fhs/www/xhshop-demo/plugins/xhshop/classes/FrontEndController.php on line 409

Warte mal noch. Ich prüfe und cleare nochmal alles und teste dann nochmal.

**Comment by frase-git** [comment]
Also;
Alles bereinigt. Browser neu gestartet.
Fehler bleibt: http://fhs.bplaced.net/xhshop-demo/?Shop

Local unter xampp:
Bestellung geht problemlos durch.
Im Mailoutput_ordner landen 2 passende Mails.
???

**Comment by cmb69** [comment]
> BillWriter

Gut, dass auch jemand unter Linux testet. Die Datei heißt nämlich `Billwriter.php` (kleines w), das passt dort nicht (Windows NTFS ist case-insensitive, also da kein Problem). Behoben mit 972b69b. Bitte einfach die Datei in classes/ umbennen (kann sein, dass dein FTP-Client diesbezüglich Zicken macht).

> Im Mailoutput_ordner landen 2 passende Mails.

Schau dir dort den Anhang `bill.rtf` mal an.

**Comment by frase-git** [comment]
Gerade mal die Datei online ausgetauscht.
Geht wieder !
Dummerweise habe ich die E-Mail-Adresse noch auf example !!!
Habe also Bestätigungsmail aber keine Rechnung - ich Dummer.
Hols nach.

**Comment by frase-git** [comment]
So.
Online bill.rtf erhalten.
Wonach soll ich schauen?
Mir fällt nur auf, dass die Shop-Adresse (Kopf) fehlt.
Nochwas?

**Comment by cmb69** [comment]
> Dummerweise habe ich die E-Mail-Adresse noch auf example !!!

Du kannst das auch lokal testen. Bei XAMPP ist ein hilfreiches Script dabei, dass die Mails einfach nur im `mailoutput/ ordner` speichert, so dass man hemmungslos testen kann. Dazu in `php.ini` den entsprecheden Eintrag ändern:
````
sendmail_path="C:\xampp56\mailtodisk\mailtodisk.exe"
````
Pfad nach Bedarf anpassen. Und wenn du die erzeugten `.txt` zu `.eml` umbenennst, dann kannst du die Mail ein Thunderbird öffnen lassen.

> Wonach soll ich schauen?

Wenn `template.rtf` fehlt, dann sollte `bill.rtf` eigentlich nur "template for bill not found" enthalten.

**Comment by frase-git** [comment]
> Schau dir dort den Anhang bill.rtf mal an.

Wenn ich das im xampp-mailoutput anschaue sieht das so aus:

```
Content-Type: text/rtf; name="bill.rtf"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=bill.rtf

e1xydGYxXGFkZWZsYW5nMTAyNVxhbnNpXGFuc2ljcGcxMjUyXHVjMVxhZGVmZjJcZGVmZjBcc3Rz
aGZkYmNoMzE1MDVcc3RzaGZsb2NoMzE1MDZcc3RzaGZoaWNoMzE1MDZcc3RzaGZiaTMxNTA3XGRl
ZmxhbmcxMDMxXGRlZmxhbmdmZTEwMzFcdGhlbWVsYW5nMTAzMVx0aGVtZWxhbmdmZTBcdGhlbWVs
YW5nY3Mwe1xmb250dGJse1xmMFxmYmlkaSBcZnJvbWFuXGZjaGFyc2V0MFxmcHJxMntcKlxwYW5v ...
```

**Comment by frase-git** [comment]
> Wenn template.rtf fehlt, dann sollte bill.rtf eigentlich nur "template for bill not found" enthalten.

Ach so!
Da muss ich die rtf nochmal killen.
Melde mich.

**Comment by cmb69** [comment]
> Wenn ich das im xampp-mailoutput anschaue sieht das so aus:

.txt in .eml umbenennen und mit Thunderbird öffnen!

**Comment by frase-git** [comment]
Also klappt wie erwartet.
Bei fehlender rtf steht in bill.rtf nur und nichts anderes:

> template for bill not found

Local das Gleiche im Adminmodus getestet:
Läuft, aber Debug meldet:

> WARNING: fopen(./plugins/xhshop/bills/template.rtf): failed to open stream: No such file or directory
> ... \plugins\xhshop\classes\BillWriter.php:12

Was wohl logisch sein dürfte.

(was mache ich nur mit den ganzen Schraubendrehern und Splittern? Alles voll hier.)

**Comment by cmb69** [comment]
> Läuft, aber Debug meldet:

Ja, das ist auch kein Problem.

Die Frage ist halt: was machen. Einfach das jetzige Verhalten belassen (Text aber internationalisieren), und die ursprünglich gedachte Fehlerbehandlung entfernen (da sie ja nie ausgelöst wird)?

**Comment by frase-git** [comment]
Da kann ich dir nicht weiterhelfen.
Ich überschaue die Folgen nicht.

Und (bitte nicht schlagen!) die bill.rtf hasse ich wie die Pest ;-)))
Wer soll denn das pflegen/verändern?
Da muss uns noch was einfallen.

**Comment by cmb69** [comment]
> Da kann ich dir nicht weiterhelfen.
Ich überschaue die Folgen nicht.

Wenn die ursprünglich gedachte Fehlerbehandlung gefixt wird, dann wird im Fall dass `template.rtf` fehlt eben keine Bestellung ausgelöst. Wäre das zu bevorzugen?

> Und (bitte nicht schlagen!) die bill.rtf hasse ich wie die Pest ;-)))

Das gehört in #18. :)

**Comment by frase-git** [comment]
> Wenn die ursprünglich gedachte Fehlerbehandlung gefixt wird, dann wird im Fall dass template.rtf fehlt eben keine Bestellung ausgelöst. Wäre das zu bevorzugen?

Glaube nicht.
Unter dem Vorbehalt, dass ich jetzt nicht durchanand bin:
So, wie es eben lief, is doch gut - oder?
Mails werden verschickt und der Betreiber merkt, dass auf dem Server was fehlt (falls er mutig ist und in die bill.rtf wirklich reinschaut).

**Comment by cmb69** [comment]
> So, wie es eben lief, is doch gut - oder?

Ja, finde ich auch. Ich wollte mich nur absichern. Ich schmeiße dann die sowieso nicht funktionierende Fehlerbehandlung raus.

**Comment by XHalbert** [comment]
> die bill.rtf hasse ich wie die Pest

und ich liebe die template.rtf
(ich weiss, das gehört in #18. )

**Comment by cmb69** [comment]
> und ich liebe die template.rtf

@XHalbert Magst du dann vielleicht im Wiki erklären wie man die `template.rtf` für eigene Zwecke anpassen kann?

**Comment by frase-git** [comment]
https://github.com/cmsimple-xh/xhshop/wiki/Tipps#templatertf-f%C3%BCr-eigene-zwecke-anpassen

Nur mal als vorläufiger Ort.

**Comment by XHalbert** [comment]
> @XHalbert Magst du dann vielleicht im Wiki erklären wie man die template.rtf für eigene Zwecke anpassen kann?

klar, gerne

**Comment by XHalbert** [comment]
Entwurf fürs WIKI:
Die Bestellbestätigungs-Email, die der Shopbetreiber erhält, enthält eine Rechnungsvorlage "bill.rtf" im Anhang. Die Rechnungsgestaltung ist in der Datei template.rtf (Rich Text Format) festgelegt, die im Ordner plugins/xhshop/bills liegt. Du kannst "template.rtf" beliebig umgestalten, Texte, Grafik oder Tabellen hinzufügen, formatieren, ändern oder löschen. Es ist sinnvoll, zu Beginn eine Sicherungskopie von template.rtf anzulegen. Die gemachten Änderungen in "template.rtf" siehst du nach einem Testkauf in der "bill.rtf".
XH-Shop ersetzt bei der Rechnungsgenerierung nur die in %-Zeichen eingebetteten Platzhalter durch den richtigen Inhalt. Die %Platzhalter% werden also mit Inhalt gefüllt. Du kannst sie natürlich auch an andere Textstellen oder in eine selbst gestaltete Tabelle verschieben oder kopieren, oder je nach Bedarf auch löschen. Eine Tabelle (oder mehrere) bietet sich an, wenn du die Daten aus der "bill.rtf" in eine eigene Kunden- oder Rechnungsverwaltung (z.B. Exel) importieren willst. Du brauchst dann nur die Tabellenfelder markieren und ziehst sie in deine Datenbank.

**Comment by cmb69** [comment]
> Entwurf fürs WIKI:

Danke!

Ich habe dich jetzt mal als Mitarbeiter eingeladen. Du solltest eine Mail erhalten, die du bestätigen müsstest. Wenn du magst, kannst du dann den Text selbst ins Wiki stellen.

**Comment by frase-git** [comment]
Deinen Entwurf habe ich vorläufig reingesetzt. Kannste ändern ;-)

**Comment by XHalbert** [comment]
> als Mitarbeiter eingeladen

das ist ja "nett" - eine "Einladung" zur Arbeit (warn Scherz, ich helfe gern, wenn ich kann)

**Comment by cmb69** [comment]
> Kannste ändern ;-)

Vielleicht noch kurz die Besonderheiten der Artikelzeile erwähnen.

**Comment by XHalbert** [comment]
hab noch keine "Einladung" erhalten

**Comment by frase-git** [comment]
Vielleicht bist du schon Mitglied?
Gehe mal ins Wiki. Rufe die Seite "Tipps" auf.
Wenn du rechts oben zwei Buttons "Edit" (grau) und "New Page" (grün) siehst, kannst du loslegen.

**Comment by cmb69** [comment]
> hab noch keine "Einladung" erhalten

Hm, bei den Collaborators stehe "Awaiting XHAlbert's response". Vielleicht wird auch keine E-Mail verschickt. Schau mal unter https://github.com/XHalbert nach; da sollte was angezeigt werden.

**Comment by XHalbert** [comment]
kann nirgendwo was finden

**Comment by XHalbert** [comment]
sind keine buttons da

**Comment by cmb69** [comment]
> kann nirgendwo was finden

Ist unter https://github.com/notifications oder https://github.com/settings/organizations was zu finden?

**Comment by XHalbert** [comment]
nein

**Comment by cmb69** [comment]
> nein

@frase-git Kannst du dich noch erinnern, wie das bei deiner Einladung war?

**Comment by frase-git** [comment]
Absender: Christoph M. Becker <noreply@github.com>
Betreff: cmb69 invited you to cmsimple-xh/xhshop
Text: (mit einem großen blauen Button)
```
@cmb69 has invited you to collaborate on the
cmsimple-xh/xhshop repository

You can accept or decline this invitation. You can also head over to https://github.com/cmsimple-xh/xhshop to check out the repository or visit @cmb69 to learn a bit more about them.
View invitation

Note: This invitation was intended for xxx. If you were not expecting this invitation, you can ignore this email. If @cmb69 is sending you too many emails, you can block them or report abuse. 
```

**Comment by XHalbert** [comment]
weiß nicht ob das war? Keep my email address private war angekreuzt
geändert und zusätzlich eine 2. Email angelegt
magst du mich nochmal einladen?

**Comment by cmb69** [comment]
> magst du mich nochmal einladen?

Getan!

**Comment by XHalbert** [comment]
hat diesmal geklappt, an die erste Emailadresse, war wohl die private-Einstellung

**Comment by cmb69** [comment]
> hat diesmal geklappt,

Super! Willkommen im Club! :)

**Comment by XHalbert** [comment]
hab bearbeitet
https://github.com/cmsimple-xh/xhshop/wiki/Tipps#templatertf-f%C3%BCr-eigene-zwecke-anpassen
ok so?

**Comment by frase-git** [comment]
Gut.
Nur leider hat sich der Pfad geändert. Und wohl auch der Name von template.rtf - was mich jetzt wundert.
@cmb69 
heißt die template jetzt bill?

**Comment by cmb69** [comment]
> heißt die template jetzt bill?

Ja; es fiel mir bei der Umbenennung erst auf, dass wir sonst `templates/frontend/confirmation_email/template.rtf` hätten. Wäre total unklar, was gemeint ist. `bill.rtf` kann natürlich bzgl. der erzeugten `bill.rtf` irritieren. `bill.tpl` hätte den Nachteil dass einerseits die Dateiendung nicht passt (Öffnen per Explorer), und andererseits würde man dann meinen können, dass diese Datei durch `themes/frontend/confirmation_email/bill.tpl` übersteuert werden könnte, was aber nicht implementiert ist. Vielleicht sollte das aber gemacht werden, und die Datei in `bill.tpl.rtf` oder so umbenannt werden?

**Comment by frase-git** [comment]
Ich fürchte, da wird es Protest von Albert geben. Und ich würde den unterstützen.
`bill.rtf` als Name für die Vorlage UND als Name für die verschickte Rechnung - das geht nicht.
Schon deshalb, weil es im Wiki kaum zu erklären wäre.

Vorschlag:
Die Vorlage (beim Betreiber) nennen: `billtemplate.rtf` (statt früher `template.rtf`).
Die verschickte kann `bill.rtf` bleiben.

**Comment by XHalbert** [comment]
> billtemplate.rtf

klingt gut

**Comment by cmb69** [comment]
> Die Vorlage (beim Betreiber) nennen: billtemplate.rtf (statt früher template.rtf).

Gute Idee! Gleich umgesetzt.

**Comment by XHalbert** [comment]
hab billtemplate.rtf bearbeitet
https://github.com/cmsimple-xh/xhshop/wiki/Tipps#rechnungsvorlage-f%C3%BCr-eigene-zwecke-anpassen
und Überschrift geändert
ok so?

**Comment by cmb69** [comment]
> ok so?

Ja, prima. Siehe allerdings #107.
