### ISSUE TITLE
bill.rtf: order line total is always in €

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#92]
Ganz egal was man als Währungssymbol (`shop_default_currency`) einstellt, wird in der Rechnung (`bill.rtf`) die Artikelsumme immer in Euro angegeben.

**Comment by frase-git** [comment]
BillWriter.php
```php
if ($currency == '&euro;' || $currency == '€') {
```
Wann tritt denn diese Bedingung ein (erster Teil)?
An welcher Stelle ist da jemals `&euro;`?
In config.php wird doch nur gespeichert:
```php
$plugin_cf['xhshop']['shop_default_currency']="€";
```

**Comment by cmb69** [comment]
> Wann tritt denn diese Bedingung ein?

Ich denke das `&euro;` war nicht untypisch für noch nicht UTF-8 kodierte CMSimples. Das eigentliche Problem ist aber der ursprüngliche Code
````
if ($currency == '&euro;' || '€') {
````
`$currency` ist eben nicht gleich `'&euro;'`, und daher wird `'€'` ausgewertet, was immer `true` ist, so dass die Währung in der [darauf folgenden Zeile](https://github.com/cmsimple-xh/xhshop/blob/e7d2082d1b75c2e8afd3456b08ed4653e7e97d74/classes/BillWriter.php#L35) auf Euro festgelegt  wird.

Der Fix e7d2082 behebt nur dieses Problemchen – weiteres ist in Arbeit. :)

**Comment by frase-git** [comment]
Es wird dir nicht wirklich helfen, aber ich habe einen alten Thread gefunden, der sich mit RTF und utf-8 beschäftigt. Vielleicht gibt es da Anregungen?

https://forum.selfhtml.org/self/2008/mar/1/rtf-datei-utf-8-codiert/1219072

**Comment by frase-git** [comment]
Sorry, ich höre gleich auf mit den Tipps ... ;-)

> Im nächsten Schritt müssen Sie der Datei noch die Endung .php hinzufügen. Dazu benennen Sie im Windowsexplorer die Datei einfach um und hängen die Endung dran.  Die umbenannte Datei können Sie mittels PHP einlesen und bearbeiten!

Im folgenden Link fand ich interessant, was der Typ (ganz zum Schluss) sendet:
`header('Content-Type: application/rtf;charset=utf-8');`

https://www.mbdus.de/php-eine-dynamische-worddatei-erstellen-und-aufrufen/

**Comment by cmb69** [comment]
> Vielleicht gibt es da Anregungen?

Eher die Bestätigung, dass es so wie ich es mir vorgestellt habe wohl wirklich okay sein sollte. :)

> Im folgenden Link fand ich interessant, was der Typ (ganz zum Schluss) sendet:
header('Content-Type: application/rtf;charset=utf-8');

Solche Content-Type-Header braucht man immer, wenn man nicht-HTML direkt im Browser anzeigen bzw. zum Download anbieten will. Das ist bei `bill.rtf` aber nicht relevant, die die Datei ja als E-Mail-Anhang verwendet wird. Allerdings dennoch ein sehr guter Hinweis, denn der PHP-Mailer verwendet [`text/rtf` als Mime-Type für RTF](https://github.com/cmsimple-xh/xhshop/blob/e7d2082d1b75c2e8afd3456b08ed4653e7e97d74/phpmailer/class.phpmailer.php#L3598), obwohl ich bei meiner Recherche immer auf `application/rtf` gestoßen bin. Schau ich mir näher an.

PS: Nö, beide Mime-Typen sind erlaubt: https://www.iana.org/assignments/media-types/media-types.xhtml. Also alles gut.
