### ISSUE TITLE
Hard coded currency symbols in template.rtf

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#94]
In `template.rtf` sind Währungsymbole hart kodiert was völlig unnötig ist, da diese genau wie bei den Artikelpreisen beim Erzeugen der Rechnung automatisch ergänzt werden können.

**Comment by frase-git** [comment]
![bill](https://user-images.githubusercontent.com/24246330/28165752-73a93032-67d5-11e7-96c8-188a73071b18.png)

Ich wusste jetzt nicht, wohin damit.
Is ja nur 'ne Info.
Bill kommt also richtig an. € im Artikelnamen ist OK.
Nur an den Texten müssen wir noch schleifen.
Und die Tabelle sollte auch mal formatiert werden (Padding ...)

**Comment by cmb69** [comment]
> Nur an den Texten müssen wir noch schleifen.

Ja. Wobei die Anrede frühestens gefixt werden kann, wenn diese explizit bei den Kontaktdaten erfasst wird. Und insgesamt fehlt die Internationalisierung für mehrsprachige Shops; in Zweitsprachen ist das "Drumherum" von `bill.rtf` immer in der gleichen Sprache, aber die Produktbezeichnungen eben in der jeweiligen Sprache. Da könnte man etwas wie `template_en.rtf` ermöglichen; ist kein Template für die aktuelle Sprache vorhanden, wird auf `template.rtf` zurück gegriffen. Ach ja, der Name `bill.rtf` sollte eigentlich auch internationalisiert werden.

> Und die Tabelle sollte auch mal formatiert werden (Padding ...)

Ja, sieht grausig aus. Leider sind Anpassungen am Tabellenlayout nur etwas für recht fortgeschrittene Anwender (wenn überhaupt); ich schau mal.

**Comment by cmb69** [comment]
> Und die Tabelle sollte auch mal formatiert werden (Padding ...)

Schau mal:
[template.zip](https://github.com/cmsimple-xh/xhshop/files/1145546/template.zip)

**Comment by frase-git** [comment]
Ja, Padding ist drin.
Die Rechnung sollte aber in einen DIN Fensterumschlag passen. Die Absenderzeile im Fenster kleiner ...
Aber gut. Das sind dann wohl nur noch Peanuts.
Gute Arbeit 😁

**Comment by cmb69** [comment]
> Die Rechnung sollte aber in einen DIN Fensterumschlag passen. Die Absenderzeile im Fenster kleiner ...
Aber gut. Das sind dann wohl nur noch Peanuts.

Vielleicht magst du dich bei Gelegenheit mal "austoben"? :)

**Comment by frase-git** [comment]
Mögen gar nicht. ;-)
Und "Gelegenheit" dürfte auch nicht so bald kommen.
Es sei denn: Die Prioritäten werden verschoben.

**Comment by cmb69** [comment]
> Mögen gar nicht. ;-)
Und "Gelegenheit" dürfte auch nicht so bald kommen.

Okay, du machst sowieso schon viel. :)
