### ISSUE TITLE
config: use categories

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#95]
```php
$plugin_cf['xhshop']['categories_use_categories']="true";
$plugin_cf['xhshop']['categories_allow_show_all']="true";
```
Ich bin mir nicht sicher, ob diese beiden config-Optionen die gewünschte Wirkung haben.
Schalte ich `categories_use_categories` aus, wird die Kategorieauswahl dennoch angezeigt (bei Demo mit Artikeln, die eine Kategoriezordnung haben.)

**Comment by cmb69** [comment]
> Ich bin mir nicht sicher, ob diese beiden config-Optionen die gewünschte Wirkung haben.

`categories_allow_show_all` müsste funktionieren, aber `categories_use_categories` funktioniert tatsächlich nicht, weil auf `'false'` oder `'0'` geprüft wird, aber nicht auf `''`.

PS: da das bei Wellrad 1.2.1 wohl noch gepasst hat, kein Milestone.

**Comment by cmb69** [comment]
Im Frontend sollte nun alles passen, aber im Backend wird die Kategorieauswahlliste dennoch angezeigt. Bin nicht sicher, aber vermutlich ist das Absicht. Was meinst du, @frase-git?

**Comment by frase-git** [comment]
Erstmal so lassen.
Ich kann jetzt auch nicht testen, was passiert, wenn auch keine Kategorien definiert sind ...
Frontend passt.
Feedback im Forum wird kommen ...

**Comment by cmb69** [comment]
> Erstmal so lassen.

Gut.

**Comment by frase-git** [comment]
Reopened:
Wenn `categories_use_categories` = false, 0 oder '' ist, sollte dann die Kategorienverwaltung in der Plugin-Konfig nicht ausgeblendet werden?
Oder zumindest oben deutlich Hinweis:
Kategorien sind zurzeit nicht aktiv - siehe Konfiguration.

**Comment by cmb69** [comment]
> Wenn categories_use_categories = false, 0 oder '' ist, sollte dann die Kategorienverwaltung in der Plugin-Konfig nicht ausgeblendet werden?

Ja. Aber sollte konsequenterweise dann nicht auch die Kategoriezuordnung zum Artikel (multi-select) ausgeblendet werden?

**Comment by frase-git** [comment]
Hast Recht. Fände ich aber zu aufwendig.
Wie wär's nur mit dem Hinweis?

**Comment by cmb69** [comment]
> Hast Recht. Fände ich aber zu aufwendig.

Hier kann man ruhig mal etwas "schludrig" sein, denke ich, und einfach das `<tr>` auf `display:none` setzen; das sind nur wenige Zeilen Code.

**Comment by frase-git** [comment]
okay
