### ISSUE TITLE
Improve customizability of template.rtf

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/xhshop#96]
Während viele Anpassungen an `template.rtf` leicht machbar sind, sind Anpassungen an den Artikel-Zeilen praktisch unmöglich, weil die Zeilen in `BillWriter.php` hart kodiert sind. Das wiederum macht es sehr schwer, das Layout der Haupttabelle zu beinflussen. Schöner wäre es, wenn in `template.rtf` eine Zeile für den Artikel mit entsprechenden Platzhaltern für die Details (Anzahl, Name, etc.) vorgegeben werden könnte, und der BillWriter diese entsprechend vervielfachen und ausfüllen würde.

**Comment by frase-git** [comment]
Daran habe ich mir vor Jahren schon die Zähne ausgebissen.
Und ich kann ein leichtes Schmunzeln nicht verheimlichen - ich hatte euch dahingehend informiert ("Pest") ;-)))
Schon wieder 2 Tage rum mit bill.rtf.

(Ein bisschen Schadenfreude ist auch 'ne Freude)

**Comment by cmb69** [comment]
> "Pest"

Die Pest kann ich nicht heilen, aber dieses Problem sollte gelöst sein.

**Comment by frase-git** [comment]
Auch, wenn ich hämisch war - gut gemacht!
Kommt alles sauber an.
jetzt nur noch die Frage:
Wird es für @XHalbert einfacher oder schwieriger, etwas an der `template.rtf` anzupassen?

**Comment by XHalbert** [comment]
> Wird es für @XHalbert einfacher oder schwieriger

wenn ich das richtig verstehe, ist jetzt statt %rows% eine Tabelle mit je 1 Artikel pro Zeile,  und Spalten für Anzahl, Bezeichnung, Varianten, Einzelpreis, Gesamt - das wär gut (aber für mich weder noch)

kann man das denn schon testen?

**Comment by cmb69** [comment]
> das wär gut (aber für mich weder noch)

Könnte auch für dich interessant sein, da du erwähnt hattest, dass du die %rows% hinter die Kundendaten setzen wolltest. Mit der neuen Variante kann man die Haupttabelle leicht aufteilen, wenn man möchte. Wichtig ist eigentlich nur, dass es eine Tabellenzeile mit `%pname%` gibt (und die anderen Produktplatzhalter entweder in dieser Zeile oder nirgends auftauchen).

> kann man das denn schon testen?

Ja. Einfach den aktuellen Master herunter laden.

**Comment by XHalbert** [comment]
Hab template.zip jetzt gesehen. Kompliment, dass du %rows% auflösen konntest.
Ich würde für meine Weiterverarbeitung brauchen, dass die Artikel-Tabelle separat zu SUMME, SHIPPING, FEE, ENDSUMME kommt, die dann in einer zweiten Tabelle stehen. Das kann ich ja leicht selber machen.
Also alles gut (Ich müsste template.rtf ja sowieso bearbeiten, das ich ja noch mehr Felder brauche).
