### ISSUE TITLE
shop without email-adress

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#98]
Bei jedem Abgleich mit dem Master, erhalte ich die example-mail-Adresse zurück.
Okay. Ist schnell geändert.
Heute kam ich auf die Idee, das Feld mal leer zu lassen und einen Bestellvorgang durchzuziehen.
Das ist lustig. Am Ende kommt:

> Pardon! Obgleich eine E-Mail-Bestätigung an Sie versandt wurde, wurde Ihre Bestellung nicht an unseren Shop übermittelt!
> 
> Bitte informieren Sie uns per E-Mail:
> 
> Fehlermeldung: You must provide at least one recipient email address.

Bitte informieren Sie uns per E-Mail: Hier kann ja nichts stehen, wenn keine eingetragen ist ;-)
Vielleicht so: Bitte suchen sie auf unserer Seite. Irgendwo müsste unsere E-Mail-Adresse stehen. Oder ein Kontaktformular. Geben sie sich Mühe!
;-)))

Und die "Fehlermeldung" ist wohl auch eher an den Betreiber gerichtet?
Das sollte User nicht zu sehen bekommen.

**Comment by XHalbert** [comment]
> Und die "Fehlermeldung" ist wohl auch eher an den Betreiber gerichtet?
Das sollte User nicht zu sehen bekommen.

die ist NUR an den Kunden gerichtet - Shopbetreiber erhält nix (wie denn auch?)

**Comment by frase-git** [comment]
> Fehlermeldung: You must provide at least one recipient email address.

Ist nur an den Betreiber gerichtet - wird aber dem Kunden angezeigt.
Und das ist falsch.
Ich hatte das schon irgendwo mal angesprochen, dass geprüft werden sollte, ob der Betreiber während der Konfiguration auch wirklich eine Mail-Adresse eingegeben hat. (finds grade nicht)
Und deshalb sollte - so der Vorschlag - der Shop ohne `example@example.com`  ausgeliefert werden.
Solange da keine Adresse drin steht, sollte eine Fehlermeldung bei Shop-Aufruf erscheinen: nicht betriebsbereit. Natürlich können wir nicht prüfen, ob dann eine "echte" drinsteht.

**Comment by XHalbert** [comment]
Vorschlag:
1. "Order Email" ohne example@example.com ausliefern
2. in Systemprüfung: "Order Email" in config darf nicht leer sein
3. Fehlermeldung:
"Leider ist etwas schief gegangen. Ihre Bestellung konnte nicht weitergeleitet/gemailt werden. Bitte informieren Sie uns per Tel. oder Email oder probieren Sie es später nochmal. Danke!"

**Comment by XHalbert** [comment]
besser:
Fehlermeldung:
"Leider ist etwas schief gegangen. Sie haben zwar soeben ein Bestellbestätigung per Email erhalten. Die ist aber ungültig, weil Ihre Bestellung nicht an den Shopbetreiber weitergeleitet/gemailt werden konnte. Bitte informieren Sie uns per Tel. oder Email oder probieren Sie es später nochmal. Danke!"

**Comment by XHalbert** [comment]
wäre es nicht besser, in dem Fall auch dem Kunden keine Mail zu schicken?

**Comment by frase-git** [comment]
Es wäre besser, **vorher** zu prüfen, ob alles klar geht (soweit möglich) und diesen Fehler komplett zu vermeiden.

**Comment by cmb69** [comment]
> "Order Email" ohne example@example.com ausliefern
in Systemprüfung: "Order Email" in config darf nicht leer sein

Da stimme ich auf jeden Fall zu.

> Solange da keine Adresse drin steht, sollte eine Fehlermeldung bei Shop-Aufruf erscheinen: nicht betriebsbereit.

Finde ich übertrieben, und vielleicht auch Vortäuschung falscher Sicherheit. Man kann bei der Shop-Konfiguration viel schlimmeres tun als die E-Mail-Adresse zu vergessen, z.B. falsche Steuersätze eintragen, Produkte aus dem Demo-Shop übernehmen, die man gar nicht anbietet, falsche Preise, Versandkosten und was weiß ich. Das wenigste davon kann automatisiert geprüft werden.

Zur Fehlermeldung: das ist eine allgemeine, falls die Mail nicht verschickt werden konnte, was andere Ursachen als eine fehlende E-Mail-Adresse in der Konfiguration haben kann: Fehlkonfiguration des Servers, Blocken des E-Mail-Versands, etc. Unter XAMPP könnte man wohl einen Fehler erzwingen, wenn `sendmail_path` in der `php.ini` nicht gesetzt wird.

> wäre es nicht besser, in dem Fall auch dem Kunden keine Mail zu schicken?

Gute Frage. Derzeit ist es so, dass der Shop erst die Bestätigungsmail verschickt, und falls das vermutlich geklappt hat (man weiß ja nie, ob die Mail tatsächlich ankommt), dann erst die Benachrichtigungsmail. Spontan würde ich sagen, diese Reihenfolge sollte geändert werden.

**Comment by frase-git** [comment]
> Zur Fehlermeldung: das ist eine allgemeine, falls die Mail nicht verschickt werden konnte, was andere Ursachen als eine fehlende E-Mail-Adresse in der Konfiguration haben kann: Fehlkonfiguration des Servers, Blocken des E-Mail-Versands,

Dann ist der gesamte Text aber zu überdenken.
Meldungen an den Betreiber sollte der Besucher nicht sehen.
Melden Sie sich per Mail oder Telefon ??? Könnte u.U. nicht gehen.

**Comment by XHalbert** [comment]
Wenn der Shop wie besprochen im Bearbeitungsmodus ausgeliefert wird, und "Order Email" im Download leer ist, wird der Shopbetreiber das schon merken beim Testen. 
Also Fehlermeldung ganz allgemein halten, wie "beim Emailversand ist was schief gegangen...". Und sonst so lassen.

**Comment by cmb69** [comment]
> Meldungen an den Betreiber sollte der Besucher nicht sehen.

Es ist ja keine Meldung an den Betreiber, sondern eben an den Käufer: "die Bestellung hat nicht funktioniert!" Und ich finde es wichtig, dass der Käufer in diesem Fall informiert wird. Allerdings sollte dieser Fehlerfall nomalerweise gar nicht auftreten, wenn Shop und Webserver korrekt konfiguriert sind. Daher sollte der Shopbetreiber nach Abschluss der Konfiguration, noch bevor der Shop veröffentlicht wird, einmal die ein oder andere Testbestellung durchführen.

Was ich mir aber neulich schon beim Internationalisieren dieser Meldung gedacht habe: es wäre wohl sinnvoll das Log von CMSimple_XH zu nutzen. Zumindest beim Fehlschlagen des Mailversands, aber vielleicht auch bei scheinbar erfolgreichem Mailversand. Schreibt man die wichtigsten Infos ins Log, dann kann der Shopbetreiber ggf. den Kunden kontaktieren, auch wenn er keine Mail erhalten hat. Und man hätte auch noch einen zusätzlichen Überblick über Bestellungen.

Man könnte das Logging auch noch ausweiten, z.B. Eingabe der Kontaktdaten wurde aufgerufen, Letzte Prüfung wurde aufgerufen. Dann könnte der Shopbetreiber sehen, ob es hier öfter mal Abbrüche gibt. Vielleicht passen dem Kunden die Zahlungsbedingung nicht, etc.

**Comment by XHalbert** [comment]
> Dann könnte der Shopbetreiber sehen, ob es hier öfter mal Abbrüche gibt. 

z.B. wenn das paypalproblem doch weiter bestehen sollte...
Aber auch andere Probleme würden mich brennend interessieren, wenn sowas geht

**Comment by cmb69** [comment]
> Aber auch andere Probleme würden mich brennend interessieren, wenn sowas geht

Geht auf jeden Fall, und ist auch nicht aufwendig. Allerdings ist das CMSimple_XH Log nicht wirklich übersichtlich; ein verbesserter Logviewer steht bei mir schon lange auf dem Programm, aber ich komme nicht dazu.
