### ISSUE TITLE
mails: greetings %COMPANY%

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/xhshop#99]
Mir fiel gerade auf, dass in den Bestätigungsmails als Unterschrift `%COMPANY%` verwendet wird.

Da habe ich ja alle Hilfstexte falsch geschrieben.
Bisher glaubte ich, dass `$plugin_cf['xhshop']['contact_name']` verwendet wird - was ich auch besser fände.

**Comment by cmb69** [comment]
> Bisher glaubte ich, dass $plugin_cf['xhshop']['contact_name'] verwendet wird - was ich auch besser fände.

Ich auch.
